---
apiVersion: v1
kind: Service
metadata:
  name: &app plex
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    coredns.io/hostname: "plex.davidapps.local"
spec:
  type: ExternalName
  externalName: 192.168.100.64
  ports:
    - name: http
      port: &port 32400
      protocol: TCP
      targetPort: *port
