---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./automation.yaml
  - ./personal-dashboard/deployment.yaml
  - ./uber-item-viewer/deployment.yaml
  - ./laundrey/deployment.yaml
  - ./boarding-app/deployment.yaml
  - ./davidapps/deployment.yaml
