apiVersion: v1
kind: Secret
metadata:
  name: home-cluster
  namespace: flux-system
stringData:
  password: ENC[AES256_GCM,data:zLyoYlhh3XjBDKvjgdebGUghlbZKKXFuzsKJKLA+kGy7Krf4qQSnKA==,iv:T8W3/EWywmQc2iaD/1NBylld9m0fCchrusF6EeQ5x6w=,tag:b7yDWsU1GTHvPslThmb9JQ==,type:str]
  username: ENC[AES256_GCM,data:p0VS/D9S0JYP,iv:pPm8L4fZADwlxh/fEfMiakr6B3JheLid9QLf3tQQ9W0=,tag:bFeLxw8ffplaa4dtMC1kgQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTk1MRXFqR1lGUFhkcnJN
        bDFjeFlWZStabkszb1Y3VVI3OGlFdWU2ZVJFCnNCbzlHcE1YaHBpNzYwczUyL0xj
        NnBIQ01aRUNHekhZeks0ODdzdGc3SDAKLS0tIDBJZHVmVWx6L3l1NS9ySUhBS0dJ
        ZGZQd0h3L2RrWUh3NHZ4TEZub253TUkK56/x9we2frtAi2++/2IRFDJmgJa5a5kj
        NCEk2P2zOv2RGn5eP80DYLe6GACP9y2j+zqLW1AQM+6OfaMYta/gTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-04-27T23:23:43Z"
  mac: ENC[AES256_GCM,data:O566b3O9qtNWPqMZpdUHx4tgSkgNRNg7gcGHFb8FDWRcuUaCf95reENnQbwKNgPh3pgEBIqytYJJ5DwRUYU/t2v6qFtYXXmT7LD9UAQ/ZDzC8Sq76xMaVAO/s2+bCkze6uDlALpvvDb2gkz13ZX9XmO6fv7TPTpiaLC2wNBAzWk=,iv:sxMhSGkRlA33dKuajdnWkWRoR00HSwjiGgqtMi0QWd4=,tag:/hf2OwSUcebjlvfbU9Y5Zw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
