---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: littlelink
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/techno-tim/littlelink-server
      tag: latest
    env:
      TZ: "Europe/Bucharest"
      META_TITLE: "David Ilie"
      META_DESCRIPTION: "David Ilie Link Page"
      META_AUTHOR: "David Ilie"
      THEME: "Dark"
      FAVICON_URL: "https://avatars.githubusercontent.com/u/47594764?v=4"
      AVATAR_URL: "https://avatars.githubusercontent.com/u/47594764?v=4"
      AVATAR_2X_URL: "https://avatars.githubusercontent.com/u/47594764?v=4"
      AVATAR_ALT: "David Ilie"
      NAME: "David Ilie"
      BIO: "16 year old passionate web developer | Dev Ops Nerd | Gamer | Photo & Video Editor | 🇷🇴"
      CUSTOM_BUTTON_TEXT: "Website,david@davidilie.com"
      CUSTOM_BUTTON_URL: "https://davidilie.com,mailto:david@davidilie.com"
      CUSTOM_BUTTON_COLOR: "#000000,#000000"
      CUSTOM_BUTTON_TEXT_COLOR: "#ffffff,#ffffff"
      CUSTOM_BUTTON_ALT_TEXT: "Personal Website,Personal Email Address"
      CUSTOM_BUTTON_NAME: "WEBSITE,EMAIL"
      CUSTOM_BUTTON_ICON: "fas link, fas inbox"
      GITHUB: "https://github.com/davidilie"
      TWITTER: "https://twitter.com/mrdavidilie"
      YOUTUBE: "https://www.youtube.com/channel/UC92hn9Y8WcY_5LribMDW8uA"
      FOOTER: "David Ilie Apps Platform © 2023"
    service:
      main:
        ports:
          http:
            port: &port 3000
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:file-link-outline
        hosts:
          - host: &host "links.davidilie.com"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
