---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./personal-website/ks.yaml
  - ./personal-dashboard/ks.yaml
  - ./uber-item-viewer/ks.yaml
  - ./boarding-app/ks.yaml