apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:xS+IWF9McpJxdN+VS8QNYY1ZGg==,iv:KKwyfs7LRtP/LjwDfffIzLS2srhkr5ShscJeDSmIF3U=,tag:fsGfp3cjjFVk32gM/vV5Cw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:2HwLv8qN31z74/lNpQjcv/zbnIYdki5s5DqfR7agn91OF4jKOQ==,iv:LjzH+AjchZxDHeZFqUVsM/KmxYxSGgtRn6huJjALm0A=,tag:ak4ZVcs60mht/mwv8FH/AQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:fFYK9BL6Oa8BzJb5wyX7Velm,iv:K7qTQScdHwv4dodTOzyweYTCCKEo4GFAttJe6tYa3aE=,tag:7y7J9Cl/KSpVKGbPJ1XDzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dzN4REovYVYrUTFTMjdJ
            dlBjd1JXUCt0L0RsTEtqbkx2TTFVaC9aWDFZClFlemtWOHN6SXl5L3BKS0dxVmEr
            QlQxdXYwbC83eElDdk1GOHBRc0dVd1EKLS0tIGNnSmlOUzJpVU04M3pOeFE1THRS
            UFhYMWdkaDJnZk52em02dytpeG10TUEKMn079Tq/F88dz8mF5UDShE75GcDwehBW
            oCRSC1BflYmwWUWE3lbz4qpxqJqWQ5um0djIIckeAEwuLnEoWlM8MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T22:31:18Z"
    mac: ENC[AES256_GCM,data:H9O/gVk/kVCTrCGDUXIAcck12Lf3np6S98rOnPHlIR5XqBSdOv8FjfkoLdfQV9VPnh4neCoPdY7ciM9vSC6X/qEaUh5Gr6v2D78+Usfl2hAicLXsI7xncIGlgiCflHMnB2+D/GLzhBbBN4qCRwsM0elLmsJdL29p2uz4d+GD0I0=,iv:baZ0mKz45ZRcxKAA4T4XXGte3xHx5KZeA8qhqv6uVss=,tag:Z4ThMePWisDLZZRXh6b/uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
