---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      backend:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.33.0@sha256:08ddf4b4dbfdc4fc1f5b0fe535915998581085402e307b57bb308db68460e372
            env:
              #LIBVA_DRIVER_NAME: i965
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_LOG_LEVEL: debug
              OLLAMA_MODELS: &modelPath /models
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 11434
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 60
            securityContext:
              privileged: true
            resources:
              requests:
                memory: 2G
                cpu: 2000m
              limits:
                memory: 8Gi
        pod:
          runtimeClassName: nvidia
    service:
      backend:
        controller: backend
        ports:
          http:
            port: *port
    persistence:
      models:
        enabled: true
        existingClaim: ollama-models
        advancedMounts:
          backend:
            main:
              - path: *modelPath
      data:
        enabled: true
        existingClaim: ollama-config
        advancedMounts:
          backend:
            main:
              - path: /.ollama
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
