apiVersion: v1
kind: Secret
metadata:
    name: donezo-valkey
    labels:
        app.kubernetes.io/name: donezo
        app.kubernetes.io/component: valkey-secret
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:J2TWbL3Fxm4WcwNUsdBiWsphN23tfxER/saE97IsI5Tdg8CguH9Fu2ogDwm3FXx13pg=,iv:wCLdWb9W4cahjDar3dPKglweQ5TNO7U8co7LT+TLUhg=,tag:xcetejMM+Jypq3dhgDXzIg==,type:str]
sops:
    age:
        - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZUlGVHo0OHgrUGVvN0M5
            TmI4ZVduOHVvYUdzYlByZC9EanYwQU9FV2tZCnlmZlR0T09HMjhCa3RFK2FEb0Zv
            aTIrYStNczl1ZVlQQ05reU9zT09IU0kKLS0tIEFxUnVWRmVDT3I1OXFHT1pKMm5x
            MEw3OG4xVUtxMGdHbzJyeFRhQXB2dnMKb834Txl4Qmb2ys7mj6P5Dv5beax8+GZa
            /d0+zCGQgRKOCaNEonZ1w72ajFuyHAkDgLW1Ib96fmCyD8lwk3XRqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T14:15:45Z"
    mac: ENC[AES256_GCM,data:tVkzmcVOdrKoCExxaFl9qpKcL5jFwt0zeHrshud+I0BZael+QLfv+v2eDGldWH9dvkJp92HbgcYUVu7TmEUBPrKa94S/dt+FPasotKP1CxnNFHacT6feSKI1Lhn5fLbnTisdDVJK3JYMtbsAxmQXyWMw2H+6mmO+SNOveUmvzek=,iv:gAmyxCoGsQI9KYNjK7DlTj1ilNIA5vi0WhSxTpX2PGs=,tag:7TvjFeKXk5NJBJL+0xP61A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
