---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  - ./node-feature-discovery/ks.yaml
  # - ./nvidia-device-plugin/ks.yaml
components:
  - ../../flux/components/namespace
  - ../../flux/components/sops
