---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infastructure
resources:
  - ./portainer/ks.yaml
  - ./scrypted/ks.yaml
  - ./go2rtc/ks.yaml
components:
  - ../../flux/components/namespace
  - ../../flux/components/sops
