apiVersion: v1
kind: Secret
metadata:
    name: worklog-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:iuiiD74OJJ97YhywfWygWd3c/oUvt3jcIOxOuP3EB+OVgUvN04LTMBBIt9D/Tt4+dlZRpq4ZELkdoYg4U+wSzx+kHFySRt9ywSmRtxjJV7Ynru1iH0hwPmdfYCUEeqCEUkHhzzWQOkE=,iv:d3gUtRLWCzPLRi1tBwoJER0UeWfP/eKbGxNTbBF+gfE=,tag:WA6U7EmCPiNc9ex+EOqFCA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:abwL1/NtTkigTJsswV5wlzrjLJOxC9jg6mbL79H5wnJP4hzb,iv:C01LQS3pcYNPneG/ic/ltOnqf5MRN31zdw8lcdXR9ic=,tag:qjr41vEk/LfRpCX6P4N8WA==,type:str]
    APP_URL: ENC[AES256_GCM,data:sn1gHR4ND/rwK/modEtDHyGucEjc3/3x03IcG00=,iv:VUpUTnXQzNfi13jlu8rVz0ZShsLLj2zZu4JjNdl6R1E=,tag:geMeJH3BqEsO0OSJb7jcSQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:xIwqM/k832/GThNqMGyzuzfVQc0ZwztHcwIya70IdOJJzbtJqzmQUD5JF/qT5z21vRwhpAbu1EqasdmK,iv:H7/UhvvGnL0+3ssIAo92+4BrJrTJ0kL4PYiL7ugWqbQ=,tag:1yeTiFi0fglHUcJzx0Q1ig==,type:str]
    STRIPE_API_KEY: ENC[AES256_GCM,data:c9zOvxvCNvGKZbbmeJbzaCyr2LtfaLNpUris7Bs33+rvojISeY+QedTQaNb6pNFlj3Tk77TTBwraouMrKmpJ8hDIf0Ug0UYrXioNX34wXO1UvoGmTZbseqqjTJ103hm2ZeKQkUMZZeupoeo=,iv:9Gu3fnoUXligu/nEvYlq5LLjCO22S0uMECo4NWm3PyY=,tag:cVfSq4iDN4dKQ/w9ALPu7Q==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:DxmbPQY4ia/XjSC1H5ZD/5RqMZd7ZynYozJJBYuXkGDO8CU6l/k=,iv:lNnFai/H9Rmio1OHM/Xw9BzkUXgBJNVJpQ5+coOR8zQ=,tag:cBGguvs3078GO1r7EVd+FQ==,type:str]
    SIGNUPS_DISABLED: ENC[AES256_GCM,data:o/v0aQ==,iv:G4EcqJtbmzI4C8IWHx7dILi9MGyBajItiJkw2Kvqv8Q=,tag:Ra2eaCGqDxd1/vF8ukq9VA==,type:str]
    SENDGRID_API_KEY: ENC[AES256_GCM,data:jjdkuXXxdApKUXgd3+opsj/35m11Z9S09HK7wegHrVFh02FEMpJAuqor03a5WqFmbRwBmiQ+Y6sm6hGwp+IAc9gSqUCM,iv:P3slxBRCcXOlUPPfROboe7n9YWGRj/XYwFyFfL6NBEU=,tag:dDtyANf/JAZ9pdnq4BmMDw==,type:str]
    MS_CLIENT_ID: ENC[AES256_GCM,data:kkTAlTzZDL9cS+eWeeoZCvMqiscRqF0/hRJ3KAXefBabsuNR,iv:5/+zz1/Amr832bmCldGch0UfBRg7LuXkP4wy6461dBo=,tag:wioEvasdJm+sQzQG+fdzNg==,type:str]
    MS_CLIENT_SECRET: ENC[AES256_GCM,data:Pa060OKlTN2+cPh0vhhOqLIEjYA6HLFLgZgLMXViQNJqBoHKNzK3,iv:VnOiExeni905vVJQkUvpyUv0QoqpGT6PKxsOoiwjUjQ=,tag:mgHkmkWs04Zr9keOxhT6+w==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:JXH0sDFRsaulvAQUJBBMYUoEgaUEtN3LsPZ5Ni0DWLulgJ0SCN3iskBHganWQEjduXFe8brKzdn6XDUkaRnaV+nyY8eJdbo=,iv:4cozKRA+O9TzOk/eI7hM4RMwZWmFHWojrWLTXLSb+Z4=,tag:+l/AlVM6ZB0DJ/HcR5ln1A==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:XJpHf/wtCoMLES1D/G+EY2w6ybMjNmqoZrCnkymWPrW5j2U=,iv://7MmJ/ZNJVhXLiT32BVqbkY3wEW9I8sHQs9O5syIQA=,tag:iI0GPPQEn5MEANOCRrYV3w==,type:str]
    OPENAI_KEY: ENC[AES256_GCM,data:s7z95wKpw0SEKJqkE6Z73O7bogD5zSf/IDdWBU7PTkRxBfH99yCYtMAIsAXOD2q4SIiB,iv:iPqh/DOryIx3UoT8NhsTAEsvMi3+kmPjXSXHf/nkf9o=,tag:wwL96HdQIKhgzHTEiz/qAQ==,type:str]
    S3_KEY_ID: ENC[AES256_GCM,data:PthyEwo=,iv:oTVEZB4R/is1Ivvi7ujgUMq8z7xPCLP7qfhEaHO25ww=,tag:Nb6vv1wv/vDi6kuE8XUFMA==,type:str]
    S3_PASSWORD: ENC[AES256_GCM,data:0KVzHz3zVd0yK2qmrKw=,iv:53uvfVNsoFDXOHUryhGkJ0YY+4BHADc3vQrp8swhN34=,tag:n7Y2r5B44LlrTScqP/wZqA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:l+oIvxfWTQ==,iv:a6vtJ5s27QAgZhYoCLaBUheSv7ts5HXXkYOkXEy1Gg8=,tag:xvBR3Jq1sXiv7i0mWCGbJw==,type:str]
    S3_URL: ENC[AES256_GCM,data:KFDxLVVmoNwNky63p5yH7tI=,iv:/iLC7KLm4/ozke+jpSDfSFVxywR4HrrdEjbzEotmOYw=,tag:LcP03MvOqgK+vdLCB1KzKA==,type:str]
    S3_PORT: ENC[AES256_GCM,data:mOQf,iv:VBEjI6/+ooflWdo1G8r3uBu8FfrL8uqtmyapd1OmkTQ=,tag:Y2wVKzU4/7fFVBt2nVHgfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1JIcWljSThtZ2JodFVJ
            aEpqZWdESDFURUdLckFWQ1IzUldyT0ZCd0JrCjh0MFRRQ1c5N3haRkZrQXYvU0VW
            TkpKQ04xTUVLN09ZUUx0T3pwVXp2U1kKLS0tIHl6RG5INEVpSzJvRnZUeldXd3R4
            Nk95dm5qdEY0d1lVc3dqRDJTNDlvQ1kKLixoeBTKgw8tdBEOgemi4P13l+WSaenK
            HX//jMdwuyBbOVgBvrQaN4u6NQjNANoG9WQC2pdJ5woT3aklNqaV2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T15:02:43Z"
    mac: ENC[AES256_GCM,data:bTWX+1/mNtycM2LGqhvW1w4/LILZnVAedFxur12pyWmNrqadrvcxRTLeZRJCVjS0k1Kh6y+2kXn3vhWNDfwvh4a+etHeHeli93bt+KBlhOhakanXpqUQskWZWdzFeKFi795T3NCyR5mn3hUApH4HmzwlsciWu+w/mIclawZppfs=,iv:3SLney4DZXTGHIzJOSduMSr+TR2SEWucjsRfgQXX1xU=,tag:Nr8IitO0hV0iykbqqTA+Yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
