---
apiVersion: v1
kind: Service
metadata:
  name: &app homeassistant-spain
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: ${ES_FORWARD_IP}
  ports:
    - name: http
      port: &port 8123
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app homeassistant-spain
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
    hajimari.io/appName: "Hass Spain"
    hajimari.io/icon: mdi:home-assistant
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: nginx
  rules:
    - host: &host hass.davidapps.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 8123
  tls:
    - hosts:
        - *host
