apiVersion: v1
kind: Secret
metadata:
    name: freelance-network-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:PFpWL85PV7VdYvj7nnlVtHKF8JTLj5hL6ZbOscKJo/FFbjeLXT1C243ktB7j1BFVPUBhm54tjeDDefZLjKtCeG/puliWdcbaVlOVNAHQCcFWauwM+mo=,iv:PrKJ32jTVleQOkJbDEsMe18YUXqQBvrzgFmOdL4PmXY=,tag:XSSi4vSfa3veaKZShoFHhQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:SrD1M9yCtfbdPmDIEzFs18vDByp1ozbD54wBVhS6K6ri+x1IVdHpjMo2NnE=,iv:Y+wpEVTRKd6CbcvKMUPeKOpWt7ONEcpa+z76RCsmi00=,tag:USbJGFjwpw7cYtCUZ2xmpw==,type:str]
    AUTH_URL: ENC[AES256_GCM,data:nnE2ywg7vMLiKUAlLudfDBLT0ZaTEl+i6dFe9wg=,iv:/qC7GRttUD1CEjMTYOedx1JnNNZZwyUeB8BTcj6kqYg=,tag:5kMo1JI0dawCxd309L/1Cg==,type:str]
    AUTH_DISCORD_ID: ENC[AES256_GCM,data:2TSoflcyJeqnQfgW51KfIkuOWw==,iv:OMoA21azaM/ePAIYepAIzk2Kdc/Z00O1ig2UNQahAeY=,tag:7OsxfUpJR27KyHBK87RUHQ==,type:str]
    AUTH_DISCORD_SECRET: ENC[AES256_GCM,data:MXMynzvypavDEaybaQsaL5eCQUr3GMD/6jp9Zcob/7Q=,iv:5qD9CxmzgSsI/Ah/BOslOB46tiMVefHWsBlDey0QFgk=,tag:fNuFJtVjUbmccSBFnq6qyA==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:PI5F+br4k1gx4VZv3tfGmkI=,iv:LtGQ4QyXSAgnPMmwEvDmrZyZbJZa6Y1+Tzbv00FKW00=,tag:/kH2CFz/N4SKquuuIQrIfw==,type:str]
    MINIO_PORT: ENC[AES256_GCM,data:k4qc,iv:EA7gpE9pzRcGkvFx/lrujUXuYnp22dAxrPFF383SuGo=,tag:wcmGcn0kFyDOv9K20acpgw==,type:str]
    MINIO_USE_SSL: ENC[AES256_GCM,data:t5uUmw==,iv:8mXrcE0LR6Akk0iIr8qZqC23AdUukT+9OxvlnwzPIc0=,tag:XeVDVW+vOk36hCh3WQuKnA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Sg/q1xg=,iv:IJWk9R3mQIXZIf4MaBiVQLC1mtZJsoL28l8FMNEh3qI=,tag:rJmQhZEY2M8xdIi2yiJwcQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:RX3+4r9BSw9gp3wsOPA=,iv:2dZVI2ngJTXqem5gtYq+AQUJJ7gs2IpfLgKwZbOwpZE=,tag:QZciFxu/UR7tFOu31laKow==,type:str]
    MINIO_BUCKET_NAME: ENC[AES256_GCM,data:xCUfhsUQLjuA,iv:r+E9EWXLGv1Rdtuxw4BHuqW7d92ObVzEjy8JsWiAoq4=,tag:JgRCFIdj74fWAWAADaasWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG1aTWE2TkpydWg2NkxT
            TnlmM01IeFBjN3RtT3dGNU5qb2lrSnFqT1VvCnFhRXFicVBtbXNFNXZkcGtCMVpS
            bkZvQStaSFBnci9yUHdkd0o5bWx4eEkKLS0tIEp6aGEwVzh2SVJRSElQK1ZXbUhM
            RlMvS3ZObnJaSTcrSDdNaHQ2ZXlwQmcKEaouW/Op7dzuu9T6er3NT14A8hW0kj95
            D+fwjgQCWt2wP6o2UjPHcew0cH/ZZZ2aKm0Nyd5qwFvlavcSrHa1EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T02:45:31Z"
    mac: ENC[AES256_GCM,data:e/JlVnrqKwZVHayecJXMcxqFPVmCT1f0WfYfIe+p6QOkyG3kUM6DMSjTYkBsU8DFwOAPO/tuxy5JurOPns1TxwiaoxWQ9cV3uTiFwMD6P/YgeN9dJsriqXEalHDS8CSBE77j0AxXWrmizCBY+0B1j0GWqczrbQizAq/0IKdTjZg=,iv:Taukh3nlISsqZybKubxB76T+tKZjZljhxaT19HOujxE=,tag:tICGX73sbCofUyBNYEaKlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
