apiVersion: v1
kind: Secret
metadata:
    name: freelance-network-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:VrjwWqy0/wIwVkkK8XAnv3iSyCBw65bpXAFfqhbQHgKnNoZ8dqDWRe0OgGhka5U82M5iv5O9I+mHFh/1S0OcwNH3C0OAbJFKmmZCBUHbT3Jl,iv:H/rRCUdklTLV/0iBbLuVYlnYo4c8LBGHc1O4jRweJzM=,tag:BiDFZ5aaOdZNmueGsj9/5g==,type:str]
    AUTH_DISCORD_ID: ENC[AES256_GCM,data:2TSoflcyJeqnQfgW51KfIkuOWw==,iv:OMoA21azaM/ePAIYepAIzk2Kdc/Z00O1ig2UNQahAeY=,tag:7OsxfUpJR27KyHBK87RUHQ==,type:str]
    AUTH_DISCORD_SECRET: ENC[AES256_GCM,data:MXMynzvypavDEaybaQsaL5eCQUr3GMD/6jp9Zcob/7Q=,iv:5qD9CxmzgSsI/Ah/BOslOB46tiMVefHWsBlDey0QFgk=,tag:fNuFJtVjUbmccSBFnq6qyA==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:PI5F+br4k1gx4VZv3tfGmkI=,iv:LtGQ4QyXSAgnPMmwEvDmrZyZbJZa6Y1+Tzbv00FKW00=,tag:/kH2CFz/N4SKquuuIQrIfw==,type:str]
    MINIO_PORT: ENC[AES256_GCM,data:k4qc,iv:EA7gpE9pzRcGkvFx/lrujUXuYnp22dAxrPFF383SuGo=,tag:wcmGcn0kFyDOv9K20acpgw==,type:str]
    MINIO_USE_SSL: ENC[AES256_GCM,data:t5uUmw==,iv:8mXrcE0LR6Akk0iIr8qZqC23AdUukT+9OxvlnwzPIc0=,tag:XeVDVW+vOk36hCh3WQuKnA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Sg/q1xg=,iv:IJWk9R3mQIXZIf4MaBiVQLC1mtZJsoL28l8FMNEh3qI=,tag:rJmQhZEY2M8xdIi2yiJwcQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:RX3+4r9BSw9gp3wsOPA=,iv:2dZVI2ngJTXqem5gtYq+AQUJJ7gs2IpfLgKwZbOwpZE=,tag:QZciFxu/UR7tFOu31laKow==,type:str]
    MINIO_BUCKET_NAME: ENC[AES256_GCM,data:xCUfhsUQLjuA,iv:r+E9EWXLGv1Rdtuxw4BHuqW7d92ObVzEjy8JsWiAoq4=,tag:JgRCFIdj74fWAWAADaasWA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FXv6toS//P2OgxpRm7hRmqs=,iv:9L1DrlHKz7VFUbAK69QtVHKaxTnUrs9rMqePkMquDRA=,tag:GdX3baQFwCeJZtw5WDAZqA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2v2Ri+vDa/HwavYX,iv:kENGF/GoKRjk9KBHnIttUHww9boqsxT4jDlnJ/rLOP8=,tag:f/6qvjOtABxU9hjPN8LlKQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:4nl33Fj70W0z,iv:4mvWEhUAmTWIIA8JtJcZb3mFFRFWIyZOZycGVKi9Cv0=,tag:hBzwiWRm9GVCRqv0jnIZag==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:amENC4lRvfg=,iv:XrvOEaDmqmxOKZnJ3Iu2nRJ5X5kQjbvu1CK04bcrJNI=,tag:s8uL6iZzq1WCwF2KQiR7Hg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RL1vnzV6coqGFpJqRvg=,iv:JxAdAHKfAcI7zcXs2y4rfusjXqIX/q/XFop3YSB4At4=,tag:LoRai8HfPstsPCo4t4i5yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG1aTWE2TkpydWg2NkxT
            TnlmM01IeFBjN3RtT3dGNU5qb2lrSnFqT1VvCnFhRXFicVBtbXNFNXZkcGtCMVpS
            bkZvQStaSFBnci9yUHdkd0o5bWx4eEkKLS0tIEp6aGEwVzh2SVJRSElQK1ZXbUhM
            RlMvS3ZObnJaSTcrSDdNaHQ2ZXlwQmcKEaouW/Op7dzuu9T6er3NT14A8hW0kj95
            D+fwjgQCWt2wP6o2UjPHcew0cH/ZZZ2aKm0Nyd5qwFvlavcSrHa1EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T02:23:13Z"
    mac: ENC[AES256_GCM,data:Io0G64KGUzCbt+jnDNQjrMSlVqZ8NFRc70BUIZk7wyjU9+TNyt22PL1ckt2bRFjvNMIIwz06t+A15ULM+FiIFaxsHw9sUJHl1ZjKozzkXUipsyKryvl+PRxKnl/5mydS3to4DbVZNjt5g22sqBiYuEK9qs3wRNF9NlsA2J5H2c8=,iv:E5JKvE8NqnstpgY+18VahR9zP6VF7tOPGrUJgPji920=,tag:mD1crzJajku7hVSwBsWivQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
