apiVersion: v1
kind: Secret
metadata:
    name: shlink-web-secret
type: Opaque
stringData:
    SHLINK_SERVER_API_KEY: ENC[AES256_GCM,data:N1TX5j5krYnZlhcW6PO2OMpWfMjjdU84Cb+J1H/0wTrFGDMp,iv:QVeMUU/ODilpB2ALb08PZM+XFQ51Y/s4lKPp6BeHjP8=,tag:UP2KT3+75MKZSZT1yQxnPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T21:46:12Z"
    mac: ENC[AES256_GCM,data:w70smzwFVk1C+38DvecaxZ/9NAC4mabGtq7bJeEYCP/Nf/0lXeNiaZ6R/k+nT20a2KFmiu9BF81Uy6QH3J0hUKzXhYadeeVmkEw04C/abBQ7KOmXdzFw3h/uX8xWoFEiiHSsPuCq1AREcvy5WtqiADMOVh5uLzAYVMsYUMaTL0o=,iv:ewC0UzHID5aaA+c5hEAzJHfRzdpccIKlPR6Tp6yBmz0=,tag:C3Lxp+KvXin9SYG9N6ov0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
