apiVersion: v1
kind: Secret
data:
  token: ENC[AES256_GCM,data:gcye6SryAWv6S8IPGn7lTLDptPG4ytpuxIa2DKypugZOPfbyGdx0kfXXXA+PN4B/zu5UwGMPg5dOHnHOrGJp/WWf4WnxfPVYFAoG1jXLIv1cSVy64zmYBA==,iv:zWqxnWdEzC811DcNaQtjhFqiT7jv9cLq24h7roPpsQ4=,tag:JlnD4N4pEtWebpKmH+xHuw==,type:str]
metadata:
  name: pelican-forwarder
  namespace: default
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VzAwaUxtVGorc2ZqcFlF
        a1ZVVW10Tmw0Z05RN0dTMlR0ZnhrSFlSL2t3CjVRclJNT1JMZVVQUUJ1UzdEcG1G
        VHh1cDJyWFRmTy9OdytTV3J3YkVlNDAKLS0tIGNBTTRsV0V6ZVQwSUR1UUE4SXNU
        emN2cFVQQVhsZytDaU1sWWZ4S1ZZUmMKxPJwQR7krFvGvRqynBQTVqOKM3ohmcXg
        4SCC1+zXX4DGFTrN3KM6tqtYkxOZ90QYyRmmHpLXg0iV/m6esfTwHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-15T11:53:20Z"
  mac: ENC[AES256_GCM,data:w3WcKv48kQPzpxM+rTkNMW7F55HEk3cxScAFmiyYlfOmNXhZJk+VCewT4kExfnGi+YjsoKQYXC70FXYlHKjrJ+W2piLxntJ3tBP5WYR+vmtNS5ffXZcl8rF+pRU5JCsFmseamceMlU2PESmfNxpgj59wOppqjlRdhXj08G3yoRA=,iv:rJnLKbRqKvU66Sjp5DFnMYFkZZn4P1CdqaYeNLXDAS0=,tag:sl9tyLWi7BgQz7VeH3iNMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
