apiVersion: v1
kind: Secret
metadata:
    name: personal-website-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ECpcGzhnFGc3fcQqiXPYv+ONqTk+KjrT7guMqyLECc6oG5Xdn7w68Rc9RxOa27XTA2jaaiCmb3AchcYOr9IgnL/nyjHy7ZdSKHCGNlkCuVrTPkT/HlU0Hvz/4lbzBNIsbAVia2Su+zKfLimy6YiC1Nw=,iv:6aqPinQtdLIJSWisn3uKxoGNpQsZk/3wqs0ieuszlPc=,tag:4S7waORjbtnklAIWQzmucA==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:9/ddFaPKQohJsaFDzASaQINWsN3qO6WM2KauhhNxF5c=,iv:7i9grUezzaHRNx+K3WxosoICV26SBSY89km9XRv9ehA=,tag:HI9o9hyi2DXVgL3vmVDpuw==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:bWVEhS6nRz1UGX5IW6hDeXbJs12Hjd9og7Cj+qi4T+I=,iv:iaAhQQHIulPaHQVEGGWwg5Ax7QNBXPTcrWt7UyISYE8=,tag:w3w2OALm/8OXt1S3H8jL2g==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:5IjACRl0j09DB0xOYFSloqPdOaqptbNG6PAser/RyGv4uIk68x6rLIYRsE415ESi8HcD/THAa4SBMdz6V3ihMf/jSnvj38zVMuvWi+OpZzicUaduUyo4bHdaNmMnCTFZVH5OSheQi5bR2Q8gCStBJa6lr0Z/ygOgYeoHk8aENO68jZs=,iv:FTMOTBOBXR02H7Kgo7GQ76Kcg/3c/xgizR//ZqSAPrA=,tag:CeXhtd93Hcber1KfuKnQ1A==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:u17mZaLBTogUBCUcYCZi4VnEvm0p,iv:B5RkiRrd6t1UnrGD3L0KmhRoBxO3fvbkPIipIlzkzqU=,tag:m5RxXh9fKgJGu6b1pvXlew==,type:str]
    GITHUB_JOB_SECRET: ENC[AES256_GCM,data:uvvjDmD1o1SqadSUMZpp9pxh0RrTmzCplTHjcSAJnY6i9z0oWi1XN1bBO6BbHHkZv0pJWJARVQcJ1rr4,iv:DQFTCsqOogIEGuVpM5o0CF5PUBIAs6gWeiQ1jbMuejk=,tag:owdpN5Q0oHNw0ESo9pV2iA==,type:str]
    GITHUB_JOB_USERNAME: ENC[AES256_GCM,data:Yj43AR727xaP,iv:w12U4C/JEI7cCK8BLNf9JIIxZVWtjtwwifZhywySCFo=,tag:lCZaBbuKU1bECK50V8ss9A==,type:str]
    STATISTICS_JOB_SECRET: ENC[AES256_GCM,data:bX2gA+D1yLwpfXLKKzUbrhVJfMYCLMEnbzM2yqgqkqvhJZoRfOhnoKkRqXef1ZKApiLfsw2fAmT6rEjF,iv:Geya7qktgFE5cwOMcWPP8/WJtkbyQfN7vWDp7g/qG1Q=,tag:W5eDOfAh9fj+HQof/KowTA==,type:str]
    STATISTICS_JOB_CHANNEL: ENC[AES256_GCM,data:88txPurDXKFBsmZEtpSEYjf5SWvrmoJg,iv:N06gmqC3AlVg9vgnMgNcasnzZDFdNTKXI1KznC5HAZ8=,tag:q/pEp7oVUKSvYhM2146bFw==,type:str]
    STATISTICS_JOB_API_KEY: ENC[AES256_GCM,data:BLde/gEF8PKCtO/Pb0MOhdbjqvpTD08bvxl+9hprLrUTDTrzSaOH,iv:8WVGRmc1/1R3J5GGIWJvD0j9gscdmXUlIGH2R/7hF80=,tag:nMOvwgYh9mVqaLfxb2RUOQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zV2JAXmOcjZ5sfyQEhpU,iv:0kdGGhGZnU5NcSQZbMdhqXNi4atzX6p1pHfDnrHVUy4=,tag:dCWhgg9Q7LOM3SobEuK1Gw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3ghWdrgixTPc5av2zmLWSsBJFAdUPaPiUoH/JE7mQFWHlXH2er6uYw==,iv:secon+sxePxJLK7SGgnxI+KNt/hvxj4QPVE1+2U9t1E=,tag:Bld6cUiuiZlQR80GvlQ2mA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:v3CLjd2k9l+rxgyLDrI8,iv:2ziOiY7tx4+c+AZnvvZAH4y4qunbx5fNGcNwhI1gwDU=,tag:j72NSOL9nPykT5PtIrv+Yw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:amENC4lRvfg=,iv:XrvOEaDmqmxOKZnJ3Iu2nRJ5X5kQjbvu1CK04bcrJNI=,tag:s8uL6iZzq1WCwF2KQiR7Hg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RL1vnzV6coqGFpJqRvg=,iv:JxAdAHKfAcI7zcXs2y4rfusjXqIX/q/XFop3YSB4At4=,tag:LoRai8HfPstsPCo4t4i5yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG1aTWE2TkpydWg2NkxT
            TnlmM01IeFBjN3RtT3dGNU5qb2lrSnFqT1VvCnFhRXFicVBtbXNFNXZkcGtCMVpS
            bkZvQStaSFBnci9yUHdkd0o5bWx4eEkKLS0tIEp6aGEwVzh2SVJRSElQK1ZXbUhM
            RlMvS3ZObnJaSTcrSDdNaHQ2ZXlwQmcKEaouW/Op7dzuu9T6er3NT14A8hW0kj95
            D+fwjgQCWt2wP6o2UjPHcew0cH/ZZZ2aKm0Nyd5qwFvlavcSrHa1EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T16:49:27Z"
    mac: ENC[AES256_GCM,data:LTXgwuL0fGaZiqs38LTVMRoyivNA9nGYe4KBken6LVhr5KOjp5wTPEbcG47qQGzlZShu7DSEsoD6neOyWjHs0YED7cgukcTZcg5GFHL7ySp1i10xlHde9bcIdq10QhdkTqHmRXvyTlFOymzncPPbfawf9fhU6EitnIiTnLO/gkE=,iv:L8BX8TgiM25HRiqItynLspLuTv4gl/qiRcX1BnTZoiA=,tag:o6JE+Wko0/wDoMEMXS9OBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
