apiVersion: v1
kind: Secret
metadata:
    name: personal-website-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:u7Zni05HY5lKWETZXOqRAg2Gz5TK3YpYoEdWstuPbjJzM8G7AZDjuHxSLrc/9CTutbF4qFooGPV3IXtsAKhVB/lfYm3TzDoE7ftHHLlo3SVpNyK8HMJk4AHjIkZ3Wz66aovTV2lhU4bJNA==,iv:ReKR2CebysIeK7tqDLNDyRMEzCr+BSpX10gmiCcyexg=,tag:KRDc+ZxYJd0CIeztgkWcEQ==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:Ll4Reqrw9cVC/fJUGEJI/eGwLy2OOnh+Z9g3PhuCQI0=,iv:jarsIA9TZ2oYUt5pPplRkN5jCCfaCr6t9CJE97BJ8Aw=,tag:2V3HyRT5LNgm/zR+gdYm1g==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:8Gmk4RNBPfxo4utCA0bI7SHVEgQnW6Ln6mE3ecU7BMQ=,iv:FV8FEP+UTkmL+VzuJc0iV2ng/fhmRT51B+mC/rDWnuQ=,tag:AmCaHa8mZIlgBxjj2VNvzw==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:cx748XJu+i8saMVaPJ5jM6TY7kTkVBNEUBe+AsDiSw5/BANOADW0fJHxGWGHHBcXC/l1Cr+FpKZTX88sB+AdOv+bAD4gU9hPjGMpEfX2nGyI0+bmu6trKGapI5HMiKFUSQd+Xps2J6tNEDxGQKUum3vmEHztUpGyajgLoTO5DF044SE=,iv:4Ql1aY57DZ4h7hyUxhvYpyc5YrPiWFpCAB4c2Y5dhOM=,tag:B/P8A7K7GgeJxkZC5YiPCw==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:u17mZaLBTogUBCUcYCZi4VnEvm0p,iv:B5RkiRrd6t1UnrGD3L0KmhRoBxO3fvbkPIipIlzkzqU=,tag:m5RxXh9fKgJGu6b1pvXlew==,type:str]
    GITHUB_JOB_SECRET: ENC[AES256_GCM,data:uvvjDmD1o1SqadSUMZpp9pxh0RrTmzCplTHjcSAJnY6i9z0oWi1XN1bBO6BbHHkZv0pJWJARVQcJ1rr4,iv:DQFTCsqOogIEGuVpM5o0CF5PUBIAs6gWeiQ1jbMuejk=,tag:owdpN5Q0oHNw0ESo9pV2iA==,type:str]
    GITHUB_JOB_USERNAME: ENC[AES256_GCM,data:Yj43AR727xaP,iv:w12U4C/JEI7cCK8BLNf9JIIxZVWtjtwwifZhywySCFo=,tag:lCZaBbuKU1bECK50V8ss9A==,type:str]
    STATISTICS_JOB_SECRET: ENC[AES256_GCM,data:bX2gA+D1yLwpfXLKKzUbrhVJfMYCLMEnbzM2yqgqkqvhJZoRfOhnoKkRqXef1ZKApiLfsw2fAmT6rEjF,iv:Geya7qktgFE5cwOMcWPP8/WJtkbyQfN7vWDp7g/qG1Q=,tag:W5eDOfAh9fj+HQof/KowTA==,type:str]
    STATISTICS_JOB_CHANNEL: ENC[AES256_GCM,data:88txPurDXKFBsmZEtpSEYjf5SWvrmoJg,iv:N06gmqC3AlVg9vgnMgNcasnzZDFdNTKXI1KznC5HAZ8=,tag:q/pEp7oVUKSvYhM2146bFw==,type:str]
    STATISTICS_JOB_API_KEY: ENC[AES256_GCM,data:BLde/gEF8PKCtO/Pb0MOhdbjqvpTD08bvxl+9hprLrUTDTrzSaOH,iv:8WVGRmc1/1R3J5GGIWJvD0j9gscdmXUlIGH2R/7hF80=,tag:nMOvwgYh9mVqaLfxb2RUOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG1aTWE2TkpydWg2NkxT
            TnlmM01IeFBjN3RtT3dGNU5qb2lrSnFqT1VvCnFhRXFicVBtbXNFNXZkcGtCMVpS
            bkZvQStaSFBnci9yUHdkd0o5bWx4eEkKLS0tIEp6aGEwVzh2SVJRSElQK1ZXbUhM
            RlMvS3ZObnJaSTcrSDdNaHQ2ZXlwQmcKEaouW/Op7dzuu9T6er3NT14A8hW0kj95
            D+fwjgQCWt2wP6o2UjPHcew0cH/ZZZ2aKm0Nyd5qwFvlavcSrHa1EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T15:02:47Z"
    mac: ENC[AES256_GCM,data:MJ0nHUee4MlA5k8e7XgCpwJEceBo/NbvsttAFcFq5AI/O8QllB4eOcXnn17LWK0oOkZIf9RnmoHmUBp/1P5xHMYlUsGL1ySwrpLvLzXR7SlwKWpEb8quekgMiXRiPpqHRgjmmKo9wuEewvjMI9yrN7xjdVXmsoWs80Ca1fDeds8=,iv:sPf3ziR1ChvUKvbwRqZB+zT5BM8fyfLauca1UFJXazE=,tag:JpTbWon6UbcsVTUcxksaQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
