apiVersion: v1
kind: Secret
metadata:
    name: personal-website-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:K4uXjnRMWYiG0HblixzCOfAm2JDj8lMdQhwsdSlg/B8X2qN0YQiY729gnUE6bxXRc9ttHDzpdXe2FHx3TEwy0sYbRtE18CyjUTb5QiLnmsrWVLHi3A==,iv:zRspV0y/p7AKjxG1PmLRMGvRmXTlKr0C2d8rI7xKu84=,tag:/YcfkkvvV8YBbYZnbUKNIg==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:9/ddFaPKQohJsaFDzASaQINWsN3qO6WM2KauhhNxF5c=,iv:7i9grUezzaHRNx+K3WxosoICV26SBSY89km9XRv9ehA=,tag:HI9o9hyi2DXVgL3vmVDpuw==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:bWVEhS6nRz1UGX5IW6hDeXbJs12Hjd9og7Cj+qi4T+I=,iv:iaAhQQHIulPaHQVEGGWwg5Ax7QNBXPTcrWt7UyISYE8=,tag:w3w2OALm/8OXt1S3H8jL2g==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:5IjACRl0j09DB0xOYFSloqPdOaqptbNG6PAser/RyGv4uIk68x6rLIYRsE415ESi8HcD/THAa4SBMdz6V3ihMf/jSnvj38zVMuvWi+OpZzicUaduUyo4bHdaNmMnCTFZVH5OSheQi5bR2Q8gCStBJa6lr0Z/ygOgYeoHk8aENO68jZs=,iv:FTMOTBOBXR02H7Kgo7GQ76Kcg/3c/xgizR//ZqSAPrA=,tag:CeXhtd93Hcber1KfuKnQ1A==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:u17mZaLBTogUBCUcYCZi4VnEvm0p,iv:B5RkiRrd6t1UnrGD3L0KmhRoBxO3fvbkPIipIlzkzqU=,tag:m5RxXh9fKgJGu6b1pvXlew==,type:str]
    GITHUB_JOB_SECRET: ENC[AES256_GCM,data:uvvjDmD1o1SqadSUMZpp9pxh0RrTmzCplTHjcSAJnY6i9z0oWi1XN1bBO6BbHHkZv0pJWJARVQcJ1rr4,iv:DQFTCsqOogIEGuVpM5o0CF5PUBIAs6gWeiQ1jbMuejk=,tag:owdpN5Q0oHNw0ESo9pV2iA==,type:str]
    GITHUB_JOB_USERNAME: ENC[AES256_GCM,data:Yj43AR727xaP,iv:w12U4C/JEI7cCK8BLNf9JIIxZVWtjtwwifZhywySCFo=,tag:lCZaBbuKU1bECK50V8ss9A==,type:str]
    GITHUB_JOB_API_KEY: ENC[AES256_GCM,data:5UhmvjMwOFyL0pKL8QJB5aPsxyvgSEKuYQjDdI5/IAEjxJuX8C5INQ==,iv:9ptqNXh9g2JvQCpCMe6FwX+PPOx+Ueu/dlROIkw9NSE=,tag:sL60+66zczLiErRzw+6ogg==,type:str]
    STATISTICS_JOB_SECRET: ENC[AES256_GCM,data:bX2gA+D1yLwpfXLKKzUbrhVJfMYCLMEnbzM2yqgqkqvhJZoRfOhnoKkRqXef1ZKApiLfsw2fAmT6rEjF,iv:Geya7qktgFE5cwOMcWPP8/WJtkbyQfN7vWDp7g/qG1Q=,tag:W5eDOfAh9fj+HQof/KowTA==,type:str]
    STATISTICS_JOB_CHANNEL: ENC[AES256_GCM,data:88txPurDXKFBsmZEtpSEYjf5SWvrmoJg,iv:N06gmqC3AlVg9vgnMgNcasnzZDFdNTKXI1KznC5HAZ8=,tag:q/pEp7oVUKSvYhM2146bFw==,type:str]
    STATISTICS_JOB_API_KEY: ENC[AES256_GCM,data:BLde/gEF8PKCtO/Pb0MOhdbjqvpTD08bvxl+9hprLrUTDTrzSaOH,iv:8WVGRmc1/1R3J5GGIWJvD0j9gscdmXUlIGH2R/7hF80=,tag:nMOvwgYh9mVqaLfxb2RUOQ==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:F/jePgrbuZS1EHAXxFHQl06KgPKSUFnnBqR3C8bZudrrf8hnzfg7GLIvtXt43iBo0V51KWp+FHRhQ4hoWqjUffmrLTFjTVBY20EPBRtnvOSllwfXumr6W7AeUmGscPZ9dVP3P6NVO1MTZe2joJ/sS69A+xn8WDt6CA==,iv:PwrTGit7y1jn/6m+2/x5ueTJ6GOm3k2DoL2PwjiL7cg=,tag:TEJXyM7wwxceA0tChCnsWA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zV2JAXmOcjZ5sfyQEhpU,iv:0kdGGhGZnU5NcSQZbMdhqXNi4atzX6p1pHfDnrHVUy4=,tag:dCWhgg9Q7LOM3SobEuK1Gw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2v2Ri+vDa/HwavYX,iv:kENGF/GoKRjk9KBHnIttUHww9boqsxT4jDlnJ/rLOP8=,tag:f/6qvjOtABxU9hjPN8LlKQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:v3CLjd2k9l+rxgyLDrI8,iv:2ziOiY7tx4+c+AZnvvZAH4y4qunbx5fNGcNwhI1gwDU=,tag:j72NSOL9nPykT5PtIrv+Yw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:amENC4lRvfg=,iv:XrvOEaDmqmxOKZnJ3Iu2nRJ5X5kQjbvu1CK04bcrJNI=,tag:s8uL6iZzq1WCwF2KQiR7Hg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RL1vnzV6coqGFpJqRvg=,iv:JxAdAHKfAcI7zcXs2y4rfusjXqIX/q/XFop3YSB4At4=,tag:LoRai8HfPstsPCo4t4i5yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG1aTWE2TkpydWg2NkxT
            TnlmM01IeFBjN3RtT3dGNU5qb2lrSnFqT1VvCnFhRXFicVBtbXNFNXZkcGtCMVpS
            bkZvQStaSFBnci9yUHdkd0o5bWx4eEkKLS0tIEp6aGEwVzh2SVJRSElQK1ZXbUhM
            RlMvS3ZObnJaSTcrSDdNaHQ2ZXlwQmcKEaouW/Op7dzuu9T6er3NT14A8hW0kj95
            D+fwjgQCWt2wP6o2UjPHcew0cH/ZZZ2aKm0Nyd5qwFvlavcSrHa1EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T01:50:04Z"
    mac: ENC[AES256_GCM,data:n44bArliaI6HMtBqk5ZFlEEloO0epr0VAuwvSMQGpOKvbSF6RmS/cBf4BiD3q6Kf56fla793hPiglzMPZR3X00Fb7tQQMV9VOv6q/ezC35DsiGjZTvQiyPN12Q0XyNyIZwWfTK/oRYHepwCvVg0pb9pauA8ZWEWNiwINrjf73iE=,iv:zmc+hNHyGWswNXE2it8j/c0v5N8HYIRcRco/cnLt5PI=,tag:stUR+9KRT4MgjSKjbgecmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
