---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bostan-discord-bot
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
