apiVersion: v1
data:
  discord-bot-token: ENC[AES256_GCM,data:jzSj40alu6Sc6cbZ9FdrXAiGy27i+n6SNEaY24a0lChD5TeGIo7r7f0/VwTb+t2qJAUKjajt4MuhH+KdwAPxpEZ7W+Unl2GZBu/tg2a8EfyeIa7KPJjmRUOQ5f8igXht,iv:pWnLQwHGrLp3vDDCC9hzFqu+Wg9hTiew5zoarpjG6x8=,tag:oqbMWMKok0N/aEq6MHKlPQ==,type:str]
  github-token: ENC[AES256_GCM,data:UNYqBchG+N2AuWmmxSroKzvPd4YQOlQXaDAex/Kuc6WFMGfrz7GN86/lRfmrFE7YOrRIGYhg2oWQtB1h0oIZlhsj/HMImoDrQPjbIIgB3ixE4sff1ddLo7mYaSaMAI9d+3sKgwqgJIHIDEhYUHB4QxmvFPUlXphUvSAhGQ==,iv:RGcy+6NlhgHugJYWFY4/zfMXazzNj50q4ACA+qLsy+c=,tag:1N/AXFXvtkkEoHTkCUypWA==,type:str]
  interaction-signing-secret: ENC[AES256_GCM,data:DXr8oWPEH1SEunhMPwZX3j6IwqnPRvMSnd7lcvNq/TlwGgqx6gQFGP/fGTcRGJEzvG+cwjWiX4KcQCBfPZ6waZG3BUEdUymeazzZw8EMAFB18TcW4dwX+w==,iv:i4OBoIMZSrOSH/PDAcAo9wHf1LzHgG7qX5pGuSWa0HQ=,tag:UL1ubARQ6Zcl6coI0g2Xvg==,type:str]
kind: Secret
metadata:
  name: bostan-discord-bot-secret
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbFI5ZTBnWE9yYUphUTBQ
        VDErVDEwQkFWNnhMb1FKcGZiNFRVSllnaWdzCitScm9RZzhYVUxTR1J1aUJtdVFX
        eFd6NEJwTFhmV2M0VDY5N2Z5V0p3OVUKLS0tIEVFcnpTZVZCZHV0VnZlMm9admN2
        Z0I2T2V0ek1aUFVON1hDZm1mWWdpNDQKS+TzJETNdsPoGKtOXZPtQJ6cUxitJajU
        CaPT4vMbc8V/DGwECow8lHtnNqSFtHuFThzwM5trF1J8ta2dCu1e4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-22T19:23:50Z"
  mac: ENC[AES256_GCM,data:XOTsaEjGmHVsHPf00JyyN04msEMbCwg+dYXO8QNWkSkaEk4tn2Jn6iPSg5ZrbVkZ5buf613cb1QF6PDQYceCeV5dRiBpDOLD3u6IUo+EL6KbdyonX06z9t8fjZiYA5VEmKWLGpSYnZ33gy2utaBdTiD4NXlN69XfdkdTp0CBsiw=,iv:HjcgTghwA1AoUqB0GXzZZOKTxEnI/PQECi+2fVr7uEM=,tag:mtOStIbD0hg2aEkaDLMcKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
