apiVersion: v1
data:
  discord-bot-token: ENC[AES256_GCM,data:J01HubRYNQnak3KrOqH2sWgw3iSTLLSrYbXiK5YRo2GZGxUHK3GU9IIZQBxqc19GpydHj7oejPCkPB93NZcnsTr6KJpxCWXCySGiFaZfjDO745A/YXgNTOzA6mYT3s6T,iv:q8wWd84XNBJb8x8snyCrLGZ03ktaF7Dr7sJs4nkwnKM=,tag:JfDrHSQ2a89unF580nNowA==,type:str]
  interaction-signing-secret: ENC[AES256_GCM,data:3FIu2cVFdQ7Z/ywMgEpuqF/FZnRjZTOywaqQOPFLV0RRI29aAjhS1QeWoSTYjOGiH2bvX0vj0RpQ5oEfOj2ENO74Ay/FeUVbio+LHT20yw4fo+HWGvu3WQ==,iv:FEKU4I9QdOrpuyR7LOnqWd2/Xq2x8eed3TSZNj3pgFo=,tag:rjA7UR91wsVSEDHNByMgfg==,type:str]
kind: Secret
metadata:
  name: bostan-discord-bot-secret
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHNFaUJwQjByZGRuYWJt
        NWFMVWZjNStia2U2bjk5S2MwcUdMT3hLcVZVCkZOaVNqMlZFUHpldVJONURFL1FX
        NWNTeXhwTkJiVnNHcWJDVjZocVlqaGcKLS0tIHh6TUpGYkFFZ3Vxa0tuZEo5b0No
        cGJwZXRSaVpJRlNmdVgxaUxRUEpzeTQK6HJVDjXLac05XjGyQj09zdKVaXUt+1Lu
        kBA/MbMVl3a8f0+gBu8O7TVl5Mh5b1JgWY7OVP1o4sJOv8mrEH22JQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-22T17:42:26Z"
  mac: ENC[AES256_GCM,data:tdlB6yM0IhD138qEJYPVnaec9nLAAVAY+luIUZhHyBo+zXEeR4gAT/1nBI6sx9EDC1uD31LLq7mWAdohbpzH/ESsaxUfsiOzMoBWsTnFbmixQnLlpnjOwv2aL7CUVSHN70E96ZPK+5WTILfJh5dGKdBaq8w4WFqzS95uT5d0A80=,iv:lkupIMqkKggW2dNUhTE3jnrixILK1HWOLx+wqBTs3is=,tag:HNmcgHAPMDWJfWnq5FZBtA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
