apiVersion: v1
kind: Secret
metadata:
    name: bostan-discord-bot-workroad-secret
stringData:
    github-workroad-token: ENC[AES256_GCM,data:Ys3ZopdgmnfuOXkR7zamOUr3wabZ3K4o4QnzKufiCdz6BeI19OJg3f8bak4/FOzrqGbZ5LfXk73fmR9IzNglbGRH8eXOjkPXeuQWpr22cXAFwsBugOsg7gvMX1cL,iv:phgolMvPeOXSeC/JRqJJMlnJlbcX0WtXqWmrVFB5JZI=,tag:s9TtGiRTnle4ycwv0U3pTA==,type:str]
sops:
    age:
        - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENmFxaU1GVzJVQ1BOemNq
            OWtVRmNFWWFrVmtkWjMwWkR4UVZGVzl5cW0wCmNHSHAxVGNmcUpLSm41VmpIcnB6
            WmRPak9ETWZGb1lzb1p6cVB6eWFHZDQKLS0tIC9vVGRuK2VxRGNxR01FQW5iT1Nl
            ODYwQ1dWenM0UGQ5SUdnMWNvQjdDVkEK1qABhhWGsFoNJMHaPbGHAC4ShLyL8KeD
            xoIqFFE5AVbEKYGf/EVvIZ6HVMR/Tg/PNsUctnRXDIRDi/HY4w0L+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T18:15:55Z"
    mac: ENC[AES256_GCM,data:IOoqKOiCqO6z1m1jNec2prbHG/bEhDXhkFr979i/DGGkTTZeZ8t0+nCxNDu4k19nMRi/IMKKLhczrl6Wz+mZBNOMmiD9+HCpocyFjFsMiZFhoDRKvFAA1UZ31ZOF96obMGWYPUsJIT0Pdyz6pgWQj84XXr8JpP2U0aajSvXTHeg=,iv:weXPyXuivkeH3VqyeflgDMQR6s5zX9aPJj8Dw5XdwCg=,tag:XJgztUv5tjXEvTvOECcPhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
