---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server-wildcard-test
spec:
  ingressClassName: internal
  rules:
    - host: "*.wildcard-test.davidhome.ro"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-server
                port:
                  number: 8080
