---
originRequest:
  originServerName: "external.davidhome.ro"

ingress:
  - hostname: "davidhome.ro"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.davidhome.ro"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
