---
originRequest:
  originServerName: "external.davidhome.ro"

ingress:
  - hostname: "davidhome.ro"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.davidhome.ro"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "dave.tips"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.dave.tips"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "gurt.ing"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.gurt.ing"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "childpizza.com"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.childpizza.com"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "monitoring.davidapps.dev"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "plausible.davidapps.dev"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "panel.davidapps.dev"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
