---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: davidapps-gate-revocation
  annotations:
    gatus.home-operations.com/enabled: "false"
spec:
  ingressClassName: internal
  rules:
    - host: &host gate-home.davidhome.ro
      http:
        paths:
          - path: /internal/revoke
            pathType: Exact
            backend:
              service:
                name: davidapps-gate
                port:
                  number: 8080
  tls:
    - hosts: [*host]
