apiVersion: v1
kind: Secret
metadata:
  name: davidapps-gate-config
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:Eo5ZaWWfrEoc2Nz5VCJRChRUzA1Vsvjd0fy9Lkt1fvwwSfgIBQgnPSDpeXeMiBkxA5ANp8jfksMHZbxZVAaWCo3qliUpTFl0bQGUjqxhuon0+LakhaEnqdo3LCBJHH1lzom2LdnIAMJ5sWVK8mpZP+0jwvLOGRCZOmgl68Lxg73aLT9hpJrclzSfybH/0DGjQOppfCULIEADSrzjlKZo8sckF7OocFWSQ5zbmykgEBipTL03Jpn4Pm7OVhTKzZ7e5jh0FvM9rGA=,iv:Sfy/kH1nj7EYCYL2insPGKOqi79v69vJGH5fnAO5N48=,tag:mLyo2TjrtBt1MGlQQdlMRQ==,type:str]
  HANDOFF_STATE_KEY: ENC[AES256_GCM,data:74gmaNmcCpc1Yzez9ZfKh42fujEO+MkFZVSqk6yZv+Td3PCN3BVm/L1dZWYuiWKKZjgABaC8BNpQatpIiWq/8Q==,iv:iGQNowJfzh8MnVvJhlUrcuLS4eiSTRAoFiIuqEymGZs=,tag:+9dlahaCcyXd04xtCvlQAg==,type:str]
  REVOCATION_HMAC_KEY: ENC[AES256_GCM,data:oyepzKxsOvUeaCOOohZcdTG7ogCdNfRRkpPR1dnHys96Xz+N4Egzs7kSETA8gM1hgJyVmNHzGivH6HXHivtFmQ==,iv:v4IXYAFdPfyMh4z0gucMB2IcyYbJAFHT541LtfsV1UE=,tag:5myCQpgQRqGyK1EfyiOjXg==,type:str]
  SHARE_LINK_SIGNING_KEY: ENC[AES256_GCM,data:YzOFPtTONyJnGBjGoyVBTghPDq5JuKkNo5OWp/VomfZztb3zLue3Rhxbki/3VjxYTSasw+0heGOc0V8nyXOmVQ==,iv:qJUW/qikWik6Q1fKYxhtTdGOXma0sHimoLYG28VLyxA=,tag:r0WlkRjHVRaxzmMTc2zXgQ==,type:str]
  GATE_ED25519_SEED: ENC[AES256_GCM,data:LFquHW6HLI7A5zokMtZ5AOvOycPdzEP4fSSNaJC0VXf5zB58ZTLMzUQhXdQ=,iv:1XuFl0895KMb6hcvDNj9Qv4nIQTIVJDHaQcbHvLwNUw=,tag:S4VTlKfOQcOBM6Rt4hnqcQ==,type:str]
  ca.crt: ENC[AES256_GCM,data:TMqdABOa370MOv2oyoChC2SC21B9iRgO3SsgPifQqknC5vfN0hIaN8qoIgk428MrFOuSzvgufrcFIezuGpi7QG03wPYg026ZmrcN6WdfwXEJW4mLGq/tRXn0va9LzmA1fqlDEvj+nXGVuLwb46CSuzMlwG9zQkGimzINklkSj50Ll/v3NiQjXMaP1Kug0EX3ufBv5ZvJfcb8D5WklT0G0XXPe1/md8ZdAu3dXYx4AOowkmkkxri7dGHsnEP8Pv+SZiQxGhzShT9Djz6E3c5K0y5BApwPb7LscsCwduWkyp2CjYQXlJ78EylTr3/5skLvvwg6QNVzOyvbGleR5vSfc4yOb/FDhqp6gblUuVuxKzppKYBndU30oejjU4zPulzzOeD5lUTv1teL7m2Lf05aWrpvH5ol8GLpwYHOX/CPJuT6+ATr2N6m9SimLSCgLNgBAefLYXDsP4ojWhZ9/2ST+Ph4KnInT0q6TfUvvATPBgGl4NMZCqtYzzpDHRiJDYgkig5dveb97YzEEldcOCtkHb87Ui32DXo6dzYg5neSmI0Sp8hKQQmCmdZ2VCiJ+NdzF1IK9uFexr2A6ZY/nRabu1yf2htOJiQGvDqUzTtQaBdz6b7NxMw7ZIaARIrPJHur0Mv/FFY7vWKTX0hdbMlu6+BvHNgoB6pPQmqbJOS3aFI8XEmriJsV0QGxnborfc1ySVrQYVCUsC6cDjY/+MK6DkNqjkEYYEhzIUc20GFlr9nDtqe7kVW+kIXjaXcinlECoZ/M+TU/FQRC/YgfplLHtIVfAjiswqQLUg1U2iYhuAhpHWZClyCWWLGTRZJHw67ccMXwWfUOOAIjFSUauYakXvs15wJTCCdP0pMJjhd8VuBvdLlkyRlP2fQgOkgh4M9UE4lwTreWpx3SgVOBAsFt,iv:MFse+DAzp2pnmCirr1ufhjgGAtQyCPUXHevEnM8vDu4=,tag:WB2IBSUpvjRCxS8idl8suQ==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRE9PZVpxU1RuSncvbFdT
        Y3Zsd0NEYU1kOXdqRk5zMHUvWmVoRWZCaEhFCjQ2ZVBGSGRIbXZrZmRkQU85KzFV
        eW44bU9yWjNFek1hdGIzNExOVGNFTVkKLS0tIDNEaVRtZmVWY1VpbmEvbFZLS0Uv
        ZnQ2MnRuQnlFVTNpWmx6MGpLMXpRRmcK5OPsi3bqaxqMkys93RamygBw9m6KbWwu
        KasQhlh9OBh0WjtXrKmaAvm8VUTwg7EExRc72CnMRIxSE8Aiy4xLPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:50:45Z"
  mac: ENC[AES256_GCM,data:kbKif4LUVq2W8eBW0F91RpS2NziWGQ+Dk0BnIjaCTjOoiXqVdt+Nks8n0Pmi3fj9ku+XMzgFI5xSOzldfYlq7ZjP5JPXQwSra54wNWJ52wJqPm3RjzYyqgPILELSDWQQSWrnfuc4E7YNPIYDrOVaEXdrthftf3qr2BCMIe678Nc=,iv:CCH9Z3xKxs3FtOxYWzngKTidWMYq3Ov5U5K7GTI7J08=,tag:F6ipKzhMvYGo+otyqaFNoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
