apiVersion: v1
kind: Secret
metadata:
    name: plausible-secret
    namespace: default
type: Opaque
stringData:
    BASE_URL: ENC[AES256_GCM,data:kL/Qf9WNFKa4c9/2GUx+gjexEDB1wVaS4VHUrg5rZA==,iv:Ih2ufRJxjwlTA45w7LYYUpdq3CBSAcN7NEJc8NOYLZA=,tag:1qudU4qpl7sALE9xqYje3A==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:/fs3BlksezCRk5oJyth6tEEHouqco4XFU8dla3prwIeDyTiARs7dOtK7H/aMQVSKOgEMN27UqQk6Bbh/wcMb1fWu8XmUPic+z9RfN3K6GKG+W+exkvtWypCbAm2SSpp1lPE88fiFlFFYQJVeMWIWHqVu7EdHitzlEyo93XAAWwc=,iv:G5Vx2YNPWlCIk4tujWRMyd4mo40TNowcVh7p6whD/7w=,tag:ww/SmFcMbs/Gq1UteLBKeQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:rImxcQJZseJ7Xd10HqQtGwDGSzD81O1C0ZriskfbB75TCdCrfqY/Kv/XTMI/YvFr3VLDPM79Y/WkWQhFuAUECn/S+lCk8AOjTy5rbV7kUcOMv1eb4YI=,iv:xm92bSZLaL+pLGqjmTc+tnsF5VqV730LgvBHs8BV4kY=,tag:nUS2NjJpVQ7OzQEXfVtD6w==,type:str]
    CLICKHOUSE_DB: ENC[AES256_GCM,data:FDsjFUxSEgGb,iv:bQIUde2IyIoO1Pdi6hnY1Et3OzE7o0DV7vzjT21NldM=,tag:cLE8bMPB8W2T55EV5j25iQ==,type:str]
    CLICKHOUSE_USER: ENC[AES256_GCM,data:G/w+5mEAd+1E,iv:PMgxNL/5i43M3z2kRK2zQSgFNOcNRcroCnZxMcX2S18=,tag:3wGqcIlbkLX8PGfnyus5rQ==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:mWZDGXb54YzB1PSGJfU=,iv:sVumLEaFZZ30TxAnsiQP5cQ/qlU5JDApaWWXgzKBI0w=,tag:CGdjbW1spbwlO1TbbLz2DQ==,type:str]
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:Wcuq6leX,iv:Auu9l9Mog7Zr/ov/IPGzzBkpYSdbeDXefTOA4vor8PE=,tag:pfLMVnqsD3gAc7T569GgRg==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:mGuJnsXJdecjlQmKuD4W9GeUOA8t1hzbx2X7TKulbN3s/pRGzmhSwg==,iv:S2KMQOwmZvdx4hL6dQu2AqOU7B/A5MSSk5W4ucE3UhI=,tag:AxazIeBvwWUakzDvl1oFag==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:e2M8A84=,iv:JNXlhQQPMMHmeHM+ypLVNDh4JRNXCkm790G9ZtDvAFY=,tag:I6gpE6YogtSGgMKAbPS0WA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vrTtVWILpDrELBrcSi4=,iv:599jtUm7jW7rPvRHXzjM8esm04NCbRcGUvZuE7Zgl+U=,tag:+rAbPGmewOIVj/yCIa9e4g==,type:str]
    CLICKHOUSE_DATABASE_URL: ENC[AES256_GCM,data:w+308p950m1twn8ExbNYOq/p+o73c+mBcQXP2+6AVvhzOkkiYQUNvSYEkZd6e0FczwbmYc3h32l/T/RhB62pYyTwXVI=,iv:PPwjPCY5RcYAkl9RvBnSnoA16C92yla6Co1nK5zwxr0=,tag:O2aUe+2V8CmwtlUydA+A5g==,type:str]
    ADMIN_USER_PWD: ENC[AES256_GCM,data:Fq1gBQyRJF3XesaFk9k=,iv:s2RhcX9YNHdtRFMdK4g9SQgQER1PLRjWa1faP16m0uQ=,tag:vVXQcPP5FlTCW09Wrz913Q==,type:str]
    ADMIN_USER_EMAIL: ENC[AES256_GCM,data:cZmIt6QExfPpN3G34/bGA+RX+w==,iv:6gCd44WWHH/zm9o0xNNWeA3ufpdB9ADojoaIUg6kB5E=,tag:rrxhYFTtT4/VWXco92ZlFA==,type:str]
    ADMIN_USER_NAME: ENC[AES256_GCM,data:UvHvqg+VRs6tMg==,iv:1cX6Q1uFmqaO8BY/xPctHSMhXpXD6NtUukHuB/WPHz4=,tag:1tSHhQlsBaDo8MboCbl94g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnczBrTUVNQ2ZJT3pJOWZL
            STYxNjgwU2t3blFFUkduanlKUDFtN0lPQXprCkl4Wk1FNnNQSE5sb0VZcHBOcUto
            TGMyREg3U3U3MHpabHc0MDdDd0lNUDAKLS0tIFNIUTRqNW5XWmk1ZkhRMEM1RXZl
            TzQwZUZyc1ozNkFvV2lCTERwRFd0eFUK+6s6OAx5f7p94XnW5OJf+IhpldnyS+O1
            O18DIqnyeWzdk2U4Xm33d/nGCF9wb+8iPnTciroVVsFFev9U/OHOmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T12:30:30Z"
    mac: ENC[AES256_GCM,data:uYltWzbTjUaidjvF9CMk+kRi4A8jLanyiF6FwBVOf5cYy//kFVJfiswVv0X+nnl3tRHToC0ukZNW6Dt8HKIzf38Wa+rfG3CyoALJk54IdK610JdhDQfdO2OHVk9APk+Js+s0Eee0S2flu4vJCK9HXlr75XF5MliKpgdYGI3izEI=,iv:kFLICINpANljm5KeUl8Zff082DRVJGcRLJ/oxpg6Qo4=,tag:+hnUEBFimG9jUkwaefG3ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
