apiVersion: v1
kind: Secret
metadata:
    name: plausible-secret
    namespace: default
type: Opaque
stringData:
    BASE_URL: ENC[AES256_GCM,data:kL/Qf9WNFKa4c9/2GUx+gjexEDB1wVaS4VHUrg5rZA==,iv:Ih2ufRJxjwlTA45w7LYYUpdq3CBSAcN7NEJc8NOYLZA=,tag:1qudU4qpl7sALE9xqYje3A==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:/fs3BlksezCRk5oJyth6tEEHouqco4XFU8dla3prwIeDyTiARs7dOtK7H/aMQVSKOgEMN27UqQk6Bbh/wcMb1fWu8XmUPic+z9RfN3K6GKG+W+exkvtWypCbAm2SSpp1lPE88fiFlFFYQJVeMWIWHqVu7EdHitzlEyo93XAAWwc=,iv:G5Vx2YNPWlCIk4tujWRMyd4mo40TNowcVh7p6whD/7w=,tag:ww/SmFcMbs/Gq1UteLBKeQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:rImxcQJZseJ7Xd10HqQtGwDGSzD81O1C0ZriskfbB75TCdCrfqY/Kv/XTMI/YvFr3VLDPM79Y/WkWQhFuAUECn/S+lCk8AOjTy5rbV7kUcOMv1eb4YI=,iv:xm92bSZLaL+pLGqjmTc+tnsF5VqV730LgvBHs8BV4kY=,tag:nUS2NjJpVQ7OzQEXfVtD6w==,type:str]
    CLICKHOUSE_USER: ENC[AES256_GCM,data:X0DVwrUXdw==,iv:i3a6HriQ7EVw9w2F2w+YBoczyc4SnwFk8JlHGUUE3kQ=,tag:/zGX+a1l0RaowfkN6KZ8cw==,type:str]
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:Wcuq6leX,iv:Auu9l9Mog7Zr/ov/IPGzzBkpYSdbeDXefTOA4vor8PE=,tag:pfLMVnqsD3gAc7T569GgRg==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:mGuJnsXJdecjlQmKuD4W9GeUOA8t1hzbx2X7TKulbN3s/pRGzmhSwg==,iv:S2KMQOwmZvdx4hL6dQu2AqOU7B/A5MSSk5W4ucE3UhI=,tag:AxazIeBvwWUakzDvl1oFag==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:e2M8A84=,iv:JNXlhQQPMMHmeHM+ypLVNDh4JRNXCkm790G9ZtDvAFY=,tag:I6gpE6YogtSGgMKAbPS0WA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vrTtVWILpDrELBrcSi4=,iv:599jtUm7jW7rPvRHXzjM8esm04NCbRcGUvZuE7Zgl+U=,tag:+rAbPGmewOIVj/yCIa9e4g==,type:str]
    CLICKHOUSE_DATABASE_URL: ENC[AES256_GCM,data:w+308p950m1twn8ExbNYOq/p+o73c+mBcQXP2+6AVvhzOkkiYQUNvSYEkZd6e0FczwbmYc3h32l/T/RhB62pYyTwXVI=,iv:PPwjPCY5RcYAkl9RvBnSnoA16C92yla6Co1nK5zwxr0=,tag:O2aUe+2V8CmwtlUydA+A5g==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:q19WIRb2gCwAc+WdAvNkW2UaF1L1GzUs+xPooRF1lLgCKFcuM3o8470G20/um6dwgl6VbTHg+IhpKbsHcYuSS3FZmsoSkyo=,iv:7+XvwwKiQzTao6ss8TUFBtMZ5IhEtWqcpJIPlqzXTfE=,tag:ArCp78Ehfe/BuPV2zIgtjg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:Ku8g977PpISVK9nEcA5ZRfv1KNtLt/HxXJU7Ov56rQDxkhY=,iv:/SEcSh1HlowY2hiVy4dllPVvEeJZdtNTcIBZC1puOfU=,tag:4ekonAmjhhSvOdApfh1Jdw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:MCnrv0+IDMg2/2Z65NM+wUGj7FeE7TZ+JYMQzEwW1gGxeKM6ZRVC,iv:mtFJsTvhHZX3cekuH+JD8+AcBkiU7ngEXBViSFhp1KE=,tag:jG5Xe5quyQ+XL2pF0cOmng==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:vRwguyI=,iv:hgaqpe8NPq2s3COV15fm9nV34eYduCxJGPPeXisCCro=,tag:VPbqob0h7BTchleuee8lZg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:oRqxWD6lueeWtfc7vvc=,iv:LEA4ZCEAcQpwcjQO7++2+ahBehbOkgYYRB1W+CA/TeY=,tag:aPs4qQaiRMC2emT98zoaeA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:JeQ7MvexsYRn,iv:n0OixGLyMPgunYgb53gJIEbTKGBmUEwns/daxf0NBiY=,tag:3MFbKq5fUU+OwXmQLQBt5w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZkLX+eJQqlZqNq78WAA=,iv:LoN72goxp3ykvATW+flrIX4cUTLD0v/qV+x/RfKr7ck=,tag:A+51cFfSYAgV1WgqtPDm4Q==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:D7TXn2CFqtQ+,iv:TqUbrvynsGCJJBlhnY9JJaPB8Uw0AGBTuqTOkRLwFqM=,tag:HVCLIDL9zK43fg/cpJXgpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnczBrTUVNQ2ZJT3pJOWZL
            STYxNjgwU2t3blFFUkduanlKUDFtN0lPQXprCkl4Wk1FNnNQSE5sb0VZcHBOcUto
            TGMyREg3U3U3MHpabHc0MDdDd0lNUDAKLS0tIFNIUTRqNW5XWmk1ZkhRMEM1RXZl
            TzQwZUZyc1ozNkFvV2lCTERwRFd0eFUK+6s6OAx5f7p94XnW5OJf+IhpldnyS+O1
            O18DIqnyeWzdk2U4Xm33d/nGCF9wb+8iPnTciroVVsFFev9U/OHOmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T13:33:24Z"
    mac: ENC[AES256_GCM,data:AOycT3mreeeW7nvZU830LLLoX4oTlJ63QI2DucvhUAaV/ruLWjzyVyTRegM2ySV887+hdED3+WJ0rUbf5F3ASCP3ZSQv55L5cBvddS7bgejR/BlTfhodYoUinaW2nPKxaH3Gj1NgN7JNkI7nQzktxmm5D6UaKkWzq/iRdUUeA94=,iv:CHNqfG7UZFvqV6DBwRt5RJ48iEuCfpOAOmMhnAztksU=,tag:dmnIjBW83Qee1eQ01JD4wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
