apiVersion: v1
kind: Secret
metadata:
    name: plausible-envs
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:DOsibAAj6u5E7o37p5mpwBLhqiZc+WS1CqOGuLIoBXfxvmOuTeECA2HLAuttHnTscaPH4jAe+AiLJVaDeKvqtU0R1/7FGc+qk6Jo9If4sfV7ZZ3jTCkS9wJU,iv:5Of22HEdyoiJHOFuGKQPcKF+TCTBliTX55E3CcVVBwA=,tag:97MIes0WsEPabQgwbmumrg==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:mhC5bdkzZS5PM40SeUkRDhNcVAmr+Pypejfu47ZxmHmhmk+/zYM4yw==,iv:sDGyWQlk8BASOXsPumrpSeMu/JYvP+Oc75HNjuxAFsU=,tag:9433CFqbXeUo6A1zvsnwsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T01:03:59Z"
    mac: ENC[AES256_GCM,data:ucXtrF9aKrsSE55y6EdFl3s15tvF3ThFjTDPy667XFa1LUfkqKjJfjSveFyN1XczmaYCoKd1dMMtZATiEZ69U5zI1gGADzEmzefGv4Y7TkzeKelrbO0QTds+PXtHTq3lqoIOdAUV9E1/VFzXn+rokhdC3vvDdp066ZoZImkf2qw=,iv:2oaadB9fyN6O37Ly0ok3+0N4Q1nDIVQ8FvEW6kl7Wnw=,tag:gX3hd+Yul9w8bj1GupMbew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
