apiVersion: v1
kind: Secret
metadata:
    name: shlink-secret
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:ZOnP2w9s6ZmvSNbf+0wjv9HyG/FL2c2Xt1C/MImqShex4aT/nCUyh68=,iv:BOwfoBqdNhbexOwj2Rs0e9VCzFGjikQbtmLbIYtRlXc=,tag:KV4V6QJ+4c0bJB2e4obpqw==,type:str]
    DB_USER: ENC[AES256_GCM,data:9o0NEiw=,iv:22T7l0im3m0IL9lXxtH501X9uKAhxYAcVIPPFG9yR+0=,tag:cJnf5JhV9FD5IB94BADQzg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:mTW4qHHpVwszwypeMOI=,iv:K0bfUqH2Tii10CAWTDTLfy6z7/bgKt3xvwObJAtYR0Q=,tag:H7cQUsa8ED9Vw6juQ/YGTQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:1qTTDfwx,iv:c0C6HzR60ZZCyC5fkDX48olPhIrkiegsUBdVXq0XhB8=,tag:uOp0XZi1s7GCNyzJvf0wsA==,type:str]
    INITIAL_API_KEY: ENC[AES256_GCM,data:ZQkyjQUw5Pt48OLQh6/5Fpz7cXhjZBJHBHgu4mR4WvgZ0WUr,iv:mZIcRivD9Jk2h/NORx/CVzdnTS5yL29zQJU0pYqwQCM=,tag:faAabDoalQsrl2x9eaMCSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T21:45:34Z"
    mac: ENC[AES256_GCM,data:8KmZLBJOAKWpY3A/DaPSPj3tZPPflVS0ocMgY5JJDYDbi8O0dVGvl193EcwuiwBHCwXb4QGLzo0yB3f0oHJ/3KuGRhbDn29riHqjAuVYBFfCXcGdU2E+GlvhW0eep8FA451txq9zxnJYHVEs3Stak6B6iHMk2f3LnYCc7TD572I=,iv:IM2dBwDUeUGC45LeCwV6qPG3LAH4o0W/LvMgfbNIZUI=,tag:C7kfhyEzwU3+HiGlmWW8nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
