apiVersion: v1
kind: Secret
metadata:
    name: shlink-secret
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:ZOnP2w9s6ZmvSNbf+0wjv9HyG/FL2c2Xt1C/MImqShex4aT/nCUyh68=,iv:BOwfoBqdNhbexOwj2Rs0e9VCzFGjikQbtmLbIYtRlXc=,tag:KV4V6QJ+4c0bJB2e4obpqw==,type:str]
    DB_USER: ENC[AES256_GCM,data:b3xoGEK5h3k=,iv:Uq4oar2QRNe805YhQ8qBhAicsgWAqK4pTafJcQPl8TU=,tag:SZXem2KNJak7102qfJMPdA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:mTW4qHHpVwszwypeMOI=,iv:K0bfUqH2Tii10CAWTDTLfy6z7/bgKt3xvwObJAtYR0Q=,tag:H7cQUsa8ED9Vw6juQ/YGTQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:1qTTDfwx,iv:c0C6HzR60ZZCyC5fkDX48olPhIrkiegsUBdVXq0XhB8=,tag:uOp0XZi1s7GCNyzJvf0wsA==,type:str]
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:1yOKXc2dPwjJlkBXvNP3Lt9RkuA5zi3AS5wTk0g0kzbUWA7kcCotkA==,iv:eMy0c6H51j/36cIVTPq8naWcd4vJACDgcap1hY946jo=,tag:3fl/B3ZlgFSJIJ/+iRyxgw==,type:str]
    INITIAL_API_KEY: ENC[AES256_GCM,data:ZQkyjQUw5Pt48OLQh6/5Fpz7cXhjZBJHBHgu4mR4WvgZ0WUr,iv:mZIcRivD9Jk2h/NORx/CVzdnTS5yL29zQJU0pYqwQCM=,tag:faAabDoalQsrl2x9eaMCSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T21:50:40Z"
    mac: ENC[AES256_GCM,data:4Ovy2aX2r1xj7RDOny5rgq1+eSeXKW0mqwNAXR+g7S+G9rVh1FHdQ2jbcmgyKc4at4jMCMFn6DyuJXxVmK+nZNPV03MGRSRpfOGpru4KhNtZ0BcnGn/AOAAci8QDIo0ewZFHiURvHR2pZyc6B6H6KegAXOj+fCEac6fpNbdRPss=,iv:RzzZuV4d3jVo/jAocDacx027WOAEChnrWDbduZ6zr/o=,tag:RH2FhsXE4zsCqtzewON5lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
