apiVersion: v1
kind: Secret
metadata:
  name: altinity-clickhouse-operator
  namespace: databases
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:aUZS2ADwZEWUXDwB3Q5ta9lhkg==,iv:nTT/ZDml2riK+6tRQ+KPlWbujL+Qpy9jQ7pR9SqVQ2A=,tag:KiJN8L5Owsh41jA0+2ezDA==,type:str]
  password: ENC[AES256_GCM,data:Kob/2dysCdgOiLJfzbU95LEzVXp7ZC2A0yN61ccdV4YRvwj1/olkd7mop7AEZifp,iv:Ip69MI8vhR8mnXRJLeDpdgE3uj32Tr9tGPUoKTp+qEM=,tag:bjgi2YaBcFvkqloIiH9X8Q==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcENxOHRQMzJzSXc1a0V6
        b0JiTTdwcndqcGhpQkpZVnpWcFJ0UFcyOW5nCnR4ckFUa2VRanFsNTRuRktUN2Rx
        czdDRmNvUy85bDRZRTdsWHVBQjA1cVUKLS0tIHJYMEVoWDUxNitGS0dTdWJhRkxz
        Szk1SnA4TVlMaHRlSStxRnUwaXh2S0UKQ2qAhDS8igfHuwwOD4IcutIkGKNhsT9A
        Jl8MMpTPyf2IQFmvUuJgpqjKzKi0EA2T+71buGVgeAURPPPBrmujKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-25T08:44:22Z"
  mac: ENC[AES256_GCM,data:qmR/+S9RboDs+r+p2ITyKN3jToAXNYUbhZKW3DiZBI+euY+4h8hhUo9FEIPzFKkk4pwbFfJgwuykc5+B0ghrcgVLiF6EBvJsSLN4A+/HDdNzLZ2LaJvvj+hmjk5HVv5DuB28PzRONRgVqSDbKSTPq0oqwzbZPas6fp1Wt+GjtZA=,iv:OfaUaodLiq8XORD9w+V+JskrHJYnKaDxOhcFaF7pb8I=,tag:moitXrwI9GusGKBu+IXIjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
