# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3V9F5rxLJUt/Acn/P3yEFLCSzt02rhx9REO7TQoLSd4=,iv:n/zdGu/P21c3IpDmtQhSR1TP1shm07Ow563GgE77l7E=,tag:nzthGKpfK3GQqAX8LFPpHA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhR1dMUTVBZlZMU2lMVUZX
        cW1TU1ZxeXVRR29ibFF3UDlMdlJBQjFxUWo4CnM4YU95eHNiUEdVQ1FVYTFmNk5T
        VXVzQ1RjcW94NVFCT1VEZXp6Z0Zzc1UKLS0tIFRDRjlpRzdJcXp3TExIZHBkN29H
        MXlJeS9yZHMzS0xUSG1jc2NxaHlwZkUKn4AA+CEEqPGqlHfI7XzCvfd1W/v/YKUr
        2N1DWlOnVkVMV66iAOLhhSg1eR0pyr0joScwqHPIQjw3zYeEEy2PkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-30T13:13:29Z"
  mac: ENC[AES256_GCM,data:nrhR9cqIYsFvtLtDqQzhTgPj6Mz17ykf2+g19c07X/KCOF+2gV4lNcuhOcagx81ae/zZXeszqQP2P+ZVGNFGucoSH35k46SqHxGFRpdJVSYCYRhQZb38JuEy5HOb1caVGkK6r2JAgHkFx85+ymvgHQrLY6CNmVqrO/VQzA7YLdw=,iv:R3QLVfOuHcmbxYJUeCTvkcWTO132JyDdLU3knI3MaUg=,tag:8bIT9S/gW4XNWObm0l1ZSA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
