apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:PeHfVHExfvTEBuSLuHhwbrqUsQJb0zC4duXPNd1vxs96nUeM8CRqShX4UyVi/dCMa+wb2FsgvCEWyDYYAxUBVJQ=,iv:XL09oTz0KE0poQZ+yKxShIRCdkMJAAGqZqZeMiHUDTk=,tag:KfdY1N46qyi/o4RZ2O+q0w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:4O+ZpJUWGPFn7dEQhcfVi0Khc95FSkx9VWUek9hamYDkpacPyeNoVsiaTSvLrA/EMBPyRto2eVGjM1Fh,iv:gm3wMYus6/wrzYTgIlZljcTRU8z2bEH5kfxxf9l8q8I=,tag:ISoC8x8lxOiSYgEpOHE2Zg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ct9U5Gw=,iv:rI2krBqdpSElyvb6koPcziWfgcFPX9T+8shVuVBzFAk=,tag:xdNP8RQ4HExkh3mjsLA7Tg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gWGF8btLh+NDryUiDIw=,iv:V34A0bhby19jEL+Lhrq4Y3+2Uhz+TB7ws/bDnzHDkYY=,tag:wCls5xIsiJyrOpv02xAS1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T20:46:30Z"
    mac: ENC[AES256_GCM,data:fkEn9N5GkK8QUX+4+Io6M/l6M8IOY6fP4TjIgwgmuVWezxcTxlqBBmKet7bfyVioEqSVhYRbapwRpn1s2oMt5s36Nf5FJiLGOB0hpJCIxZtOcuZ0qIb9jVcZSL+uJrm93eJGvtT9TG8gvb3oO++SrLUxyh/4ppO2zZTHIHo7554=,iv:kPxgF7Ls/f0fmDl25NWPbn5+5CJwZnRyYw1TOmCQP9I=,tag:Z4ZFcEf6DRuuhp+9DorMLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
