---
# yaml-language-server: $schema=https://frigate.davidapps.dev/api/config/schema.json
logger:
  default: info
  # logs:
  #   frigate.record: debug

mqtt:
  host: emqx-listeners.database.svc.cluster.local
  topic_prefix: frigate-spain
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: preset-nvidia-h264

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 1

record:
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 1
      mode: active_objects

objects:
  track: ["person"]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

go2rtc:
  streams:
    frigate_living_room_hq: rtsp://wyze-bridge.home-automation.svc.cluster.local:8554/living-room-cam
    frigate_living_room_lq: rtsp://wyze-bridge.home-automation.svc.cluster.local:8554/living-room-cam

cameras:
  frigate_living_room:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_living_room_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_living_room_hq
          roles: ["record"]
    detect:
      width: 1920
      height: 1080
      fps: 30
