apiVersion: v1
kind: Secret
metadata:
  name: claude-usage-tracker-secret
  namespace: observability
type: Opaque
stringData:
  SESSION_SECRET: ENC[AES256_GCM,data:3EJYMbUcJtYSD7pP95TgPQY0cuMV4Oepm7MvFBKT5xhqFo/al+H7ItMAX4I=,iv:P7/3FfllTwZtgjvWqT8Og8sR3PbD/n+7r3QXgT57hMc=,tag:YMwUFZ+7E/xW73rV0BOHLg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:qf2ZLyM/RygWQ9+zjdUr9c9Q21rvc82F,iv:vwXb1MpPVTM6zT6ixLXsWHsIZ1vkDkVIjFc+IUKyiww=,tag:+8XQNG3HtxozDoaO9w7L5g==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYmJVL0M1UlZjTnJ1UTNp
        M0srNC9xaDJWc0VkbHQrM1NlZTRlZHNVWGs0Ci8xSENpUjVLMDJGZ0RBb1IyVkZn
        RDlJUjhORFJ6NUY3aFdQT1c1dWUrTHcKLS0tIGd6ZXg0dDYvbnFXQjlNbjFWcG5B
        U0FrTkcra0ZHN0tBeVJFc3hWYXFTOGsKM4HZgdWJbKhOdWspso45C4YtKVsXwZ6p
        RVWZvTvtPvDlEKmA3GKFCB+LztIkKgDrMBzCRJQ4sZIrDVOQj/xxJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T11:19:08Z"
  mac: ENC[AES256_GCM,data:tU0+Ax3oy3C3G5otvHjJwsLwIZT4nhKDTaI01UhgoorsoD7G684K2ClSHSNJR3heCG18Tsl6jY1AoQw6OPf+hH7XWbR3f7DAF92gTbl684m/iuezHK7rtmrJwJBKGysUvBpzngjf4RjGz/Q71hVUTU5yy40V7Q9gOXmBNhOWRYU=,iv:VzHOCLCzU0iKM9Xrk15PEGXOSyjiVf9k/1IBvh7WdeE=,tag:vews+0KuKdkBdRCXDgnEKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
