---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: adapter-demo-db
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-32
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: adapter_demo
      owner: adapter_demo
      secret:
        name: adapter-demo-runtime
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
