# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:I0WerqMAiGMxwK4rJFKHVfbNkQ/CDgKdVOyHunL1sUxU3F34U7hvpg==,iv:FY8HkDaknCJiwadshrhGTDpVeICr2zjeW0maD0nlJpE=,tag:C5yWAJIytiaFT0x3VVjOww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRmg1Y2VjR21DT3hLd2Js
        MTNpVU8venhLMzg5NWQ4Tk1CSXlNQVB1OUVBClNNVmNaTHNRKzFKOHJyd0E0V2ls
        cXBDYzJrdUp4dW94V3JPbUdReERtaXcKLS0tIE9ldFNIOVUzRE83YXNkdGVQS1BB
        cmx2VzJZdjVEdTRybHBtbTZibDVBajgKxxZZrLhS55c6/o86LkbfcUH6JVRBiMrG
        k9uKOx2M0qrqkYGbA40NXpDy1YuU/DwwbboZvy11FrJoRvE5pddh6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-30T13:13:29Z"
  mac: ENC[AES256_GCM,data:BEEFyejRR360PT6KADKDDn9d7ZtBmyNi/NbnLHx12DA126Y1y1FIhCajZCg6Ugu14KO1qJ9nFF8qhpowj7caz7kDvgCP+94XrhaH0HfmNd0EUiY4aSiPmOV+FauorEHumISBYq9/nDTHJ1tQdmfGY5seTsX6I2VGmgAVb8bhMTU=,iv:nuz4cTMWFZSU0xwzfBflOQkfTM0HgMIXMgzLveYyh2M=,tag:yX8RxfqryZaLmDO8MP2coQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
