apiVersion: v1
kind: Secret
metadata:
  name: workroad-store-secret
  namespace: default
type: Opaque
stringData:
  SHOPIFY_STOREFRONT_ACCESS_TOKEN: c76c26583bed65428465d81b4ad3b2f1
  SHOPIFY_STORE_DOMAIN: https://7h2m18-1v.myshopify.com
