apiVersion: v1
kind: Secret
metadata:
    name: workroad-store-secret
    namespace: default
type: Opaque
stringData:
    SHOPIFY_STOREFRONT_ACCESS_TOKEN: ENC[AES256_GCM,data:TTbQWp+J54/kBSGjl+Rk/xRa/vzgGtQIzuIN1a4YoJo=,iv:lHdrkwy2FAOPHixWXj078uauQEgbVQ1CQmPtVeAHwJ0=,tag:bH/W4T159ll4DFCgpxxQ6w==,type:str]
    SHOPIFY_STORE_DOMAIN: ENC[AES256_GCM,data:rbzdko+FDGrsR/Hx7rF5/8uPzP0QE6vVuS44SmoshoYO7w==,iv:zAZnu9IpTdc9DgkS+jrqLv2Aw9FVJnSHqGwkdSOwxp0=,tag:dGOyXC72pBZAi4QGCXtiYA==,type:str]
    SHOPIFY_ADMIN_ACCESS_TOKEN: ENC[AES256_GCM,data:ml8kP/iru9yDNQzfffqHYsZ8pGZz1JX3A78TjJq1oLJtHltBRUk=,iv:eLOM8XIIyyWKCBLSr6LscomwB7M/+FSW3OsiTils70o=,tag:4ZAIzSIr1MgeCiocxoioKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1JIcWljSThtZ2JodFVJ
            aEpqZWdESDFURUdLckFWQ1IzUldyT0ZCd0JrCjh0MFRRQ1c5N3haRkZrQXYvU0VW
            TkpKQ04xTUVLN09ZUUx0T3pwVXp2U1kKLS0tIHl6RG5INEVpSzJvRnZUeldXd3R4
            Nk95dm5qdEY0d1lVc3dqRDJTNDlvQ1kKLixoeBTKgw8tdBEOgemi4P13l+WSaenK
            HX//jMdwuyBbOVgBvrQaN4u6NQjNANoG9WQC2pdJ5woT3aklNqaV2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T20:37:55Z"
    mac: ENC[AES256_GCM,data:SHy9C0B194Frk4YqkuCrOObfozjXM5eT+RTEmkq/FJKzdmVsulHYYF8H6C8o0D6+84qnrPt3ztxDZS1FY3XvZQIy/knYVTKUsx21PV4FzzJ5MTieCZd7Y07R/k6SK9z1B5HPv9oaMHT9xJiZfbHN7vXBSOZV7EFKS8CAET/nVwc=,iv:r2OcUeGe3/EzVd976b60Ljj59uK6AY8DD428d6FU5Dg=,tag:L8ncWQHugqe1XEdPGp94bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
