apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: ""
stringData:
  username: ENC[AES256_GCM,data:euZUJKj9/q4=,iv:+oYDyS/uctykRzTrPGupBmyeckleJnbupXhjyp4b9es=,tag:wXL/Lt0AXiUeCtAYRpUCtA==,type:str]
  password: ENC[AES256_GCM,data:vVCwkksj+GFgWncyXpY=,iv:S0r9sUgmkQVM9K2ArA9KyI3NrvAe14Ixhb2loIv5Dug=,tag:1ELXMA7cAeoD9uS+lcDArQ==,type:str]
  pgpass: ENC[AES256_GCM,data:ohK8BPnj3DfjaCRun74=,iv:B4gVCX5qdnGwGVfNmlaeS4QnsSSfgoXJf8Y8bsQ+DIU=,tag:PlZZynkw11sv6Txk6lsrPg==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:2NqbKNTvZ+NzyC3hPrg=,iv:Zs1GFap1ykbSbwDS9TGrxYMGdbT5N0C0jcn9MRvj4Ek=,tag:qOi5QdzGanBFskiZOmxqAw==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:SDXFSQU=,iv:fy5uUXZCdrDEP9n+L1fhjZsx6cb0qC9S04e8PzREqp0=,tag:4LlDnQtNN5oxn6SkVz9Zlg==,type:str]
type: kubernetes.io/basic-auth
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQmhnZ01NU0tzb0JOa3lq
        bDZESUNRcjUycFBaa2QrZlNkYnZHaytXVmljCnVDMEZabjAraUEwZDRsVTR2Y1cz
        RGc3K0FtaGM0ck1QaEoyWUhHby9RclUKLS0tIEhoSU92UzZVVHBuRnpyT2NtZFJU
        VmVZL1dvckV6dlcreFZPY3JFQWNKOW8KOaEJj0TEEoOT1XyfFdtvsFp25CRJpBiT
        Cmy1PdHptOz1B8szJqLkDJMroYSTwoXf6m40f0475fJVOv1WW9jtOw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGME9pVC94NDBRWnV2RGM5
        WWZFdllZSnFLVUpLdmVFR282WHFKWTNiWlZJClJXcUhqOVMvSjB6UXBkTWJFelVH
        c1pvbjFQZlJjWWMxWmF0aVlCQzBqYzAKLS0tIFlBM2R3cTVTRXArb3M2c1lHRDR0
        WHJtSnZZUmJ5Ylc3cm5mVml4M21rQWcK8nYmOTYlTLMK3/HGE0Inlx+NmLLN1YlF
        uP6koK3TQ64h6eCNcn+qWKU7Rppt164EnJr9qJ5LXzgIsoCHEviHDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-04T22:47:57Z"
  mac: ENC[AES256_GCM,data:2Fch9eWO+JbxDOgNnXg+eKUwpDMR+QmnhmZB2NzXlKxhwPBVQ/m/r/d6vgFjAZp1rERMMBE1r2BmC7BaIxnYHzNQR8+htqJNEY3hYGiQ3C4ZDSeIHX6VGM62pTPa+YCOL0TMti7/KxiJrksr8jcDHRDzqAB/CxX9eEBpj5k5LFU=,iv:QglKWU2Pxq/ZBcrZjICAKuTjSXs6vA7jH9q/5h3kFWc=,tag:D3bLhRo3BvIOPlsWeNh0qw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
