apiVersion: v1
kind: Secret
metadata:
    name: personal-dashboard-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:PSA4wVs=,iv:0F7JbfgJMN+KUaXwP/UI1sxgJoEVW10Uoj5NS4TV7Uc=,tag:Mqw9YjLmG2pzzgTXBl8HZA==,type:str]
    password: ENC[AES256_GCM,data:AxU8mhxkPf3mHM5V3gk=,iv:ZPAD+JozL4mbjNUofaLHBi1Ju7uN+TPLm+ohbqRxs0o=,tag:Jn440mP1238h4plPFKsWRw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:yqSY2o4=,iv:RzP/Cwn/FgGo21CQIzwFBjP02IEkeMuFFB+jq83VvlE=,tag:f7+jo8qrhCLqJe4smyVFPg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:xLAb7du8tFhtsAIkhXg=,iv:qXRoeUCuoXwSoSPsCyl63o5Q8Rnf78od2KGdjSr8TjQ=,tag:I4aNkc4FdK4JZjAD7ZNzUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWko1dVdwRzZKRlZtejVJ
            QjdDZlBZdHhHUkJmbSswL2pEdG5keEZ6cFhrCklmVmlwSDhralphbUd6Z045eUZQ
            SG9TOEt6REJTOCtucVk4UmlPK2Vxa3MKLS0tIGFwMDdaMDhsSG44MHQzbDhLNk5h
            YmRlblVWb0JMTU90UEw5WU50TUdOQlEKhGd4S9h65G7VnCXmRU1zzC85akSFHkjU
            4ghTdRAtrn9YZgAGOnK6bOigSp9D+9ixQUoZig/2ks9m0x6QfXsQJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T13:15:39Z"
    mac: ENC[AES256_GCM,data:tv10qEh4TA9MN8lm/zuxWkB47+whr842k7urzKL5PGUbWDo5hvQl2WIPZIAQ8MVALMgJyd/9s7N2pTsN8QsEHzWijJr01GLQy4fYMKh2JyrNBu2AjOSqtTa1paRZAg0unB7ziUz7MiCzrk0ktKFK6p/gDb3xBs7oe64TcmX2usc=,iv:KWDXRGAKFh8BPcl1R18y6hkBVlBbMXsGVe+Lnhod5KM=,tag:NVJFNLXDjs1j/JX62IIecA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
