kind: ENC[AES256_GCM,data:rRdAZy2h,iv:Fs0dsb9UcmiwJEGo8KpbzDKSB3BEt/b37TjQNOILw+8=,tag:Ut15r0iSqfvYtVSS7cFQDA==,type:str]
ansible_user: ENC[AES256_GCM,data:B48gjjc=,iv:QM/nZsf8Z97sazRePeY12OeO2DJzLTz9/mNMMfMNsz4=,tag:GOfJ/GYSyVHJES1n/Rqotw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:l4chlW9gnDQHsNutDHg=,iv:7FNRKNLZ/mwjLHwrVb6Mk+gTG8VOeY9N5x1VmnkNmho=,tag:j5dJgk4kzclT4ALb7dUCzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d29VUDNocWJyb0p1eDc2
            VlhJNU92OHFpNEs0eGpPWS9qNGRmdFk1UVJrCk5oNTJUdkR2M2dwZU10cWwvUG1i
            eVJPalNqbGtuaEhvbkVKbXJ6b1VhcDgKLS0tIDZTbTdqdUJTQ3BSNUplUGJDWU5a
            NGhFQ3JUYkZXSHFjMXdMZTh5WWtCemcKPy2CX7V8o5iVQ0j8qILWnyqwoUadskIE
            A0YDkYHwlZzK69ev0v9SF0jFaiZGYNXKYOXGTdhM+zT8GNsOqcmWXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T19:14:32Z"
    mac: ENC[AES256_GCM,data:igzW93gRaT6REoOhR5y+MYuKWPGQcgcCIY3aJUpbC4uZ4+P3mqzzyI2s+a9x8nwN4VHHfahDcCeymoPLj/6kQGmn8xYZeGu7WIF/u2TuLwjuEUwaor1m3ka0oUM408urFPQ+udkusKhgGOIf211S/CmwcYSSy5Mpdbk8oWa/Ou0=,iv:q/EcAvh3PK4SfO6GiJqkukgpKVLsKlO28F+kJfibqzc=,tag:p+nW18DV5bY954rAkaLROQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
