kind: ENC[AES256_GCM,data:gOOBB2i7,iv:ETqctUZdF2bbmAAzKO/F1oiu4svrukQ/erRb4e9GcOQ=,tag:hX2WRLMXdPfvqOjX0v3Ytg==,type:str]
ansible_user: ENC[AES256_GCM,data:zfMx5yo=,iv:Od6tHK1o7nhxWs6g9gT5EdSnZ8BpQnLWJxChOpXNq8E=,tag:Pc+esUTeCUpCGtAxY/0smg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GsTPXYaDmSad/ApWDI4=,iv:7/i5FRuYdXECxxbwR+aA2ug020M91DyoEYQSPcjYRNQ=,tag:OIOmB3B1Z+Vz9Xha6Ovf/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ1BpTU1FQ2dFSTlXbkVQ
            SlRCZlpPTFJNNHhZSjQvbi9jSXpBRmcrdUM4CjFmMVZhbnQ1MU5RaFVNeHpjSWdI
            ZUJESGxpUzlabjJ2YklKTW5TTzZiWDgKLS0tIFBmRGxaek51bFJwMXJUTFhnMm5R
            WkhPRHlsVStmcmJYV0E3TkpYMC9zY1kKjUyKPSs5R4DEWBuVhsEeg0YfAqh7e7iy
            gWMDM8DrD7dySV8z1uNHwnNAjn/29d5eWlYqhWkIKtY4bBkBxc8KUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T22:31:18Z"
    mac: ENC[AES256_GCM,data:zu61b3GwVfTXIYdafGG+TwwsdyE6m2GGZsVFwuM3zgdRE0CEJUF2Nrqm2GymFi1rFJGInN1RAsME7g9xZGDkXFoF9IEPIeo9jWp4CX6KTgxXqV0nOS37rOk5NN1EhmRSlmLjX9Ogps4mLUj+nC5x+gwg8Evo9Om00cOXldN54l4=,iv:wRGH2XfZgrIuuIEAMRa8mxLmsbLGd9iaYJbmWN0Ouy8=,tag:0DoqC8n06h7Iexy5imi76Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
