kind: ENC[AES256_GCM,data:0aIEKRWv,iv:Ik6MAG1pQUokc1sgzJJHpS0iENH37FER2qfcC6jzypY=,tag:yreCWDSK4yN9yoJn51keHQ==,type:str]
ansible_user: ENC[AES256_GCM,data:m0OvWcQ=,iv:GNgcx6IcroFj/wbolfKUizWFv/XFqFB30B/lKi4r4J0=,tag:9s0/f2BTyF3gijBZnIkH8g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Qh8VdmEA30+QqcxBMnc=,iv:aEwAAtriR8j5HjpNjboC9xy/xtRuc7Dz+RXk3ABjbcQ=,tag:GTqf+yw404LHN6/X0zR0ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeDU4d0c1WlFvRkg1dlpj
            aHFvWkliNEJjK0lXUGpnQTI3b2hVNklieVJFCk9WTXJSalZmWUJEMTJucnR6WExT
            cWFaSkNRWm9wYmVyMDhkeGtOZkoybXcKLS0tIHluekNkd0poUjNWdWZnTnQwYURH
            VEVtQ3NtanNCUlhENEhMT2IwWEZzc0EKupVC5BxCAHpqxEu1jpMiHRaQ5tV8VoYS
            A5nfbNVxmWE9SbyM48Th3fwGfE5L12o/ruYnAPQH5SHd9PvXvpZT+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T15:13:00Z"
    mac: ENC[AES256_GCM,data:NjZHs0EOxoGZ4+CPQSrRRugsfFp/G1rOPphzGnBLGPhdoUU1H//i3GgvGbZGYq60qHh/J2aqBh67/5ppnBWBKUO4xzIWXHf/Srd5k9bR94lFfzGgdvOFMvA9JPnlW2WlJkqp29MMV6m4mAEreDW5FTLRJCw0dt/r1evqEUEvJvA=,iv:tHP2HDxE7T3x6kQWWsaXZ/tnZYWWYYNMbbMjeXXdX+U=,tag:eVNWMmn3Kpw0XagyjJJeYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
