kind: ENC[AES256_GCM,data:muTanWmo,iv:GJk5lQZyz0LrUkY6bPJzHTCHz61/X2fT0I2S/60fla4=,tag:U9xXMTO6PqzC5ODvWMvUXQ==,type:str]
ansible_user: ENC[AES256_GCM,data:m3/0oC8=,iv:dceFh0OIAAzRLDmbGOL8zE+KkGu2XsQQdFHxebgNH5c=,tag:mGGi7vMEZcxAO587YCP73Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Qv4W/QttPRykhYxskcE=,iv:fxLoKJqFfQr87qTqK7yPpK/jjKWhc/R3y53ScyPMlDE=,tag:8FTGwMw3YhqLmdjQSJ2ExA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRmhSMm14UEU2ZkM1aDVC
            OWxjUkhOTmFOY1RnSkp5WENUNjY4UVM3Z3g0Cm56SVIzb3J5MWx4dUhCQldrUlUx
            a2toZnhmQzhJZUdpS25wTUd5UWV2Z2sKLS0tIE5yNGt6OVZZUHRvRkllLzI5SWxn
            MG5sQnlBdDdHT2dUMFhmYVhjOENkSFUKJvUwA3KJJz6h7hjO6r8LgnTp8FMV+xhp
            66EP76ToU7fhr/tq6mp8aYsDRVPaSsEAvUJ3tenGTCIzivZTKaHjBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T15:13:00Z"
    mac: ENC[AES256_GCM,data:n6XSTZvvOD27xYQGngpSKba0qfZxhalsLPmjYwkRr0MSdbQB7nfkBUa2nZKSmmfz9GB3WC5xrY6xR91xKYdsM75L5P2CXoAZQsgN2Zq/Zj/dzwZsS8BI5DJEgC0N8v5eni2hVffoFOIhQtN3RTNA0AAnx7WJ0oVtyc9VfRUvHyU=,iv:QzFhOwvZe6F8wG0hWfO3cBso3Ud3hXHovgnbqMSOiYM=,tag:gpU6PUCukpj1vcj3Gszg+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
