kind: ENC[AES256_GCM,data:3I61uDTl,iv:yRKG6eNnleytYJKUMErmj4IrGRDD7HhsrkGKDZXeRvk=,tag:++htolEqWcaE8Fc9Mc3aeg==,type:str]
ansible_user: ENC[AES256_GCM,data:3GBpZOM=,iv:6vZlYI3SPRnXecE/s9nOJRR9MBBS+QxtyCZoFsrh1Sc=,tag:y8aXbJCx6SkEpAM9Dd2nZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:iGJP6MuPFLdvj5sR0bk=,iv:JVquzWEcez9v/yK5MBJmEhqFPr6tgTJQo01cY03YgJM=,tag:CD7KBeYxXRN/HrLulPpXxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWEVDbVdWWWhNVUNRRklp
            cnp4Wm9mL1g2dTZhR094UHU2ZVRvL0h2ckFNCm5KRUZLOUNjQ2tmeUVQazB5dk9M
            Z0pvdWlMaUg3eStWczZLUjU4bzR3M1UKLS0tIEZ0RHc5LzFPTmZuMzc3K1IvS2dw
            VlBKYzBIR0dtWDJ1MDN6VU1pNHp1UWcKkMjsYSOaZvUi50OIm8q583gSqIXxZcrR
            /8b1UhIQaK6KAL6oAUtjGVFIRMekZtcXuq1ZRBw9ErNFTTyf02g8xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:56:23Z"
    mac: ENC[AES256_GCM,data:fAWbwmQ08Onim9WmZg+MCXJ9eFHB1JWTKsVJosyMm1BmgTn1tXxxxu8Jt7qVC1GVD2aWqEmCsc9xHAk2sG2/uKHG3V8SGuZOcRKTVwXomQh/veQZZjKmlPUQNIYjx6DQNrRDTKWDmQ4SO7eXKz7svWDB658jGGVdTHYF1FqXICk=,iv:nV8qOpmsuZ4Csr997nS9jctiZcwMWS8NH1KnY6TEVgs=,tag:2YXTp5K98on0j1xp6FCXEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
