kind: ENC[AES256_GCM,data:dlN0Vsya,iv:FdsqNJ3quZeGSdSE0xpOkoMo2vFUCFlndM3dYr1p9/Y=,tag:ecDX6EdCSf3djZWWk0bUcA==,type:str]
ansible_user: ENC[AES256_GCM,data:HhWm5Es=,iv:5CViO6NXAubXMiEeDHJhu/q718Z6GPMZWcWrD8oFydE=,tag:+EQRbimTbJU1vrpDZU1jsQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:k655O72zNoPjgInd1pk=,iv:N3PtRtLWk2AhG+7e/b67cFnJd1W+3A4QuIwNS5z9dU0=,tag:4c6s0ok9tUObVIdEg2h1Dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTU1uaDJKSUpXTHBDSFVY
            OXZtR1FtbWhLenBieVlFQUFWYVZsM1orWXpvCm1URkVURmZpZGRrV1ZsN1lONmN6
            bUdTWklxNUYvNjRYZUxWUzA4cVl6RVUKLS0tIHBqYytZYitxYmpTNWk2Q1ZSK1ov
            Nk1lRGMzVnpvMlEwNDVPTm1RbG1CeW8K/kpxtsZYcgb9zQ08NGSGz8gUOJpPkOCI
            IHTp389TUvB13S23aGGz7F1j1UtbVNIfgwQi8TEvr4gWrqaJvm0hjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T17:38:10Z"
    mac: ENC[AES256_GCM,data:87VBASvFXhtSid29X7TwuBrL2cphglHnIC2z7BMd9VCI6b7hY4pEh69VP3DDOjKMtUvJrLNy+DxTlnaEsYhvoJmikUHnQfpmGu1nY9RkN2WJyGtdVhF2sGXsGVvdOz0TJMbBTiQYdHRji0zAHSlj8OEq09ynLc5Zvcy5EPeiLpc=,iv:4iWfiqNwCfzIQxYZhyG1HjijB7OgR/hhkJLa/Ch6u30=,tag:aimp4wHB7QQHoraltkM/ew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
