kind: ENC[AES256_GCM,data:dj9qhXqh,iv:ESf0dXY4tCz9d6zl0zQ+qmYkO92Vg24Hyg6Jdmj1L3I=,tag:Lb+buYgVaLkrY1deFC25oA==,type:str]
ansible_user: ENC[AES256_GCM,data:Q3II7yQ=,iv:nYJQVQAYdF3mudKNAsw5DDT1CAdYy2lw04TVHYNXDF0=,tag:MrDRhkKc2CQ1/eRkYcDotg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OCKnt142PcfLKCnRsVc=,iv:UOA65mUOV4u2plVNt7WdXhdEZNvghCEQ5qVdIZwbM50=,tag:yXDsd+3NJb1AvlZmcgcjBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUTQ2N3FETTJES3FiYThp
            dlpMdm42bzFlMGl6YjJCbjN3cVl5Q1FVVmw0CnRWbnpuVzZRWWQ0R2pJZVJIY091
            WU9ydE05WGpIZy8rNkFYWDNjd0tvZFEKLS0tIEZUTTBGMFB1THFMbnllczZKRWdu
            TTRhTityVXpINVl4YXBqa0JISGhFQzgKSlK1BTvFHcMBRPS/bCmkGJjfDK5h73HT
            48VJDyMnna5d+98urBot5joUKsoRHSvj/hOTa8XhJGJ9vP44fJJyjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:13:29Z"
    mac: ENC[AES256_GCM,data:i5eVDna8MIQTupgnUfdxJE7QQTUEP/r90SQ3/Lyd8AIJww5mD4of4b4HtlBlTMv3GCOLDr+OTc5Jlf2v7rhusBNORyvVMo/emycYn31Mi8jsV4fYN3APJfETDk72DcvejOxwgFgajNatP73OxJVe9F8kjnsnV0tDjDDqi+Sc8y0=,iv:rhnmHsj1RhQUMqhKyW+hO6SpY0nBDISdG94mEmrJHM8=,tag:3YNdWjsWnVMUl3fGQG28Dg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
