kind: ENC[AES256_GCM,data:/c0uMHnL,iv:upUuwQWKS8BChNMEoBSVtXRGniqGJCdbPG75RxEAaa8=,tag:Wvn6Ff2c3bnAVOyV9JsQWw==,type:str]
ansible_user: ENC[AES256_GCM,data:fTeg6Fw=,iv:8+J0rLhiKPTTHG630NOV/UYcc4ExMmdOJIT4olXCkCo=,tag:6CPYgzYfZNQfvssh8zTgJQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:kR3lJ8A9ecF1cr3Y5J4=,iv:wH0VT10Xa+WbcYh9ocWdMYUp8K2+a1U0P5d4gMmj8H0=,tag:cDDR8ikSg3ssFd+7unba7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQjJyVCtWeVRFNGdaRUlt
            Zytsd2J6dHg4YU51TXBYbDR6bjg5c21MQWprCnJqVXpPeGREM0hrTjlLVmhEcG1G
            SHRpVnBtM2JhL1psc3ZJNHo5T1EyZEkKLS0tIHhyazFobnhzcmJNMDNBM0trd0pH
            MTBzeFloWitYUm01bGhic05PdVNkcDgKeoRscpYj9inlHWQKghiXeistelvgHxLL
            U02P2mE0MxIuMppoGdEd74+YP87DD8Jlx8/BLzqOaqnfPzH+qZH/Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:13:29Z"
    mac: ENC[AES256_GCM,data:axCJLFHodSs1HnCwoSvR58bjbZ9tOCa/VWdPnK7DE9aVPK27fiOB35doKPZvDalNxLupc/+p+R4U1FkCTmpob48eIsiECQzuWAcT1SDGspp2ap0SNZ45mF4jybG1LrN7RpazZVtq/3wEBrGn7LkJlr/VdJHvwZdfYBlSrFD2u7Q=,iv:cWVNs0EMeU+d0UScKUY+b2PhAVISXGibKK/3TQClo7E=,tag:11f4X4hwfkQiQX1Sh+bnHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
