kind: ENC[AES256_GCM,data:SFoMjQuJ,iv:7q5KbupYIW0qVJxms8qfPEWtPO5+4jl62Xs0sicYMbs=,tag:bPLz8/zYEoUQ4gg2D0fmrA==,type:str]
ansible_user: ENC[AES256_GCM,data:dgOYcRM=,iv:PJY+vNb2Pm0fe9K4aiChLMHQdmSKpsbeYqw9MTVjNeg=,tag:JCGZEr1Svv2sJHj54GYmEA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:dXfrykLHOdzJ34+lXH8=,iv:CVzrWdRz81hT33oPyajLkUzVzsRFrcqKmxkOTZYLYJ4=,tag:0G3ZQPJapvqdY9ciRB1JJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUjVEeHZqbHFaSXpVb2t6
            N3FlellsWktadFVZSlRSVmpFSmcvQSt5b1g4CnJkOGRIa1A3dk9XZFlKS0pqVmYw
            T3pjV1R6Wm16VjRDT1NvdjdZTnB4emMKLS0tIGo0QmdrTVc2T2FTU3luaHl4ZUtl
            aldubTRyVDBSTGY0dUFRbmdldnFXejAKTrxUWf/cBjGP/VNuvaaYYpsKbKEMc7d9
            ISouajy1XJmr64k5QRm5cFqx73gfBZn/oJS4hGdUZZ61Q2rWozmjPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T23:22:16Z"
    mac: ENC[AES256_GCM,data:FCV7rvuJO7wofS7J54OAKmqZnn+wdnw9ZAJT9QKvzUugiBsIfuCyL9eL37v/SbgYNVhutkbkEPkz5fnJA/685+le9YnAM7tTbiLwwDKI0IvBK+Rjr9uc+2vyNwvvJLbBSoUYXByCCihRgzE58wpp0xT7z6FokHP6u1morAYEnhw=,iv:Cpyb2gNMFApRMIz83mQjUcCR2ZcWXPMC3TXMZo2Tcus=,tag:ebMRTVyO1/qUnxcuJR4g1w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
