kind: ENC[AES256_GCM,data:zabMi+CK,iv:tJkihRZaQXruJMuADryjdlxcTJGP83s9ftArPDVZQ+0=,tag:WUYmbBnCm966yNCvBChIIQ==,type:str]
ansible_user: ENC[AES256_GCM,data:HpHnNoU=,iv:aveGywM2olFH4CZA2tt2FDQ1yyqlQ+m7vM9swFg7iRw=,tag:o/SV1a3QMlXNd/v/E6XjTQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:JTOs8NqQjaGgU6Listw=,iv:ChJXixD76CUD3ta1dxY1tROQ3+WEFZGeTUP7ghypZac=,tag:uglXU1eu4tWrkMhkwg1rTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dXZISVdURDdubEZxWE5N
            ZytYSEVmVTMvSG54OXUwa2Vrb2VXb2xZUlJBClNzS0pUZ040dnlKenFzSEZxcTY5
            OFMxMzNxYWQ3SyttbjBmZHVrK3FibVEKLS0tIGRPMHFDUkx1WkFRN2tFUlZaRXdO
            NHdsbmV1NXdXTnF6cVhUOFcxWmIxTUUKpZZaEuE++GNUCTQALsxjeOqEvceX6cOE
            AFrf20xwHNx18xwbLxPG5P/BviFskqPBIx7V9mYp89zKGMzNUTg1Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T18:49:41Z"
    mac: ENC[AES256_GCM,data:k7dUGGGCp5JEJhaYQWgyILFyCdCM1ErWd6OPIHD+YI5iZsx1YSt4ZnpIZJuQPva2RHy1RUiTNVYG/uEDNy+KAzn0DQKSjb2GX51KQP5jZGofrwdlY4Y79+GTYL1CoE8/aw2z6RKRaBckyXvRVAaahXfz76VZF4bcYJxI7moFzk8=,iv:+9k/lyVQPW9yezJmZ7wUxHgb6GTITJPXq2kFOppLXv0=,tag:vJEobKwywjtnq1N4pzoAQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
