kind: ENC[AES256_GCM,data:ayY8zOXj,iv:GtlTghrfR0b+qd1uHGJxlAnxpamJjG8LbQ+pbuAqMho=,tag:hhIsUVOI8m0XfASEtx4FHQ==,type:str]
ansible_user: ENC[AES256_GCM,data:O+OxS70=,iv:6RmNoYmsdccpFAbWroLNSydsNmjFKRJpho7PK9hm9pw=,tag:BxJVPQyKkS7VUJ19KBzWMA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HNUaaxZ7kOK8Vg6GXCA=,iv:mASSbJ1IpRbkE4ePLKrT0OX+amsRo0HULEqLcQzH7kA=,tag:QT5dHoTSidenvtk+kbsu9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T3Z1bzlLYkFRNFdIZ2lt
            M1BKMzJEQkxaM01yS0MwbmhwY2t0VnAwNXpVCnI2TUxJY1lnZklRNlVWbEk0ZUNZ
            Ti9NRzUrV0NBVDRrRG1BZjQ4Y2Fzc1kKLS0tIE5DRG94b1NteDlnbTFrZkNOa1JT
            eDB0dnQzTy9vOE9NV2hmTHhyOWNRaWsKI7pDiPny9McfB16KJSCwBikrh8qXsIGd
            Svo5zx+FISp4C/DhYZbMB/WSStq3w7WmivkCYtMJUEwKBs2VdLUm2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:13:29Z"
    mac: ENC[AES256_GCM,data:TMz6QNsjd4p0wjtKTJ/r/4OLCqvHe2Nj59M5LLSHS3w/0RwKRQ2Wjw83Q/0JmNVRSqE6piIj9W7pvmz9PyP2q0aCRkH00nMST1grYggO8GlMjz4MKRHvoxqG/OR/J0m20TeNkydeS3OITh7hqZ0RpuT+wIf1tIeQBHY8mtKOy74=,iv:8SrYdZr8PMFYLvobx5GF1b3UUSEs9k4cgTg0qf5ZXvs=,tag:P/BY29t8i8EZYttjBwNmhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
