kind: ENC[AES256_GCM,data:fbkmHiJ0,iv:pTfAHBSpbaOpdaBy5Z8BoyI5EUAvfO7K0UBRVeoBi+E=,tag:DwTl3MFzkddFmJFd22MQYw==,type:str]
ansible_user: ENC[AES256_GCM,data:wYJiX3k=,iv:1ohrYI7grCkzOBDeVDAyE7Qh9MASeuPOBeSQ+tZkyck=,tag:V/J56vin41+c3ijo2cSc2g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wRp9G9DuEwQfxQmGbqw=,iv:wglmZ0hlzXZ7sk6NfZHxmfM1kATdznuaPJGVh/3STM4=,tag:EQwerpqTuPMf2NwMVdTcFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRWl5R2lyVzBSMnR4MXpX
            bFpuL3pDMFltZm9HQzdwUWcrSTNPRG1IMFVRCmdWZ1dCa1I3SnpaWGtJMlVYakFN
            VTFualVpbzlnY3ZrRFBPbFlVYVJ2RnMKLS0tIEZySUJReUVXTnR0SFlTTE5FaDRp
            eitOWUhrUmJTcVdaV3kvKzcrSFc0dnMKitTQWdNA4mD/vAKeUFJVoElQvLUl1AmJ
            uUbhIEDCBfww2ZnAwiNh9C1EtQJQES5fZWa9ekVWTbzdl/UAivMtng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T18:47:59Z"
    mac: ENC[AES256_GCM,data:77pWtRaocSn5o3ddQBE3hNn4CBx3QdAuLvZnbnmY3IOXmw5Tv8knR7pODU/yrfPFgI5kSykNKkUjg4PZTmmmnifhXSyPENMXDTGc7CugH0+JuWsGdcn64lrz3QxQxBkswKU5pI/HpktEs04pCshV1J1jwHVdfWe3TixuT2u6B0E=,iv:F4NfENG6uCtSTr4yp3I9FqCWUcBBuwA308KUDfeRJqY=,tag:osinDn1DMlheeLQiE1/h+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
