kind: ENC[AES256_GCM,data:cO1H54ln,iv:MWzgLpF8xMwR/Ri8DoK3KUNpNmQiW3f71PiYni/HGb0=,tag:yNSQg7fsxO8I8OWHip4VZQ==,type:str]
ansible_user: ENC[AES256_GCM,data:qEtN/Sc=,iv:bgR6HGaYnqkaUjlm2GnG7ltiZKPja4OBDaUqqgS2i8k=,tag:jHBJFYssDjr+eaAMgFjT1w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:W3nCDakgkl6cUCMEZzE=,iv:7cB+zUtmdAnnq3PAXLjozEAWwPgicn1MagcJ87FLsBk=,tag:EKsRil5ow6uHbzh6oCNgHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcnRIWm0wK0NyV0I3S0s2
            eHp1Z3lDbjljRGdFYlhGQ0hYdUJubFdHbkZvCnQ4ekRWajEwK3ZyMklkc3BPazVJ
            VENzT0JhTjVwSmxYRHRWcFV1cFNNa0UKLS0tIHJOQzRLMUN3NGZDVGMwWC9iTU9l
            dHlQM2NuNWJDNG5JZzNqcFlkUDVIVFkKGfYSe891EiyFUFgZkvwX5QGbfv8AnCgj
            mWjPF7caa4/D/V+8Nnor/EmCTl7BPgDsTvPt/QFMHTI5R9M2x3W9Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:13:29Z"
    mac: ENC[AES256_GCM,data:4CU+jpl3WMEb43Zj9wV22Jl65qTlFxeGVLZLTL9LeNiYBjnACLOUZzzvCxbqERekhYkYRDiRc1CjHL+e9Iiqg067dh1kOY4RgqzIERrk37BBxSQM6y81jtzddexs60/LEi5mOe7OTw1tIfmoM0tNi6eITqfqJHQM9u94muIAd/4=,iv:Y43yR5rqIumlFTqRfub6/5ni5dzZFpy97LX6F6x/eZs=,tag:oHHdj7mtFGxlQ2RLzysR7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
