kind: ENC[AES256_GCM,data:C6g/x6eO,iv:VRMwj47sAaeHmJVDWzuqO0kcGt7D7RuzMAkEUnFqTc0=,tag:d4VrQmiS1Sp9dajRs9416A==,type:str]
ansible_user: ENC[AES256_GCM,data:4eMUf4c=,iv:VBZnyl19AvSO0hEAx2EiFvaQE6tc2jgp2lCM9xAyFug=,tag:QCJYU8j0Wcj0dsrHjkj5IQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VLzfDm/LMwLPBygyCV0=,iv:Jvjv5VNpEaGQzWHvrANvdDPubLGq5S7X2oEj7c5oD5Y=,tag:9S4t2ZQNhJMBVXH72u/5Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaFp6Njd2a2lOTkpJYkFq
            RVhPKyt5MnJjTkRaNzhsWEN2RTY1R3RGaGpjCkVWQ1lGMWlJaW5Ybk5QQzNiOTk0
            U003c1pIQmFINVFZaHNRNUs3Um05R0EKLS0tIEdVcStibzNUL2crU2JPMThZQmlB
            Y3hjRHg4SWNOUVpUWU45enY4UmxnSGMKBCWG49a0MwjXO8ITpH2dcdMgij+JbkSo
            ORdcZRHwZZ9amJ6pkcl/IjdhzcyWloxG/fxkySqXal45cIb3maSSAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T19:14:32Z"
    mac: ENC[AES256_GCM,data:C9WOjJ/Cxu1pHtN/r20mNadfBWzU4m+vf1TX95SnXmeyZtY3j668zhiMJoOj0vMwQvHHTSCDe2pgEC+kgS757lmn8bv/G1LH7+zEluxThDjdx634jL3apIAITuhuyAG2f/oFKl196E8zlh1yc807750eeZki9a0zVglUNi66NT8=,iv:nWNgnv87NONicwwuc/rxNvLpFnPKO6VX/0yKHJEyVVI=,tag:4IzzsRAR5IkZqqdnjGYIFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
