kind: ENC[AES256_GCM,data:XJLeXFRT,iv:YK0O/u6Lh4yTB5skfZB6F0r5/wEDIr4hLdOgFel0cmM=,tag:cfr8+5UeatdY6WmuAOpmCA==,type:str]
ansible_user: ENC[AES256_GCM,data:n05rnZw=,iv:qDJmpyAARi5TI/QyHrYWyW8MWb1Qydgs1L5OUj5zZXk=,tag:rmhGGKgfzpXjQD9zokSecQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:g60ulDtkrhTm6W1LYgg=,iv:DLhR9FCdNyenisbGJ0om1X/yitZmD8pxhEeaBIXkN/4=,tag:qYnJMEVWe4KkJetc5sBLag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdGxoRFdoem4xRWJJZ0xC
            ZE9NRnAxOU04OE1GYWZhVFc1R2UwaGxVekNzCkZkVXBuL2FOU2JuNXFXcFhqeDN4
            eGhvNnpZaDM3YUZoN2VocEJuWVhEQ2cKLS0tIFEvdHViTDBnMHFzMmhWay9lNW9P
            R253TmdNd0RKa0RmNXQ4dGE0QmM5N1kKb9mt7Blw3b6pOs54km56Yh5/cbLlGASA
            7v02Cv4dMzoomHLQ+AmpGEllBNGk4wAjhPY48KWhkYqoi6MvAn124Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T17:38:10Z"
    mac: ENC[AES256_GCM,data:x9aF/zVmwyJ0duip459tFjvOF9wBSsjjpUD3N8tDXphSA/WVcZOig47eAWpdvKmJVYG9hl1bmbEpoTSlWEP/UcMd3EYLPD3nF2XzKQYsasLMS/zq9xYy5OnSIFuXSlpvydmOaaJcGk6+WGXBZh15TlbvwozUt7uhybUKjJMrOAc=,iv:xnDZDdqcuiR5ps5dvRAn5vAKzAbPjX/uBsrsfZxkU0M=,tag:yhRjq1EeWWe7GN16oL7Ndg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
