kind: ENC[AES256_GCM,data:UtO5TH2F,iv:bGBHIyews9XvgzphHeFGxBvWRtUS1B0eTtR1jZjAhBE=,tag:+xuBwktHfkl6aSZ8S2epYA==,type:str]
ansible_user: ENC[AES256_GCM,data:6UJj+AY=,iv:mI3JZRvev9YjwlDNo031vZ1JcItdWWMvAkND8F+Phe8=,tag:KqZxF2ZH3Y5T5S4rsDEm/A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OIXITWW1JUX2RSNj1g8=,iv:6lkh6gTmABIqZPbugJkbILrbb5UZl9Dk6hkV8M61LTg=,tag:w1kmqhy4kjEFxa9EoR8UQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQkxyTkdBZFJPQlJYVjFK
            c3NkUkJoalhvZStuWWhCMlJES015c2FiUlFZCklka3lHUWc3clVydHlWSmpRWVpH
            bFZNYm4xRWxObjVTSWkvOUV2cDhYbXcKLS0tIEJJbHg1SnpsU1ZMdFlCOTNGSXlt
            S0tKdHZsb05NWnE3ZithdnVudVdSclEK5jVO4Hh/0PnIH4Spy/hGwzEdR8Vgw2BA
            EV/MX9lOuOTYiM5YoKwTxPKWsZU/BSt9UyAMibsgkckvVpuFf/FGNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T17:38:10Z"
    mac: ENC[AES256_GCM,data:F2ggMMZHnuOMzFCwQ+IYVXJ56S1QCXzjt8S7PxFv1duHnYMPvclHK1zGG4EfXSL1FHRUdYQGG+jm8uCCGnDHb0O1L9bJLIWZSLGRXQJHoNZui5RQGfVeVq5HsyrY7hHvd4SpxP0eluzbrnkVhQ9wU+Wa3rG1gKq/E1Q0yGl/tOc=,iv:xPlEu56HZCIyM7E+UZBYHB2WF9XJ/z5fIBDuxzcHhjg=,tag:OHQqoa7hyUa+B4Q0vLluSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
