kind: ENC[AES256_GCM,data:cvtJjbGM,iv:NJlGdpTZfhdB4045XPcns95UFBZOH//OAJbIDgeC98g=,tag:hmowVPy4xEh+6rH9J8AvvA==,type:str]
ansible_user: ENC[AES256_GCM,data:Rd/vfQ4=,iv:3BYkIdP+9g2hYAIH7eFJZ1phNoqySMVFd5gASvq7EEY=,tag:6zI3neYqv+NQVs8q1LtTZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Wb6QV4n6jdeM3kY1UMU=,iv:KmlgQe8TfbRZScLJfHsO8QJH+/gk3RgY8QbNv1/6n+o=,tag:HF/8ch7HJep1qX5ZTBq5eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUkNFcEdIckUyTjR4dmQz
            SW5QQ3NiR0N2WEZqeXZjdEdhb1FEdXVtTXhFClBlL1c0VmRJUjVldGJhQ285MVJ2
            Wk9sRFA5VWJMbTNjYjBTRnZXSDRyZGMKLS0tIG04OEprRjFaK3RrYnAreDNrK2tp
            U2VFMXRhOFArTVZ2R1p3Q3c3L2cvOWsKe3eDe5v/CKK0M9wnHpmeuybmw55j803Q
            CFkIa7M/C4Otrooj+xEgNUN9Xnld0k1aNUSrTFInawNddahX7ui7Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T15:13:00Z"
    mac: ENC[AES256_GCM,data:r1c3zl+fFTkmwDlzhB3wb3PLlGMuDJ0qBviQb7MRqGt2beguF+h7El1B431iJrDGt/YRcn7OAJ0BcqH9aJqIpIP5Fwtf00BdEfFKQTdSZUwsp3MgpG997RCMJQqL4VkSCpkI4yzDWevkSKnpPfqSL+Z6YkDDfd9AUDozCP0MVZc=,iv:e4YowaHptjJJtbvVLQeYj67c80LnGVemK+cadre4B40=,tag:KSxSS0h0VG681djpnCMARw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
