kind: ENC[AES256_GCM,data:DRaxH/Dr,iv:034dHvUWUiMdBlBhV5K3Toc/6lir1UrcEjvA/KFd+DM=,tag:IaqnDQdmg0mEDCPVBoAabw==,type:str]
ansible_user: ENC[AES256_GCM,data:CUmZc3M=,iv:lv0M8te7cB9HLyQkRyDkEhYqa972BdLgQNM3BHhta2A=,tag:r51+sHo/PnXfB7CIywk5gA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:eZX4DBHf7LG2kw/BVQA=,iv:DRSkfveaWxDJmMu/lX3vEE6Di4Y0IqUEmOZPNs5gt3Y=,tag:+YYBxpqolhNB2qgZwZRF8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc3Ruamwvd3NOKzc2dFJ5
            c2IvTjRrcmZBVm05aXZETk93NmlVVUNYVWxvCkZlZUtOTTFTanlBNHczZjZDM1Z1
            YUFKdUcvQkxHdy83L29YRGNiTFlPNDgKLS0tIFMvNTY2eGVwWjZmRVBPSlB1TlBY
            bEYyTWZ2QjRoLzZYRFJTWVBQZ0RlOEUKtaWQDSYxAMcJL7PC0EOpKec7wcThrSWT
            xUfXuAA+i255Q1cR8DBJyIXNL2gCvRP0WkpnJgZRUilpOGTRnfeMZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T18:47:59Z"
    mac: ENC[AES256_GCM,data:9IPpETgQl4FVmpivJ2t2cvSob0SPEY5l7zwYXIwp4pPXpGl+KaJERwsLhuULRFBVNpjlS3SKqZGRrAr+3DdXdx+o4rZpsWCw/ybdvcKKOTW0nGTVBitepB1TZfIh/YmnGvG/WcUhoS4Rp1nDmU65VZzwMNvud/XHTh3aRYIZ7uc=,iv:Rk6QUA0y8jmqRX2iK2syH6EzAax7ejMxuGfSIrEiG30=,tag:QUNg1gIESosxMNxR3lof0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
