kind: ENC[AES256_GCM,data:yIO6Ygkr,iv:P65L40Ft39QZeI/7kfcAotNOBYytGlq1fN1Izhc/X2Y=,tag:KWihL97J5IJHtzAMNpc2PQ==,type:str]
ansible_user: ENC[AES256_GCM,data:4SE8bHU=,iv:AlCFc+d6oUUdtJJNWr8LgfVyvaKRYkCllYW6Zu3QLPM=,tag:Fi5lUZk3OV2qU6UvJAljag==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:EBdFUAjGTCBT9KaieFY=,iv:Rf5YhvtTVypMk8vGh4uYWcF5eRbSdfLExkL3FnyHdi0=,tag:ko5eM/OhcBmQp4+nokxljg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwLy9aOHpud1EyM2RXTFFG
            NzYrMTg2cnRXNnNDb3dyZE1JUE5vSXIxMzBJCk1iVTB3U2tQNHI2Q1dHTU5VUDBS
            RklEeEwzZURDcm02VS8xRmpzWThmVWsKLS0tIDJJdGVBQllISS92MkxCUjNMd1FM
            UzBTOVJXTkVQMVVXZ241VVV2ZTA5QU0Km6q3fNKnLr8QEPTb/KdIt32ttMCOPuhP
            X+itY0y8KXmNfEKAiqlczIAQ9F1Lu/8sMDkG3pLZdE63mw6bXODR8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:56:23Z"
    mac: ENC[AES256_GCM,data:GDxfGzhVowywQ87BFJZIe5DOhsdhZF2hFyh1aCkeDqDRtUw1RaKagbQnoEB6xb4ux9E5Bdr2r5DhAKPYaPTm7rM6SrmtsLC8TDel8XOa1wrqqVaf3wJy4iCuYueCSKP84e7+yv2LFyGt/HGIya3QDK4+LIsGKh4niJKPXmazSSE=,iv:81nnSYdKYh6UgJxFu8r8nHVPYe88BHttJvBGcPjrosM=,tag:HOW3/zhNoMhax8ckSy0gcg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
