kind: ENC[AES256_GCM,data:BRLnU19d,iv:9Fb3VM1X5u+7cfFTzowC91Sqkg1c2GSIUGs3yGG5owc=,tag:1VSLULaNReCwGYmmqzYlAA==,type:str]
ansible_user: ENC[AES256_GCM,data:o1FbaQI=,iv:Ys7zbEF4E5tcY13E9UwHh4N/UwqWEFPP/COZcjcMPz8=,tag:EzKxYm/uwsTE5TIqFrrzEA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:MkOxB0zpEPWOx0QV7fU=,iv:9CG+vrYce189XUTdPUgUHt69HjQGLzQ/g7xGiVv2aTk=,tag:5j7MmQMTJykAO/z/9yLrAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacWM2cUIzc0xTa0lxWFVZ
            TjNwMnhBcjlaVkRTYlg4ZU5RWm5IRWh2bkJFCjZXT2ZKbFNiekI1dkUrNVlYNWk4
            RGNCMzJkdjJFazFKazhObUZnTGNCVmsKLS0tIEZtOHNJaFcvbEdseUhWNUFsOFV0
            TitTSmdCTmtUNE5PODhCNCs3N2JIc2cKstHtzMVRokleErTEUkdOl37vBx64w+rN
            wTcAEuXPcZ52rmHIvnIUIhlMStzenoZqqhaX1f/RpelXIVdfeSM1PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T18:47:59Z"
    mac: ENC[AES256_GCM,data:4+prZXJtExQYHPCndRRWCK1SARl6nkAGQTN1hqgkk7YoEuHN6H2bAisyMERi8KAf905dgrg3qUN0hTB9wy9U2mlgf7ZkRI7gCMFkEsCpHw+0JnPZhL1X+QOqW9nbYzMUms2imEZY1Oim17cZYnLKAtZscQWLWo4Lbge9raGLlHk=,iv:Ct+y89GSx3FG/kepKescU5etBYrvnBcv2yFjlZOa0o0=,tag:9G1Xmo+hYSawMySLkro6Mw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
