kind: ENC[AES256_GCM,data:DmOZ8rlA,iv:YbN3dzXeBsgt9IcT/ir/qNppRJwS2JgxTYsWqGTE8L4=,tag:wBtio/4fXfzSwkkM93/gCQ==,type:str]
ansible_user: ENC[AES256_GCM,data:Yo4N//0=,iv:HjvP5rNvEQCvPovLPbMJSEsmmTU3u4u+SMkcHtNXa0Q=,tag:sZ9JfPaaVleNOMGAa3wQrA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4x1+IWcRz2XPufi8t9A=,iv:pcUFiFc/DvbaBGKu6X3Q9/FWgKhnVb/NanQNbIEqnxc=,tag:a/3dKc9d5Sz3qunvTccb2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeVp1TFV3eG94bko5bkhR
            N2c5SzlId2JzSG1qVzdwdWllYmtvRitab3hjCjJ2QVZrVnlTZTFvTmNheUJZZzlB
            WDR5dHE4eEszVk1VVzdpZFJpWEFLczQKLS0tIEZQYytyOGRqWEErZVJuWm9xN0k1
            NCtuU3UrZ0xzVFR6NUZ0WHJJY3oxNlUKIEHCPmNqvQVZkT0IBVc6zJHGybAsXpQL
            pdGAF539yaKPxtO6p7fArxMfUak76X4/B/IVapA+A15pe40Wi9cwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:56:23Z"
    mac: ENC[AES256_GCM,data:Esaq3KbiJVS/Cw7H47vQ0/C8sETjS2CEiqmbHwtX8/uhjHyXCoahYrowLG2tHtLqkfF5JWFjnK7/0/tg4y75qn+y8sva7mu3sahiFJGKd9IOej/9ecZmooDoCTs3L9s3aqI8fO8Qhw0YxRgkGFxImyVmY+Ylz5FRD2jnOfRNKjY=,iv:7culrTQnAr0qMQx5sTiuHPcu6YyK/Tnu17mRuQNhs34=,tag:l3xosi7gJjZQGYo0+v+/fw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
