kind: ENC[AES256_GCM,data:VAfH3DA5,iv:B4SbA2aXF7pwoxHYbE1uA1nM8DJoIZI366kKI5Z4zRM=,tag:/xLugB8SiXaABumnvud2qA==,type:str]
ansible_user: ENC[AES256_GCM,data:s1jMyQc=,iv:TP7gncUFeGlpb3v6OAodQPQ+gh4Cgtu2mJZbl++mZdY=,tag:z+LAQjk2NYFA128Eq45CnQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qkUlwbvWVKzdfJoGMpo=,iv:9qPz3CmpqhN/HxnKypovvTpbXIQ3R7FOL5glq4NWpcQ=,tag:/ejqlYQ0Dnb3nnM5wcjuXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MmVjQTRPUHV4bnBlZEZt
            VGxMaWFVUCs3UU1wd0x6bXBPV2x6VExxNTB3CnpBMElJSStleWhoeXpobDBsdVAr
            bnVZWHFremtycHZxTkJ6RjlkcTRaamcKLS0tIGlIc3RRcjVIZzh0MzlFR1pZUDZD
            bytxTjFXWDZWK3ZydkRweXBFTkJ4NEEKpnPbSQ5IyyAsVuWcAk/5aH6MFwSPF4gp
            Xjdgx7cj4FJoPFaS91deZVMqz0sII5rzHp1PAc/LfiYNmpdJJCOD2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T00:17:59Z"
    mac: ENC[AES256_GCM,data:gB78o9vYVf/YTp0iyfnPVAgI112S/Mxkx5U6GJ1YYEm7O5Q++ejOAX9KYKC+HY2I+kCJoMPAeXdg1H94qTpE2s/djHqS4u0Kl6s8gRMTWU82f7XqeLU7U/rFwJgYdy5xSJpyyi5P5GDD4XyqSLxV/IO9Sy/++VftNoUJR1EgxGg=,iv:k+K+80cy3XnRgd14f7Ie1XeqGbf3P/OA0oaMa/uVzOE=,tag:BYuvD2bVcdcBL9KFdCh7Bw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
