kind: ENC[AES256_GCM,data:GZPmhZan,iv:LGGa8LNGiSlq6+aKhJbCobaRHnYgrVcfkVw0/P45Nmw=,tag:y3bDsvDP5xuxWj8tMB+TxA==,type:str]
ansible_user: ENC[AES256_GCM,data:XV9QVWY=,iv:k/rgeJoH7YEI6zcVv2Jv4FD/6O7LFhPy3af7jnzI1Jg=,tag:XIsDbjvPNviKVMfxroiIlQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Z2Nw6e4zRW4pKz15X38=,iv:x2jZfG1v4DbRiXGLiELC67V3sqVLRN6o2EEYjf5gIFg=,tag:2nWXxN+ZFnDHshOTvX8uQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaThOaDBhdFdzajdFMisz
            a0pSbXNBWkVpaHpNSjMrdm1ESnpxMXJEYncwClp5QUNlOFVsN2tubHJndkppWDRY
            b3lxSFlpM0JCWTBnRmdTdmxPLzRqcmMKLS0tIDR6elZZQmFLT3VDZk5yZ3dGVFZi
            OEhJN0MvV05aOGVtRmNydmJOazdiS2cKfzWrCXPpZ85jS6u2VRU0CezVkKp/jOXz
            j1FZU351SRm4ebFZ9dMoBkSAdVs+0ZZRExnHymuhMRRiMROB/pYG5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T00:17:59Z"
    mac: ENC[AES256_GCM,data:rjBfuAU4PFC5ObzlCUq6iPfVHJ6LRAfNOfLU8/R18+bS72Uo2K+Q3neROEX7fXvyCsxd4pQULybvZ1HqEF2yUgdcIzYq3sBGwqrGCtX4JXdw5kPJR2hqoW/tYR5ECIQI3WW4/IOENTdiH8fIezhYZW5vOQYNA07XrQgIBpeu2TI=,iv:VLeQUSwN7f3hPsREJ2V+7O6A8mavdRzmKGiFtAFXbZw=,tag:BjMI37y+6Fo+lWn1CQJC1w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
