apiVersion: v1
kind: Secret
metadata:
  name: decluttarr-secret
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:GN5co+Wm6FIIU9wc7/OWbubRwMa2KroX2MPIy6AdVU6Bgs/Dd9XSl9SO+SXmIARlIWC7arkodJIFsC+p/8Z8G+fyaUXM7cw1T1XYBTfbxp8yeXJlJ9bGzGy21HXX+hnlgjAI+H1C20fWyt2d734+UKtuoLkDmM1vgqCsK4f4mTPJk+KOPkBnpr61NBePzLyy5T5doUbZaVOCiqMRgMqZBw9hiMgsArTkUU2+2bO4xFcPGWAQQi25MtA1OSS1sG7suZQYqvC/HuqMBQCOu6w4NH1vmM+BRTF4AsE6EqCH2aFrtx/mTWV7XVYnjOaEcXWQ/2OUvknr9wJgrpPhaoqbnMsg10ubqo+QNcjO37GsQpkOteVvV2uLxffG50uatoMDCyY3Y4wMEO6VZZwnR2S3Wn1C6MfJiBuGG9XF2++2s/75vj0338TAB9CPFCu6WKCke53WbIPE9UsV3wjvr03vcq+biTNVFxEZ2720tXf62Vj6VFfpXgJr2lKiWRiQL3xXy/1PSWscuaHFC90pz9ThIXG6WKQN/biNU446lpQw2PjzOzkWmBuwAKBYeHJ+uI9MCLdX5OJnJOTntbN8t2rLEizBk8TaLSxjFunh5LJ4i92XXkB4H/r5YcsrKcT8idi+DTz+hUwIZrIChN4XaRzWnAdO5rBkmzWvz1PhqyI4zySj3+VPCgfB35x2jWYsfJkq75Yqz7x62ZiEXVst0ldAmnL3VlKxqEz/sx+i6Tgvar0ZQPJZNiUliMYbhNXU7PKOEqOJEApXSs3wt9EjYJw14dNyvuXUl1Kdk8Z7A9oHY/3lh3UtoSGAysCdmT9Z78zSDsIaAkwXujlMDnCoakym5Gr4BM96sWGwElEnEqmMaL8G4U370oOi2uomit29o/GayvNyp99EytDzD1P5aqV4K1nJ/xwmvVegsmqI9gCRAXAKx6+Hoy/sBfeUBUT0gkU2a6ezpwOBkxrAJkM03lDoKn+JrJEftB9sHY9Hr2BCYlGZ5QoOwZx1Uzqd+OXyeHPxz36EkZM=,iv:J8t3BPvvq16jf/GBhMJ8Xz1sC8eAQMzLb5aGmvNzKm0=,tag:8w8V+XCJUaKDXqPHcMKBxQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTFJkUXYxejRaRzFnTWJN
        bk15TWoySE9kUGtncFh5bHhTbmNKS1ZrcTE0CjhTSE5DUXgwaUJPVEhPQWU4R2d4
        WWhHWlNLWEJUdkdMMC9BZTFUZ2x1YjAKLS0tIDdCL0xEN1ZlVzJVWkhPblA4Y1do
        RTVwWGhtTkNYa2xvVDZMYnR5ZXg4OG8K+lvi8LLZhxClsQqk3838Auz6RWW29jgG
        38US7PokYOoHVsKxZaOp/Re1coZqKbqvvXQa372hC5fLNq39hHSbCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T23:16:27Z"
  mac: ENC[AES256_GCM,data:O0ji33Fo7hhnUR132XJc4h/YPeuZTkyAUu5fS2o4NYwtFyk53ag8JrwYCXkY36XCZqOaGRlmGra3FyfRrVszMEQjg/e729Juo9XVKS7ZReCcmVyo6n0ztCXRtKunNQ+IaZHXQUUlIipSbQq/BQlG6CU4k3MbKNaDQhYZ+IX2KHg=,iv:1lBId8mlJVhHTG00oBaRGsxbdgNuNVdklrD77NmZ7DE=,tag:50G6YZj9578p85gSkue9YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
