# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-home-cluster
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  driftDetection:
    mode: enabled
  values:
    controllers:
      prometheus:
        strategy: Recreate
        containers:
          app:
            image:
              repository: prom/prometheus
              tag: v3.4.0@sha256:78ed1f9050eb9eaf766af6e580230b1c4965728650e332cd1ee918c0c4699775
              pullPolicy: IfNotPresent
            args:
              - "--config.file=/etc/prometheus/prometheus.yml"
              - "--storage.tsdb.path=/prometheus_data"
              - "--web.enable-remote-write-receiver"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: &path /-/healthy
                    port: &port 9090
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
    persistence:
      config:
        type: configMap
        name: prometheus-home-cluster-config
        globalMounts:
          - path: /etc/prometheus/prometheus.yml
            subPath: config.yml
            readOnly: true
      data:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/mdadm-analytics-storage/prometheus/home-cluster/data
        hostPathType: DirectoryOrCreate
        globalMounts:
          - path: /prometheus_data
    ingress:
      plausible:
        enabled: true
        className: internal
        hosts:
          - host: &app prometheus.davidhome.ro
            paths:
              - path: /
                service:
                  identifier: prometheus
                  port: http
        tls:
          - hosts:
              - *app
    service:
      prometheus:
        controller: prometheus
        ports:
          http:
            port: *port
