apiVersion: v1
kind: Secret
metadata:
    name: autobrr-secret
type: Opaque
stringData:
    AUTOBRR__POSTGRES_HOST: ENC[AES256_GCM,data:94jp0qD6V3pA3DTVOshV/kWozEwG4yCowaA1k6NdUBRdJE0Se5h1FQ==,iv:wW04iLnrI5smE9ufqgjgTwQQ8aRwzNISZDo8vCigFqo=,tag:85ReIQM7iqhzdeikbGwB4w==,type:str]
    AUTOBRR__POSTGRES_PORT: ENC[AES256_GCM,data:9o4UtQ==,iv:ktyTk2/n3Au8poCkYXi93r4lh9jGgSzu+Uyf4EAOdQw=,tag:2dm7pIxrBkvMK080M576aw==,type:str]
    AUTOBRR__POSTGRES_USER: ENC[AES256_GCM,data:uxkoDZHKZA==,iv:74pWBb2MsjDG6UnfIT3U0S6At0xIl6AqHBB+I8u+870=,tag:1/WPX53nVNZil7UHrwSc/A==,type:str]
    AUTOBRR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:TuytrAze8E8=,iv:l3aVuAod6Zq8rx2p7hijkysNIPiXEEkGmsOY1MVOpzw=,tag:Dl9jK3Vs/M/Oi5OxMAEzQA==,type:str]
    AUTOBRR__POSTGRES_DATABASE: ENC[AES256_GCM,data:xusQCR+tkA==,iv:5DGRqBHz4bwbzYRC6YHBlptG1fAMVUXAhNzU3YGCRK8=,tag:dLwYPdRmCg6QSvna2675qw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:QStcD3bW8A==,iv:FZDqRuQ/QaAUjOokZRQqEbRF3EPBPC2bovxNlXA/P7c=,tag:4DSfQEnCZlecBWNF9eF4DQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AgHkeJMUhDEjwNBbbG+LuDBcIeJlULM1bXilh9SKOphqpF+nmHSePQ==,iv:di+rLzaQJ4wzC+m84o9H9dJO043Izv69DpVNSrg3DXQ=,tag:OzPtURI0FA8lu8YMfyCBJA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:8enj48yjGA==,iv:RTsf7EvkXXo5RmW6lu/QaYVowppmFmyOMkff1dvtjZo=,tag:cgO55bYdJJwFBdQ2IoIRUg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:27:11Z"
    mac: ENC[AES256_GCM,data:GpEnFO7D82nRDoHEusrgile9MJdFU2uy6gYH8WU24PtjiU0nDr2/kfUdJXKfCHR4qphJQQZ1Xr5/kO37zHT3MYAFQgaqZtcACoaqCW09WH6BtIH4sunf8BRwlcfH0YErNurhBvuLgPhbRnRktYDuvpGSV4/wACavb22nP2KV29U=,iv:kdWbIz/267M0YCoaFnRXWNo9KY5yD79bubN3T8+WoVk=,tag:7j4M9Z3PNcOYtDLvQzlAVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
