---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nextjs-control
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: nextjs-control.davidhome.ro
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: nextjs-control.davidhome.ro
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: nextjs-test-tls
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextjs-control
spec:
  parentRefs:
    - name: nextjs-control
      sectionName: https
  hostnames:
    - nextjs-control.davidhome.ro
  rules:
    - backendRefs:
        - name: nextjs-control
          port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextjs-control-http-redirect
spec:
  parentRefs:
    - name: nextjs-control
      sectionName: http
  hostnames:
    - nextjs-control.davidhome.ro
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
            statusCode: 302
