apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LHwFyIW9c3NvrqVm7v0FzFszU/t3BiOalFD5TA+lOyj9rxKZ,iv:O9b1qJbTps1708CR7mJNE/ltGxlw5uTDkM/C/ap357Y=,tag:p9vjNVtXDZIL7YFAkdcS4A==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:IjKkf7erYW3nmozIVyWApKSaPxK7IS8K2MVLooofLvqEB/79kdjAMk9V/D88VQQgNJZcnC3nq/1kCSoygpZhXVHtdXO1rU5XDJSadnXA07WygZwlDof2QgLx5LKcJsF3muu8PR9LSNeW0ptWa3A8oA55PsvLvR0iokx6iogEMKIqeeg+kK0Dgl/WqsxgFlobra2uNGPNo2zEOnRQSrIORhcsc4BFZVDHsH4Bq1dJoxf+GmEVzmKwdw==,iv:HC6iTvqBi2CYE8EHEfK5WGldy37XlpwSo9NkyWa0klI=,tag:s6km1nuLK+oQ8v8nL9EGUw==,type:str]
    credentials.json: ENC[AES256_GCM,data:vNYgibv9rr4RO1v1qC1ZFuLHTYsvOtF79sDb3Lb3a0GFCr0d5clEda8iQf0GfczlXBn5UOJpDrXPeb6bHUgtHCJ0WQDKOrmYre0Ab4egAcZvF+FqL/ssN+WxL84OZtj3p3G3,iv:k3PqrQBKyywz0pSPpsaNzAo2SMGxHkT0GxQeK1PwZlc=,tag:flM3s88OhGfSEtaSxaLPew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdWN6YlRabFdESzNyL0Ju
            NGpWYkwzdmtxV0R3cjhRaGx0M0owbnRnY2pFClZQcnZzcjlNQmtDSU9sUC9wbFky
            N3lxdnhMa1ZVdHc0OXRZWlZmSUF1aUUKLS0tIDRHbyt3QThqTkMzdTVzMmVCZVRG
            ajd6T2p5emJxbzRCdWx2cjRNMjhYdHcKMcLVPZwbkb+7tupVs4bCMQGQZ/7U+ND1
            FtQrI7AVYfOISBmSva1oCQJADo4BfMg8RLc9SbFBRccuKj6eeM8Fyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T20:16:58Z"
    mac: ENC[AES256_GCM,data:BW/bV1AMp6oQ9WhC8Ckxfcm7+1aefE212UhyZnloqJoXCo2H5u7oiLGtR2zy6pD1R/9UUGSd8k80XcpbFFiSsU4Yyc5oGUMaMTRH/tkXZRlThC2ABS8k48ctaQxZFZURhvgDhEDgK6/2n1q/9rcQPJ4OaY/0Ouk9aJt+LJWw2UU=,iv:QIwdUXPwgWYYiqTFoc+zsVVQGEb34BTDbLj9oKFHn4U=,tag:i/4dNrkpOQmqT8t2cp2TYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
