apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:IvesQr7AwDAKsf/t/MwqYgzkG+NU+Fxx74YrvO+jD6vtEWf0,iv:1B9dKen2oSOFbToIR/tGFtMzjuna+yARzZ6VYJDgL5I=,tag:f5GfCEhvmNzjC2aykB8OYA==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:cHSOMKNHxH+X8QjYMO6uywjf++q7dsUx/SyG2q35bjPOH2rXHFqy+MGY+kR++8gRQZqDB9TuSXdUHVL+udpk/RJZyv1oYKXljTUidNNhPZ9XN7Lp43OaBzyK1B3SSGy+NegRGCcCv+67EDIQ5N3kcZBYzySN3j38kqf3UGdpX4ZRzk0ME1tqj4iGMY2Vh8YaGZ93Mrt+OuQ0BPPNf5Hpw/gAe36Ukyz0YHcWeCpNzyEvyScB3iJp5Q==,iv:dQPJCyCQOViWZwuMTaJ4r1B4ZiOrvtbXoY3pWS93wGE=,tag:yJ4PfMAd+ezbcdUKbAZvVA==,type:str]
    credentials.json: ENC[AES256_GCM,data:NkmcoZlq3ulnIOc+PuKdKLZNQtArXZ0WDTzNCT7o4bbSKpfEA7FeTlVYKU69JSAnJwWvsFZhYjQ6g+QEtGO4kkwN7aMem93NfVXUReh7iH+Kx//Qf0VQOnfvOvAYhhUMGA7J,iv:D3lWPJ2/PrqPrrBQBBbVEPuFZGXuElmH+rrJJZ2skO0=,tag:DOamsYs/W3M9lutKp06sug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U2wvSVB2emJac09vWUVs
            N2cwV2VOUXA5TnQvbDVPMWZYVU9EMkhQOW5zClUvVWVqdVBIOXVWMXpYeTNkTXp1
            NDZZa1dxV1NETUVUa1dIVTgxWVJ0Y1EKLS0tIEpYME55RkVlaXIzUlZxSmpkY0d2
            R2FRdnkzS3YzTElIZ29ka3NMK0xMRGsKIbpxIbos008LbjIB3jUbWTzi5RP4+VJw
            GZpVAlGR5h5B7J7txgnVaioBDvXCix0vRxDwyDMJDwY7DojDiroy4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T20:03:40Z"
    mac: ENC[AES256_GCM,data:C5zw6xF3hBXXyHMeOZzR5p8M0ujGDb6/UaVGYEXEc+p8iNT2Rs7AejtdbLnlJJ8aosLDq/Dahn7IOHwE/9aL0uOj67f8+9XkHRPig5mC8SvX/ytoKKTFqH64gbu7ZP83xOge2S3/uFEGKGlioV+1UpGPHJ+W63zP/v1Il7TrN2E=,iv:bjbuFjGJQBE0mMAFSAJx0ywEzG6Iv0qTICc2o3KVjf4=,tag:K+8/CkSUB9YIC4fUDgo34g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
