apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pFVMPpmfd/vkvZKLHCRdwCwW6I1Zn4Zto8GN/5a6kRmWWfHC,iv:rCRnta4AveC1A3075GUHMoN0Qh2WRyBZN6EO/dq8hy8=,tag:+m5lePgt+xeVvZO/POz1Ug==,type:str]
    credentials.json: ENC[AES256_GCM,data:EHQrU7QLTFGuySRy7l8nv8Wu9Lig+oAsqufwQKSFwkgLW8hOGQFcrpLDZRrxr3oHotQ56LfN7L/u/7G0g9+e4nK/VOeyiRjooOqz8jvkXYN61b/aalYuS32p2iMe51MLTnh5HHgeSXQAAKEqrDCZ1XppiNKjcNp75DPzIuk9u/ogAw7orpEF7Znwzi/HTTs1KbJHXL34/w+l6Qbvx2GPvy6rjvHWb6gFrItrlYlpYA==,iv:YUUavt1kvk/vxn2dcetWGM74w2E19ngox9kE9c+IbP8=,tag:KpbI/DtslGVI38dL9WsNcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QVdLUTlubDZWaERuWDdM
            L1hhRkI5alNCSlJVb2hhZ1FIQldlaDhueFc4CmpvQmpPK3R6TGxMWmxWZXkxMzJW
            WXBTMStLaWp3cFQya1hSLzlHMndXZzAKLS0tIGNaRHkrMFBjRnFFdjBUR01Vc1F5
            TG5CeWg5OTZJZktZM00wdjFUWXprMWMKF2dhZfCb4bXGtT6vOdcBbLkFVt8zDUoz
            wzIVYxw42ZX3BxxE2trlZvE4E1Lgn9O36DsrAiyyajdIYvA0D9w6fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T14:03:39Z"
    mac: ENC[AES256_GCM,data:FJX1oJpMh3nQ7gDAwf0P5PpB2LAwG1SirPD1zkkyGfYyNmLhAnPiRhv9ozu0ymqpTcc0FhqGa8irbyv19Ui+0M6FKicutS7KNH7r9de8LsD+nVElX1+c86ZaFZ7rV8XLFslQXGGvDLVsQn8j+kOAwEMYjBx77Lxf/fslyDf9rOY=,iv:mAzxdc3Kzoq1mqJg9ofyv9NdSa1ozp70R+fpxxKnW1s=,tag:/R2Gd7n60Y1MMv7E7bCQUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
