apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: hermes-friend-dispatcher-auth
      namespace: hermes-friends-control
    type: Opaque
    stringData:
      runner-token: ENC[AES256_GCM,data:JNc3gXP9DC/QaGmPkLgvNRob/1fl32qVy6jDKk9pzLlvxKWafguBTtI44WxgGWVr7QaJIndx6e/F+6I47mYTtw==,iv:Gvb70tU7JgIj+TSW7EWrPvMjRASE9qDDd75dkaO/E78=,tag:Bq86qKfaj3/ip+0+78Bmbw==,type:str]
  - apiVersion: v1
    kind: Secret
    metadata:
      name: hermes-friend-trust
      namespace: hermes-friends-control
    type: Opaque
    stringData:
      approval-public-key: ENC[AES256_GCM,data:s8vAKdO86XI4G/vaxlMMyNvkSYhFx1fJfNNXqvTRhH1qQTa0ERNd/oekibv5384USCGe8NLmNCy1e1GFnrJidA==,iv:uqoZcSZHC2f1kUbk0DkTBrVJu8j3hoQwqI7znnmpqM0=,tag:yxevGn8kH0IW0qpmqLpsJQ==,type:str]
  - apiVersion: v1
    kind: Secret
    metadata:
      name: hermes-friend-model-relay-auth
      namespace: hermes-friends-control
    type: Opaque
    stringData:
      api-key: ENC[AES256_GCM,data:mxOngtVOVdVkUUTPZf7yeUKT+kJgmOgdY1J4tLmnXCmBLdVUeLFDPHqmKixU/V77vXc1gA==,iv:qtU5QU8unjkdOc/8VvCqlYqNLxAvpYO5eK08geFU9nE=,tag:0I2Js1pY/hoKocIA346LOg==,type:str]
  - apiVersion: v1
    kind: Secret
    metadata:
      name: hermes-friend-trust
      namespace: hermes-friends-artifact
    type: Opaque
    stringData:
      approval-public-key: ENC[AES256_GCM,data:s8vAKdO86XI4G/vaxlMMyNvkSYhFx1fJfNNXqvTRhH1qQTa0ERNd/oekibv5384USCGe8NLmNCy1e1GFnrJidA==,iv:uqoZcSZHC2f1kUbk0DkTBrVJu8j3hoQwqI7znnmpqM0=,tag:yxevGn8kH0IW0qpmqLpsJQ==,type:str]
  - apiVersion: v1
    kind: Secret
    metadata:
      name: hermes-friend-artifact-signer
      namespace: hermes-friends-artifact
    type: Opaque
    stringData:
      collector-private-key: ENC[AES256_GCM,data:0fBzETRP4cfjkC7h8OueeTwRicBnCRNDr/RlMZsvhGQHMc8oplX6gDvhVXO7uazmPVQ5LL/9Yv01ap3RMPnqmKJb/3eyE8N3SvrWwMDCjbdsMPvbjjFiId7dK8uiirtPmSnaomWx34lcGkUoGS8Gnm5xWt68nF7YLEhUhWdYQuU=,iv:4zmNcmXXxdFSrCzodnT4As2sItfCs1N7USafPRp4kJU=,tag:8bDSkB9q3M22sTGjmpNKdA==,type:str]
  - apiVersion: v1
    kind: Secret
    metadata:
      name: hermes-friend-trust
      namespace: hermes-friends-creator
    type: Opaque
    stringData:
      approval-public-key: ENC[AES256_GCM,data:s8vAKdO86XI4G/vaxlMMyNvkSYhFx1fJfNNXqvTRhH1qQTa0ERNd/oekibv5384USCGe8NLmNCy1e1GFnrJidA==,iv:uqoZcSZHC2f1kUbk0DkTBrVJu8j3hoQwqI7znnmpqM0=,tag:yxevGn8kH0IW0qpmqLpsJQ==,type:str]
  - apiVersion: v1
    kind: Secret
    metadata:
      name: hermes-friend-trust
      namespace: hermes-friends-publisher
    type: Opaque
    stringData:
      approval-public-key: ENC[AES256_GCM,data:s8vAKdO86XI4G/vaxlMMyNvkSYhFx1fJfNNXqvTRhH1qQTa0ERNd/oekibv5384USCGe8NLmNCy1e1GFnrJidA==,iv:uqoZcSZHC2f1kUbk0DkTBrVJu8j3hoQwqI7znnmpqM0=,tag:yxevGn8kH0IW0qpmqLpsJQ==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNFpCeUJ5VS9SL2ZRQzVr
        MXdrYXB6dkVkMDY1TlZKcis2QTc3Nkx6TVV3CkpJNlplRVQwbE5sQm9kNEY3cFlG
        WjRqRkxlcVdORnRrVkFSaWJmRTA2YmsKLS0tIE9xeG45TzF6a0ltRU04eFBIcXN2
        MGlwWm9HUmVZRTMyeDdhaEp5WXdxZ2sK86SUmhg2k+cx/fg8L3p+RDzA2mBcAA48
        gGGGHUOD9boTd3ZU5zIyG5dEhCNKGWChvB+FzlwDM3c/QhF6CtCj5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-23T08:43:31Z"
  mac: ENC[AES256_GCM,data:e37HILNpS5iPukE9F5+jmrL0rx3Rq+M5Hzj+qru6Yk8KvmwPaUaeQ3iGZQH1TGVtno0HcyIATOjUg/NjqD26+G/6uSsW21N2fg6UM8YGRV7N24WW72kNID2l6EEM4ddmSR9cc96024Gf8rijl7toxj4G5s4zirsMoINlfQVbn3g=,iv:lKtLjKrCBuAzUE2psl3Z4C2ldzBF1l3urtFHFsujNIU=,tag:8crlRA4xtTXg0ty5Fgn7CQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
