---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gha-cache-canary
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: gha-cache-canary
      app.kubernetes.io/name: github-actions-cache-server
  endpoints:
    - port: cache
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
