apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LC9+ehOwI22Z3+5cNgXqFahzFlh9/xniDoFyXTAhPG94jwqR/PHSLg==,iv:7ll6/DcDgp8PZMeavXwXF04YxefAxySAasIOu7IDck8=,tag:fYltsnj69Bcgx0ThhpYPnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0RpTzZlNGwvOVk2L2JQ
            SXVYZjhScVBlV0dxeXU5OWdaeVlSNzZaaVdvCnQrNHhteDUrNmdoSDF3NEprdDYy
            cVZoYXlzMk5XMkIybHE5WDExQ1JIU0UKLS0tIFkyWnBqSWVlV3RrRzhLRU52Yi82
            U0szNmZUNnZQMVN6NlM2NDArOUdoRkUKruz14B0WrhTdum3JgHUkJsfpZVcAbLLV
            PzCc7Tt8wOIjXpW5Wlq1/YNGt3zmAeo+4HJubzoXn7G/bs8f4HcExw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T22:31:18Z"
    mac: ENC[AES256_GCM,data:zCuxlhb3LWGvkroDASlh+xvqhgO6diHoJso52YCTvzaysINbtXLlw3QYVWQn6yXJWdOHqHaSO/b7Lx74K4jK0OckaVjlhpCDHtVMfpk0zhZs8q0mSLtuIK2lzg5P9hc9M/l2Nf9kiX6TkbuZGwyhHi/5gmrx71vdwkZxmbGVzD8=,iv:oxyj4LTz0PG4UfCtbMauHoINgcnXEw3wlPj27gbrlME=,tag:SSTMwjKSiDEd8kW48xWtgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
