apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:v+LoYNrGJbZcq+tC9oKMxes8wes0MqBrfWsE/QH9ymr+ab7u9qVnyA==,iv:ZSvnB3p6VmVwRTCicRqxjzWPG+Xy7lMXVqwVRLw2xFQ=,tag:07+GlMtmNiJgMWE3q/u9Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERzF4TUZVaEJ5b3BKa2g5
            N0ZsQzVESVJuNW43K3ZsZDZLUTZvQTJIN0hnCm02WUFPSUw0cENab05vT3NSR3pl
            WWJOQ1VBaUMyb0Jac0QvOERRbDBYVzgKLS0tIEtnaktqWVc2UTRkMkhLd05WemJo
            VnQ4OWF0QzhyQThMcGNqbE5JU0t6ancKgsDAv1tWpVF+soqzVWutzdZXcXzdnNgG
            fs5Clem0z567Qkva3QbVixgVKd7GVLw7bN9BCssKDhSiXnI2060OcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T19:14:32Z"
    mac: ENC[AES256_GCM,data:2QsUiHfR347+pTedp0bJzq0HR4muZacYw53ftMvqztZs282pGLlYRNzN650+REQLMbXksOxbeGlmSt5UWiqrICVoSRIEGw9l9PU0mSeQKQVp541Lo7WU7GxbbTPy1nHmwvQ+koPRcN2xFOgv55CFiExgUl0sejO7ey6LvkygqqE=,iv:gz94u1tyGlaNYtAf9Z5UwpNtOLirsY0YrXqPP068w6k=,tag:cVcpsQypK30tNpa5/pO0Zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
