apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:E+4rkdDav8I4EpDb+3Orn+VAxCjZ8EG4BhHm3AbkDi3aSix15cYBfQ==,iv:Oi3zBX9JJBGsK39ueiNZTBoB3jiyN6iEbuIqSCZyBIU=,tag:RcBtgDi5UnrF5ym9W+d1rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TllnSjJ2QkIrMStGZXF6
            TVZWc0J1WVpDbER3NW5LckNHcjRSOU9vSUNRCjlvaXNYWThReFFwb3NleG00NUFZ
            UVdYa1YvVThjbk5pSVlqQjEzVG5NZUkKLS0tIDVFbVBVdUJNR0VwZG5HY01HTUdt
            Rk5NUlRJWGRmWEVRdGNOR0hYTW5mWHcK8x93Eyxnltc2KQYHbMzCkj9VdF4w+dYU
            ySRHyFDRwvwZi7/r/nNh8ZLJwlC9inMZUROKDzp0oLt+kM5uktoagg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T15:13:00Z"
    mac: ENC[AES256_GCM,data:yXomQHleSaiik/SuKysGqn1FQna0qkwBB2LFqXSuFJjy7iKio3PCg1iQLe9kfEdsWbPMn7FDUNQd2Is4+tqlsy8uGf1F/qq0J8+LwLwtOwtM7Aca6FM7bKpCbOxusAtQCF10ItwRbd+HwYEGM7V8/w0bqyyjI7pClI8NtbH3Qig=,iv:rBZOkJGnXIEmlRUPaPb8G9dUH5sXaZVkxUFxnfF0JHM=,tag:htc552KecmcxDZGcFG7zyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
