---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 60m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: nvidia-gpu-operator
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      jellyfin:
        pod:
          nodeSelector:
            node-type: worker
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: "OnRootMismatch"
          runtimeClassName: nvidia
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.8.13-1
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Bucharest
              JELLYFIN_PublishedServerUrl: https://jellyfin.davidapps.dev
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 4000m
                memory: 4Gi
                nvidia.com/gpu: 1
              limits:
                memory: 10Gi
                nvidia.com/gpu: 1

    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.100.110
        ports:
          http:
            port: 8096

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "jelly.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: "jellyfin"
        globalMounts:
          - path: /config
      storage:
        existingClaim: storage-nfs
        globalMounts:
          - path: /storage
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcode
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /cache
