apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: databases
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:uSht+fqRKpt4wgdmDqoL4YkRBw==,iv:eAOAAc6aEgm+Vp+NlRKbqELe9ovkNlMHO3hnpMPHte8=,tag:jejxSddcvtsKHmEJkBQKAQ==,type:str]
    password: ENC[AES256_GCM,data:h32EToiqGibV9u4RJT8=,iv:vvtZikgnFKSNPKKnC2wvRMZv8c4onm4A6pIJEmyYZUc=,tag:EmJA6suHoYrjOjXguQ9zDg==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:DcR7GvEkOth7sC0VlSI=,iv:r5laXyS8sWC/mtqGVjZxU2gtX2HD/df0fuSvq/Kqm2U=,tag:V+zKPRrvVEhlZhCmmQoj7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUFIxWE9KcDI1RmlaRnQz
            cFNpOW5oYkdvcnRLNm1jbE9XdHJNekdoQWt3CmxqRVcwVHlLazFvTmE1REFldUJv
            NUwxdlhWL0RINWVPOFhidXBkbi84UFEKLS0tIC9aUXhLQWMwUG83bjFlenZSa05r
            YWt4bFRtbzFYdmxwdHZQR2dYUnM0QmsKNuiGk71QO5xekLT4xakBSB0CSjf1J1Cs
            YicrNLOZ/JhscFAOcREeWTyFgW+EAP6iOqgkF3LPweX5JhT6POazdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T14:15:01Z"
    mac: ENC[AES256_GCM,data:MzoE5Cr+sWD1B+MqbvmkVui15o+VLzaRGEvXiF0IDWpRnNM6AqRNVVOHLKHDd0Wbrjweev/Aiv6yFtW2BsSdKDOboS4kaxXuJyJASdwX3u1dPzZNmmRGNkD4fcGSJi4jbtq1JijgfJuTrBRv+DzhE7CneK8Prscavd0apGt1E8s=,iv:YcB7qI5BUUcsJ0ij5GUOygnfzs/FU+mMVxdSw7RUDeQ=,tag:SrmH0lW/opB7EkAbzQbudg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
