---
kubernetes:
  children:
    master:
      hosts:
        master-01:
          ansible_host: 192.168.100.40
        master-02:
          ansible_host: 192.168.100.41
        master-03:
          ansible_host: 192.168.100.42
    worker:
      hosts:
        worker-01:
          ansible_host: 192.168.100.43
        worker-02:
          ansible_host: 192.168.100.44
        worker-03:
          ansible_host: 192.168.100.45
