apiVersion: v1
kind: Secret
metadata:
  name: geoip-secret
  namespace: observability
type: Opaque
stringData:
  GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:5N/MGImq,iv:Dx6G8NZho/fjwEzdg53g0mQ9mV15u7wvmxL0tkjIKU8=,tag:AEkSwlAd1pDLT8uni/6ynQ==,type:str]
  GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:MhZjVDn5iZEIOfQtUs9yA/mmOspEUG0zg1cS4X9AtkMmHQ4SZBTnzA==,iv:0GtrSUgYPuaGNnaUaGxixjjpKrbCdtC4skWyPEAnPYg=,tag:tk7uNT+Zf598OiMr44oR/w==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbDlrVVQrUGgvdkd4WGZE
        alJkZ1JybUxEU3hrVGhwNGpVbVhkZ21vRUNrCjhWOVg4Q3d0R2pVYkVlQVM5VEZa
        Mk03SWVjZ0dHQzRzZkx2b3RGMHNpMUUKLS0tIDAva2FFUFlTaFVpMU5FRUM0QzVX
        cFQwMUhJamdKeW5JTDQ2YW9DeXJRYVUKqLgdSVUIzuDJE6zKUGEe3bQ7+L17vr/7
        EstWKv/SPIav7PtOiJiX3elnCwh5I7PcJYwnkBjOgDWtDtfyWQFRlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T11:47:18Z"
  mac: ENC[AES256_GCM,data:9ajLlC7yimwwFvzcbhqDnP43FM8gdhO127rQUv/qRS1yR6Q+4wTME6gz5+TUL88j1caX57gA89hYoQr/7N1BTj2kYIpqF57rxrSoxEhd1P6x2g9+8tIeS/lDpU9Vapwd+1K+fIzR6oDryc9RcLC4O5FPgWZQOsdvRelkt0Q2RLw=,iv:cALFAlyjT9rbljH+oIX+Cpeb3wHfdl1MzerbAURYt+I=,tag:SO8zxlCjkfwCuWm3DZnQkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
