apiVersion: v1
kind: Secret
metadata:
  name: geoip-secret
  namespace: observability
type: Opaque
stringData:
  GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:5N/MGImq,iv:Dx6G8NZho/fjwEzdg53g0mQ9mV15u7wvmxL0tkjIKU8=,tag:AEkSwlAd1pDLT8uni/6ynQ==,type:str]
  GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:MhZjVDn5iZEIOfQtUs9yA/mmOspEUG0zg1cS4X9AtkMmHQ4SZBTnzA==,iv:0GtrSUgYPuaGNnaUaGxixjjpKrbCdtC4skWyPEAnPYg=,tag:tk7uNT+Zf598OiMr44oR/w==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeTVNbjk0Q2l4MVJxL2o5
        T0ZXdEJKcnJyZW16ZVIrVFlTUzRaZm4rQlRrClRMQW5yWDBYT0E5VVBlYVRTSHk4
        Z25aRnhOMWR6UllWR1JMbnlkK3JxdUkKLS0tIDcwREFRbE9DQ2VLUjRrM21sdnJ3
        L3gyUzFOUlFtbFpvTTFkMFRRaW51WlkKGBHib+0IpQkA/SI+FeVYSpdYkrOFYi/N
        1uJ/y+vgXFh1s1DwVm583GgJ2fWE7yT1sT9LKn0KHHUMJlS7oepjbg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WUo2VTMwMUFpYUo3LzI4
        M0R6RUlSbzAzZm93M0QzdEJGdStVVk51ZzBRCjhCSWJGTHVmaXlaeFJvRW5mRXlI
        bWpFU2piY1ltR0NtK0hHem9vSFg4V3cKLS0tIEpNNTlMa3BDRWgreVpYTnIrU1Uy
        ZlozOEwvLytKUlpQZ0VSbHhSN3pNTGsKjDpEZr4mVMyEHW7XChZx9D1w5HTQ4xhU
        NS2XwHLbgbPE0O9GcdrkPtHggHLdVw4SUI/6PpGjonN6bDowP1K3Qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T11:47:18Z"
  mac: ENC[AES256_GCM,data:9ajLlC7yimwwFvzcbhqDnP43FM8gdhO127rQUv/qRS1yR6Q+4wTME6gz5+TUL88j1caX57gA89hYoQr/7N1BTj2kYIpqF57rxrSoxEhd1P6x2g9+8tIeS/lDpU9Vapwd+1K+fIzR6oDryc9RcLC4O5FPgWZQOsdvRelkt0Q2RLw=,iv:cALFAlyjT9rbljH+oIX+Cpeb3wHfdl1MzerbAURYt+I=,tag:SO8zxlCjkfwCuWm3DZnQkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
