apiVersion: v1
kind: Secret
metadata:
  name: geoip-secret
  namespace: observability
type: Opaque
stringData:
  GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:5N/MGImq,iv:Dx6G8NZho/fjwEzdg53g0mQ9mV15u7wvmxL0tkjIKU8=,tag:AEkSwlAd1pDLT8uni/6ynQ==,type:str]
  GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:MhZjVDn5iZEIOfQtUs9yA/mmOspEUG0zg1cS4X9AtkMmHQ4SZBTnzA==,iv:0GtrSUgYPuaGNnaUaGxixjjpKrbCdtC4skWyPEAnPYg=,tag:tk7uNT+Zf598OiMr44oR/w==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOGxTWHVVbTdxdVZZM1dZ
        bXNtbjZJZXBrU1VYREJHVlQ1MGdQRE1MazBRCmc5WlR1SUpvZ0N1a2VOY2tDT0tZ
        YWJYeVBZWnB1T1FoL0txOFNEVDg4RzgKLS0tIEZlcUI1alp0MkFvak1mQWRKS1E0
        cjkzcVJUMXJaS2N2SzJEVFF1UVVIaXcKZcAfvpp+emkZPx169bTKNN2A8/5JFMU3
        E1HEc9Yf3UgJodym4veAv6meVmP3n00aBK1hoNbZkCJnrQ20RGVerA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T11:47:18Z"
  mac: ENC[AES256_GCM,data:9ajLlC7yimwwFvzcbhqDnP43FM8gdhO127rQUv/qRS1yR6Q+4wTME6gz5+TUL88j1caX57gA89hYoQr/7N1BTj2kYIpqF57rxrSoxEhd1P6x2g9+8tIeS/lDpU9Vapwd+1K+fIzR6oDryc9RcLC4O5FPgWZQOsdvRelkt0Q2RLw=,iv:cALFAlyjT9rbljH+oIX+Cpeb3wHfdl1MzerbAURYt+I=,tag:SO8zxlCjkfwCuWm3DZnQkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
