global:
  scrape_interval: 15s

# remote_write:
#   - url: "http://prometheus-home-cluster.observability.svc.cluster.local:9090/api/v1/write"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          ["prometheus-home-cluster.observability.svc.cluster.local:9090"]
  - job_name: "idrac"
    scrape_interval: 60s
    static_configs:
      - targets:
          ["192.168.10.50", "192.168.10.51", "192.168.10.52", "192.168.10.53"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "idrac-exporter.observability.svc.cluster.local:9348"
  - job_name: "pve"
    static_configs:
      - targets:
          - 192.168.100.56
    metrics_path: /pve
    params:
      module: [default]
      cluster: ["1"]
      node: ["1"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: proxmox-exporter.observability.svc.cluster.local:9221
