apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: default
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:+GPeoYSdVjeZJdxR/Uk=,iv:6Ij9myIN/wVaPh67eniR8YtY/ZdXJVc20+haGN6hST0=,tag:yx8Ll57r3s/0voUqwZ1JlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcmlzVGdROVFRWlovMnMw
            M0hCRHdFMHFOOVZpcC9rZUVXc3ZUVjRZa25vClI3a0tVTktCK3R1UEFWdkhPa1du
            UVZFWExCOEUvQjhoc1h4bE1hVy91SU0KLS0tIFEzRTNmVkdLVGNvb1V1SVUvYXF2
            MngrcVdRMVRSaUx5Z1VObkNsNDc1N0UKbCOuY+VU6f0Y2dtdBOUXVyvOeM0XEBSu
            ytTWu9EH5T1dGfCPlMzZQ/oKAu40Wi5qiKrqAjjJsCCq+N+b3FpsWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-28T23:45:26Z"
    mac: ENC[AES256_GCM,data:HXQ5NhrBcGiXPOeZ2SVm+wn6M7XP74NGPOUL2R0IQi7dC2ZtGYlHG/2cwr6IzCiGQxNzmOolgM6pkcsZeUC4/12Og8kPh4/1FXYATAvkCKERGbQWjACoJUF7E75NPaDFrla37RobuSg/+W//zTnK28ZVqBaTCujgbDlQVWmN2CE=,iv:kVvTPhZj3/Xi/hPMdP8VA2Ki27ap/VhfSx/y7q2OCUs=,tag:4eA2DO+8vWIMsjlD6wpwdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
