apiVersion: v1
kind: Secret
metadata:
  name: posthog-temporal-secret
  namespace: observability
type: Opaque
stringData:
  #ENC[AES256_GCM,data:ujGDGc37kSsabkP13s5KUm5QZzWlNfiattye,iv:kvuV722T7gayHS+JmfFAEZnQ+iUCmKV+8khBw8vqRy0=,tag:U+2EH9mdpVBXMaPJUrV4qw==,type:comment]
  POSTGRES_USER: ENC[AES256_GCM,data:jYMncux66+Y=,iv:rOxeAJy7hZphIpB+652ZSKA5L++1CZTDFZg+47AOff8=,tag:8yQ3udD/8Bou4Ka9WyxOTA==,type:str]
  POSTGRES_PWD: ENC[AES256_GCM,data:4642HymiKusE8xr4/KyWgMN9NcpiW5PG0lV0BllfDns=,iv:b7uvk8+n0t1e0ysCyjZVMBQqhpzCzbi7sMr/hWTXLn0=,tag:nJka5S2O3IC6QOqiSzbeZQ==,type:str]
  #ENC[AES256_GCM,data:dX4NSKMGhrZuWGcHdALriBi6YhnEbvP42VDlHEX23GO59tLnbUlwG4N/2g==,iv:k+x72qm3dYPkggzyZy4wOuA5LB263/VLPjqFUlR2D3k=,tag:Bi4NXnHGiYdvHp3FacZfGg==,type:comment]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zOCbhJg5eABnQ4V4286F21AeAvUhjji9RUCX18Jks/g=,iv:HjP6pu0gEV0rKn4UFi6sBbmS9vbtk/T/kekv6KPY3nI=,tag:g1jrnSfP/o/kKXN7+dQBhg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2xseGOr45LVt7sP3XIw=,iv:ckinlrA3UUMXMbLbOztpL7B3+HgezOnzB2UffgXaHgQ=,tag:VD2CodZD9YUqRDm7w7mpNQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dzhnUStsb2FDM0hTa0sr
        M1g0b0FabDg0T09aalp4cVdVaGZFYnNFL0NvCnczMnVZeEdzcGVZSCtITDJYc2lk
        MTcvQ1FKNlI3cERiVktVelYyajExSTgKLS0tIE5BSnE1ajQ3a1l3T2lwekVWMkNm
        Q1FQS2g3T2VMdmVoTU4yaGF6aVZwM0UKsmCQh+ijXQLd/xJdwNSkQf22m5tsAyA9
        nw1J1rc7sFtf47rkkOjPjptqovQqXO9yi7hjt8r3GaiS62dkVFRFeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T20:25:01Z"
  mac: ENC[AES256_GCM,data:b9h2SE0xqWq43XVQ6ekiQwGr2Cr1oY5YMyKCKSjWXo1yXTFzYj6p/4m6UIEFK+hzUjkdhJmb8WreEW009BsYIfMopJ+5YGg+V1ZrPOgEaBlByl/mpvrmGYYBoq7z4doRo30abi3c/xa+r7GadLsOcKb4kWI8AoW/aOQ+rZ9JZQ4=,iv:W3JwFJ6vc4bO6wD/h9K+WaMttlPA2ZbwlV3w+iC6M/g=,tag:p+b9M7Z3YXAIuXR2m+fuJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
