---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: donezo
  namespace: adapter-demo
spec:
  interval: 30m
  timeout: 60m
  chart:
    spec:
      chart: ./kubernetes/apps/adapter-demo/donezo/app/bundle/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
      valuesFiles:
        - ./kubernetes/apps/adapter-demo/donezo/app/bundle/values/values.yaml
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - target:
          kind: Service
        paths:
          - /spec/selector
