apiVersion: v1
kind: Secret
metadata:
    name: boarding-app-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:VRJHDmTUVubZQTOZROnINJ7HhpZ564Dihjuqdk47SEKiu37JZYBdNc0tYWPOsTqcKL3dwWTIB1J3dIP8ybsRNTG57JDBEdEvN4emu65YQ2wlvlITQDqc7ham2jLQY2siyJVd1JSBqg==,iv:IsTxZKWpmgrsllHec9TWkXVLGgIJzjNZO1vgRMRJMU8=,tag:680g+dBDCsKW2wZsEiCG4g==,type:str]
    APP_URL: ENC[AES256_GCM,data:x+QZILvzEl6EG0+zkLOalHIQRkFdanQfoM10/DNy,iv:Z+LLlJH1rGT3A85rSC9NV71mK1m8b+n6Iwt96Ix0ui0=,tag:ArdQGmNIg7jGOsggKLH/0Q==,type:str]
    MS_CLIENT_ID: ENC[AES256_GCM,data:m83mIT8NB79f+MhgrOzbQzOb3Yb+F6Km81nMRc7POqgDKE/m,iv:cwKh+GNQZ8gxEMfh/jaNIDoVYuNNWViTZ/w2Y/spvcM=,tag:Lf5Xr3eEMQeWO6cVMJPv1A==,type:str]
    MS_CLIENT_SECRET: ENC[AES256_GCM,data:D63QZoapzESwMZ2VDcpiyA7jF53NTvPU8dJUfh7hHHGGZ31OX1yk+g==,iv:fY905VAl8dmxHizThE+6JALnypNHOgDfxQHMEFk9Bq8=,tag:eqXPz6z9ZwHI+tgaeIX09A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:cONmVxUnLoTzCswi70knIgWEfkS3jhCSTkXGzNb04nJICi56KmRjGf7pdwGQgVUmn1N0TNTs60/jE+6A,iv:1EIBM+AV0V84N41bl2yI0errS1wIuC+MLmNoVX+T5fY=,tag:TOghT5JMIRiYvVrIMhJCyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1JIcWljSThtZ2JodFVJ
            aEpqZWdESDFURUdLckFWQ1IzUldyT0ZCd0JrCjh0MFRRQ1c5N3haRkZrQXYvU0VW
            TkpKQ04xTUVLN09ZUUx0T3pwVXp2U1kKLS0tIHl6RG5INEVpSzJvRnZUeldXd3R4
            Nk95dm5qdEY0d1lVc3dqRDJTNDlvQ1kKLixoeBTKgw8tdBEOgemi4P13l+WSaenK
            HX//jMdwuyBbOVgBvrQaN4u6NQjNANoG9WQC2pdJ5woT3aklNqaV2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T15:01:19Z"
    mac: ENC[AES256_GCM,data:bNqQpeFQDwdqwsf6kZIZfE787MDGV/cpSQeHG8jDx13ar2gNrRyo79+V+04N4dk3ffT09qmY/2DGm6d2/8ZbVoEjV6QjCmcWRV7WBTPOSiX3vIsDu5feb/ukqr8KdB0cBslZB4tKfEMxJ4soWohh2aF4hSXwez/we9PnBq4Xpfc=,iv:pN9Ij5TVXd8/TmZ6rASIOLoDuC6Uk/4QGFEbelW3miM=,tag:Xb7TZLSwoFxDL+J3kIKsaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
