---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: &name sentry-nfs
spec:
  storageClassName: *name
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.25.3"
    path: /mnt/ssds/sentry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name sentry-nfs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: *name
  resources:
    requests:
      storage: 1Mi
