apiVersion: v1
kind: Secret
metadata:
    name: sentry-secret
    namespace: monitoring
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:3NzEzoAmVmvzulqxjgE=,iv:reTP8V8ub+klTuyuA8zo7rcZoZ2bJU7P6fYadAQTikk=,tag:5Uou9Z/0t0urJQ0SCmqNtQ==,type:str]
    sentry-secret-key: ENC[AES256_GCM,data:4TtJk5UhGbEH/KYvfSKr16AiSc9uEtXJROPoaHwqTL8LHzaLpf5sI7eaX4XFLGs2cDbenpkN0TjMsZd9OUn7Rg==,iv:4D1/jK5vV3hSPgJoU7Uz/sbpiCc+yCX8uNoKDUJ6QYg=,tag:+jYk7nxMswM7H/OiyoR9ug==,type:str]
    DB_password: ENC[AES256_GCM,data:CHhT9UhOPk1OgiSv1SM=,iv:4MJO+4ppCJfEQQFHkDZS0MJzqwX4ThDNR7AClWLp99Y=,tag:p7RuuP+C1y3VGKnIA3+fBQ==,type:str]
    DB_username: ENC[AES256_GCM,data:5qmtUQlYXJU=,iv:FKMIUYOpVCoM7XjcAz3uqNwLY0ygdaPK3CIvk8Qlyc0=,tag:BvXhR0MTi/VE+WBQlnt7YA==,type:str]
    DB_database: ENC[AES256_GCM,data:bit++ila,iv:MQwae9JTeomB5neqdTHGqt2YhniDywT2ngseZ088Bzc=,tag:8xuSuw4jJJFS37Otu+Cfxg==,type:str]
    DB_port: ENC[AES256_GCM,data:gRuaEg==,iv:yZTjJBa7G28NQST3AlFgsc5bwkxcgZBDCgcW1PFEAvY=,tag:FscFgvxnRRodPr/539AUWA==,type:str]
    DB_host: ENC[AES256_GCM,data:An9KJYFT08hEAHZK9y4kEbtEgLyFDgtpxXZbRRYS+Zg9BhdbAwzDnQ==,iv:2u422uaYlmCE9D6qy85OFIKL+i+FRKVxG03u18y6CEI=,tag:eiWKJxCQvgofQTDAEF3vmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG1aTWE2TkpydWg2NkxT
            TnlmM01IeFBjN3RtT3dGNU5qb2lrSnFqT1VvCnFhRXFicVBtbXNFNXZkcGtCMVpS
            bkZvQStaSFBnci9yUHdkd0o5bWx4eEkKLS0tIEp6aGEwVzh2SVJRSElQK1ZXbUhM
            RlMvS3ZObnJaSTcrSDdNaHQ2ZXlwQmcKEaouW/Op7dzuu9T6er3NT14A8hW0kj95
            D+fwjgQCWt2wP6o2UjPHcew0cH/ZZZ2aKm0Nyd5qwFvlavcSrHa1EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T10:01:06Z"
    mac: ENC[AES256_GCM,data:xF6OCCo5XO4J99jO92FcJS+jKLDcAY0KfHvf+gGT8oeGdg93RVTvRtsNA5HbFGGc42ncd6TdlJJZe7TJXluizZqmOo506vXLX8oIPeodAjZA9U2n9Gy0RrC5Mwqkk8rSgh7/2bgw2SqG4hUaBCyPGb5f6qTxl7Fmw7R/4Tu0zyQ=,iv:SPmg7eK3UGWK6foKvhsUdHCGnSe8v1w6tANYCuSfFaw=,tag:RXIvqYb/WuIOwZCT8Woqgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
