apiVersion: v1
kind: Secret
metadata:
    name: sentry-secret
    namespace: monitoring
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:3NzEzoAmVmvzulqxjgE=,iv:reTP8V8ub+klTuyuA8zo7rcZoZ2bJU7P6fYadAQTikk=,tag:5Uou9Z/0t0urJQ0SCmqNtQ==,type:str]
    sentry-secret-key: ENC[AES256_GCM,data:4TtJk5UhGbEH/KYvfSKr16AiSc9uEtXJROPoaHwqTL8LHzaLpf5sI7eaX4XFLGs2cDbenpkN0TjMsZd9OUn7Rg==,iv:4D1/jK5vV3hSPgJoU7Uz/sbpiCc+yCX8uNoKDUJ6QYg=,tag:+jYk7nxMswM7H/OiyoR9ug==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Z0gHZ6pn+fro2oHnzEQ=,iv:OKrwFqZFmgF756umhipTA5E7Cy+3fzHz9/cGilWnLX4=,tag:detHU3fzA5lBi+flXo3+tQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:DAF6lyeSN/M=,iv:qfGaXWMHn4Q/RN5wUpiT55K6naNYqRfo80bQ3tKQwZA=,tag:IWNOFuTWzq8u3gkofb2JEQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:uiIBckPp,iv:v7osAmLF9AkCPA3WcRsaTLOvPVPjQqXMB42bKwUL1iw=,tag:uNS2lY5BqBSYu9k8iTLpIQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:gkx/9A==,iv:xf4AGYR5KOlCom3VhJ4/cJnUw99vRIh5alIipdMLBPM=,tag:c370g34IRSxXE16nsoZ5rg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:8lO2u1cGMXWn4KUPxi869QsX+TauQPGH5xpiEIAloTyeC3/37/sJqg==,iv:kTPIipR0gW0LnpRXsuONACnIxiELFLfiZRP/abS+fZE=,tag:8ik0RDWvYMqZC02Q5p18wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG1aTWE2TkpydWg2NkxT
            TnlmM01IeFBjN3RtT3dGNU5qb2lrSnFqT1VvCnFhRXFicVBtbXNFNXZkcGtCMVpS
            bkZvQStaSFBnci9yUHdkd0o5bWx4eEkKLS0tIEp6aGEwVzh2SVJRSElQK1ZXbUhM
            RlMvS3ZObnJaSTcrSDdNaHQ2ZXlwQmcKEaouW/Op7dzuu9T6er3NT14A8hW0kj95
            D+fwjgQCWt2wP6o2UjPHcew0cH/ZZZ2aKm0Nyd5qwFvlavcSrHa1EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T09:46:13Z"
    mac: ENC[AES256_GCM,data:VaYbydl7vqqu2JLz/1hS9sm4X2VxlepaafAvk6YEdCshhlbvAXq/1Ch9PcYoH8MF6d9tLNv8D1I+oNlOmpYjTjF/s8DHlFtv/MdGl4WIOwfhmPTNexUgByMTTnMU/ibUkKHrwQ+pjsFSslwqh8t96j/8xO4711QjQ4gCgO6+BwA=,iv:y96sxt/86jg0xA5oZ6VlN9/DBiuhBbY0gvisB0m+1CI=,tag:wg7qKplZNm25ZzfMnNFpHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
