apiVersion: v1
kind: Secret
metadata:
  name: qui-oidc-secret
  annotations:
    davidapps.dev/credentials: provisioned
type: Opaque
stringData:
  QUI__OIDC_CLIENT_ID: ENC[AES256_GCM,data:megb61floPitb9/51s/y0No8pWCzy+U3mzXJkC98MAo=,iv:FWY2L9JdZhC7ruWdCcmy2Xe15FR1VJjvgwA+oNpI1S8=,tag:V2tlb0VAOt6K+PVtE4FxcA==,type:str]
  QUI__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:63/ZNLjdv+0DFUorsaeactho0u3yedlzSr08LEMDfJXgPejWCY5LTGkrig==,iv:VKBpygyxaPiEepY7IPz6qRJ1Xj9pBRUMs/IVnN9Zmd0=,tag:tnB6fkleg4f/ShScsEAtkw==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRGw4ZjQwWmtGc3lkUXlr
        ZWMrelZqM0dwQll5dmNOakRqUFhCUlFsY2xjClhxYkhIT0FkdXBEUGw1U3Vrdkcy
        Skt3cmoxNGVuT1dhbGV4S0IzUW1IaTgKLS0tIFZMWWFVWGd5Y0huS1VVbHd1dDdv
        K2RCbjhsNW5uUXNwMzU3c2RYakloUFUKwvos8/rPCFO6DHbD7WuLj8ZpKT/cseR3
        kQJUWcxDnXNY6+6u+UdFVPJLON47lRhF/L+oqG4lv1cwA5Yc8Kqy+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:53:43Z"
  mac: ENC[AES256_GCM,data:dF75nq2MXEteKKhghPliOAnUfjdGXetsH1RSntBPfA8hTAQM3jm3H//CD5rZgGjRiM23Py6DwtHX5t5UvnMGFvGV/LM9oytspd470Eai2APa/H+nSBNGv59RGr71GkH8+JkDYTb3lKKM2/IL20PdbBlnuqE7vhQtMyN6hzB18dM=,iv:Vy7gRgLvKnfLzGI7DrPoXH+BkFQNIcD4XWAI54cNMQs=,tag:UqNl97pQ5YKrBmbDJknvdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
