apiVersion: v1
kind: Secret
metadata:
  name: qui-oidc-secret
  annotations:
    davidapps.dev/credentials: pending-provisioning
type: Opaque
stringData:
  QUI__OIDC_CLIENT_ID: ENC[AES256_GCM,data:Q6MDvy0W6u0ktB/wg1+hULNMtlNCnJQalyYm6/LbDufBVu3lOTNoMqhVX3aD,iv:A7uS40CCv0QeMxFLibVoBYcl+UGwxQ22b424M0gOtNY=,tag:cY5PBKhGo9EUYzRLLMdhdg==,type:str]
  QUI__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:QVfsRc5Ieb+hiqev+oVyxSsGFY0vFBlyEAl/+c7o4BwCmsPe8AWIsTIJG/WU4mzrWg==,iv:9ZMsarbGOeAADBy/bf/JkoqJO7Us4IgDYkX3I5MBCAo=,tag:qGvROaAogYWifvKPmZZ52A==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbFdjTVRlUDdEVytwVWVX
        UDFwbVg2U0dUazdHT0J5M1B1ZkdqWTN5andFCkNUR0I2ZzBiRjJkcUF2d09LSHJl
        dm9hQlR4VGlkd0tDVldZZnM5Q2U5RXMKLS0tIHZNbkE3bnljQVo0QVNESkpKa0p1
        VCtpZDVPK0I0SWtKc1drNlBuRDFwNmMKiuI/4tdkF17tFUKhZvk6LJxgjfoWLcxm
        aoc/atVGHJUqH8jEsN+QWC33o3aqO1bG6N3KJcPptkZ2cPqSSGv0zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:34:42Z"
  mac: ENC[AES256_GCM,data:67a5a4TyWRmpKWuWXCB84t+FcQJnmM61WVT1VoFJ+eLCCUBj0afLKgpjzwaXpSJgTtDg2+jwjv066DAZNxbSW/NnawPoryJ4Wqe3oVCxnrVS45lJHCbqh5VkMaX9cS3m8b1LWW1sV54tlaZpWl7vNe9NYQbG9c/eKgkxBBRavkc=,iv:ufe1DDBg6pcKMHPSBT21esuZLPzpoEsOd8nmrutBTMI=,tag:9swkoWRHTeRyo6dlgqQLpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
