apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
type: Opaque
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:sva7fePFa/G1tEr8YflgYKR7oacbvbBigTMvrAZIES61fBtV541xSQAsRz8DAOGhcS85mrTHnAgmuHBKYIitug==,iv:YZNOXj7tdgttP/+UqWpMZa0e/1dnrr2m5ened7oGDTs=,tag:4wBV/0w4hOxhv9bBKG5pdA==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNTIvVFppT3pjY3dGRjRn
        VDRXdEVhc2djTTdLRUJxSVJvT3pzRGtJQ2c4CmdYdWtYQVBIb3BSQm9BZFhZV0FB
        WENSalJOWFlKYmVQL0sxZFZCd2g2SWsKLS0tIFJuYXdVNzVQWGNTMlUrOVhQZWpD
        ZW5iR1JhYnVkZnhGRVFpY2JjUmM5aGsKl9vb+N9Xg4DdglfGfwwcpzuzO+hZeKzV
        i0VR0UiKcbUNm5Lag51kRiW3nA/5xQcqRthwu06H5OCXdfySOQtYCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T23:16:49Z"
  mac: ENC[AES256_GCM,data:IAAmEPZBvFjmkI35z4+bLRWlq6yYx6LevFezJcEe4N8ZzFyefxuW3oimPiLyL1QeQ3dErV+o7aZouHYh9C6JUTDoH9+5t5YiiNidMTIBS5a3Fu4ybvg4P6QvH5KLzpIBPyRXPTKe4B5GYmSm80+MiagHTV/YNEUDKV5/pknEZsI=,iv:1iDwfMNT7XI8vcV+N5AFGep2mm3p2uau2DkuHLqzQi0=,tag:eXmSRmSA42XJU/o+sdpw8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
