apiVersion: v1
kind: Secret
metadata:
  name: garage-admin-token
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:ye55JTAt2cxss86jFDR8w7cX78dEka9XURXRaWqakSUiwZ7z/F+VF8nWZ9SGmXxHUF83cfZGNRdDqgGgtQSEpg==,iv:Y81Uty5Ixr5MlalTzxFK1oYkI1dwVfP55b/uWkB7ds0=,tag:juf1UxiPpM1/Tvu50bhRRA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaWpOZitXUzVSSnJ0R2xp
        eWpSTkpkK0dvb3czUmsrVUdLOWZ0bjhuMWpnCkVLUW5YMmkvaU1neHBPbzlJb1BF
        Y0t4b0grMko1eUZUQmhCQ2t1aSt5WXMKLS0tIFc2MzN1NTk0K3dGN1JIdE4rTHhq
        OTlLdHNhVE9jdExxUWdLYjhDN1hjalkKy+Kwkt3kfUlvx2tG5CZgeeikrGu3csUF
        eyf6rH6LiN8wzNALiLttKi0ZsQcfTGN30hMXLkCKT4yB6kRciI3aWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-17T18:34:24Z"
  mac: ENC[AES256_GCM,data:HIPDRwIjoWrKc0prY676KW0Ti/if1VjN75h954IWSvvgHphDKLYwexOgeJHkooMyyvbUrottYXzy48qYA+dFCVwMXoFcKbj8svxlUqaglOv4eVc8sAP1mVFTiESR6j2DkDKekQ6o7uWJhAXaA/EUCja6zFfxIFlvwI/R68KJy0w=,iv:tJmd55ly8F/wwWV/E4fBPas+BxZ0V7h8MzJeGh2sww0=,tag:BpJIip2eyPmFQgewbBDjEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
