---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./admin-token.sops.yaml
  - ./cluster.yaml
  - ./bucket.yaml
  - ./key.yaml
