---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cliproxy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      cliproxy:
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/eceasy/cli-proxy-api
              tag: v7.2.71
            env:
              TZ: Europe/Bucharest
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8317
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: cliproxy
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "false"
          gatus.home-operations.com/endpoint: |-
            name: CLI Proxy API
            group: Utilities
            url: https://cliproxy.davidhome.ro
            interval: 1m
            conditions: ["[STATUS] == 200"]
        hosts:
          - host: &host "cliproxy.davidhome.ro"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        type: secret
        name: cliproxy-config
        globalMounts:
          - path: /CLIProxyAPI/config.yaml
            subPath: config.yaml
            readOnly: true
      auths:
        existingClaim: cliproxy
        globalMounts:
          - path: /CLIProxyAPI/auths
      logs:
        type: emptyDir
        globalMounts:
          - path: /CLIProxyAPI/logs
