---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./claim.yaml
  - ./davidapps-gate.yaml
  - ./secret.sops.yaml
  - ./employee-hub-secret.sops.yaml
  - ./helmrelease.yaml
  - ./volsync-plugin-data.yaml
  - ./volsync-config-data.yaml
components:
  - ../../../../flux/components/volsync
