apiVersion: v1
kind: Secret
metadata:
  name: cliproxy-config
stringData:
  config.yaml: ENC[AES256_GCM,data:9Pndf6eHUV2NkyTHDxGS0ZlZEUhFaRjq9qt0bULuj5kxJmFUTjB8onBVfLvQuJP+Avw53XZPjgCwPo0vkR2m0D7TmPQrAxOEbJY3J9bgXtwbVYpXmEqSc8k1KovIJn9064xjewlowiNyoDiiuWR1sjt7K/wC9MF3Hjj1OYUdqSDlrooZ+H64p1+eX+RYx+mNYUwQWNWgd4kCtNO/ZMn+3oth2V3MMuxebs/hKseuwRakL3k+9XxDutqHt8TS0YflP7KMLso9pPrcm0EIqohiofjJOg1+CcJQOBMhFnZnqAYjc73C0JkmJDlfApJ7cYVR/FgEXHz04NTkuJmX0ivuXMHse3RUwaYvzQExJfW2dcnzhnAAwC3OMw9J1Q4x5wyHf81WcsO8E2ji65BBCSAWjsb00vDjjRmmF9paJUElkDDr4DqPqNuJ58DPN9ehIRHhaq3vCMy/wCEgV1UOVcU2FeB4l+/lGHjcasAk2dZMwL4Gz4Il5fWa2wAQSEGAuvj4TJySp9YZwfdJK9InBhuF5ChLcZlRg+7gysSvFPnCl3WmWQpX,iv:1dijv0g+pzOMH3rg/eBZiXRpixSx4FjFw15Qo6P1VSI=,tag:W5KXW51eDipj5Chvg9s94Q==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dFdFYjcvMm9BTEVhYVhm
        VVJUL284Y2craWJXSk9IZktnTTFiNjlpSW1nCkpSY0duUG95TjQyZU9uWHBXa0Yx
        bytBejAyVkxYNDNTRFp5ZXg0UlJpZ2cKLS0tIHZEaFNTTnZJV0NmU0l1ZW4reS9X
        Tjc4bEdNbDA5NFQ2T0JBY2NmcERWdzQKY77jmwcV66SopIakLIUBUwiorV2z2oE1
        brJ18dwrNbNu8g70RAKd5QJkKWPhWPihXdxchmazZsgUbOGyWTrPMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-13T10:10:02Z"
  mac: ENC[AES256_GCM,data:1AlveV1GH4bMPJfZ58DpXvfWjNjtSnib11guwsiXNiSIdOLUkpu4M3+li0TEcr1m0S2RUix1f9+XiMfeP4PB1ENIzzOG6BG7JSqZiwymRMAajjAyz4yXQGeC1C9jRi+CCAeB/miyvozCXRdY94gOUMCwgp0yfzufA1zuxrnsHiY=,iv:8NdLBLrCyQ+XNtLJDKyAbJZynFfuCSgMPGIaEOIVDBc=,tag:IhbyxD24kGfjTHHgCJfJAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
