apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:lr1+lexMBp2FuRKbNYN0mftXoXBKF34S6YmGtcqyZ2A=,iv:IN9ebgXRZDVBCy3Nf+qlN5GgZAIxGEwrMd6NVHP3uh4=,tag:ZlCF4CJ5tGFYwOfecBSZsw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:zlrQPdSHTTC6zI3wa/Xab3afzVwlFqWkWKeepuwhvvg=,iv:29zjPCMtonFJyo7f1r3qLLPlefvAZgacgn0nqdKQxkA=,tag:b9gGIz70rA4rAggHjOTBBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:38:36Z"
    mac: ENC[AES256_GCM,data:PKxCFAUNrKdB3Nm8HoHlcQIT4jcQDXGCWnZ0nar58idUduhUZpYNoXPRIMB00ztpBieyux3Y1ZwmHpYIHEVRfq+IeJb4u3MwQcwQk2HEzMnbWxr39VnMLgyacv9k1eRRCl00muK6O24u4LdqQ0aMYJ3fEyMnkpUzznmYNewpVUs=,iv:lwwzl6aAD8rVFdOGp/GfPzLBlMzt6UID0WVDfXMD/Ec=,tag:6vMAbSjsJkdXvzwgz+G4Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
