apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:jVHzQHCHgda5BlmKY7mvcZ0fW/M/zm3ZfydKlRldxBs=,iv:VDehQ5HcmINuPMcdArYrqFeL+0iPP07pUzR6fRuU1Ig=,tag:lEXOHevSQEgyVVLel0l4aA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:0C3/sxicKhyX7yk/ImUObOonVRZNgC27ad8hGTkXlrY=,iv:2p03G31adZMLGExeyQrFkD/ZfCSfw66aJRQBwPCaoUY=,tag:+r/f5SDLod5eRW90oJXDSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T14:30:23Z"
    mac: ENC[AES256_GCM,data:FCsvVW9sO1dIHjg9mc5Qg/pJIgOFgQuvCC+6JyY8T0tKNNknH1J+qrXeheo+pdXwFE0wJSO4+oUb+NlQLDeps4wIG+z9dmAVdehzRzAv3yB3PADjQRisioyriJLtiShnTXcxzDnEPwginvfUjqNeDX7XIPC5yFveqkQidfhX5X0=,iv:GLTmNJHXZrh3MXAgOuIDqXg61RJ7NZN1sPM+qhi7XDs=,tag:M2IrLOZfP7mdRb86pTiETA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
