apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
type: Opaque
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:jVHzQHCHgda5BlmKY7mvcZ0fW/M/zm3ZfydKlRldxBs=,iv:VDehQ5HcmINuPMcdArYrqFeL+0iPP07pUzR6fRuU1Ig=,tag:lEXOHevSQEgyVVLel0l4aA==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:0C3/sxicKhyX7yk/ImUObOonVRZNgC27ad8hGTkXlrY=,iv:2p03G31adZMLGExeyQrFkD/ZfCSfw66aJRQBwPCaoUY=,tag:+r/f5SDLod5eRW90oJXDSA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjL291ZTgxWDlNUXhObXY2
        WVFyWmtKN3hzVHM2T2tRYmRJRFkya1ZSeHlJCm5RNktQck5qTkk3UkFuN0xSOGU0
        cVd2bVNRcTFTL1lYSnYxVEg4ZGxmaU0KLS0tIDZHVWhPMEVaK0pVUWJNRno0K2hY
        Vlg5bWJHekpadEo0WlliSEh0aEc5SDQKpBDpW3bUlSPeJDKk7YEwk/0WZ9/vJdwn
        mlerMlcrqkgunm/ZfY/dEe5fBVSDd38Pdbchs7aAI5cEFTrzKGhm3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-26T14:30:23Z"
  mac: ENC[AES256_GCM,data:FCsvVW9sO1dIHjg9mc5Qg/pJIgOFgQuvCC+6JyY8T0tKNNknH1J+qrXeheo+pdXwFE0wJSO4+oUb+NlQLDeps4wIG+z9dmAVdehzRzAv3yB3PADjQRisioyriJLtiShnTXcxzDnEPwginvfUjqNeDX7XIPC5yFveqkQidfhX5X0=,iv:GLTmNJHXZrh3MXAgOuIDqXg61RJ7NZN1sPM+qhi7XDs=,tag:M2IrLOZfP7mdRb86pTiETA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
