---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 9.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    deploymentStrategy:
      type: Recreate
    admin:
      existingSecret: grafana-admin-secret
    env:
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_EXPLORE_ENABLED: true
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: natel-discrete-panel
      GF_SECURITY_ANGULAR_SUPPORT_ENABLED: true
      GF_SERVER_ROOT_URL: "https://monitoring.davidapps.dev"
    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      news:
        news_feed_enabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: prometheus-davidapps-cluster
            type: prometheus
            uid: prometheus-davidapps-cluster
            access: proxy
            url: http://192.168.100.18:9090
            jsonData:
              timeInterval: 15s
            isDefault: false
          - name: prometheus-home-cluster
            type: prometheus
            uid: prometheus-home-cluster
            access: proxy
            url: http://192.168.100.18:9091
            jsonData:
              timeInterval: 15s
            isDefault: false
          - name: influxdb
            type: influxdb
            uid: influxdb
            access: proxy
            url: http://192.168.100.18:8086
            isDefault: false
            jsonData:
              version: Flux
              organization: davidapps
              defaultBucket: davidapps
              tlsSkipVerify: true
            secureJsonData:
              token: 4yLtxxssHuESsvLKsivoZ9dgI8vyE9ayCTlqB-l4e_hVFgTYO5Wdj9tsE_NT43LsAoBiy3w74A3fvUDSINx4CA==
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        cloudflared:
          # renovate: depName="Flux2"
          gnetId: 17457
          revision: 6
          datasource:
            - { name: DS_PROMETHEUS, value: prometheus-davidapps-cluster }
        kubernetes-api-server:
          # renovate: depName="Kubernetes / System / API Server"
          gnetId: 15761
          revision: 18
          datasource: prometheus-davidapps-cluster
        node-exporter-disks:
          # renovate: depName="node-exporter disk graphs"
          gnetId: 9852
          revision: 1
          datasource: prometheus-davidapps-cluster
        pihole:
          # renovate: depName="Pi-hole Exporter"
          gnetId: 10176
          revision: 3
          datasource: prometheus-home-cluster
        kubernetes-coredns:
          # renovate: depName="Kubernetes / System / CoreDNS"
          gnetId: 15762
          revision: 19
          datasource: prometheus-davidapps-cluster
        kubernetes-global:
          # renovate: depName="Kubernetes / Views / Global"
          gnetId: 15757
          revision: 42
          datasource: prometheus-davidapps-cluster
        kubernetes-namespaces:
          # renovate: depName="Kubernetes / Views / Namespaces"
          gnetId: 15758
          revision: 41
          datasource: prometheus-davidapps-cluster
        kubernetes-nodes:
          # renovate: depName="Kubernetes / Views / Nodes"
          gnetId: 15759
          revision: 32
          datasource: prometheus-davidapps-cluster
        kubernetes-pods:
          # renovate: depName="Kubernetes / Views / Pods"
          gnetId: 15760
          revision: 34
          datasource: prometheus-davidapps-cluster
        kubernetes-summary:
          # renovate: depName="Kubernetes / Views / K3s Cluster"
          name: "Kubernetes / Overall View"
          gnetId: 16450
          revision: 3
          datasource: prometheus-davidapps-cluster
        kubernetes-persistent-volumes:
          # renovate: depName="kubernetes-persistent-volumes"
          name: "Kubernetes / PVCs"
          gnetId: 13646
          revision: 2
          datasource: prometheus-davidapps-cluster
        nginx:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
          datasource: prometheus-davidapps-cluster
        dragonfly:
          url: https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/v1.1.8/monitoring/grafana-dashboard.json
          datasource: prometheus-davidapps-cluster
        idrac:
          url: https://raw.githubusercontent.com/davidilie/home-cluster/main/kubernetes/apps/observability/grafana/app/dashboards/idrac.json
          datasource: prometheus-main-cluster
        nginx-request-handling-performance:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
          datasource: prometheus-davidapps-cluster
        proxmox:
          url: https://raw.githubusercontent.com/davidilie/home-cluster/main/kubernetes/apps/observability/grafana/app/dashboards/proxmox.json
          datasource: prometheus-davidapps-cluster
        node-exporter-full:
          # renovate: depName="Node Exporter Full"
          gnetId: 1860
          revision: 37
          datasource: prometheus-davidapps-cluster
        cloudnativepg:
          # renovate: depName="CloudNativePG"
          gnetId: 20417
          revision: 3
          datasource: prometheus-davidapps-cluster
        prometheus:
          # renovate: depName="Prometheus"
          gnetId: 19105
          revision: 6
          datasource: Prometheus
        cillium-metrics-production:
          # renovate: depName="Cilium Metrics (production)"
          gnetId: 22126
          revision: 1
          datasource: prometheus-davidapps-cluster
        cillium-metrics-home:
          # renovate: depName="Cilium Metrics (home)"
          gnetId: 22126
          revision: 1
          datasource: prometheus-home-cluster
        home-nvidia-gpu:
          # renovate: depName="NVIDIA DCGM Exporter Dashboard"
          gnetId: 12239
          revision: 2
          name: Home NVIDIA Exporter
          datasource: prometheus-home-cluster

    sidecar:
      dashboards:
        enabled: false
        searchNamespace: ALL
        label: grafana_dashboard
        folderAnnotation: grafana_folder
        provider:
          disableDelete: true
          foldersFromFilesStructure: true
      datasources:
        enabled: false
        searchNamespace: ALL
        labelValue: ""
    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - natel-discrete-panel
      - vonage-status-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: external
      hosts: ["monitoring.davidapps.dev"]
    persistence:
      enabled: false
    testFramework:
      enabled: false
