apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  annotations:
    davidapps.dev/credentials: pending-provisioning
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:O2ar5rE236tZiOM4v1BXsGlQGL3SXdRbx3nd9x3Toxgn6TKgmy/0j5HIw+G1,iv:1x/ZZaFAgugJMdUnL0SXp82mhMPOrQA+uwYiJy/9ec4=,tag:P4wbGK5VZAxbPPU8bbJZzw==,type:str]
  client-secret: ENC[AES256_GCM,data:gQfh8TlJrtJSjxw5V0YbHYt3bvK/A5q7uyTxbUL/XSWQOg7TA6QizCczpfgc54P5Dw==,iv:CMTzz+TlZSteiZNGQPc0j2Zns5oQzPSCEc3rugDofJU=,tag:uhz4cElBm7Cxzc5zParifg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFenNYcFFUUHhiUW5WR3Fq
        NjVydDhYRzF1ckV6eWZxUUdJVm1Yd1dRTW1ZClZhTlFKYmh0L3VYcEF4NXdTQ0Z2
        MzJTd1ZQMzI5RVUwbXA2ajVTRXkvSXcKLS0tIDFVdEl6cU40SjBPRlJIWFdLb0tQ
        NlFJZGdUQ3ZGQk1Nb2xFYldoZ3JUcm8Kue2OMeHddjpGYuHGjDzHjqZgB20/2lub
        pQ7yqLoW3DajkP33QOXKcCXdMUQmVLN+CnHfLwJKnvj+p7dc3H0fVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:34:42Z"
  mac: ENC[AES256_GCM,data:g/KiLUbLVKzH4QZt49jUwH8oMstJT3Cgqf11U9/GwiPKsOFaeQbxiH9dHeMRSA9rb1fdl73XeUvxXM1npin1trhlFUmpIezlPsAkL9z4rpb6ufTygTkDwrswOYZZinKH/LX8v1iZ6MDwlKmGVBvDfOCnhoNCckDkVJbMGhsPhjY=,iv:ZFw1afA8K/NN7VMyanti2YTeG1XQ8dtP17j1KBNZ18Y=,tag:sJKvIuN2Vo8vKWofexquzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
