apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  annotations:
    davidapps.dev/credentials: provisioned
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:dAk9o0SXb3XoEX8ff9GnnR1U8eXeJce//cI94Gnfxwo=,iv:5n74QVW1LMf0gRMgYjaGMsXlN5GIIeTSL1eX0U1mGi8=,tag:O2spP3JFqyCCULFajFYXNw==,type:str]
  client-secret: ENC[AES256_GCM,data:jwQKT8fQnb0bEMfTpWH9AZf0k9FRdz+aLzjGQyfEBihjkrnAOxYZiDrd3A==,iv:cA7MbOMD5SWYhNDVnNJt6nGgMtPYZqeE/UFQcgrp1ps=,tag:5KKZiSgWzmwrScpJsauhoQ==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV1NOS2Y1Qm15VHVTbDJj
        YU9rck1sRzJRUm9jSmNEbDdjN1YzQ2ZQLzE4ClBwRjVNZXVpRHBkeVdMN1B1Qzl5
        aVZYR0lWYlFFS1YwWGppZGZIVFF1R1kKLS0tIGtrV2c0S3dBMUEybXV0NG9zSGNk
        Qk1Oa3BGYmFWcGxFemp0TS85V3I5b2sKqA10t62nDwcuL/otzO9B0dPA0jQU0axm
        5QD5aywlsuoXrNmprr9sdQBUIjtTZv/nDwMbDReNNHWQSAWV4wg/DQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:53:37Z"
  mac: ENC[AES256_GCM,data:pGDrJEcVA9BTrdkQg6d6sYj3basX6ElW38yLn1foVSbWIPmIzsUyz7pQBtGRm8RFPUyO6Ib5/y7u6JIGiykPJw7xFKqu7oteWEvOwuq5/vA0NzJXnc0JZf40Lz6N49Ed3uiVpopyrxY+rN1ebOtOJxRBCVMYKLgMhUF7DmgtGvw=,iv:nbu2jvI9Bayo/5/k0Tg44t7KkIMuZQN52aT0JaypBrA=,tag:108a/KYXOT0aRkPt3TWVDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
