apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:MLYi3nU=,iv:z6bP0SAHX38oGc8/KmykivaQi9o+p5YrVX2yNL5ZoX8=,tag:T2jDTF/VgvpxRVTXIYcuMA==,type:str]
  admin-password: ENC[AES256_GCM,data:mr29vf6goSPxT/yAHBY=,iv:eaHrACdbjl1y0JqvdkCGF4t059h21gM4pozWNThVCoI=,tag:EmVSO1OCYO2lho87TGISmg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMXlIa3RvSVVoV24yaXBC
        Zngxb25SVE5ZUm5WUWk4TmRkQjBDR21mcGlFCnZrTnY2WDZGQ1VTc3daYkpHZVlQ
        aFFGMlM1RlRPS3ppa3lEc2xzUjdLdEkKLS0tIEJYT0pQUHk5U3JtTDVDMlA2THpq
        SnZGRWI2SThaMVVaSStOR0ZjRCs1dDgKlnbfuepWLEqGJJPxF7xp0sYXtjQAgSq4
        fpLBwJycL2lzwoLWRf2FwXOWMOwnNn7DeX+oy7zeD0BSVYPSgmF6yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T19:31:41Z"
  mac: ENC[AES256_GCM,data:aLWB0w1Sm5t+AF7VrEUJvKVm+uA4HTbCZZCCz5j4XA7oYf4hJUR/hqCnJ3Ovmsw8FxRpJAB9zqn9/1bSAaT/mI9uI/MX5GliCz5CJuS4MkWfOAxhuD3S70BxfCA17nhWJIL4OyFKB5LeqkCN1oPIYenUCs1ilHJsJWZ+SAosHpU=,iv:a9ACAUQVxMGV3xlgSWeYk2XqeOLy4Rq8Vyc6QWyRxZk=,tag:rfeoXXkZRzCfyvKLOlcqiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
