apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:MLYi3nU=,iv:z6bP0SAHX38oGc8/KmykivaQi9o+p5YrVX2yNL5ZoX8=,tag:T2jDTF/VgvpxRVTXIYcuMA==,type:str]
    admin-password: ENC[AES256_GCM,data:mr29vf6goSPxT/yAHBY=,iv:eaHrACdbjl1y0JqvdkCGF4t059h21gM4pozWNThVCoI=,tag:EmVSO1OCYO2lho87TGISmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T19:31:41Z"
    mac: ENC[AES256_GCM,data:aLWB0w1Sm5t+AF7VrEUJvKVm+uA4HTbCZZCCz5j4XA7oYf4hJUR/hqCnJ3Ovmsw8FxRpJAB9zqn9/1bSAaT/mI9uI/MX5GliCz5CJuS4MkWfOAxhuD3S70BxfCA17nhWJIL4OyFKB5LeqkCN1oPIYenUCs1ilHJsJWZ+SAosHpU=,iv:a9ACAUQVxMGV3xlgSWeYk2XqeOLy4Rq8Vyc6QWyRxZk=,tag:rfeoXXkZRzCfyvKLOlcqiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
