apiVersion: v1
kind: Secret
metadata:
  name: hermes-secrets
type: Opaque
stringData:
  discord-token: ENC[AES256_GCM,data:BIRXEjS35Gj0bj0nonvmv2TyqjKhsYpbrXfQAvgBcma7NfR3CrQOysdvO/iexv9KlKvH6e8o/L7ixC0KfyI5UOY/nQLcBOIu,iv:oOI+GJoxipb2uwNRZ2vipVIJIVXAzaInxpo7Dq5KDN0=,tag:c+liwf7lk3uPePjnG6HBbg==,type:str]
  fleetview-token: ENC[AES256_GCM,data:mNsUCbiTd1XjNLu3Rf6wUq7oPuiA+i3Yavj9l0A6Z6PoOwTOpc6KDCnnHZjJt34HZCNFuYVoGBuTi+H+pVs7ag==,iv:rvXfP4e3v9rUEwTR6r9Bk9kHsK9bbDtawLPzlcX5U94=,tag:lhgRosUd93yUwvLEQk8PPQ==,type:str]
  ssh-private-key: ENC[AES256_GCM,data:bID/LXa8JpcfGMoHKUGl+M1hOEDDJ2edZIqrkEZEAFQsW890vqRcBH4vkFt5KbonExVnQF7rqMIReFFG8RCt8TXQExn5VMhzlmpLbEb9mw7asDOX1bC6qybScRsrSGhC/ybNf7fpmWxdbNsKLavUd4bbDhljG5tJenWmm780zoZjaHdbzj/s13YeEzgedxVIEkIYS3sPwo6pN11q5FOlT0Eh6Zv3J2sVI3GyaU4j0ejNUx2cgt89sQvqLfoUzsMoYzFRpduG3FRESkl8cCMifGyEVmaEKog8BTw9qiT7QeALwFXc4qm72Nt7KqIPVWQUMQ5BB00AIhCw180it3M88C5EWvaV908dnq/3YQ+QRyneRaNoWil81Z28plIwMp9lAS+RY1FXwLA7q06D1mkzYs/XyLhHt7mPMQOJkbIc3cqLCZnogvLwlGvu+Wc7BCPLyqtIDfbTqv8pOhfECuIDYa+H3ckc7xgWMR1C8Y9XmNN0eKK3Stu7h1V6l27rWl6LdD6MocmrixD6BtsSIQw0,iv:kAuJex2eT+tYjHeMIK/gPrhHQPcMIqXIlDWQNxsjpsQ=,tag:ja3zzNkCQGfqE5sMC9XbQg==,type:str]
  mcp-token: ENC[AES256_GCM,data:cFCTimgEdMeMMDFNUOsjySTFHPeM0pVQ4h+sgXxF9vF+aYsCXlipoRSNabi19L+K058SaDu1V1u9dWwThxioGg==,iv:mmm2KsZgbZh9uB2QZPXz8+4xwbRrXDQVeDkWAquDT5c=,tag:yPLlkWWbhCTHqwpzNc/+Qg==,type:str]
  api-server-key: ENC[AES256_GCM,data:1WcFi1UV26YKD0vvc9REnpSi9UNliyuv9Wr46hd2EC2Ae44N7CFGATnYzSyWvDfYsTxjyqq1b8hnI7Fl7YoUpw==,iv:SXFmoAKeip5jjAUvVIwlSN/24oKkj0M9f1f7seWN8QE=,tag:Fa5IgqGiTEnaHJCZo8V1Hw==,type:str]
  cliproxy-key: ENC[AES256_GCM,data:ryvmwTke60XGetPkmJpW/5FebKEQp9zgbzt8uHWHq8B/SC1PP4NTaOhzQPo2T2LiKD6rKA==,iv:ifOeFbncUwQPf/VQnRl4HbjdGpLd5iLhLt+TcZ1BsA8=,tag:8U5NsIODM9lodCuWiYhliw==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQi9WK0t4Uitmck5xV04x
        Tmd2S0lQdWZ4Nm1CcmNVekFSRjFuRE5yQWpFCkpacDNVQ1ErVjNOOGkvM1J2dFI2
        bXRYbUhhc0YzNjQyTkRIMFpYd0VXTzQKLS0tIExORzRLZkMzOVFBc3B4Q3RieDU4
        WmlxbVNvcVRpQUJqVGdwaFo1RGIrdnMKxb8JSJY6/xdI1veZBB8UJoxh0ogBP2mU
        CCP3hy933a/Phtuege6fz++u3MWbzIAC05BnpR2S7D3ctDxkLc+1wQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T17:50:08Z"
  mac: ENC[AES256_GCM,data:zVkKGot7qyy1zOHHbiLFheiPtQxGQY3sDKzEkHDRyd54xTl89QdmKZ3Vgd8yi2R7BFLQlQpb5ZpuDxJKTZUDW+DIcvkio8IZpci5aGCjfXI71ds+/jRAQr65q6+ZdtmfGIQe9YwQkmYhbXoIVFpRrasbFUWBgWGG2MclbZrXzaU=,iv:OgHfm4CkxCVtj+MTVIsw0obHlna3PqxPOHZSAFF7kFk=,tag:H4euzxkc5LkJCAsxb80MCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
