apiVersion: v1
kind: Secret
metadata:
  name: hermes-seedyn-secrets
type: Opaque
stringData:
  seedyn-api-key: ENC[AES256_GCM,data:f//jN9mLADmgtGbXxUm3ZGTOCvyQimdYL/1L/vMdwE/DRQ2hf+GABtqk0M8km1uYUPMgYIKm2dc13HcCGQ==,iv:cJ+BukCNKiPZluaJcAD5tdwUXqah/Sovc4doFqbqQ2s=,tag:G7ZQjlcRkpvqfdxXPRre8w==,type:str]
  seedyn-broker-token: ENC[AES256_GCM,data:TKFtYHwJvOReagRVgQmQEmtMgi0OTakNR5eznfqw3GQvBdL9X3aycijJZJScoojgTpEMJQIpN5z/GpUjAAceyA==,iv:2tiWjRTbJHVPvqdOlULB72S2JqE3b3S7nOu8/hLqO7w=,tag:AXpJzJ6Bqaf6jbD2nJ8dGQ==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TkZOdnVGekhpMHllNyti
        aDRaSW5wV2Y2QXIwMC91NTFKZ08wOXBUSnhvCnc2ZnZaOFROMWt6YXFMYmpjMmhG
        VXd1M2lpUENuNjZ3dStCdGRTZTZHeG8KLS0tIEVHRSt2NHdlTlJVTHpPSFo0eU43
        cHJGd2l6YURFd1IrRW55T3dzemFZN2MKUBeivzB4/+7qTj+C11ThGtyIs0tF/MU9
        7eFrBMou9mWkgluZbPxYGKw03HNLp6NCkqf6E1YBAdZCFybrIFfk5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-23T18:17:26Z"
  mac: ENC[AES256_GCM,data:teo3M/L98zFyImpPgLWrgth04f3RHRCfya2SThuQNh3QCFF/Eh5y8EWgJIz1OkpR6UwZKVA1YaTeKE60lGwNwokhDAvVHMcec+DrNb10tlbTTCP4fUL9aBUXQ/qa95h+qyylke17Hsqykjx8PlCNCt5A5I5zPl/BNj3JwLxYlO0=,iv:WuGr4HXipeHgd0MQko6GG3ySimbCLAqiIJmBkHrR4U4=,tag:hj8fQcnRJ087yn854SXkLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
