apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: default
type: Opaque
stringData:
    EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:Juj/ZMs=,iv:aMTHOb+YfjfYwQgsBB3XiPkmUk7wChEVgzaSFdDYLfw=,tag:7fAVTNV0RMjZgvoZ7uYkPw==,type:str]
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:HwMQzcUTuNtLf5RsgV0=,iv:VMsaygC03fSI71AZJEvSb478YHhG438GGX1g7ZEvs3k=,tag:klN0wPJI7QynC21SjeOxUg==,type:str]
    X_EMQX_MQTT_USERNAME: ENC[AES256_GCM,data:yznsS1I4Q8Y23g==,iv:Uc0OELcBwKzbKxhVooiLnZffStSi98NOM+fhtK18x84=,tag:h0u/e+kfdwtfLCIhZyJo8A==,type:str]
    X_EMQX_MQTT_PASSWORD: ENC[AES256_GCM,data:PihZL3/mK68=,iv:FP/OwrxFxhvaz/uClufQYVxUcQzpn0cwWAGsv0OAEtY=,tag:KMgeSToZrnp5vnRDScuGtA==,type:str]
    #ENC[AES256_GCM,data:yuMF8a/ObIuLLeGt0quXeiIBhH8=,iv:KxXI5dKUrOy3r4QJ2bN97tlqtKAQzHDxPpI8YBHz+Ms=,tag:Ds7n1Gi6kzShMXsFpU5gkw==,type:comment]
    #ENC[AES256_GCM,data:7EANXLkxQZ3Pg7O0Xk8XaXM0HrIydAQ=,iv:+af5KPsq7UG10qJBfQnyjCizxGjRvCSwbDkek5G1zGI=,tag:ih9o98l3kOpmc6q0Yv2cfw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-13T13:32:56Z"
    mac: ENC[AES256_GCM,data:EFrQRgyN0LfCV2jY+aNKYhge+lAROrRWNYa9PmDW55uPlHaHLYBth4/3Tkhikp8nT4EKBgG39cCPKEGMzWsw8Se+OC9NZ42WnDSe+NYLViM1Uy7wi7zWIaJ2qMfGAeiQI8XFQM2ir1m1L8Euk7RbC+3fY7YMOCcqRD0ClhDndQo=,iv:imoDtYdJmcGsd360kPmNblQzppKqLlMX13tZCfW6akU=,tag:qItd3bihNtzY8IK7QYp40A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
