apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: default
type: Opaque
stringData:
    EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:Juj/ZMs=,iv:aMTHOb+YfjfYwQgsBB3XiPkmUk7wChEVgzaSFdDYLfw=,tag:7fAVTNV0RMjZgvoZ7uYkPw==,type:str]
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:HwMQzcUTuNtLf5RsgV0=,iv:VMsaygC03fSI71AZJEvSb478YHhG438GGX1g7ZEvs3k=,tag:klN0wPJI7QynC21SjeOxUg==,type:str]
    X_EMQX_MQTT_USERNAME: ENC[AES256_GCM,data:yznsS1I4Q8Y23g==,iv:Uc0OELcBwKzbKxhVooiLnZffStSi98NOM+fhtK18x84=,tag:h0u/e+kfdwtfLCIhZyJo8A==,type:str]
    X_EMQX_MQTT_PASSWORD: ENC[AES256_GCM,data:PihZL3/mK68=,iv:FP/OwrxFxhvaz/uClufQYVxUcQzpn0cwWAGsv0OAEtY=,tag:KMgeSToZrnp5vnRDScuGtA==,type:str]
    X_EMQX_APIKEY_KEY: ENC[AES256_GCM,data:/ul7lzQYd7O+FlhJQww=,iv:gqKhZ83hICXGc+2tkF+MLHc1IsGma/NoF4H72sMhu48=,tag:FHJmkb9O/bf42A6Mz1PUIA==,type:str]
    X_EMQX_APIKEY_SECRET: ENC[AES256_GCM,data:fB391K+0dkA=,iv:BksXwbmPDp2alD4WOPnW/Fhg0u0AKAlsM0AaYb3rPIg=,tag:qfFJ0h6e2GXI5pmCjHqqAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-13T13:45:08Z"
    mac: ENC[AES256_GCM,data:VkUm5cNvlnM+m1t0Ec7+S+WszXGwpS90hwnpCxp5blX8Vw7bifBkLzPKgZ6tqyKjWkKf8v4Ik5buTVUS9ghlSLt3eumRXHp4Js0f3BCwDnQtgyqUxkLYIMua6Fu+zMXW7CzCJlWmjWNfczWB4BVLmAW1mBEb5PFrPPmQx7UC/fE=,iv:vkXOP0pQ1JL99fkmmC2quqT/FIsss3PQ0M9jkUaWBKI=,tag:QxrTfyxp53IuGV53HDQhFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
