apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:OCPKdN8w5NZRtYK+hHjgAabNud4vllLHS/t5NkCS5LA=,iv:JQOf4buIabtHNQdqcabcwcJ4yk2va+Q8lbuiSe/fO1o=,tag:LJLJWGUd36LfxE0iD+GyoA==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:d27tEhkXBEXSnS85Um+8hJ6n2vmDLcYopGogwV/LttMYDDfncsFLwQ==,iv:cDegIiXyx1+phl8vRgGf8VYc853SrGHsfLbISuIihfY=,tag:ffNXofqNMnIe0vBaLTF8GQ==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:9Bii+g==,iv:5AwwyOmlEZj/E14heWMSUvts//EXAUqIfqHMzf2YKqs=,tag:IndmH9cHPyfvGSJC5yzI8g==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:T+Lb6fee,iv:Zk9BBk01M4NHVbxdrIF03sidpyf1pvOv9hOv5MZ/1nE=,tag:yCQHEkrWxmgUkDZ5MAwCfA==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:D+lQGPdI5yo=,iv:lqQUTHRa+tUYS5bRJ/nVwyel3cUXehXZmD+rd16Nuh8=,tag:suGpc//sWrmlYdMQPDMZig==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:tMV5Bh8Y6XoYCsk=,iv:NWnte1AjPyctM6czkmFCYga6/e7WYEy9lM2acyZ4YVA=,tag:WB9Ufpupy8t48LB0eZBy/Q==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UcPwwtf1rF5911I=,iv:tu5twiv79JB9Rh59SjNnZcEEKw9NgKilsckTjHrmBOk=,tag:2oZl+RfHTGKvrYyQgNFxSQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AgHkeJMUhDEjwNBbbG+LuDBcIeJlULM1bXilh9SKOphqpF+nmHSePQ==,iv:di+rLzaQJ4wzC+m84o9H9dJO043Izv69DpVNSrg3DXQ=,tag:OzPtURI0FA8lu8YMfyCBJA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:X4orfr/q,iv:1dbhXNykOwhfVnvSINiauYT/Ovl90/IB8WZIEuWrjcw=,tag:m4a+qjpnPKD2OY3JaXV8/g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T20:45:06Z"
    mac: ENC[AES256_GCM,data:6swFmWZBmdTSfc2sZjasgs+H556ln8QmSAiaZvZgDJWQTCqzNyOjWUJoCvUAYZ6BH+OgU5CMLEjGY4TBuiWqDUzzMdE+TLK6p5clqjVplbfV2B3vcRhOxu5+xqdiGvdsFm20eRQD9AFogI5nWYNDTKgMM8ygRSiMFuUaOyApyyU=,iv:eDrfUeAQ8/Hf9UB/uaI7K5n11J0addcQCQq8ViuUKXU=,tag:t1Lwy0EyE7MWW9dzN/6CVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
