apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__POSTGRES_HOST: ENC[AES256_GCM,data:DZyoJ6ONPeZXE2Cj13MZZm+Czjed/wgY27PwTeOpRpe5y8albjdR6g==,iv:nYqqdXF0lzIKwbg9o1Hu9WOdLmaKCO906Ib/9Vstbuk=,tag:l/rldZLaao7AtZYXFSgywA==,type:str]
    SONARR__POSTGRES_PORT: ENC[AES256_GCM,data:j8N+BA==,iv:ymhChLIT0JZva5lM2mGQPaFg6ZLIj/1kGVLUGZL91vI=,tag:TAFpVUMCNFu4fgnNBpOLNA==,type:str]
    SONARR__POSTGRES_USER: ENC[AES256_GCM,data:5pXTI0cd,iv:F0R17unhLCCztsIN1mbG9WV04bLVAVU2nFGx/ej0DMY=,tag:gl2mNytcdOhDGfgUrHe5fA==,type:str]
    SONARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:PKY587LoUW4=,iv:jc8EtGVVgttcIjl2VU89nRoT6CCWiUXpeJ6jO5UFuCc=,tag:i1yc48EuLf9uONIuqDqw5w==,type:str]
    SONARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:TRXAGTQJ/uDDiyI=,iv:GNotiDE4lOLhXCjxcqS4E0LUh1dx9GEv3wKpEUYvM4E=,tag:Bumwzvuol0Io6tug5nZwgw==,type:str]
    SONARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:NGo13Mqrz0CTFQ==,iv:Mb+4trXiWC9gkiFsbqfU26Es4QM4aOCL9YPL39cdMxI=,tag:MCKC9nqPvye+QPTfMQwhog==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zkqTtKz53vRQX/D/3Cv1a7H+JSs44w==,iv:xjBWAabHUj75kBj/uXZ7jVIYih+BpmwdBXIFjZx7Rzc=,tag:ksJ4DtBNvJeDkM0jvs3fBw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AgHkeJMUhDEjwNBbbG+LuDBcIeJlULM1bXilh9SKOphqpF+nmHSePQ==,iv:di+rLzaQJ4wzC+m84o9H9dJO043Izv69DpVNSrg3DXQ=,tag:OzPtURI0FA8lu8YMfyCBJA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:X4orfr/q,iv:1dbhXNykOwhfVnvSINiauYT/Ovl90/IB8WZIEuWrjcw=,tag:m4a+qjpnPKD2OY3JaXV8/g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:32:11Z"
    mac: ENC[AES256_GCM,data:ivMhUhnjqcGLkucjgWsFiGYCU3tSdV6zP4fwyYhs+Y6EovTuHvH78nUHPLrcA+jUaVOC4ALorWxAk+33fj/W0lvLVU5kJnlNhRdgsqBy7PZgtND1LU0G2F+cE3mqCQeBDPyfQodnUk8/2b6bSXDhLqSHeFPApD2WmYi/4u8AKLQ=,iv:XE0r3cD4jk7fi6nkMfAcKnWbJ5E+q3zAN4LzlRMt8ic=,tag:+Bmiq8Ug99SuIvDWSTsIoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
