apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
type: Opaque
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:OCPKdN8w5NZRtYK+hHjgAabNud4vllLHS/t5NkCS5LA=,iv:JQOf4buIabtHNQdqcabcwcJ4yk2va+Q8lbuiSe/fO1o=,tag:LJLJWGUd36LfxE0iD+GyoA==,type:str]
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:nejGu+FtvX7M6V+mbevNQBMpxeuPWPJferO9TfR8YDr1aiO4zIJlEiA=,iv:iXSARf3hFknukMcB00vRXQu0oRZ2lyNe7rgWwgKfETM=,tag:zoWnUaS04ZI0ztqN+NrqBA==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:9Bii+g==,iv:5AwwyOmlEZj/E14heWMSUvts//EXAUqIfqHMzf2YKqs=,tag:IndmH9cHPyfvGSJC5yzI8g==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:T+Lb6fee,iv:Zk9BBk01M4NHVbxdrIF03sidpyf1pvOv9hOv5MZ/1nE=,tag:yCQHEkrWxmgUkDZ5MAwCfA==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:D+lQGPdI5yo=,iv:lqQUTHRa+tUYS5bRJ/nVwyel3cUXehXZmD+rd16Nuh8=,tag:suGpc//sWrmlYdMQPDMZig==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:tMV5Bh8Y6XoYCsk=,iv:NWnte1AjPyctM6czkmFCYga6/e7WYEy9lM2acyZ4YVA=,tag:WB9Ufpupy8t48LB0eZBy/Q==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UcPwwtf1rF5911I=,iv:tu5twiv79JB9Rh59SjNnZcEEKw9NgKilsckTjHrmBOk=,tag:2oZl+RfHTGKvrYyQgNFxSQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9CHR4dP7JwYTcSc8AWqZJRHRADGChdFq+ytH70Izddz4uPW4JBmD4cM=,iv:9GHQ2f/m/whrekvVkcidouNkpYiiZnljeD2+XAWTryE=,tag:PPcLBTFUATdw8qHOkn4v3A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:X4orfr/q,iv:1dbhXNykOwhfVnvSINiauYT/Ovl90/IB8WZIEuWrjcw=,tag:m4a+qjpnPKD2OY3JaXV8/g==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbnlJb1JnY0JwQkxQN0Q4
        cGpGa1k0eDhjNmFWVkc5V1VUdXlDU29sYmx3CjgzczZPYjlMdHQ3dk05N0UzQlFm
        WVprZ2tYS1o0NDJtYy8xcEN6MUdqcm8KLS0tIDRRMGdzaXVOcHJiSkdxRjhZUHB2
        aUZCYWxMRUZsR0ltb1E2VUNIb3lZcm8KvKWZdZ7SgCk5lTeTtQSgQL3Cbk1YXfOe
        f8u3Cbvn5/Rp9LK4+sjooEfZiMZvH47Xk1o+cuqk6FWLqUlFz85Tsg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUEkxSXNrT3M4NE1rL0p6
        bEdTZUVOOHE1QzBEbmIzbXNaa3ZqYUhZZ2dvCmhrVk5rZUdObXpzY0N2c0V3K2VG
        UzlaTk5ObkJzZWVjUkxCQS92YXVuakUKLS0tIEw2OWJITjZpaWk1L0xkMWVpeGZW
        Vnp0UWNkempLNTBINnhUUjlodmpMZlUKG2JUoH2iqMsz7LjRFqnF7UOpqfYYObWZ
        B1nut/FjoMHbHG36yAy6M52pJktsNKJcA2n2HkdEXrsIjVvimhYFHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-07T15:18:05Z"
  mac: ENC[AES256_GCM,data:XAw+VJ+wRtJqGW9iKdNG/6TdCgooaXhciq3ajpb0yTpMFiVatWIKaj2dUVOMRbBgnmZR59weo4iapcL8g2ECJ/O8N+64vrrUVXxxg+FLnmgzr0MamPWyhhSPhPXUCqoPXWN6fVMLwTauRmcI17FXV7hjh8jg3fYYpUxgp1GNKJs=,iv:RyIVwHNIPO0FMiaje5Q9eWf0x/DRbqQJKlgp/yo8OKY=,tag:xou5iRA4nOLjVAChqCfe5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
