apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:OCPKdN8w5NZRtYK+hHjgAabNud4vllLHS/t5NkCS5LA=,iv:JQOf4buIabtHNQdqcabcwcJ4yk2va+Q8lbuiSe/fO1o=,tag:LJLJWGUd36LfxE0iD+GyoA==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:nejGu+FtvX7M6V+mbevNQBMpxeuPWPJferO9TfR8YDr1aiO4zIJlEiA=,iv:iXSARf3hFknukMcB00vRXQu0oRZ2lyNe7rgWwgKfETM=,tag:zoWnUaS04ZI0ztqN+NrqBA==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:9Bii+g==,iv:5AwwyOmlEZj/E14heWMSUvts//EXAUqIfqHMzf2YKqs=,tag:IndmH9cHPyfvGSJC5yzI8g==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:T+Lb6fee,iv:Zk9BBk01M4NHVbxdrIF03sidpyf1pvOv9hOv5MZ/1nE=,tag:yCQHEkrWxmgUkDZ5MAwCfA==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:D+lQGPdI5yo=,iv:lqQUTHRa+tUYS5bRJ/nVwyel3cUXehXZmD+rd16Nuh8=,tag:suGpc//sWrmlYdMQPDMZig==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:tMV5Bh8Y6XoYCsk=,iv:NWnte1AjPyctM6czkmFCYga6/e7WYEy9lM2acyZ4YVA=,tag:WB9Ufpupy8t48LB0eZBy/Q==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UcPwwtf1rF5911I=,iv:tu5twiv79JB9Rh59SjNnZcEEKw9NgKilsckTjHrmBOk=,tag:2oZl+RfHTGKvrYyQgNFxSQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9CHR4dP7JwYTcSc8AWqZJRHRADGChdFq+ytH70Izddz4uPW4JBmD4cM=,iv:9GHQ2f/m/whrekvVkcidouNkpYiiZnljeD2+XAWTryE=,tag:PPcLBTFUATdw8qHOkn4v3A==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:X4orfr/q,iv:1dbhXNykOwhfVnvSINiauYT/Ovl90/IB8WZIEuWrjcw=,tag:m4a+qjpnPKD2OY3JaXV8/g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T15:18:05Z"
    mac: ENC[AES256_GCM,data:XAw+VJ+wRtJqGW9iKdNG/6TdCgooaXhciq3ajpb0yTpMFiVatWIKaj2dUVOMRbBgnmZR59weo4iapcL8g2ECJ/O8N+64vrrUVXxxg+FLnmgzr0MamPWyhhSPhPXUCqoPXWN6fVMLwTauRmcI17FXV7hjh8jg3fYYpUxgp1GNKJs=,iv:RyIVwHNIPO0FMiaje5Q9eWf0x/DRbqQJKlgp/yo8OKY=,tag:xou5iRA4nOLjVAChqCfe5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
