apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: default
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:RsxWl8w=,iv:TIGcdMzaZXy6MjbPTxtJzKqYgdH1G4CJVD5jwZH5H9M=,tag:9sgA+VKOkuHm3kp0JAYh6g==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:5IeAPxBP4sGUF24THlE=,iv:jrVtgMTUBzWSF8h/hewbbZpTLNxl7JfxPOEsAPK3Gqk=,tag:IlFaWjDr7QOlQqQv1eiMLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T04:20:11Z"
    mac: ENC[AES256_GCM,data:H2zwEtVRtNjBUsVu0PpDMk8VnUOpGAEm3bysafYETuiX+PKF/wulyEt8Xd0NY+JvVcavKRiozcdR6WjmeBSOlbxgikpCT7Ydloy8HE75Mn0pkOIKvVlpDxzqT4nYeWGq+5bXbKxTHSCib+YWkEcJWlZp5t6pKyYX/tdcs/Wmw8E=,iv:Qwrp02KW7ZemK1I0r8BOXp1352hI20TcQi1tqeGD3f4=,tag:+MOP5iY2QXrj8U7gqB8UhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
