apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: workroad-production
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bernd-schorgers
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: dragonfly-operator
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      workroad:
        pod:
          imagePullSecrets:
            - name: docker-regcred
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/davidilie/workroad # {"$imagepolicy": "flux-system:workroad:name"}
              tag: master-ed20d7af-1733908646 # {"$imagepolicy": "flux-system:workroad:tag"}
            envFrom:
              - secretRef:
                  name: workroad-production-secret
              - secretRef:
                  name: workroad-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 1000m
                memory: 1000Mi
    service:
      app:
        controller: workroad
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "workroad.app"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: &hostwww "www.workroad.app"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
              - *hostwww
