apiVersion: v1
kind: Secret
metadata:
    name: workroad-production-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:qV3lmT0RnJMi/TwEktKi+W+MatW1EeaiIlRXoaP0QZCC60Dv75R1JVrgoNLNh4q3Ffr+okpleDwc2724edv8hcmQiXqQ16aeU15C6ZCw9ZpDb+fYqpSNRMEUsHcEhRRLvFoytoEnaxbKnDkPfjLBpjZPHVaARQxbCglNUz+VPvW18/Bg2eO1qtiP0I4=,iv:cw1TdKo0vhKhwRjSYOa+UPO151XoJGS2gzbDfDgVq6w=,tag:5/uiL0wVXGrk8vi/l1xh9Q==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:EcdcVJSf5vBf8RacKR/gmbUznkglTPadclu4+/DK8XXOrE4I7Eg3UoW08xpE,iv:zRmd4ZeWMKFrmvDO5BvXUmSDLAnJdAoRUqzR/e1sHvY=,tag:2VnDVcbgn/iScVljLsh/8Q==,type:str]
    APP_URL: ENC[AES256_GCM,data:jsV/MjicOCI7OHmxuZLds04GHJE=,iv:dD0qNZxb16KW6JaQi2oKWi7SBfcDyMh2j7Out7RO6eM=,tag:w2hq0rT77CFSgntALpBx7w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:PYRQwmCIVfC2HNA/ZFf4hMVo27TFkVT4n+hcLp0mYU+TMHkywQlTGFojs05qypHcP8V3qYvWhbCcVvFv,iv:OkOGsxtmWAbceA/ihlNg0DXev3NQr+VzR5CvwbKdpTA=,tag:AI1U9Aug5r7kWB4jzx65WA==,type:str]
    STRIPE_API_KEY: ENC[AES256_GCM,data:rhBbIxBDnjs/2bbbJ12Wwy2JZlDfLCHL4zQckrjp1do0+/3AGHtATb6OMK4w8368XMXNx5MvmHx8S3QTCuerpPX0poXBaf1G1Bywto0qT0Onl3yl2rdkqTqcq8skmSDqwGv9Q4e27OsJuRo=,iv:QLHpbaMxmAxKYLaNkXb16mSWdAU2Vx++NybIIEFsW9Y=,tag:czt0PYROJ4UIZppntRxgRw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:ASUtFvKQYgP3gAHUd10KnZbc0S+cpIClQWZE9XZFEVnAIWU+cN8=,iv:qN9u27BVgHxEjvq/7oCruuK396e7GBH9LosaoGUncAY=,tag:iaL542MK/F+d8sW6qR0tIA==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:Z9N0bYBOji89MWbA2yMMi2xowIZpDCfqOgluY6D+VyQT6EMM,iv:gHVg5SnO4gTQ3hvYXUvtnnD9t3FkjS2zYNUaI0Z+Rd4=,tag:LAL1Exq38yDC6jSR+H0lJA==,type:str]
    MS_CLIENT_ID: ENC[AES256_GCM,data:kkTAlTzZDL9cS+eWeeoZCvMqiscRqF0/hRJ3KAXefBabsuNR,iv:5/+zz1/Amr832bmCldGch0UfBRg7LuXkP4wy6461dBo=,tag:wioEvasdJm+sQzQG+fdzNg==,type:str]
    MS_CLIENT_SECRET: ENC[AES256_GCM,data:Pa060OKlTN2+cPh0vhhOqLIEjYA6HLFLgZgLMXViQNJqBoHKNzK3,iv:VnOiExeni905vVJQkUvpyUv0QoqpGT6PKxsOoiwjUjQ=,tag:mgHkmkWs04Zr9keOxhT6+w==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:69MmkW3OTI9sUxw37O1LN6aQvYK3J6AHCIsSmgli5y7370E21bzOPoYjSqgqKn0mrIJuv7ok5KWy6tgfbMWoMDCRdY9AaZwG,iv:2taC3BfXXhJll/whIxk0dF9igR/QWJmRVAaE+bbWD48=,tag:n3fI9HpomkDfn/GGEjbPog==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:cJt2i6fgy6YVJJLJGDBEPDjEWhvky2M2DFo6XNB4pJrUIPA=,iv:d3X/E+vAwjFb4lWW45tORHncyImMJpK9boxJ2ONvyn0=,tag:nR/ipBLHKCKEPjbKj4SJzg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:HbGU84sr0K8m5wovHNtMVL2Wi0TVlAkmSRifF2jMgjNpBTV+JfOJq/iPSMZbhQmQacpQWinNTf5Tbvg6nx5P1/Jpw+HLWJVZojkHkS3xY6EA0NqWabgxYW198PUo8ULS4qDtkRPiueESgE0zhQE1ZFEUq2HiWrvZI0HJtrxBMhSozahe,iv:fR3Bj2Y3puGogjKpcHpzpM/HYhsmDWMSbkX7KHYBgIk=,tag:+YeqlxbXYVdcw6nqrqyj5A==,type:str]
    S3_KEY_ID: ENC[AES256_GCM,data:7N8kAecKRKkEqQ==,iv:cBKrelFkitmNjRA70unhRI1NUWr7ZBi5Tm/yXv6DVpw=,tag:6AJM91rHh9hEvLcyS6CFYA==,type:str]
    S3_PASSWORD: ENC[AES256_GCM,data:VLS6UX4e/6OewsI8m65cFE96qBdgCAd6MkZfwxuwUHE+1vmk9PhALg==,iv:eWEXZQrfsrS6DW0B10wf5tTurPZlxywruyG8ZMuFqmE=,tag:UkfWMvJ8d2Tnd/d6xVUbWA==,type:str]
    S3_URL: ENC[AES256_GCM,data:4cqr3vjFnEfFxeay2kcAjg==,iv:8B/AA7WQnV6jtMeflvbgzqZkVGfJRBUrmjcIJ1AmvAk=,tag:UTV2Qvih0zgqzVDpgb8SVg==,type:str]
    S3_PORT: ENC[AES256_GCM,data:mOQf,iv:VBEjI6/+ooflWdo1G8r3uBu8FfrL8uqtmyapd1OmkTQ=,tag:Y2wVKzU4/7fFVBt2nVHgfg==,type:str]
    PLAUSIBLE_URL: ENC[AES256_GCM,data:S6fzNFK+wX3ydtoBPkbYdQAeKZQxzUJ6d5MET/nNeJCRqqdR6OqbR3k8LdnCJQg=,iv:xA3GEp3wH8N+YkF2UzeCwqZ9QxB/lZi08xPt01zSskM=,tag:qLKcFMz6kYZwwvLvbd5v0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1JIcWljSThtZ2JodFVJ
            aEpqZWdESDFURUdLckFWQ1IzUldyT0ZCd0JrCjh0MFRRQ1c5N3haRkZrQXYvU0VW
            TkpKQ04xTUVLN09ZUUx0T3pwVXp2U1kKLS0tIHl6RG5INEVpSzJvRnZUeldXd3R4
            Nk95dm5qdEY0d1lVc3dqRDJTNDlvQ1kKLixoeBTKgw8tdBEOgemi4P13l+WSaenK
            HX//jMdwuyBbOVgBvrQaN4u6NQjNANoG9WQC2pdJ5woT3aklNqaV2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T01:38:28Z"
    mac: ENC[AES256_GCM,data:btz7NxjvrQstfKGGTmPCCg9kSYTVIvwJtJTfdBilAxTYKNv+M5rcRVJK8+zc4Ag4/vEr0gVPo501DiQ7pvLK7IWu9DS3kgNLrr9zcHTBCrqelFZek7s+Kb1EAyc272NdtrdrpRHZIh4/Q0hD5fWoOO+fnpRfCOstTbGFipCs2go=,iv:ict+A1GdrlGB0/powyUUemc1GqAjwSSd0bnxOWfoWNw=,tag:Z1i2soMDcJ07mIXkWp/MVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
