---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gokapi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      gokapi:
        initContainers:
          init-dirs:
            image:
              repository: busybox
              tag: latest
            command:
              - sh
              - -c
              - mkdir -p /share/gokapi/data /share/gokapi/config
        containers:
          app:
            image:
              repository: docker.io/f0rc3/gokapi
              tag: v2.2.2
            env:
              TZ: Europe/Bucharest
              GOKAPI_DATA_DIR: /share/gokapi/data
              GOKAPI_CONFIG_DIR: /share/gokapi/config
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: gokapi
        type: ClusterIP
        ports:
          http:
            port: 53842
    defaultPodOptions:
      hostNetwork: true
    persistence:
      share:
        type: nfs
        server: 192.168.25.3
        path: /mnt/data/share
        globalMounts:
          - path: /share
