apiVersion: v1
kind: Secret
metadata:
  name: proxmox-exporter-secret
type: Opaque
stringData:
  PVE_USER: ENC[AES256_GCM,data:GlshntiloHw=,iv:/wT/HL23vp4hPy76L3dAosYx1fGTSQfQnhvEfHjOTMw=,tag:KiE/mtNwLMZZFKUDAVv0wA==,type:str]
  PVE_PASSWORD: ENC[AES256_GCM,data:WffNYznacOtCELXxHoA=,iv:FU5IIiM7vxdx1Xnb886iDJzsDqZhPIMnmZc8A0yuFw8=,tag:Nn4wB+FcMfEHxilz6Fvtmw==,type:str]
  PVE_VERIFY_SSL: ENC[AES256_GCM,data:xVNPggM=,iv:KapjSO/jeoPUbmBrBjT3szmJEuIwfYTkt+qLQmUDIz0=,tag:olFhCqtLXIcJnDCb87rbiQ==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibFJPMUhyNDBoL1IvaG1X
        UUplbHFDblYxL1ExQVJDcytEUnZZK1NOdkVRCk1aMmRzU1BZRlRKbUhCZ2kzZGdh
        bjZkMjkwWkdUQ1l1Q2xsMHNVaTFNUjgKLS0tIDJjSE40aU9zVENPbUQ2bFJPK0Nt
        RnZBZnlWcC9ETWRkYVE0bTdIekJQeG8KwEXtHE4KqFrzVL3zPbCerDjbns8dXycF
        Ugeg8SQE7VxRLZHC5QFdXlUQ5oJrq4Iv2TDiOOGqjfnOVSaxJHCy7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-31T12:13:13Z"
  mac: ENC[AES256_GCM,data:cywZNf602jIcVQvxqkFzPfgeylVVRmK5qmsiRvK4qullF7oOvjMyK/BcSTf7enkN673W5Pn78x1vH4iRhYJ/222gkg2jyUcIWrFmqFiY8A6q5fdebbXOUzejnxxg7OobB29oGzrWT/hbNxjcyP5D0jfJfBzBZVeZ7A5Bmait5zo=,iv:uElbd71uywb4XMeHHpgO60h8n/eAovPLYVkC6MLgbDQ=,tag:5WBvsUD2FMnCiMoW+UcYdg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
