# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  driftDetection:
    mode: enabled
  values:
    controllers:
      influxdb:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/library/influxdb
              tag: 2.7.12-alpine@sha256:d948cd7aa274696d76ccc3f7ef732180d9f9a4229aace3cf68ae008693665137
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 1000M
            probes:
              liveness: &health
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8086
              readiness: *health
              startup:
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  periodSeconds: 5
                  failureThreshold: 30
                  httpGet:
                    path: /health
                    port: 8086
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/mdadm-analytics-storage/influxdb/data
        hostPathType: DirectoryOrCreate
        globalMounts:
          - path: /var/lib/influxdb2
    ingress:
      influxdb:
        enabled: true
        className: internal
        hosts:
          - host: &app influx.davidhome.ro
            paths:
              - path: /
                service:
                  identifier: influxdb
                  port: 8086
        tls:
          - hosts:
              - *app
    service:
      influxdb:
        controller: influxdb
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.100.96
        ports:
          http:
            enabled: false
            port: 8080
          influx:
            enabled: true
            port: 8086
