apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:S7UzaT8/9j47EQ54fwJc5C2gfs3uQw9+Blha6LYEpDppWS9AbefPeg==,iv:6CrUzr5Nh5IoxfuWNZWOYA5IagXtCNTYAL7zDeh6RCQ=,tag:fd+jq/AmFLCW7sZYYGMDsA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:rLY+FgA3SFsV,iv:Ud6Ovx1dYXzAArY3PD2sCvutwopjtU6NxCv+qf+3pHA=,tag:Jb378lZcYoCjhqa7kiXxQQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:xjONj4nfFowL,iv:Tu91qwKjeV/q62rccpBWwSs498OUx2NksDPAxyKAe4g=,tag:H2lFGS//caKsEEx58rxRvQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:cArBcxDmo04=,iv:X3f0FxZVtqV1PDpdT0e+HdV5mwMbiTXbxOhyxF4FFsc=,tag:sXrY7BvQHTWOYn03Ms43Kg==,type:str]
    AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:KQ==,iv:mCZDfn9fol8Lu64FIYT9u5XDTFKk7YC8dRBeABpslOE=,tag:5B1XUmKhHnTxqveAxjJutQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:wbErk9P/MzWEjnqa9CwqZjgwITFwSwSz3EYnuVDXaZC/2TV72JTxLbLve9/hibJUQUF1m1L4jDEZiduy,iv:uwiNyrQ6tEoH1vMeEPyrk06DhSP7Spc5RkmjEACUCto=,tag:Mn47f93k3UjKqVLjcRuhMg==,type:str]
    AUTHENTIK_STORAGE__MEDIA__BACKEND: ENC[AES256_GCM,data:sfQ=,iv:U+WHD6IFb6T3Sm10nkq+kUXz8UAI3UldqONwZ/PQKpM=,tag:HRQ43/MMRyxCCXm4h6DInQ==,type:str]
    AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: ENC[AES256_GCM,data:XHyA53op+NbG1X1H9O1w85yJIBXVYux4mw==,iv:yGcTAEnI6vN9N+P8A7myBz0Hp2eJMN/uSsif3pW9cBU=,tag:CbmmXJcL2BfteKxPs8Wymw==,type:str]
    AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: ENC[AES256_GCM,data:1+TCLsgiowU66K9jv5oajk3HAA/iqSaeqj4YaHsfzhUNRPs=,iv:++34vN8DPgrad54bmT+1AbS4RyvgkRUnXRRgj5H8PJg=,tag:t5uT/WrPZJU6iKq0JQ2dIQ==,type:str]
    AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: ENC[AES256_GCM,data:ejW3L+g=,iv:mDTajT5HpPugnOa9C9fdS0RVc4rDcvrh/GT/SA0KWZQ=,tag:WJ3gPsWlbaD+qOs8lA1mrg==,type:str]
    AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: ENC[AES256_GCM,data:XtvOQjP0QR1z2g0DQhU=,iv:S/cwlj7z8+8zZiP1iybFaGrxGs6xDPKMtfmyCgNuQ64=,tag:ur+tXzzzKucRqw0mCyajcA==,type:str]
    AUTHENTIK_STORAGE__MEDIA__S3__REGION: ENC[AES256_GCM,data:1BePK3qi/qKw,iv:wmOeFiFzUGU+GmHDjq1sQSEvlowPaKD2mMyZtPDiAqs=,tag:nNb2rlXl5Ng3A4ppS5VJyA==,type:str]
    AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: ENC[AES256_GCM,data:Ta4ufBOtmGuZ,iv:w06klxE7aBVEDR9ZWUEqlPQjyA+UIvosBPoyCrR1c68=,tag:aW0t+vaXN14CWotLBDZ90w==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:xYgyzTGllbeOasioS3aaRSgEbDQ=,iv:9/9jCxTbSV98kD+nuRS4bqSmdBti3vVZSU8B3q8qWcs=,tag:yjLqwMJUybj+ervAObTXOA==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:ibnG,iv:2un+Y5YA6LnCzAjCeV/LTvkTzKhGoAQ5mZ/JTy4XGCA=,tag:79tbqlDzRgn54x2DXenfOg==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:Zv+3xBCmJr6o1Mkb02vlv/ishw==,iv:dN9UunUhhoEv1Ibu/RKB634SU84jmd4b34Wshp8e01M=,tag:rpaPwlxA4clCOmCwhKZhaw==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:fgYYn0ipkQdVCA3dwl0=,iv:swJB+TUkm8Uh9MrZqu/h7x3CD6pYSQHaxsRPFng/qdw=,tag:vCwqV2R3P4MpLbYGI+2kHA==,type:str]
    AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:xYtaHg==,iv:gEzaqRbnFdUgqdb2ur3J8yaz4auN7cIb0FjWWgyk5K4=,tag:Om6/NyoAuykfU2gU7AirNg==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:/SZ1khyTsboApScRRs0a7Hbox1nFE3sNcgge9pe1eg==,iv:Ey9gDBnKjQeXEsW/NehcQhFqaXNgNA57lixTuI+Bfmo=,tag:u89M5mC7R/MYSm5Mz1Y8EQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:69vvwFwSbDMv,iv:v/3+dnAl8hxLq9Vifz9j2iR4U0uwK/wJMLzgE74W9G8=,tag:ezTZx+xQ+ceAw/QmwdNfVA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AgHkeJMUhDEjwNBbbG+LuDBcIeJlULM1bXilh9SKOphqpF+nmHSePQ==,iv:di+rLzaQJ4wzC+m84o9H9dJO043Izv69DpVNSrg3DXQ=,tag:OzPtURI0FA8lu8YMfyCBJA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WS0AeB+Y9Kmc,iv:/31td5Cf2LWpR5sZkOP4JU529QIl4oK2RDim0fkCRl0=,tag:LfeHqmLwvl6q4Tb/lXwXyg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T22:20:15Z"
    mac: ENC[AES256_GCM,data:5zAIiP7bsNduvfOcieSKuGEfBLGzmZdQMKYE7pps+s68VfE+MinoDvbCnhIwBua882QTk/kKETrYWrNq6lyrb9yoJ+WccfW9XVW6vt+ds8rDLVti2ML5exJgM0ifQgsmu/lUI3v2OuYJZ4k0tHBl3B2JKTx6mKZanrMX0yf09hY=,iv:wGgLOzQ6h1exXerYJq3at9bya4bKytQP8hW2QAmJPWc=,tag:XKKtpXftqt7UJPVDevJBVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
