apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: davidapps-spain
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/davidilie/portfolio-davidapps-es # {"$imagepolicy": "flux-system:portfolio-davidapps-es:name"}
      tag: version5-ab3a620e-1688380535 # {"$imagepolicy": "flux-system:portfolio-davidapps-es:tag"}
    service:
      main:
        ports:
          http:
            port: &port 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "davidapps.es"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
