apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:VX+wSKeUhSxCbiwnN4Pp2R0KPRZWLmcr7v3++3hFkNU5RUu/Ijd0NA==,iv:GbOEzLY3f9kk8DLxVfAmRsqtgQOt2BqCG3L1Sw7noUk=,tag:S9EGDAHEe4Wy/pWWN8eKXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQnR0d2gzTUYyUmQyOG8w
            bUZGT3FyNTJodDU2WU02SkVXUis5a0xkSEFZCk1xNVJ0aHpnUlFvQ3B6UlNzZ1c4
            WkZEN3lRZWJzU3NOaUsxRk4rUytOVXMKLS0tIHEyQUpBWmtybUJrRm0rQ3dqeEpl
            ZDMwT0dRcHdhQlVVOTdPUXR3NVJEckUKRim80wZZ6AIWUYtlqFzgR2QRbN2UzsKd
            fT5IoCtOpjvuoqhOOUkm0q+kxW0Ghr0JKtvBPqGasruvFxqnM8fIGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T20:16:58Z"
    mac: ENC[AES256_GCM,data:LzpRi81bqQJnHXFh5D7q7/e1sKS+wOI6/yAsXf2fv0XvIrOaXrk0B0eKMt5EC4qqR7aIwOhaStdUKn+Ocq0o57z2lJg0GzsGqkQ+zpaXdRs/5PydcqpmHGI89lim3tavIf+rahb0utFAJtKqJisl3G1SQZZ64ZUtwu+OZXKVG9c=,iv:jMKfAE+4/ok05eeiF4V6B7OF8DlN9QZF9AuKnSt60PE=,tag:SPvKfylK3UuW+F7r634yEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
