# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:eUEJG4FYfcZHuxicAg4M0lwWpy9FdiXbGCt0+zrfyJ8GqaFdj3ybpQ==,iv:EsJmFni1pUdrWwIdJBcv64aiscoudXfKHAJl61xQPn8=,tag:uW+0XzPQet25V2e5/IYoww==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMXVTS1NkVytVQ3BXU0lB
        YU9wQ21ubStnOGFIUGlzK1cyWDdxa3RQazI0Cm80SmlHMHVqRzZjd1k2ZGlvMldj
        eTI4VDVyc01jdHF3Y0I5Und6R1dJcm8KLS0tIEVwaTVuU2tPQlpSdnhvd2h5OXdT
        SklVT1MzNDZ6eGZZRVJTVEcvdGFLNEEKHM7A2b1YMzgrkwKfc1PcR/My3N+XesfD
        tG+nDdYRV1+RUeoMil2Gw2fN0wouFuNxKDyZXyAB3NhXA1FSM5Yh4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-30T13:13:30Z"
  mac: ENC[AES256_GCM,data:41kdkMX9ldgMMK04kfuZo51Ropy6ZVPkJpdcrgxiIfMznjxgzwS10IplbYtXkaOYrhBYzwSTphLwa3eNC28F2/GCFvFzVHLJqBU+e04R9LON1z8R4b25kRdjaYxwAADVJ0YBNi0D0sweZ+natzIg1fdRYCd1OxXn5odtrRR46aI=,iv:iHcivG8OGEteKXaeopihmqpQk2vSmskB+Qjz41Jgp60=,tag:y9DA2hLygi0kBrnBGnco5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
