# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:eUEJG4FYfcZHuxicAg4M0lwWpy9FdiXbGCt0+zrfyJ8GqaFdj3ybpQ==,iv:EsJmFni1pUdrWwIdJBcv64aiscoudXfKHAJl61xQPn8=,tag:uW+0XzPQet25V2e5/IYoww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNTJhSUdZRXU2MFpKUFFF
        OTBJRjg0cmgyS2lSd0doNkN1OG1peFZtRkc0ClBwZzBObWJ1MUZwMk1zVzJsM1Uv
        dk5JZStoZW9MK1dkVTZOdUZBOHMvZGcKLS0tIFpzdnJmV1NOVU9YRUd4aFY4WnVo
        aHZ6a2NCMWRFUHlhTFBpMzJkL1BPMU0KN2PUVTM2qHEMB8fyOMUCAeQyEnwBbF+r
        d2P0JsVCiDb/FjgFSu3hYMAEJoiWQZCs4/WRc870H/STU5daAPdyaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-30T13:13:30Z"
  mac: ENC[AES256_GCM,data:41kdkMX9ldgMMK04kfuZo51Ropy6ZVPkJpdcrgxiIfMznjxgzwS10IplbYtXkaOYrhBYzwSTphLwa3eNC28F2/GCFvFzVHLJqBU+e04R9LON1z8R4b25kRdjaYxwAADVJ0YBNi0D0sweZ+natzIg1fdRYCd1OxXn5odtrRR46aI=,iv:iHcivG8OGEteKXaeopihmqpQk2vSmskB+Qjz41Jgp60=,tag:y9DA2hLygi0kBrnBGnco5A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
