apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZTLgT9qmridgV0PUaWhKEoNPpuJ/Q27MoRiSIpMxLf2Z5QyxKg==,iv:5oVfLIAeungXPTrGdivoAJx24QxZjM/CIAoqFOS+uPI=,tag:QZIOwUvr0BVcrtWwIQNLug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeGV5VllDNElEV0Mzc2lr
            MmpYdVNaVVNsSDFsbWZqMEZxa3Y0OG1udUFNCnVWektMWDBqRXBSYTlJM0p0ZzdD
            NG4yNkVDSVhLZ1RaQWxGc0V3Zk5OZUUKLS0tIHZ1RFFudUtEc0RHNkQ5eERjY0FT
            T1dMZkxqbmFSNVBucS84VjhWTWV5anMKBTHY2hfPQPyHGobM33d+81kplFWY62JG
            PaFHLfimT1RS8Fv0m6VslhElhQz7GNZ5fXGMZt+6VlfrXZG/Y/8zsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T21:32:53Z"
    mac: ENC[AES256_GCM,data:yHprA1vgZb0GYwiRitQKCb5SpS1X1sRPVdr7w51YEDtReGIbgkP2yYSeweeqB/eO00r68GEf82UD2RxkSdLFCTr/vEH7TgnplyA0BA3EmS7nGSh+3WlJ9EUHBGdVITW4pd8AVEPar5uOhI6J1WZJ9enY9X0eZzF+1JsRXEkR/Tg=,iv:ZjfxjFts0VnHWjnUb+gjXrO5XRZsfp5DV9R3PsxL0Xc=,tag:01Wxuhx7WUsN8moi27jI3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
