apiVersion: v1
kind: Secret
metadata:
  name: zerocut-canary-credentials
  namespace: databases
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:a9Ia9y/BGHe5B9H4lvE=,iv:NLJGHAi9p7Q6nOPV+Q6b5jnjjtAKMxYdZwPJluiBmgs=,tag:NTMj9EfRoNQFKUa6EE5dIg==,type:str]
  password: ENC[AES256_GCM,data:uAzLMxeIVkV9ew2D2S5vT7jxup/b/Re6jFnd5xHjvWu34bE+R45sUvB7/N4s1hQN,iv:pWlIuN3Ea2HweCTp53QzmgL00ftUDXPWWrRHOFOFEbQ=,tag:HTHIpt6+9VfStmQWPXgHcw==,type:str]
  password_sha256_hex: ENC[AES256_GCM,data:mqYrt/bT6mOm6qjcnwn2l92imKuFPf7Wxscip25rAjVw2SMY7TkXA6a4uSBxqfxVf2IHZ8JG4fGtkIStP/0WXA==,iv:6vpiFrRXQtfwxLKUSpHIxut5FdjWjiR5TjFjGe38S04=,tag:tJaY49Fazn44m22Xd4SYaA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YVBnWHZYSDU1WjdHWGlw
        M0s3anhjeFA1bStLZ2lMNlNNL3ozZ0VMdVhvClZEdG92dHJ0ZjNFYUNtWjJJTU9n
        MThYMjV5WnZ3MGVZMXA1clA5TWJTc2MKLS0tIG1LK0t5VmtNY2hvaFoxTUhDQ1JV
        TTdRWEU4QTVmaCsvTFEwMjh3akFGNUUKkCmliEqZjhR+M5An+BZJPJB+OJdeVRK+
        D25aMmV7eJCqhbqZtFUWIE62mWDADG5NTnf2U6GeDV7mzjns+a2Z7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-25T08:44:46Z"
  mac: ENC[AES256_GCM,data:sZwPaMto2veICybH+D2AEXSPyy97tDlaHOTpgp0yvrL6bMf8S3LmQ8dU+J6Y1bRuv3YUGWQw5kGJjcKa9qhP3w8vuxCMnpeLMxXhJEe+xzuxtMtgfCSFoLn4aVMr/DAbJ6vzViM7Lq3QSOCyCY3QrwuNcvk9oR05tcvBiZDilQI=,iv:YLzSf3U4YProJrqCGY1WHqIIRmluWTzKuUyB8Slc7cE=,tag:XP5/8fymHLMtLZb/TKoJJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
