apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
    namespace: default
type: Opaque
stringData:
    SMTP_DOMAIN: ENC[AES256_GCM,data:H6XJW1pgVnJXYpL4XltJVKReLqSLOyvJlPs=,iv:mjC1TDBA2DCnXPvjdblnWoReyBRvDlx6NT5xphLOV2I=,tag:1Tz8M1eIfkZNZHxpBHhwPA==,type:str]
    SMTP_SERVER: ENC[AES256_GCM,data:s7S/19d+iGFIk7I3Os4=,iv:60VhIpTKEm2+eJDgGnw7jPwY8LUw/x0VAb8Ilqn+mmg=,tag:vBBTfpuXKAviFR6hCFW/Qg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:rnctSj7x0w2T/FOypy/ngbFtlg==,iv:dgrf7KAq8WYirP9tU5ZB+eb7ZB5NKYPv5pOyQV23NiA=,tag:IJtVI62wE7jC/yPOQYymJQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:H3HR9N4O/VE6GLUezKY=,iv:5aXfQG9s0Fw8IIeW22VoG/vUDwg8vn8DC20iSyzX7yE=,tag:rXmz9GnJNgWJop+4zsKq+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweE9pOE8yemFNYjFFcmtr
            QktqRzU4YlE2NHo1eDNxRisvV2lJeTAxbTNFCnBtNFlQR3pramo4YldOeUlFMGhq
            L0liRERSeVVEN3pqUlZwcmhxc3gvbGcKLS0tIFJ1Q0FJaWtjRlRDanhHR0VLWXR3
            SytWZDdySDI2eWNBdnlpMlNTLzJDT3cKydfkF6yrLyEHEZL7OTVyaaDrK7AifWze
            UlMIwf3VaOgaYdwCRh47AsNIoj2TFiPyutDXFyAnKoyX9GIb5M0MUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T13:41:34Z"
    mac: ENC[AES256_GCM,data:CssWvR+VzOE1Qyis994q6xSSkEvgk1H5Rpg83LYtt52ZcqzH0zcHeRyNfcY3A3L14MkPpSVTEU3dbRaDDDML6doLmfCd95fJuWVAbe3+0q1h8JL1Hi4beTZ1X1efW72QbBpAr8a7Olb2nXsd6zs3lusYk9JGEbm89f1AlwSX0eE=,iv:jGPnke52uxay8rgTbXoGYIe1lDPHcuerb4xAvKvkcd0=,tag:vgVkLaa8Q/w/EQVg3LZJ/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
