apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:DujQIIvkp8deEBnclKRQ6qdASQ==,iv:26fKn304crCxqF+b8smb4hies77kpYcbRcs4dMl0bEE=,tag:CXLAHg1xLptz8nUVP36GSw==,type:str]
    api-key: ENC[AES256_GCM,data:94K8E0kNoAayV6Hc+TwPUr2bFg5Gf11TRsy/yXFCYU8SmvKafA==,iv:+ABQ6ooOw8UwWd/kvd0kX2FYX4Ene9ATzwGPyK010z4=,tag:uNXJQUnQ/eH/7OmyoL/WWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUGVQeEtoemN6SVVlTWk4
            SGRReUFjaWhQYmtpSThsV29lM0RITmlyZFJnCnVuLytGa2VFV2NLc0hkdmlHQzRt
            djNnUW1BNk1CejZoQUlHSm5JZWNxTkEKLS0tIHVBVkNOWVh1OFpjZDhOSHZPdUI2
            Vzg2ZnVMQzBZQmVHWDFSYnkreE5YSHcKQoa/kQUpZJHODY8LcAa3AndnSWoE1w99
            fwe0imrqd6QW2FVa0O9BVxnZvXUb4k9K5JC+rZKAJG7SoU1ipVw3RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:13:29Z"
    mac: ENC[AES256_GCM,data:88FoI9oXJO10Tncg2gDEwQGe3gGkOWe1kaiTkqX1XZGW8ebBMsw5y11jltURheSIEGBZemRP13JMTv5q3NT5Ijach6I5NOMmDZnsUgb1Um18R1e86/vjJLkKyqbfObUccuvfPi+ttzIX2o8PK0JxQTqtDILZE4lfHZdFkWk5SeQ=,iv:WR79nM+E8IZiCry2mxdgtgdjtfMboYhO3XtLHSVOanU=,tag:mz6Fm4l+jKzWpkZHJIk+Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
