apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:2Ffy/95LlIfCa0VB7fk6y09y0w==,iv:2FcfSGkNsxV9lrTOuYGe3pAp2dhDe9xsBlFKgcETSpI=,tag:+XRGWaDmit2ljYNA+DmPkg==,type:str]
    api-key: ENC[AES256_GCM,data:n9Ai2Gpf/S3x9rPOo9L+YvTclb6RSNtC7HDUBUKeR6uUJwIhdg==,iv:pgl04n5c3RdLq884ZudeU8WWN0i+tSLAGOnF1zGOeVw=,tag:yW+G8PP80SU8YV1H8vuKNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT0U1eHltNEwycWlHclJK
            eEFJVE05bnYvbmFYbDZ4YmFpMk9YMWpFUHkwCkxSMkxJWFVpSmRWTEsrNjU2OHVF
            b0Vmbm9LVDBBMHNFUlFwY05xSlN0VzAKLS0tIDdPZDZCZmJiU2VVYTNHdzBGZ2VK
            bk1JMzBvM09udjlLL1IxUEZvalkyaXMKUZ3f7qJGwKHbcO87Z1BOFamxQdr25U8Y
            ZIw4iMU3TrgdHu2To3NxiXqgNMBlXMkYUaXCUiFBTH1rgVFftGWvKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T15:13:00Z"
    mac: ENC[AES256_GCM,data:kq7lhAMGeQ7EZulcl0ndL/lxESbUx/jOQbG10excJCJRnhfEWtZOJMxD0rv5sCVDS1oGsEaxerEXYoaunaVeS5QGz0x0D+ophVuuIcJ3nQg0Ew2aR+Oy7+DjxIeIyA5PNXX5BbPvISuMaMWKNbAqhD5pLp5KZyLjj8DhE2XSNqs=,iv:3VQZJy+mb+Ys3lBUoKYg5NqZm4gWN8cy3aD1nfiMf3o=,tag:HKAONy4RhdoBY48J7h00pQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
