apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:oILsDWhcTCmZ6gz/JYylIlDRnA==,iv:3nSMb7r8dMOOvkCry6nTx+I28yvop4SB5Cwr8Rkx3fI=,tag:MVyWM7L4FNYB/2LR+zzL9Q==,type:str]
    api-key: ENC[AES256_GCM,data:N2dMtvUypAmzQeg6Ii45B38HDOQHQlybe8SCmihfAcCxerBIfw==,iv:MzGXlvHiQBWDhuKGBcUYaQ3E9Emp/2pDIQTzDnXvxOY=,tag:gEfv2WftJ6EagV6mhnpauw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MENHQTRFL3h2TkllNFpu
            VDdnb2plQ1IzY0NlWS9OT0F5K1FIUFhwRTJrCnp1aWZENy9yNTV6RUZUVUhaNzBo
            c0tNdnhoMnFXSkxEQTMxU0tkMTNDTlkKLS0tIEdHRUdrWnRBdWtHOTN2dGFMNFRt
            Uk11dWl4b2JVeXdBb2dpZ3J4ZGZEM0kKMCJUEdK6h5GupUfTgjryIaIenlV70x4f
            ErSxT8v/aPEc6ZlxaLaeS7VsckNx0Pn1YLf7aGi0T0xQaxLDx0JLbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T23:22:16Z"
    mac: ENC[AES256_GCM,data:BIvxuU1p9m/7tSmEszH68r5eDIEj8K79vvcrndLi4fltxgVWPY02sLpke4YJmbnsUEHIG0T9Aqito/DFgE+yGHyU6AeJFt76QGQUjGJUXHkwu2Yyl0pavj9RedL+ovXMiSbhg3DnNwdN3i+DAG6fM5AMRmxs932WgGmdXu9+U5U=,iv:/phzIUHsS7zqtNINc6j1Z6cYpTJLHzjx2Jovs+p6/Io=,tag:82YdQd4I533ziwAuenOm3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
