---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./minio/ks.yaml
  - ./nas-download/ks.yaml
  - ./minimserver/ks.yaml
  - ./pterodactyl/ks.yaml
  - ./excalidraw/ks.yaml
  - ./kms/ks.yaml
  - ./plausible/ks.yaml
