apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:kP8a7mkIrsU2HlVUjyZF/QYfB+cK1beZlEBxzqKVmb0=,iv:jvHIvFP2QmUy5cWtv2l2LC4++kMPK5BncDbLKKlkyQs=,tag:bHJQTaANjkGrsSJN9j2Aew==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:8JfVr9/KaIOKURcxOdPHRtOEUUg34qrwRrxBX1s3XRhC2sVz+3Xx0C8=,iv:yyuDgjOC60i9czM6aKtuyDza3SwvWIXaKHu+iEsq4AM=,tag:3YrcWV4DRl/vwJ0l1pX7+Q==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:N4IXfQ==,iv:XS2E9CjgwsRQl2ChnvHw5ILe3B0Ze9c7HRMLr0+G72Q=,tag:Kjigbxf5Tg2WY0Akscc+tg==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:FW3+sBw5yKo=,iv:TnBfTD8kIyiirhW6h9Vh/1eq51xZWnT4r1LDkwN6VmQ=,tag:zQVx1S/th/KlpfZAmuPxdQ==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:DV0V4/i5h2Y=,iv:oBMwwJG+0cVB96FASAlEwjpjBI1LTLueBztKc67EIAA=,tag:gFDFK9uluwEKC+a7plFkKw==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:8DmVd6YHTgTSFwr1wQ==,iv:LZQxpOEFttheqtAzDW3H3s+BLYhUV8m1o7cwy23jjyI=,tag:hyZVvRVU/iCbfJojuR2fww==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9rtyX/37Tu1iD04wIQ==,iv:+zM344jTdQVk+SVsdhBKFBjxp3+tOjVuMseKMP/UrIc=,tag:+kPpHNeYWs0K51JT59g9wA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:JNhgDBWHvEy4yIUgjhtLul16GvobBWfFy2W9zoQOcGQ+7NC0ileaIgs=,iv:SeXL4c8SkJk7diX23pGwar7egCcHq/KeuUGXqLeptHk=,tag:XQDWdZ3rqLNBAw/B1OwsIA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:LRPYLWLF0R4=,iv:TistkFOT0BNUSt6V839LEdlmMDq6KhygXp+Yh0Qkb0Y=,tag:+RxzCeM4LKxR1KQ9JRAx/A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T13:14:16Z"
    mac: ENC[AES256_GCM,data:oV+XnAiRdOby9o+pnkTSJOyfYrpbiSqXtupADm6IgMJv168aeMOZtF0XHLXfhFWsEd3DUIysKO7qh+uNxPMHb9WU4OCs0n8fDMhrLhjSEfWqMKfnEwuf42WL8WgRQae4s1Oxsnrup+VUv8XGylwoaUFTp18d//wUyWVis/CQOkk=,iv:h/Bm9+i/JoNAQGTdssOIIZAapfsQBph7qBmOHfV2nMQ=,tag:tAKyOEN6K14suupsjQCG1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
