apiVersion: v1
kind: Secret
metadata:
  name: volsync-secret
type: Opaque
stringData:
  VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:HS7Mci79iGdqTEt7POsk,iv:sCOdPebWXt6RhgVp3NI9xa+Ei1MP1qq4SSmkiHIQMbE=,tag:NvGZgePgrlncdIAkaCLrLA==,type:str]
  VOLSYNC_S3_ACCESS_KEY: ENC[AES256_GCM,data:4surmw8=,iv:m3R6AsWKuGmi38jKL1+JIN8KmdrzH3d53TJkiSy4StU=,tag:NHanB1WkZcdFcOG+9rPlsQ==,type:str]
  VOLSYNC_S3_SECRET_KEY: ENC[AES256_GCM,data:bq0DXdCxTJSH6NSHdqE=,iv:QIK84XL3rY4gtOrK9K0k5RGQoFR1FpofhrRPnXANiFE=,tag:XDQDY13DMcvmioBLVSZqMw==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZFdJRlBRdi9UL055L3hp
        eDFvTWt0empqTzVrVkFRT1BlaUVCMk5xZmtvClp0T1lVMkNQdDZpWkJXbzFLamJH
        bkltWGtxcnBBSi9odnFycUFpK2c1aGcKLS0tIGlUYzBWZmhpR0hrQ2MwQkRuNGFT
        anIrbVdWL3ZMaDBIb3lLNWtyNDlFckUKvKC/OU/PlyySyvQ++dnrJPyFIE4tl/yB
        SzbhrqDAQDDQ1Whl5JFOSNygDhDVkwuosq5yxZaGtN5o2xw4dvgg/w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNanUyQzZRYWxlSmwrdHlO
        a0UyNFE5UUF6SEdGMExzendjVHVWa09jMDFZCm9IaW9CV0Vla1d5RFZZRDh6eDgv
        RVozV2JTRWNTWmVzK3R4RjNrUkFHdVkKLS0tIHZ0V1JnWmJHTTJOcGYzYnh5Zmdp
        U0pRL21oSTZyTUx1YjJXaURmL3lNQ0EKlropbw9rDyuoI8Sg/Y1lwrBg3bKMfj4q
        eRubJcHCAY5h2JtibSSSsme2e4x3yYNGavWoTMPDp8DP9XLpRRcP7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T10:50:28Z"
  mac: ENC[AES256_GCM,data:Nkh7zhRTzYly1S96fB9fth4DYnqan3NUTju5Sq6hegegHZq97mOqX24zPat4d5kG94WJFSMQWKj0FSm0pRpRFX8E2WlIWwGhKQNxKwjmGMjckS5OgpUrWCoeA95kJybFpsWA1T5KL8I2ST5sVTiKjpue60v1Z9SSHBrVh26A+jo=,iv:RWxwXNJ5tWpOAv1KFNc7Sbseja2JopSzqpH9EMvSeFU=,tag:7GCaFUE1NC9AXGLBopyMsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
