apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-clickhouse-users
  namespace: observability
data:
  users.xml: ENC[AES256_GCM,data:grY4MfyL8ynr1/7SaIt4FWhwOSuFOmCtb6B879Lyioqi34IXEO/BgjCsiwetvXeTql4u+KjXCK69qLeBJF4fqS4uamA2huDzNCavYp6PVO/eTqELkbRJYzyoqNHLKkwtRvWrM6D3pHyEwudm37iCf17N3YNI1nEz7P0YboyWeuMwjNlLE0NYkm6oOh84DQ8X7KKNMMg+TiI64uN8ZkGCZsWkxkj867c8jQxiSxsHVYZHnSA6Dq9Oc0a9bbdJki0SFPp+8rvIu5xQEyh7RkQGZO2xZW5/2lr326CqYNLBupaa7uT0UgPT9qh5zc6gT9CyxA7QblzrA5D2slainQSNlbofzrMiyQTK+lrvDPE3x6J4lGQwabcgFJ5S16ftjcxOGMQ0lYPKccNbps5iwGAOdbhWHYIDazOjQSjtod5d/Fw+iiOqphQ8bfwXH7aXCO6AcTXjHNadpO2c51nSpsE606eN68vK+iTdJMUWvjaqkbqoDl9JK5jefQXxC4eMwx/4MPG2MrbWz3EP+RdTYVoL9K5a6QRJssGQv6T6JEr4HW+rehC79WkuN58FgY97DZ1Hhon23lMrOU9tlXyE26jYlX2AuRgmbbLm2nL68QDn3XaQ664tfKMqDPJLWKmv+O0X9ggeyG7aANP3ylp0lEE=,iv:CqL0bjg4tpTNGy66UtBlwljXUqKDfY/derKsJeGN73M=,tag:iIWOx0+Ur5CRsjoVpV93Sg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbzV3MFdORFMxNFRkQm1x
        dDk5eUNYMXVjSEJLZDBuYmxrRHF0ZUVocXdnCmRwQjBIODVWNE5kaElQc0l4RHJa
        bkZQbkl6UFpvRTBEbjJPNjJBS3M2cmsKLS0tIEF6bVBkU0piNXdxUm81WGxjT09y
        cGZzVVljU2x6M09TekhWck1DNENlb3MKeIgu/MJHrpETBRVTfH+7RM76xVGvySzQ
        p+qPZoYfZqbWFfk1d+81HPOurF44G15AQjsH1ZZ6eezcj56wQVr2GQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-09T14:55:45Z"
  mac: ENC[AES256_GCM,data:43BBF+hs05GIUKFg22JFbUjPHrsIG2PyWJitTzP6oIRmTQTwbZcaQN+pSTjFOaBz226rdVMG7nHaAH+L8RoDV6PrijyYrEv97D8DOBs8NNQ7lyk79bZkkeRoCaZffAhIkQJlLjqmLoTC/sifSALhYuYYgGzGPtv92xd3iuk+shU=,iv:HJ04/R0NEYW5MC1ymqbBdLOXOLh1J/lSKcwLwPvYHRs=,tag:PPUWHCnlVYGgLDWlXEwU3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.13.3
