apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
  namespace: default
type: Opaque
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:/6oEHMd8HxCUKp19wZMxDK+Z0r50RF84UReHrIv0IAo=,iv:v+MMG2r46GSJ6DNmlhpoKdbNvOGXeAunrJSQsgZcjaA=,tag:+cv50Hk9uRUryf6eVf/JiA==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ySqO5ZZlwKfbf8ezwnse+RTab+6ZkIfy2mLfL0Ksbos=,iv:0itWXzSg9kg0kFPS/RCheVDFGnyYF2OFRbGbc6F38QQ=,tag:pO2bcaiFQut6vZ0EBaBXKQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdmZtUnB1NjM0d3cxV0dw
        Y1A0U3VxYWp3MDBoMm4za0dDWXlaVVcwU1ZrCmVhM0RQZ1JWL1MxTCtQYWF3bk96
        ZkVUQWpDZFlKMi9vMWI5ejE5MS9YWnMKLS0tIGNwNXNMQ1ljZVowazRiT1F4THZU
        K3JWa3l0V1Z2VmRvZHZ2OUdhZjFiekEKPMUGgQqXv0mNJyjBWxiAiA3Hc7y1Az9e
        U5PhZfpvKGvzg+N31lL5MXo59Yl5j7QmWM3vYQx/P02g/os6Wis8iw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRjVPVnUzWEhiMmxLdW5Q
        L1gzTEYzdFRhZm96TUUwUTF6UXZLN0ZsSGswCjQxdWwxbzcwWWhHUU14LzFOamFD
        NWZ3OUVhallTVmZRL1VpREdTMUFwcTQKLS0tIGFBYW9Gc0NGUDZRWFBSTUlpV0d2
        VytkeWpQOGFzSi9WSG0yYnJtQWZFbFEKV/Wp1L3PTaqk5Wmn7HZzfF2iTyV2vCu2
        VoJKfn1QEXNegsDUo8G5oXvX865muSipSQbp9NfBbqAkiAcGR+WU0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-04-25T09:04:45Z"
  mac: ENC[AES256_GCM,data:+ylS5sQymz+giDGXf1eO3AbO7+lLcxMP+PKHkvDmqNaXWtl301J/EphSq5H7EhcGdmcsXf5xjZe8bvkEhXSBIuhOHR9yNO+eHJQlGOgFVfpiNUpEmlH/CVUjBbX0tvAP4FNIWDwx8Q1v68UfLI+UzC5HM8TqmdS7gJJaRI6STz8=,iv:69yctzQrxoWqPwtI3E1ADEpTqMXBAkB3gDX+FU51ub4=,tag:Tl2OL0e/omvcGnC+omQQQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
