apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
  namespace: default
type: Opaque
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:/6oEHMd8HxCUKp19wZMxDK+Z0r50RF84UReHrIv0IAo=,iv:v+MMG2r46GSJ6DNmlhpoKdbNvOGXeAunrJSQsgZcjaA=,tag:+cv50Hk9uRUryf6eVf/JiA==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ySqO5ZZlwKfbf8ezwnse+RTab+6ZkIfy2mLfL0Ksbos=,iv:0itWXzSg9kg0kFPS/RCheVDFGnyYF2OFRbGbc6F38QQ=,tag:pO2bcaiFQut6vZ0EBaBXKQ==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObHpMQzl5Qmd6UjVKbkx0
        YXNSOUo1bEthSDdqTFIrbFFnY2hCWFlXUFRFCjg3cnpFWG1VVnpxVko4ZTcveUR6
        NiswQllYNHRrZml2YW05TGlQMGZTOGsKLS0tIFV4SUI4ejVON2JiRUZhSnRFaWM4
        dWJibE5ZS3Z6cmlEaGVYRDh0T1dQTG8KOOHpZGOm33Gque6666FG+0RiJ+4pgVU1
        NHouv4MZNk9iZ/t/aIU69QogJ87csAz+ZyBFKMJJBk2ONqamzhNAEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-04-25T09:04:45Z"
  mac: ENC[AES256_GCM,data:+ylS5sQymz+giDGXf1eO3AbO7+lLcxMP+PKHkvDmqNaXWtl301J/EphSq5H7EhcGdmcsXf5xjZe8bvkEhXSBIuhOHR9yNO+eHJQlGOgFVfpiNUpEmlH/CVUjBbX0tvAP4FNIWDwx8Q1v68UfLI+UzC5HM8TqmdS7gJJaRI6STz8=,iv:69yctzQrxoWqPwtI3E1ADEpTqMXBAkB3gDX+FU51ub4=,tag:Tl2OL0e/omvcGnC+omQQQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
