apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
    namespace: default
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:/6oEHMd8HxCUKp19wZMxDK+Z0r50RF84UReHrIv0IAo=,iv:v+MMG2r46GSJ6DNmlhpoKdbNvOGXeAunrJSQsgZcjaA=,tag:+cv50Hk9uRUryf6eVf/JiA==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ySqO5ZZlwKfbf8ezwnse+RTab+6ZkIfy2mLfL0Ksbos=,iv:0itWXzSg9kg0kFPS/RCheVDFGnyYF2OFRbGbc6F38QQ=,tag:pO2bcaiFQut6vZ0EBaBXKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-25T09:04:45Z"
    mac: ENC[AES256_GCM,data:+ylS5sQymz+giDGXf1eO3AbO7+lLcxMP+PKHkvDmqNaXWtl301J/EphSq5H7EhcGdmcsXf5xjZe8bvkEhXSBIuhOHR9yNO+eHJQlGOgFVfpiNUpEmlH/CVUjBbX0tvAP4FNIWDwx8Q1v68UfLI+UzC5HM8TqmdS7gJJaRI6STz8=,iv:69yctzQrxoWqPwtI3E1ADEpTqMXBAkB3gDX+FU51ub4=,tag:Tl2OL0e/omvcGnC+omQQQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
