---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./ollama/ks.yaml
  - ./open-webui/ks.yaml
components:
  - ../../flux/components/namespace
  - ../../flux/components/sops
