apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:UfwDdI8ol1ynOattuXB6hU/xc0jAOTbUYwh5mpvxnwQ=,iv:ynn6kn43f3xbGK7YZS9g0UOzWv9R6x2mpT4Av1D4oJg=,tag:m94bKenMkDzIu1HcYtYCPg==,type:str]
    RADARR__POSTGRES_HOST: ENC[AES256_GCM,data:7Jhb7MkTBR/QIOHrn4PsGBNZmdbQV++t1xO+FSRMSB+7PxdGld3EGw==,iv:8BkXGpmIrgW0ex36cgs8RE+bpeRd2mKn/8AOVJEtyac=,tag:xcewSlDZG4jrKZ5CI85lUA==,type:str]
    RADARR__POSTGRES_PORT: ENC[AES256_GCM,data:SS+u1Q==,iv:AW70ygTDERZzWl+VVvIhJ3hB9aVyvIgGnQWnoSOxHSs=,tag:EsAhk2Z1nVWSqbDWeeOwmw==,type:str]
    RADARR__POSTGRES_USER: ENC[AES256_GCM,data:oBniBEaN,iv:HhlGqY65hEFsU7laxIQRyO+A+qGjpPhdGLytb1+xP5s=,tag:oAMkD88BFtyXeo39158F3w==,type:str]
    RADARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:Vd5TE9kzeUY=,iv:VJmg59B1vFWOvKr88UqIWNw1/cfxcU5Vgaep6LGozas=,tag:J2aHR9FV6t83Gwg2MEKVOA==,type:str]
    RADARR__POSTGRES_MAINDB: ENC[AES256_GCM,data:R2QZww2qDaIjTZU=,iv:1uxEogLaR5JP0OIu4WDUYc605ZUCM304EuYk3wJw94I=,tag:rQR82vOTFFVme0ng9R4qJg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:mnePk98L1uxnx6s=,iv:xQXbfmKvSAmvGoYM68wtikN/FM7+UTUVMm4zwLiUApE=,tag:Thn+I5Wvx1KWTxBQzL7CGQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AgHkeJMUhDEjwNBbbG+LuDBcIeJlULM1bXilh9SKOphqpF+nmHSePQ==,iv:di+rLzaQJ4wzC+m84o9H9dJO043Izv69DpVNSrg3DXQ=,tag:OzPtURI0FA8lu8YMfyCBJA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:+Lu3/2pZ,iv:0J+jGGEj/pOkD/zJUQB7bEwyx7pLL/Oav3z7Gdj3zsA=,tag:hbctoa449t0nfIo6cIKyng==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T17:56:09Z"
    mac: ENC[AES256_GCM,data:g+oEykODZAQf8T2v+Cfx3a0PEfME9i/05+12srvse9vbJ84mAF6UpzmpyL3t18tdoJmS+YZMbSqyEf3do25u5s75PDrYaQMkIIWQ/DLHY85YBOSqSmvJAFjVU2BJDgTdH6s9ieFVq3jVofihLeh1rbk4xMlJBSJ3WGGwlCODe8M=,iv:dAqXMzi0c7H3oMKDHy8n3sP6L5fFUkDatT9uz/Z9yrU=,tag:MIVFCeJrKJpxbttfyxP/0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
