apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:sIx3N3zLULVg5UAmXYCtSfJM9fuZqeqqSHglupsjRRk=,iv:ihVmIO4YjCMK/vY0BGytrgxDc4y2udlNyMTTVN7tStw=,tag:dy2REJexstw+tCMXHupC8g==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:t+hNgokgWDge6wda/CxJ2pdZkXhLQkHf8sPN9ZjOlFPg0tUbZhX5rw==,iv:16/AkLWAUeoL1RbM4sexz8en9erXfO3wayc+YAPqItk=,tag:GEUQYHe298k6PW+9vo+vNQ==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:6Rx/Ow==,iv:qPRsshRP3gmLLbk+H+9A0EzFM4g/xuC2yjqQlb+atGM=,tag:8ETwjMZFUY7CZLq5eT5tsA==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:C8hAVz6F,iv:CtO3BuwSc48E1y6I6fUUbIErD4+idaN7fKgnir63ulA=,tag:tQ2VJ1zw12XMxmd8a870LQ==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:sgt9w0B7OgQ=,iv:N96TQE5rXyjbWjNIwzVV36BREtLPZ7bra1x1OGSBGeA=,tag:O83DFpJ6Fnnvz+zNDrij8A==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:pXod2gOnFOtjDQI=,iv:g4QlCvuusX6icczaCQdAWfBqDQDo7QTCrKEFngyTRrs=,tag:8+Plj0+CmozsZgtRgj4u9Q==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:mnePk98L1uxnx6s=,iv:xQXbfmKvSAmvGoYM68wtikN/FM7+UTUVMm4zwLiUApE=,tag:Thn+I5Wvx1KWTxBQzL7CGQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:FAy7YKDkrqHRXuGSbC+B4EUxtW5T8ECV77ifHuxyz1AnQhJL506aHA==,iv:NMMGzp3PIlKqdW7CYUSvC5AyuQea2vtg4dnFHQ0dEFk=,tag:dfSV4dZHRG6eV9z3aVrN/g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:+Lu3/2pZ,iv:0J+jGGEj/pOkD/zJUQB7bEwyx7pLL/Oav3z7Gdj3zsA=,tag:hbctoa449t0nfIo6cIKyng==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T14:53:15Z"
    mac: ENC[AES256_GCM,data:fvuYdvfM6GnfF0S+DLz6LVOF8f7GGsz/rGpK8dP/t2+IzcUKHdZqFX7GtWW7K2u2sSzFTyeKQMuyc3xuNLVK8tCAgSANWwOp5b0Ai1kZ/o9rLdJR+RIpscENqA2X6AMBt2IhwLuDt9w3Tq5U3SDHFGZDD8WSkBYI/XeALr7uC+8=,iv:975YyWcWShXtz8KwxUpVb3G4l54MhyK/SMUhfirLB8o=,tag:MidxHogGc1eiJaC5TuEEMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
