apiVersion: v1
kind: Secret
metadata:
  name: hermes-friend-broker-hashes
type: Opaque
stringData:
  friend.sha256: ENC[AES256_GCM,data:B9iQelGiKM306urvt9eYjok2EssLbL2gCWTHkdIg9O49ujSmBNkdAAm/M7oHHjOn23ulZH4tBeqow6jOdYFPoA==,iv:L/rLDR02NahE4nqBf8Z1s60SSsFj2DcnMEjysCVMl54=,tag:9Pmhl7vsAHqAnTXB94Hx+g==,type:str]
  delivery.sha256: ENC[AES256_GCM,data:9iogE1+5Vx7qmcAxidWyPmvblw3QBNUXhWxyhkU+sKC6N42ea6mfGBlfdn0TLXI7dpOMi4mBrIu/Io1+ITjErA==,iv:1HD7KtB7tLFMz0NXheACiaJU6HnsY9Ln9PMwiLZhS7w=,tag:BTmsyeQlb0iJBnHZUyndrw==,type:str]
  owner.sha256: ENC[AES256_GCM,data:4/h3sjrsoY2Sm5IgSynpDt4Kg41q+c/tNRMp5c0QVbAhAa8E3NEGiL8zfo9TaUqWMzr0R3TgF51Q58cevMuCJA==,iv:Fmx9inZVLiGmIN/QdKPxBydUqC5gT1HG8yNpvyJdIUw=,tag:3QSEfbUEe/4/FdXZVA7VnA==,type:str]
  runner.sha256: ENC[AES256_GCM,data:nTlLaG+vKMUUV8kKE9ykU2MaA+W5jwhN3sYBPbx74t4Rb5KVN/wrNQk4n01BDAsIKLJYeacpXHXbH+gMpBdhPQ==,iv:9XZr3E/5vmB0uBJSkVqJFPifwvYncmWRyOr6MPjjAEg=,tag:2jHXzCVCgwmc3/H7S4i9vg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva3ZyOVNUcVZ3ZUxTUkti
        RTk0WHkwMlFUZTh0NmhyYmgxT3cyTXFPTmp3Cm54L3JVbXgzSjViZGVFK2szVDNE
        RWFNS01QdzN1RXpoUHZNc1B5anp1ZWsKLS0tIFpBOWozMTJaTGpKaXRqT1VXdy9K
        QWVudTdYbmJhbHNyekdRRVdoOGxBc0EK+Kx8g+lawa67BNo7hbZqfCgCJHTMhWYd
        ZVZX2oVGGco+uQfb1tC59bFJWN8nTKbhgCG3ZocMa7cmmGtzdW76Sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-23T08:43:31Z"
  mac: ENC[AES256_GCM,data:v8Z2+KTbC0Zep+MRlumYrfuO4UiMvfmFdsqgt1FjtGyMLaAD5U8cghDfQSp8TemuZIRTVycsnfbrDSi3bJ5u6EIJkxA50tE8fzxnkMuVWR/1FtkxRSBYi8zHwfM1litZluiofVfw9QDa34RG+koZ0WYYPkXToz8Db37RUQ0r2v8=,iv:SHCyG0AiQJyDKt7p3NXla9hb0kBR6HTumuWZz5xbsco=,tag:KlISle1u5G2UHPXWSz2HaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
