apiVersion: v1
kind: Secret
metadata:
  name: plexo-secret
stringData:
  PLEX_URL: ENC[AES256_GCM,data:l4sHf19lKTPD5rzifqxem/VpUQa1Bj+5Fw==,iv:rFU6AXtp2tM/JAHD8zhjKI00DVlzjYfiHI6U9efL0x4=,tag:5INxPLesfy7Hey/LHi/baQ==,type:str]
  PLEX_TOKEN: ENC[AES256_GCM,data:NxkVZ8KZJ3mgK5+Vo6bUR4TkB6I=,iv:LbFreEujWNFP21PfwX/W7b713GKQESTo3Yx7q7Qc+3Y=,tag:uvgZ500xyPHk4Qd8y8RZSQ==,type:str]
  TAUTULLI_URL: ENC[AES256_GCM,data:dw3RGkI9rejQoVCmbOruoAFWh+5glWLyCcuqARI=,iv:owihxl6kKA3BUamcm9w0tMh7tIabVUXzbj5/WQpuL14=,tag:Bqzl98ZZAVe1ayDWlaOOoA==,type:str]
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:J68Dme/lCk1BBej+xyEvMb8JsTfblsDzSmOylKJbDZs=,iv:3kz1QNfrOB62E3ozK+5RYI6r8ZRN0rCk9H8Wnc/N1Ho=,tag:SXR8/JwaT39cVvPDBNAJPw==,type:str]
  REFRESH_SECRET: ENC[AES256_GCM,data:1ZPBc30=,iv:HlpjZNpfXy32QzKZXa/CMgI4E3vfO91lXToefHDyGjw=,tag:f7kJpgn50S8qsUvSDmxHUQ==,type:str]
  DISPLAY_NAME: ENC[AES256_GCM,data:EDKIaOU=,iv:SZztqmLiIXfxUMPEYMxYZvGfElr+fJdoKIib6sB1nRo=,tag:XhhzXWHEGkbbq6uAqFfMqg==,type:str]
  APP_URL: ENC[AES256_GCM,data:/XS4milXzap/AxQZjopTik3Cwvom/k3FU7s=,iv:alaQ0sqhY8XwbPncm+k0xTrKGK24DgXKlKAxZ9oi3CU=,tag:BjuijP3BAoq6mM3wTTIYmg==,type:str]
  SHOW_DEVICES: ENC[AES256_GCM,data:uK6R0A==,iv:6y2sVgl/N7RTZGqsLSFZpZqjVigzTDroMKC0cx8evLg=,tag:eU+TOmZxAWPg1JGkNj9dEQ==,type:str]
  SHOW_LOCATIONS: ENC[AES256_GCM,data:cBanhA==,iv:S1a9O85nNZObjzC3eYXxoK0c32FZV39aJHC2HvM1b80=,tag:aP4BAYvpRgd02W8+/qglYQ==,type:str]
  RECOMMEND_ENABLED: ENC[AES256_GCM,data:pW5gWw==,iv:qZ6POHNuDm8YYuvZj2xDsPFl3S2a+QsMjvowRmwiY8k=,tag:7E7B6JkN+vKRN95h5zw5yg==,type:str]
  TMDB_API_KEY: ENC[AES256_GCM,data:PGBNCgOPqxem2lqd4Cpvlp/EHad6hAjH1wldTvNyW9k=,iv:BNHtWZi6ep0Yx906uaUcR9AA9BfwNzMiJETyrVwALR0=,tag:05Tud9fq+D+vrLzK41ok9g==,type:str]
  TURNSTILE_SITE_KEY: ENC[AES256_GCM,data:5o7D/PTNyi3HoNertbVu69h1ZG2jG/wf,iv:XA/g21F4ZVoFjTUmt5A+oBD120mI7evdnXgT6XeGj2Q=,tag:jXaLoLPxxGf9J8oaMSCyNQ==,type:str]
  TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:pQsDUuxNQoVRmJ277vylcZS5vG2MEHQG0xH9nDL6wYT13Cs=,iv:/0SIuLKRBB+NrXtusMqu1hYiuKAcy0EHjianL2yjYa8=,tag:bLGhzHVw6aDNe8meBu5ILA==,type:str]
  RESEND_API_KEY: ENC[AES256_GCM,data:pGFK5KnQF5FyGdP4/Bscu65X/C517pWtmxH5Br6dhWSnYban,iv:2nCgHSZTzDprl9u7cc6xCHPFV0lj01bnRG7Br28W5X8=,tag:XTvuaUf5zR/a1Y6y/SrenA==,type:str]
  RESEND_FROM: ENC[AES256_GCM,data:u2wYu/nPirYDK7qvFldM9i1eRd/j4lZJg9MTcT892yg=,iv:NgpCe1MjLPUnm56E5s001G+es1O9kjcmz4724MA6Vik=,tag:YwXeAPK5N52Eltb9zTriXw==,type:str]
  RECOMMEND_EMAIL_TO: ENC[AES256_GCM,data:ZvfY5+VWyOtqVo4u/12hqyC92A==,iv:PB0pBjwOizJneZznRnUDGiuNFKTqzOKHsiSgWp2E8+0=,tag:WJIQlmrDrbzF08xz5bsFyA==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:RoRFerPb1dr3r20ifYvvz3+3y+Sf1TqN1GVYBMW+GWrmNKSCkW2YibdipEUG9WVnoNuaLg7tCBGXXIux76bLsx1T5vHZgwYLInmcgDu3Lkr1F9r9Xkj6q6ZH4uwu5Im0IPF5twG6LlAlWhPQ2cNasfePPw9kPDkTiw==,iv:9ZX5CLOHfTvDnB0k42bulm9KZ3YdfuB5V4jyXq2AylM=,tag:FWhlIOoczZzF0c0suGm/mA==,type:str]
  PLAUSIBLE_ENABLED: ENC[AES256_GCM,data:AI6Djg==,iv:z6ROYZH/dAnaq4yuJeXITppJimaK/6Mv07H0fUWATeA=,tag:Xt+LwQSB800cEpGkNIZjpw==,type:str]
  PLAUSIBLE_DOMAIN: ENC[AES256_GCM,data:hEO+PwjEKi1QXCha/nBifj7/,iv:dczfAKwwsGPczxFaquasB0J5zSEpy9XZ54UX1O0daIo=,tag:bgJHxPOuOeIWu6oDHTYlMQ==,type:str]
  PLAUSIBLE_SCRIPT_URL: ENC[AES256_GCM,data:ccpAaiQ+MwqsGDP6yHQs11lECaC77709cpFyWEahWJTp,iv:cwHzHDiucLNR2Txnf2JL184fdd3MOHppMq5YCKxQvdA=,tag:ALlhe1bQaiFaZUWS1TLFPw==,type:str]
  PLAUSIBLE_API_URL: ENC[AES256_GCM,data:m6nB7m3LWhR5pOwdCoUBdVSFn5MiDHC3N1eI9yidwzI=,iv:AhCBZCmXclMGZHhwukzJHZwQZoE5Qh0tssxzcdoXn9U=,tag:ne6xRViMLqrpDOfVtgRDQw==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMHQ5amhCSDZFRjNYVjht
        VXZYd3ZzOEhjRUgrdHp3Z3huYzZ6V1NRMjA4CngvTk5CMjMzR2NQVmVocUVyVFFk
        cmxDTWxWM0pBY2RXb2h4VXVDMHFwTTAKLS0tIGRSMXRGTVdLMlB1ZzNxRlBwWm40
        WWVFRGdwWHFFblBPMzBuMXlwSmIvUWsK7SwJrLrtAumrcJ0dlEReAcc0eizqQ7wY
        zgDgmUG+IOtB+XNRfx8qzsQVfPy4SPDlF6FeODrb3VMHGs75L+2TjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T17:41:19Z"
  mac: ENC[AES256_GCM,data:VoPE7t7HV2ysbibJrdf4CHoTVDlOt9TLEyXvfc3ZyJhPAPQDN8PbMStJMuE+lJzPtmT1elC7q/xtaB7aHZBMgBuWk64ST+7PIYixRZBqRRzkr+DSTYu42zMO0AXgwtmlH9ftkis19YdHgLxSt9CYyuCsUxEfepFtPZpVoNkilFs=,iv:RPq2QST9f6ssU9sYWHajIezNEZGiuel86jWPRQlwKAQ=,tag:zskPV3PjUn41IkpWhNIW7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
