apiVersion: v1
kind: Secret
metadata:
  name: plexo-secret
stringData:
  PLEX_URL: ENC[AES256_GCM,data:0daf2HIIv0u+TooiqkUuwl8VlBOAg13hiw==,iv:9Zf30dI3Zh2K3mOIBigsjC1TppKQSyYXPgWoF9Im4K4=,tag:nvKbEAsDFGT4/xCW5sWmVA==,type:str]
  PLEX_TOKEN: ENC[AES256_GCM,data:4yOUEBnkPWbqY9LVmcePNKPzSNY=,iv:FKqIdUqDn8KZe3S+dq7I3I78SYXf6rGdWH9PK49VuqU=,tag:Mk9NztTXsZaFdLVEtLcZVg==,type:str]
  TAUTULLI_URL: ENC[AES256_GCM,data:NSYBlYywxFMOvgQZgs1DrcQ4ZPDTXlExVf/uAW0=,iv:kZ1JLY72QXjhwCbBnsD6cYYrVFlwItT7zKh0nRFlP6A=,tag:OPnerg9bX6Mk1fItxq+GwA==,type:str]
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:68Ful3Xf5ukz2h9ec750zUbNQ8GGbz9GIFL8GHKKbD8=,iv:TXO2AMLqf6ZxbegSIeAvI2vWHJS2KfPxS4TdwJclHcw=,tag:f7b8iCzcGyV86BPqZoMsOQ==,type:str]
  REFRESH_SECRET: ENC[AES256_GCM,data:gnapa8I=,iv:pX0zylr1C6/QL+8Sh9PXa27L7S5GeI4OGXYgalu1V60=,tag:DhkbsojHqkmn/ProH1bUdg==,type:str]
  DISPLAY_NAME: ENC[AES256_GCM,data:Vt8UU4s=,iv:g4b3HIZ04k0/+2XhnjX5XlDIQGj5ufiEAGhFGGz0X1k=,tag:mQ7CV6mIL50RcHwhn+Ly2Q==,type:str]
  APP_URL: ENC[AES256_GCM,data:Tct9aXL54uQPlGlaDu6em1HKoGTbjKCl8pY=,iv:/GpAJ3MyGj/N27y91/zl2fW7aFu4WeGUGeyFtm+LXsg=,tag:YZ8wCx7cPzy7unjlWwGFnQ==,type:str]
  SHOW_DEVICES: ENC[AES256_GCM,data:eopYzg==,iv:VxV3C7JgdBDdK9LPHVjnu8cYKsEJ41IY5Di/0H09JgE=,tag:v8Jp1+0H01vRNBCI5MDhMw==,type:str]
  SHOW_LOCATIONS: ENC[AES256_GCM,data:gPg2IA==,iv:Yg8C2wrSium6U62Og/L3EXGQihCiG/5sTN3dJq5+tYM=,tag:1t9DImQuHK6ifzvQE0hb5g==,type:str]
  RECOMMEND_ENABLED: ENC[AES256_GCM,data:YDsLnw==,iv:dg7AIkJfA5PEW2sVEVZVMPqC1kC0laJZPQWVUaQTAC4=,tag:OQHLR0ass+sfM83crQMc1w==,type:str]
  TMDB_API_KEY: ENC[AES256_GCM,data:Pliav+JYGJb6MjSxjilnwwXVNAnXNq9t+6grm5LoMeo=,iv:yq7qh246Vq6i/WK/C95cH2NpQWCAI5ZceLPeKOsaElY=,tag:sK+XKzrjtD/HA92XTQCxsg==,type:str]
  TURNSTILE_SITE_KEY: ENC[AES256_GCM,data:Xe5YG9fE2IpaBJuhgUJllpD+sNI7ikIp,iv:qWUdOXVlCjlH03Rzmp6TT0j00gNoI2y1YHQSpI/RIlE=,tag:947BCz7tyNAsrTLhBR/Vwg==,type:str]
  TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:RXjyeC1BdGBh4o1sEFCgvy7JFQ3lT89ABuIVbuawTmKQbDo=,iv:1VmsGZVYDtyxDUURIXKomyRcX4/vk7/sFK8S0W3oUk4=,tag:Yaa38/btUrIEZIEwHlzClg==,type:str]
  RESEND_API_KEY: ENC[AES256_GCM,data:JNSLt8oJAGEBl5+vcgWvu8rsc9Cx0VP6srr/eTW9t/epVQoo,iv:v0NlU6R9ZqC26TdybMYsUl+tt6C9q4C9lZRYfNgy4hA=,tag:5PFUF8QSLIf2XAAqnM0yTg==,type:str]
  RESEND_FROM: ENC[AES256_GCM,data:ECdrfa3NLgovXW8DWPfzdDm+etYOnoM5dhKJ+vXUCC4=,iv:PhEIPsG9bB23O1nAcos7xR1d31vhwKEumFPQGdxUtWg=,tag:i4dS+9SsNECa/pZLdA2iCw==,type:str]
  RECOMMEND_EMAIL_TO: ENC[AES256_GCM,data:nHFZ9Ji++kcH5/2jEjaPUOq4Wg==,iv:7DlR0D//sa6Oy/EAZ8j1FfljgyHSDMR46Z1W65rF++s=,tag:/wXr7+O2qm2e786VhpiPng==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:XK+UQRJ7elWOILc1AN9m0TsmFL6mWQzmaSm9LwR+xn2RmUluD26LfHO218On7TTvTg52z32uhQRa08UHhk/JgvS8dckF1BImY6mnAig2Jlw57d3hrKLFwoTrYg5SPowdI/T//BBYNsdCL7J2NH3OD14KE1fLT1vAxg==,iv:iN6CRaOdvQTK62AEJvtaa0uGmgNU0P8lDxeFfGRJu2w=,tag:Bh7q6QUaCi2CAZoOBIiPqQ==,type:str]
  SHOW_MUSIC: ENC[AES256_GCM,data:o/25gQ==,iv:TWbzFwRGtpCdOW5cJgLio8IMd+JK4Rx4xtm1wfMtQRM=,tag:UglNyiGKr45nGgdwgNnNMA==,type:str]
  PLAUSIBLE_ENABLED: ENC[AES256_GCM,data:fZ1odw==,iv:njmd7Sdtb7Y6NUzWW/wQ693ffo3YSsuP7rh2diTVloU=,tag:PcbyFg4NGPYGsOjwv4CMXA==,type:str]
  PLAUSIBLE_DOMAIN: ENC[AES256_GCM,data:mIDnVVKufkguvIJus/wvYXDk,iv:/YY39iNo4TVQxMYBGxUVL/fiIpoA/sgV7ha3ayRZu/c=,tag:AM8QpkTsPuQIfvCrbtAaXw==,type:str]
  PLAUSIBLE_SCRIPT_URL: ENC[AES256_GCM,data:FQcAq3BPJuD987vS1aAzl7Fht9Bd/p99IzaDIPW4Lru6,iv:DrdjUuIxNAdqKQ/ZonHIv6KUvKDJtIWh/92EiVBgit4=,tag:B5/QMOVz0SxTgHXQe9GXig==,type:str]
  PLAUSIBLE_API_URL: ENC[AES256_GCM,data:7KiTpaRILMM42ofmRoWoakt943sf10EA/4c2elv5a+w=,iv:7zvZGJvQKs7Uhye3KVdphiO+YVbL+6c9uQv+aIhm8qs=,tag:wctYKLxESKB/LOdu1NpG+w==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbG9IUlhYNU1WQVo1bW9p
        NUVTbGltekdrd3ZqRjc5b1ZpSlZ2anVhckRZCjh2eUNMZmczVXVROUNUbEFOU1Q0
        SWV6MmRDVDBCdHVrTlVEK05WOHBTVU0KLS0tIExKRkN6eEhBR3cvR0dlNWE2K3li
        Vmlqb0RFMUtReXpIWkVVV0UvaENra28K5kNHhodbL1fMjSL96ixChiS4MKXoWHyg
        tL6tnQCJO571mcRlwJqGIguX8qUhBikLpdXzictbfSV+TBqysDBlsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T18:56:13Z"
  mac: ENC[AES256_GCM,data:RHCUj0BX7OTVacIV3FRcAl7BDFNYK8QRjhlOIjB5iO/ONQI1Ow0vJmUXwZ9WO1LJFoaTgc6uuaE6oGHT9ThEqzCowcp7WoQ2ZN0UrvCbSQCsE+iDShkhkoDHAnRFzNqgP0ODSYlYUldr2AB9TohkLCc2yfIxXH8zQClzWbPN9dk=,iv:t9CEWre0uvjTkVN4iF+c/90zpppWAII5OGKdH3Df+2Y=,tag:ywsnUjAKpfm0vqPtBVj4mQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
