apiVersion: v1
kind: Secret
metadata:
  name: frigate-spain-secret
type: Opaque
stringData:
  FRIGATE_MQTT_USERNAME: david-mqtt
  FRIGATE_MQTT_PASSWORD: David950
  TS_AUTHKEY: tskey-auth-khFhB6X92421CNTRL-pYEstXHSA8QKokYviLzR7QBuXxNJxvSF
