apiVersion: v1
kind: Secret
metadata:
    name: personal-dashboard-secret
    namespace: default
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:yNlTh6PALgiO7q08VYM=,iv:HWpQ2iDEV8LajjOu7YeY8E+kuE0r8gJIfO9jVOqRzs0=,tag:R1mM4evw4pkOiCVHTlX8Zw==,type:str]
    APP_TIMEZONE: ENC[AES256_GCM,data:qCpbvNmuoKCqpFT8K74bzg==,iv:ctBrWg3mQPCTdDM0kV0ZuJv/gCbungyyPm5GQNI+mkU=,tag:WDNv59osXkKsNRfgm2b7+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRVdqd3dINkVjWThTWWs2
            VVFsTnlJSnBoNzdTOGcyajRYa0RQNTcvWHowCmdyOWkrS3h3YjlYbWZ0Z0RVY0xi
            OGN6akQ3RVJSMjNUVXhZWmEydVVpRlUKLS0tIHlMclF3azM3eXFURU1VOWxlNWtL
            N0ZpdGdmbzNoZTYzRVp5K3FaUmsxcnMKq/W68Eh95iVl4KPTVagglqfyuUe3dx+z
            +dT1t2iSJ3LbbCJXX1U0JppLquyWM7T3F4VVbvmuMtKsiyhraDxVTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T00:00:35Z"
    mac: ENC[AES256_GCM,data:tDA4JEA4f6L3KKtT/6aLqt2HdyP1H+/NTwiazLpgbYpvx/PbBvRLMNOenDzFwzJMdJW3WIMvSD9FONgW2fmXd/mryLaY6yOX7+PmQ9v2WI6Ks9QQ06btYQdEklet4F1k5ee5ISaytovSDrebbeFUrxHrOQYwp6rO0EtTUezmAmE=,iv:sEkdQY0DBollop372PeGhiblrLW8b/UL3RpIzNCOslk=,tag:xXR8RvKh62zqScixeRJgiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
