apiVersion: v1
kind: Secret
metadata:
    name: wyze-secret
    namespace: default
type: Opaque
stringData:
    WYZE_EMAIL: ENC[AES256_GCM,data:X9Ze4iRGgs93KgB2jAjxbsUiew==,iv:MZkoDhRQwjlAzHhbhZ+IyMYDS+n7LNQWdJ/GzR3/PsU=,tag:bTEJcfJJSQvUvPD5z4FXVA==,type:str]
    WYZE_PASSWORD: ENC[AES256_GCM,data:CDN3qR6PrVFeHWCxQEQ=,iv:vA3BUGPOg2s9F+AKCjDP1r7u8FrBjkKXtRFb8JslhgI=,tag:lrlUQ6DSjI8e6HXknEOpOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T05:32:48Z"
    mac: ENC[AES256_GCM,data:oJK+0LzvvNESM0afoIFWoMw/vRScvf6PKB3jiwFI4cNOAaGUrnRuwOLUPJVKjVowNCX5RrEDgms3CwPkGFoY2mgNIVoi8+TjnSIyLVGL2RDaqCpkcOfusLvhP3WgmtnA0fdhbhYa00FvWch9WhrfZnSGnpthTEy2frO6fFEzNdc=,iv:0h+w+yqJ7jQjRDpyvaNnmbVogLuEpbC4fR070Pevt0Y=,tag:yAzoDB2fAozPFXWsOQPSQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
