---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: error-pages
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      error-pages:
        replicas: 2
        pod:
          imagePullSecrets:
            - name: docker-regcred
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/davidilie/error-pages
              tag: main-2653882a-1782049224 # {"$imagepolicy": "flux-system:error-pages:tag"}
            env:
              HOST: 0.0.0.0
              PORT: &port 3000
              NODE_ENV: production
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 3
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 192Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      app:
        controller: error-pages
        ports:
          http:
            port: *port
