---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-staging"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${davidapps.es/./-}-production"
  namespace: networking
spec:
  secretName: "${davidapps.es/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${davidapps.es}"
  dnsNames:
    - "${davidapps.es}"
    - "*.${davidapps.es}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${davidapps.es/./-}-staging"
  namespace: networking
spec:
  secretName: "${davidapps.es/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${davidapps.es}"
  dnsNames:
    - "${davidapps.es}"
    - "*.${davidapps.es}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${davidilie.com/./-}-production"
  namespace: networking
spec:
  secretName: "${davidilie.com/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${davidilie.com}"
  dnsNames:
    - "${davidilie.com}"
    - "*.${davidilie.com}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${davidilie.com/./-}-staging"
  namespace: networking
spec:
  secretName: "${davidilie.com/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${davidilie.com}"
  dnsNames:
    - "${davidilie.com}"
    - "*.${davidilie.com}"
