apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
type: Opaque
stringData:
  PLEX_TOKEN: ENC[AES256_GCM,data:5RkFMMDVUNdub9ziXpYPMwhsoqg=,iv:3ZX9ELIkbhnVhfmBVpbsWDsXRGCTY4E/GSThtl4OyNQ=,tag:DgTn77ZDy0rBsgrqbZHPAw==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZnFlZ3JudldCQzZpaTNy
        NGxGWnA3OXhRRVNmNVdmeDNWcDhvSjBNbHpNClc2cGs5Ky9SUG4vVkxxaVdxK1d2
        SjFDNm4zdS9RUFcySTNuMXJ1TXZqTmsKLS0tIGpTZlZXUkpDRE1VR3MwTHZ3MWF4
        MTZjR01tRXk1b2J1R1h3OG9kZzdibFkKcNaYdQfaN1jq/ZEJHv5DXBi+N/Z+zrIS
        bgXyo8309iRlYmsbcv4RD0uBy7nEhX10xrmSa4Ovor332o6UZG0XKw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYVc1VldDejQ2d0FJS3Bp
        WHdnYUMxSjlJdzVIWjlvTVM3UWh4MU1BTXpnClV2d21lZEM0d3p5T0p2dy9UbkVF
        aTJXRkNHaUluc3VQeVVwcElKSUlQc3cKLS0tIDBOVFVrcWNtV2JTcjhoa2I3ZWhi
        RjZOYXF4eDYyN1p6YmxrQVRJUlNMcmMKYwESG07AKHcs/MAbDGnA6fM49wAIXFbm
        H6fFKVVFALGrqqtRykqE0yPR+p+Zl3lVSd3ntdtR4eZ2awDMuvYMYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-17T21:23:09Z"
  mac: ENC[AES256_GCM,data:ORP8s3bSBKyUrjl0k844LBba3pz7uj4guar8ryVIwIDu7o/tA8bXglXHlLzJgqEj0Qk19v4g2dF3bnXJewF9eXrDb8tXX7RVZjMl57hvYTHEe7RdEwMzSJ2EoQ9p95dOX6MN85HU5S+K3Tx5TBimIvjBOeu036jz0TdW+f9kBB8=,iv:+8PrygZbHnWphBfUCl0g1CCrg8TpfWKmtN5sN6PjhHM=,tag:VeWUvR/O5z3DXeNLXuWTNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
