apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
type: Opaque
stringData:
  PLEX_TOKEN: ENC[AES256_GCM,data:5RkFMMDVUNdub9ziXpYPMwhsoqg=,iv:3ZX9ELIkbhnVhfmBVpbsWDsXRGCTY4E/GSThtl4OyNQ=,tag:DgTn77ZDy0rBsgrqbZHPAw==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbkVmdlljbHJqL3loVENN
        VzBjNWdKK3g3aE9xNFZ4V1gzdml2Z1VRUHhRCml1UmNhdDlpT0hqeURJYWlMR3ll
        QWxZeXRnbzBjaUtWVjliNDlZcWVwek0KLS0tIHU2U2Fod3RzZHdSSmV3ZU4veUR5
        dXYwc0xBM1cyOUNtTXZza0FlVmY4SU0Ko1pVKAIpu051Zd59aME0RkG2+kJ07ahp
        vNcz2iEtioAcgy88YzSP982FGulv1uOPvv45V7UlrZo4+nUDV21OJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-17T21:23:09Z"
  mac: ENC[AES256_GCM,data:ORP8s3bSBKyUrjl0k844LBba3pz7uj4guar8ryVIwIDu7o/tA8bXglXHlLzJgqEj0Qk19v4g2dF3bnXJewF9eXrDb8tXX7RVZjMl57hvYTHEe7RdEwMzSJ2EoQ9p95dOX6MN85HU5S+K3Tx5TBimIvjBOeu036jz0TdW+f9kBB8=,iv:+8PrygZbHnWphBfUCl0g1CCrg8TpfWKmtN5sN6PjhHM=,tag:VeWUvR/O5z3DXeNLXuWTNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
