apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:5RkFMMDVUNdub9ziXpYPMwhsoqg=,iv:3ZX9ELIkbhnVhfmBVpbsWDsXRGCTY4E/GSThtl4OyNQ=,tag:DgTn77ZDy0rBsgrqbZHPAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T21:23:09Z"
    mac: ENC[AES256_GCM,data:ORP8s3bSBKyUrjl0k844LBba3pz7uj4guar8ryVIwIDu7o/tA8bXglXHlLzJgqEj0Qk19v4g2dF3bnXJewF9eXrDb8tXX7RVZjMl57hvYTHEe7RdEwMzSJ2EoQ9p95dOX6MN85HU5S+K3Tx5TBimIvjBOeu036jz0TdW+f9kBB8=,iv:+8PrygZbHnWphBfUCl0g1CCrg8TpfWKmtN5sN6PjhHM=,tag:VeWUvR/O5z3DXeNLXuWTNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
