apiVersion: v1
kind: Secret
metadata:
  name: gurt-luna-secret
  namespace: ai
type: Opaque
stringData:
  AI_GATEWAY_API_KEY: ENC[AES256_GCM,data:1DTqAwxJk7bFgQiV5pESQwJpKJiVosLRY2ACoAkyvbgMVy9d2oEkglHb/ttuH2NWQ74SKXlyxzpBxr+o,iv:GoUKLDhwwtbp6hl52c8uOgZEl5ls7dAmF21VQEqg07U=,tag:yQTF4h/3oFVXfs2SdqE3ww==,type:str]
  GURT_ROUTER_TOKEN: ENC[AES256_GCM,data:/h0+LP28rZMxBzu7VjG0RghFpR203v7/mZ5hwzIBBus3FCQaWrtlaGU2Mtz+SBYxf5nXRNW2s9vdDRk+W+tONw==,iv:10d6wmmV7TVN2juBcciqKIiyL8UVE/ncOvO91DXqFOM=,tag:ha3pUIwO0oCQ1lWdRz3Nzg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnA3dHU2U1lsbUpUc1ZT
        bEh5Umw5c1orbXBJV1NzYVd5amcxODJqS0ZFCnRVbXpFNzBGVDhOZWgwMEF6RGU1
        WnB1NTA1Zmd1TTE1YU94YWhtSldjbW8KLS0tIFdaZTdDbUNGS3lSV3gzMGd1Um4v
        TW0ycyt4aTMxdzJPZE1iZE1iRUFRT2MK5usUP+5VpQJwpCPJh44Cymdq5+0QYVKI
        gBAlRenDekv+1G5Zkh053n9R8jXWDYPfUJXJvc1qBJx3hmtcbLoAiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-21T14:33:26Z"
  mac: ENC[AES256_GCM,data:marT+n4A2BCdpgOdfKBBVMy8i26d6jiZb3VbqTGF9QjmKeUHCrymAdAJZKTadfKjQAkR7AvE+cjpj6C7/7LLBaD4gT01hI8T4TFT8PavrQUQ44famRta2MAfa0Gp9ci5A+MgLPVPJoKfWu/51xX3p/00rtmbXquoFnaydwh/ark=,iv:59tXTQcj88vHgY0gsUjebiiYZe+uzMeEe+u7syoEvis=,tag:dZjexRhCp7RxHdwfJ2PpbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
