apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:XInrECjLE+EMLEYw4ch0sbYQDSIZW91dvM6cQHgB8wJceSHLtoM3AeW4gtnNDSuZXvsY1zExwXPHuES4,iv:pMPxrE8Y/O/Hkst0ukzkLq4YyCSm0iYRq+sYj5e9fDk=,tag:mg5SFozK0j9FyjB3zrn5lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVlkvWExTek9sb3FjR3Av
            MjlVS3J4Tm5IQ2pSRlBsVk5Wc2pvc3lJTVNNCjFYT1lhbU9WdThEbDc3YjdqdDNW
            Tmd4V2hWUTZXTDBZd21kcHJKazZ1bjAKLS0tIGNTNWtuU2FieVR6Nm1lV1dwWE1S
            RHpEQnBHSE5SOXZDKytDOUJkQjFKcFEKiyOYH+eIhsgvT+RwBK9+TweredjqcSdX
            Lvtt4GTA7GZlPyehznJ+Txdfju3Sz7eYEkSVvtvU3mVYQMsmroiKDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T18:47:59Z"
    mac: ENC[AES256_GCM,data:pWtQG/1OWYtPH67i7MlU4sLH6M1YPPtqZbH2wQGU3QrHM1bIWq4RJTs0I/7YV3qRa36eLYPoemoMlK5pE3bSiztdx4h8cv2UJBZizCSRr2XZKK2UjCLjl9r/rkuGw0pHJ87UfTE4aSRqDpqw9/I+LSWlfUrFrK7Hc9mVlKzrJw4=,iv:3ru4+nPTH8Y4+PuyxU/Zb5FEQa2ufJ/7qJ+7TarkC5g=,tag:hI4kvW3oseDgQEiAej9kIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
