apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:Xit42ML+1moMFxpGrffpdTPAPPhupNx7GyeBN/C/lpHRdWTM5ujCla7idLZTX4CWK1ZEouDpUzMAEcqb,iv:l6/jn9SWcAQtWk3FVcETXGlXVTJHyZgi0++HkEkjOfo=,tag:FbnheSHecVCzJgA2k2hN1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WUduSm90dU9rOTM0b3Bn
            ZjJoVDlyeEVOc2ltaVhrNmRUQjRoNzc0ZmdVCjFPbGphQkp5ZUliM2Mzc3lrY3ds
            bVVRb2FXRytwUUpQUHIydms2Q0dndmMKLS0tIFpVU2duNVJIMXQ3eWgyUUZVZVVq
            bFVUeEFCOUY1TFRCaWFkS1pXVjhNTFEKQaE9BYt1+isNVn8mo/XTiLFB9eSglxV8
            x1C8lW1XdLchrKNUs+XpAlV/KkjlydTO9jqYSpsbh00qH2KLu6tvMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:56:23Z"
    mac: ENC[AES256_GCM,data:Pfwbo54ywNoxlMnxL/HODfQUow1XrGNq5zXr+i4uCh/7axo14cClt47roW8H1DFDNeyw/VwwVLDnrtctiwiMLm+yoFTzVjMslVESBrIBGJhB3+xEjQXNiXGnvbs4XxbU2SXW1ohTe7VQfiydWE4gizGyq1h439NuFXPjYkiLVUQ=,iv:HVQGH9zWXvJPkuBrdDAB/l+qatSaskefv9CUIvqYZns=,tag:aUUTSxBRqI3JjIUnXraGCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
