apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:9tazU8cfmiNOJ1a/2PQ9J6KfWJdPAdg4GOhCpIeQ6ZEOBXFmpVJ7Mqys4gGNGtmDCPAJV6lO2cnuVTXy,iv:DaheICf3CQXRZ6CfWhDuw23ui8jT5XalwMtfOP4JW1A=,tag:SBHoIOnmk7TGYlzIrfsIew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WUduSm90dU9rOTM0b3Bn
            ZjJoVDlyeEVOc2ltaVhrNmRUQjRoNzc0ZmdVCjFPbGphQkp5ZUliM2Mzc3lrY3ds
            bVVRb2FXRytwUUpQUHIydms2Q0dndmMKLS0tIFpVU2duNVJIMXQ3eWgyUUZVZVVq
            bFVUeEFCOUY1TFRCaWFkS1pXVjhNTFEKQaE9BYt1+isNVn8mo/XTiLFB9eSglxV8
            x1C8lW1XdLchrKNUs+XpAlV/KkjlydTO9jqYSpsbh00qH2KLu6tvMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T22:57:28Z"
    mac: ENC[AES256_GCM,data:+1+O/jM2m5qcVsfhdY+0Ro747Mg9ciitDtLCOwYfJfNtiKevaEHSvJmqYRgS9eom4ND9Os1/Fk7ljBuVrUKKx6eJsa6MnvPzHCUJ3PS+kXrvZ9Wkajv9uXJKAdPRGgb2NmnT7AV5gzaLX7qI6wSubh0jzDFu8h4oswpvLobJcjg=,iv:kM5fObrMuPShvlhcOnzE8du/Op9b6U/U5TFueOwJ07A=,tag:YPS/O7Fp7c5VL6orrlPaQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
