---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-scrypted
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
