---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-stream-master
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
