---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stream-master
spec:
  interval: 60m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      streammaster:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.4
            envFrom: &envFrom
              - secretRef:
                  name: stream-master-secret
        containers:
          app:
            image:
              repository: ghcr.io/carlreid/streammaster
              tag: 0.13.0@sha256:84f4edf0d1afcec220caa6e71d573d412fefdc91ac6379d5eb5a00c91c5c4e8f
              pullPolicy: IfNotPresent
            envFrom: *envFrom
            env:
              TZ: Europe/Bucharest
              PUID: 568
              PGID: 568
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 80Mi
              limits:
                memory: 800Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
    service:
      app:
        controller: streammaster
        ports:
          http:
            port: 7095
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "m3u.davidhome.ro"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: config-stream-master
        advancedMounts:
          backend:
            main:
              - path: ~/.streammaster
      tmp:
        type: emptyDir
