apiVersion: v1
kind: Secret
metadata:
  name: stream-master-secret
type: Opaque
stringData:
  POSTGRES_HOST: ENC[AES256_GCM,data:bxfx9adgpzBKNW5Iit3kW8y/MxJsP4N9sYQGM3q65byLsNO6oKjQYLc=,iv:U94Oks48v0UhIDi3Co86VCLgQ/BjKHduvbFVA7s2V3c=,tag:gvtbLYkpYUlgveodD/0V0Q==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:+LXh345eBygwpxN3qA==,iv:MQvWmJxsm6QGnPP2DXeYMT0zUiIrIjPcO5P2VHFTilo=,tag:mNhXFQ4dzR/nYAB34Dp+4g==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:fZPSwygMuhc=,iv:sQNWiJd18tMpkE4lRUx4T2gaXzzLmDSUQN+JKDWXB7Q=,tag:krHZv4ZG6DGCqCAfag2QOw==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:steE5a8XKp+Ggv7RmlgBgG8j,iv:m3ptZgaJxiThwPp/kCtwMgLoNT530UdGpsXemhCOmec=,tag:1r4NIivMpxYOtwE/jOV61g==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:MABhdr6i51dbVgY6IkJJtKFn,iv:mtJ+HIBGdpi4Ifcqu5OSBBh6TC8UDwGMSmr+JtOCMXQ=,tag:de68L9qCPwa0qxBwb2keMw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:DXgPOLVgDELPkzhA0m7zuj/cats77hi6EvhmbHvt8dceioVWDin1ZT8=,iv:peFvAnSkOfCx5+TMJrS4h7pC/OUrgGoKvCPmKn3SrGc=,tag:udDsgw26rL4prFHCCFxgZw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:THw0yH5FxCmfbVwdBA==,iv:2aplCmeWiwnCy1muUGtueT1PdMSibbEWXtJ9AHDpe5Y=,tag:MCjh4wNQAuEhb+c1uq8f5Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQlM0ZmRWZ2FyeFZvZE1B
        YThheFVIMm5HbFJpbUU1OURuWE5SK1FRUUFvCnMwZ3JVeFo1ZHgycHRUZmhLYWpS
        V0xycHN1cGM5WlNTaXpBem9nM25yUHcKLS0tIG5GMHg1Z0wybEZMaVlpV2FiWXNT
        Q0E2Z3gxUFlVakJqMkVhZVJicGQ0VzgKdnWNZm4O7mhQ79LHFpnU4VwlK765/4ig
        6ha7+6vb7ajBFXp2T73gcsqhptlOdGfRGT6pRlabSwLN4xgXv6Gjag==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeHBZN3FKaVUzNUhxOWFt
        OTUrbnU3MmdvNFE0TVpXQ09KbDlvRkNGNG5NCm9NZit6OWlaVDlGeTg4UGpMZ0s1
        MEJpdk9BUytaOVhibWI4cTQ4K01lNmcKLS0tIFJzc0FFaUhRRGNaSWh3MVlrcXp1
        RGNhQk93cDJsVkdCTmRQQmt0Ry9OWjgKpW/PcK7DznOFrLEFZGhd0BTa/db2E99o
        5jBwePy9z5Oq30BJ6Ldt7AlQdvufDmWiiRPpHPrSbqy+yeK2e/o/kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T11:36:53Z"
  mac: ENC[AES256_GCM,data:zYbs0iCjRcON8jRyHPjgkRU2+R+pi3QPHSVkREyyY/k3iS/i92mjTB3gN2MgdWTppUBgTf33nARcjluV3N5g54A0XUeHeiT8ml2KrIr+3GdzeKu/SZSq2LAIzy8fKFJquRgmil4yo7zP6U6boLiyogBQXAt1966j+nqOIM1sXpg=,iv:sMDY/GfLGVkIeFkPpAqmz/d+xHJE7X6AMXEUl+EI12U=,tag:LAd6TGDeT5PklJdKIpmFSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
