"""Original poster blueprints derived from David's twelve visual references.

The references share a visual language, not a fictional universe.  Each entry
below owns its joke, structure, and composition.  The renderer never combines
unrelated rows with a reusable noun pack.
"""

from __future__ import annotations


POSTERS: list[dict[str, object]] = [
    {
        "id": "job-interview-lines",
        "topic": "job interview sabotage",
        "shape": "dialogue",
        "layout": "hostile_dialogue",
        "top": "THINGS TO SAY",
        "key": "DURING A JOB INTERVIEW",
        "items": [
            ("OPEN WITH", "I HAVE MY OWN CHAIR"),
            ("ASK", "WHO OWNS THE BUILDING"),
            ("CLARIFY", "WHICH DESK FACES WEST"),
            ("REQUEST", "PAYMENT BEFORE TRAINING"),
            ("LEAVE WITH", "THEIR WHITEBOARD"),
        ],
    },
    {
        "id": "first-date-lines",
        "topic": "first date sabotage",
        "shape": "dialogue",
        "layout": "hostile_dialogue",
        "top": "THINGS TO SAY",
        "key": "BEFORE THE STARTER ARRIVES",
        "items": [
            ("ASK", "IS THIS YOUR FINAL OUTFIT"),
            ("MENTION", "MY MOTHER HAS THE MENU"),
            ("CONFIRM", "YOU VALIDATE PARKING"),
            ("ORDER", "ONE FOR MY LANDLORD"),
            ("END WITH", "SAME TIME NEXT QUARTER"),
        ],
    },
    {
        "id": "lighthouse-rich",
        "topic": "lighthouse monopoly",
        "shape": "wealth_recipe",
        "layout": "left_editorial",
        "eyebrow": "COASTAL FINANCE",
        "top": "HOW TO GET RICH",
        "key": "WITH ONE LIGHTHOUSE",
        "items": [
            ("BUY", "THE ABANDONED LIGHT"),
            ("RENT", "THE BEAM BY THE MINUTE"),
            ("CHARGE", "SHIPS AFTER MIDNIGHT"),
            ("INVOICE", "THE MOON FOR REFLECTION"),
            ("RETIRE", "BEFORE THE FOG CLEARS"),
        ],
    },
    {
        "id": "mall-oligarch",
        "topic": "shopping mall empire",
        "shape": "wealth_recipe",
        "layout": "left_editorial",
        "eyebrow": "RETAIL SOVEREIGNTY",
        "top": "BECOME A LOCAL OLIGARCH",
        "key": "BEFORE THE MALL OPENS",
        "items": [
            ("LEASE", "EVERY COIN HORSE"),
            ("CONTROL", "THE FOOD COURT CLOCK"),
            ("HIRE", "THE ESCALATOR LAWYER"),
            ("ACQUIRE", "THE LAST BENCH"),
            ("DECLARE", "SUNDAY YOUR CURRENCY"),
        ],
    },
    {
        "id": "jobs-now-childhood",
        "topic": "career comparison",
        "shape": "comparison",
        "layout": "comparison_board",
        "top": "THE WORLD IS CHANGING",
        "key": "CAREERS HAVE LOST DISCIPLINE",
        "left_title": "JOBS PEOPLE WANT TODAY",
        "left_items": ["AI FOUNDER", "CREATOR COACH", "REMOTE VISIONARY", "PERSONAL BRAND"],
        "right_title": "JOBS I WANTED AT NINE",
        "right_items": ["DRAWBRIDGE OPERATOR", "HOTEL DETECTIVE", "MALL WEATHER MAN", "BACKUP MAYOR"],
    },
    {
        "id": "new-money-old-money",
        "topic": "wealth comparison",
        "shape": "comparison",
        "layout": "comparison_board",
        "top": "NEW MONEY VS OLD MONEY",
        "key": "THE RECEIPTS TELL THE STORY",
        "left_title": "NEW MONEY",
        "left_items": ["SHOWS THE WATCH", "CALLS IT A PORTFOLIO", "PARKS BY THE DOOR", "KNOWS THE PASSWORD"],
        "right_title": "OLD MONEY",
        "right_items": ["OWNS THE CLOCK", "HAS NO LAST NAME", "ARRIVES BY SERVICE LIFT", "THE DOOR APOLOGIZES"],
    },
    {
        "id": "close-circle",
        "topic": "trusted inner circle",
        "shape": "ranked",
        "layout": "closeup_ranked",
        "top": "PEOPLE I KEEP",
        "key": "UNREASONABLY CLOSE",
        "items": [
            ("1", "THE NIGHT PHARMACIST"),
            ("2", "MY BACKUP LANDLORD"),
            ("3", "THE MAN WHO OWNS TUESDAY"),
            ("4", "NOT MY ACCOUNTANT"),
            ("5", "THE AIRPORT PIANIST"),
        ],
    },
    {
        "id": "emergency-contacts",
        "topic": "emergency contacts",
        "shape": "ranked",
        "layout": "closeup_ranked",
        "top": "MY EMERGENCY CONTACTS",
        "key": "RANKED BY ARRIVAL TIME",
        "items": [
            ("1", "THE COURIER WITH NO VAN"),
            ("2", "A RETIRED BIRTHDAY CLOWN"),
            ("3", "MY DENTIST'S BROTHER"),
            ("4", "THE MUNICIPAL FALCONER"),
            ("5", "WHOEVER ANSWERS THE LIFT"),
        ],
    },
    {
        "id": "birds-grind-quote",
        "topic": "competitive birds",
        "shape": "quote",
        "layout": "single_quote",
        "top": "THE MORNING WAS WINNING",
        "key": "SO I CHANGED THE RULES",
        "quote": "I WOKE AT 5:00 TO BEAT THE SUN. THE PIGEONS WERE ALREADY IN A MEETING. I NOW SLEEP IN THE PARK AND CHAIR THE MEETING.",
    },
    {
        "id": "neighbor-grind-quote",
        "topic": "competitive neighbor",
        "shape": "quote",
        "layout": "single_quote",
        "top": "MY NEIGHBOR MOWED AT SIX",
        "key": "I TOOK THAT PERSONALLY",
        "quote": "BY 6:05 I OWNED THE GRASS. BY 6:10 I HAD LICENSED THE SMELL. HE NOW MOWS UNDER MY FRANCHISE.",
    },
    {
        "id": "parking-tycoon-routine",
        "topic": "parking garage tycoon",
        "shape": "timeline",
        "layout": "timetable",
        "top": "THE PARKING TYCOON",
        "key": "DAILY OPERATING SYSTEM",
        "items": [
            ("05:00", "COUNT THE TICKETS"),
            ("05:07", "FORGIVE ONE BARRIER"),
            ("06:30", "RAISE LEVEL FOUR"),
            ("09:15", "LUNCH WITH THE BOOT MAN"),
            ("12:00", "RENAME COMPACT SPACES"),
            ("15:45", "DENY THE SKY"),
            ("19:10", "BECOME VALIDATED"),
            ("23:59", "SLEEP IN BAY 31"),
        ],
    },
    {
        "id": "hotel-king-routine",
        "topic": "hotel lobby king",
        "shape": "timeline",
        "layout": "timetable",
        "top": "THIS IS EXACTLY HOW",
        "key": "A LOBBY KING OPERATES",
        "items": [
            ("04:40", "INSPECT THE CARPET"),
            ("05:10", "OUTRANK THE CONCIERGE"),
            ("07:00", "BREAKFAST UNDER ALIAS"),
            ("10:20", "LEASE THE REVOLVING DOOR"),
            ("13:00", "MOVE ONE ARMCHAIR"),
            ("16:15", "DENY ROOM 8 EXISTS"),
            ("20:00", "APPLAUD THE CHANDELIER"),
            ("00:00", "CHECK OUT OF REALITY"),
        ],
    },
    {
        "id": "signs-you-are-poor",
        "topic": "fake poverty signs",
        "shape": "checklist",
        "layout": "giant_keyword",
        "top": "SIGNS YOU ARE",
        "key": "FINANCIALLY VISIBLE",
        "items": [
            ("YOUR UMBRELLA", "HAS YOUR NAME"),
            ("THE HOTEL", "ASKS WHEN YOU LEAVE"),
            ("YOU BUY", "YOUR OWN CALENDAR"),
            ("THE DRIVER", "KNOWS YOUR ADDRESS"),
            ("YOUR HORSE", "HAS A DAY JOB"),
        ],
    },
    {
        "id": "meeting-email-signs",
        "topic": "meeting dysfunction",
        "shape": "checklist",
        "layout": "giant_keyword",
        "top": "SIGNS THE MEETING",
        "key": "HAS BECOME A COUNTRY",
        "items": [
            ("IT HAS", "A BORDER"),
            ("FINANCE", "PRINTED PASSPORTS"),
            ("THE INTERN", "CLAIMS THE WINDOW"),
            ("LUNCH", "REQUIRES A VISA"),
            ("LEGAL", "RECOGNIZED THE FLAG"),
        ],
    },
    {
        "id": "daily-five",
        "topic": "absurd daily habits",
        "shape": "daily_list",
        "layout": "right_cutout",
        "top": "FIVE THINGS I DO",
        "key": "BEFORE BREAKFAST",
        "items": [
            ("1", "REPLY TO THE OCEAN"),
            ("2", "NEGOTIATE WITH THE TOASTER"),
            ("3", "CHECK IF BELGIUM CALLED"),
            ("4", "ROTATE THE FAMILY STATUE"),
            ("5", "OUTBID MY ALARM CLOCK"),
        ],
    },
    {
        "id": "pre-nap-five",
        "topic": "anti-logic pre-nap obligations",
        "shape": "daily_list",
        "layout": "right_cutout",
        "top": "FIVE (CINCO) THINGS",
        "key": "TO DO BEFORE NAP TIME",
        "items": [
            ("1", "PUT YOUR PHONE IN ANOTHER TIMEZONE"),
            ("2", "INFORM THE CEILING YOU ARE OFFLINE"),
            ("3", "DEMOTE THE ALARM TO DECORATION"),
            ("4", "REHEARSE THE DREAM UNDER NDA"),
            ("5", "GIVE THE PILLOW A SEVEN-YEAR PLAN"),
        ],
    },
    {
        "id": "board-meeting-castle",
        "topic": "castle acquisition meeting",
        "shape": "agenda",
        "layout": "protocol_card",
        "top": "THE PERFECT",
        "key": "CASTLE ACQUISITION MEETING",
        "items": [
            ("ROLL CALL", "ONE BARON MISSING"),
            ("FINANCE", "MOAT IS SUBSCRIPTION"),
            ("LEGAL", "DRAGON IS CONTRACTOR"),
            ("GROWTH", "ADD SECOND DRAWBRIDGE"),
            ("ACTION", "EMAIL THE PEASANTS"),
        ],
    },
    {
        "id": "family-group-chat",
        "topic": "family group chat",
        "shape": "agenda",
        "layout": "protocol_card",
        "top": "THE FAMILY GROUP CHAT",
        "key": "AFTER GRANDMA BUYS A HOTEL",
        "items": [
            ("GRANDMA", "LOBBY IS NOW BEDROOM"),
            ("DAD", "WHO SOLD HER THE LIFT"),
            ("MOM", "STOP USING ROOM SERVICE"),
            ("UNCLE", "I AM THE NIGHT MANAGER"),
            ("HOTEL", "LEFT THE GROUP"),
        ],
    },
    {
        "id": "retirement-portfolio",
        "topic": "retirement portfolio",
        "shape": "ledger",
        "layout": "split_ledger",
        "top": "MY RETIREMENT",
        "key": "PORTFOLIO",
        "items": [
            ("31%", "ABANDONED TOLL BOOTHS"),
            ("24%", "HOTEL BIBLE FUTURES"),
            ("18%", "INDOOR WEATHER RIGHTS"),
            ("16%", "MALL FOUNTAIN DEBT"),
            ("11%", "CASH IN A PIANO"),
        ],
    },
    {
        "id": "second-phone",
        "topic": "secret second phone",
        "shape": "ledger",
        "layout": "split_ledger",
        "top": "WHAT I KEEP ON",
        "key": "MY SECOND PHONE",
        "items": [
            ("ONE CONTACT", "THE ELEVATOR WITNESS"),
            ("ONE PHOTO", "AN UNBUILT MARINA"),
            ("ONE APP", "MUNICIPAL MOON PHASES"),
            ("ONE NOTE", "DO NOT TRUST FLOOR 6"),
            ("PASSCODE", "THE YEAR 1983 TWICE"),
        ],
    },
]


def poster(index: int) -> dict[str, object]:
    """Return one complete authored blueprint without cross-combination."""
    return POSTERS[index]
