"""A broad, structured premise bank for runtime poster authorship.

Each family has ten title/world pairs and ten tensions. Ten general comic
angles vary the escalation without changing the setting. A runtime author
chooses one aligned pair, one tension, and one angle, yielding 10,000 guided
starting points without combining arbitrary nouns.
"""

from __future__ import annotations


ANGLES = [
    "an overconfident novice treats the ordinary setting as a personal test",
    "one harmless misunderstanding becomes a five-step commitment",
    "a family member takes one mundane rule far too literally",
    "the narrator solves the immediate problem and creates a larger practical one",
    "a small social embarrassment becomes an elaborate private system",
    "the least qualified person behaves as if they rehearsed this exact emergency",
    "one useful shortcut escalates until it defeats its original purpose",
    "the narrator mistakes politeness for a binding personal obligation",
    "a familiar object becomes the only witness to an increasingly specific plan",
    "the final payoff reveals the narrator could have simply gone home",
]


FAMILIES: dict[str, dict[str, object]] = {
    "dialogue": {
        "layouts": ["hostile_dialogue"],
        "titles": [
            ("THINGS TO SAY", "DURING A JOB INTERVIEW"),
            ("THINGS TO SAY", "BEFORE THE STARTER ARRIVES"),
            ("PHRASES THAT WIN", "ANY LANDLORD INSPECTION"),
            ("HOW TO SPEAK", "AT A WEDDING YOU OPPOSE"),
            ("WHAT TO SAY", "WHEN CUSTOMS OPENS THE BAG"),
            ("LINES THAT CONTROL", "A PARENT-TEACHER MEETING"),
            ("WORDS TO USE", "IN THE HOTEL LIFT"),
            ("HOW TO ANSWER", "AN UNEXPECTED VIDEO CALL"),
            ("THINGS TO ANNOUNCE", "AT YOUR OWN SURPRISE PARTY"),
            ("WHAT TO WHISPER", "DURING THE FIRE DRILL"),
        ],
        "worlds": [
            "an interview where the applicant behaves like the buyer",
            "a first date treated as a quarterly procurement review",
            "a landlord inspection where the tenant claims diplomatic status",
            "a wedding speech that slowly becomes a hostile takeover",
            "an airport bag search involving absurd but internally consistent paperwork",
            "a parent meeting where the child appears to employ the adults",
            "a hotel lift conversation that implies ownership of the building",
            "a video call where the wrong participant controls the agenda",
            "a surprise party treated as an unauthorized shareholder meeting",
            "a fire drill where someone tries to invoice the building",
        ],
        "tensions": [
            "start merely rude and end with a claim of ownership",
            "start formal and end with the speaker taking an object",
            "start confused and end with the institution apologizing",
            "start with one reasonable question and remove all social restraint",
            "make every line technically answer the situation but worsen it",
            "let authority change hands one line at a time",
            "turn a personal event into a corporate transaction",
            "make the final line sound like a scheduled follow-up",
            "reveal that the speaker prepared for the wrong event",
            "end with an instruction nobody present can legally follow",
        ],
    },
    "wealth_recipe": {
        "layouts": ["left_editorial"],
        "titles": [
            ("HOW TO GET RICH", "WITH ONE LIGHTHOUSE"),
            ("BECOME A LOCAL OLIGARCH", "BEFORE THE MALL OPENS"),
            ("SEVEN STEPS TO OWN", "YOUR ENTIRE POSTCODE"),
            ("HOW I MADE MY FIRST", "INDOOR WEATHER MILLION"),
            ("HOW TO GET RICH", "RENTING THE SUNSET"),
            ("TURN ONE TOLL BOOTH", "INTO GENERATIONAL WEALTH"),
            ("HOW TO MONETIZE", "A REVOLVING DOOR"),
            ("BUILD AN EMPIRE", "FROM A HOTEL BIBLE"),
            ("HOW TO CORNER", "THE PUBLIC BENCH MARKET"),
            ("BECOME UNREASONABLY RICH", "SELLING QUIET HOURS"),
        ],
        "worlds": [
            "a bankrupt lighthouse converted into a beam-rental monopoly",
            "a dying shopping mall turned into a private city-state",
            "a postcode acquired through tiny local service monopolies",
            "indoor weather rights sold to offices by the minute",
            "a seaside kiosk selling reserved sunset viewing slots",
            "a lonely toll booth expanded into a financial institution",
            "a revolving door licensed as public transport",
            "hotel room objects repackaged as alternative assets",
            "every public bench in town controlled through maintenance contracts",
            "silence sold as a premium utility to noisy neighbors",
        ],
        "tensions": [
            "each step should follow economically, while the premise stays absurd",
            "move from purchase to monopoly to impossible customer",
            "turn a worthless object into a subscription and then a tax",
            "make the final retirement condition depend on weather",
            "use one competent business move followed by four escalating ones",
            "end with the original owner renting the asset back",
            "make local government accidentally validate the scheme",
            "turn an inconvenience into scarcity and scarcity into status",
            "make the protagonist rich but unable to leave the property",
            "end with a buyer that cannot logically receive an invoice",
        ],
    },
    "comparison": {
        "layouts": ["comparison_board"],
        "titles": [
            ("THE WORLD IS CHANGING", "CAREERS HAVE LOST DISCIPLINE"),
            ("NEW MONEY VS OLD MONEY", "THE RECEIPTS TELL THE STORY"),
            ("JOBS KIDS WANT NOW", "JOBS I PREPARED FOR"),
            ("PEOPLE ONLINE", "PEOPLE AT THE BUS STATION"),
            ("MODERN LEADERS", "TRADITIONAL CAR PARK LEADERS"),
            ("WHAT SUCCESS LOOKS LIKE", "WHAT MY UNCLE REPORTED"),
            ("STARTUP BENEFITS", "FAMILY BUSINESS BENEFITS"),
            ("CITY PROBLEMS", "VILLAGE SOLUTIONS"),
            ("THINGS MONEY BUYS", "THINGS THE HOTEL PROVIDES"),
            ("TODAY'S EXPERTS", "YESTERDAY'S EMERGENCY MEN"),
        ],
        "worlds": [
            "current fashionable careers compared with childhood municipal fantasies",
            "flashy spending compared with inherited control of boring systems",
            "internet status compared with status inside one bus station",
            "startup perks compared with obligations inside a chaotic family firm",
            "urban inconveniences solved with overconfident village logic",
            "paid luxury compared with accidental hotel amenities",
            "modern consultants compared with mysterious practical fixers",
            "online influence compared with control of physical queues",
            "formal qualifications compared with oddly specific lived experience",
            "personal branding compared with being recognized by local infrastructure",
        ],
        "tensions": [
            "the second list must beat the first through specificity, not wealth",
            "both lists should be absurd for different reasons",
            "let the comparison expose the narrator's strange priorities",
            "make one side polished and the other operationally powerful",
            "begin plausible and end with a role that should not exist",
            "use parallel syntax while avoiding equivalent meanings",
            "make the weaker side sound more desirable by the last row",
            "one item should be bluntly personal among institutional items",
            "keep every row short enough to scan as a true comparison",
            "end each side on incompatible definitions of success",
        ],
    },
    "quote": {
        "layouts": ["single_quote"],
        "titles": [
            ("THE MORNING WAS WINNING", "SO I CHANGED THE RULES"),
            ("MY NEIGHBOR STARTED EARLY", "I TOOK THAT PERSONALLY"),
            ("DISCIPLINE IS SIMPLE", "UNTIL THE LIFT OPENS"),
            ("I USED TO FEAR FAILURE", "NOW FAILURE BOOKS AHEAD"),
            ("THE OCEAN IGNORED ME", "SO I SENT AN INVOICE"),
            ("THE HOTEL SAID NO", "THE LOBBY SAID OTHERWISE"),
            ("MY ALARM CLOCK RESIGNED", "I ACCEPTED IMMEDIATELY"),
            ("THE QUEUE MOVED WITHOUT ME", "NEVER AGAIN"),
            ("I ASKED FOR A SIGN", "THE CAR PARK REPLIED"),
            ("THE SUN ROSE FIRST", "THAT CONTRACT HAS ENDED"),
        ],
        "worlds": [
            "a morning rivalry with birds that becomes organizational politics",
            "a neighbor rivalry that becomes ownership of a natural resource",
            "a productivity habit interrupted by one mundane machine",
            "failure personified as an organized professional",
            "a motivational speaker trying to bill a natural force",
            "a hotel refusal overturned by treating the building as separate authorities",
            "an alarm clock labor dispute",
            "a person obsessed with beating a public queue",
            "meaning extracted from a parking machine malfunction",
            "a legal rivalry with sunrise itself",
        ],
        "tensions": [
            "write four short sentences with one clean escalation",
            "make the final sentence reinterpret the first",
            "keep the voice dead serious and the facts impossible",
            "use one exact time to make the absurd claim feel documented",
            "move from self-improvement to bureaucratic conquest",
            "make an inanimate thing appear more professional than the narrator",
            "avoid lists and deliver one quotable paragraph",
            "make the narrator win in a way that is obviously a loss",
            "end on a concrete administrative action",
            "let the punchline be a job title or ownership claim",
        ],
    },
    "ranked": {
        "layouts": ["closeup_ranked"],
        "titles": [
            ("MY EMERGENCY CONTACTS", "RANKED BY ARRIVAL TIME"),
            ("PEOPLE I KEEP", "UNREASONABLY CLOSE"),
            ("MY LEGAL TEAM", "RANKED BY FOOTWEAR"),
            ("WHO I CALL", "WHEN THE HOTEL KNOWS"),
            ("MY FIVE ADVISORS", "ONLY TWO ARE AWARE"),
            ("PEOPLE WITH MY SPARE KEY", "A COMPLETE RANKING"),
            ("MY INNER CIRCLE", "BY DISTANCE FROM THE LIFT"),
            ("WHO CAN CONFIRM", "I WAS NEVER AT THE MARINA"),
            ("THE PEOPLE I TRUST", "WITH ONE SMALL SUITCASE"),
            ("MY SUCCESSION PLAN", "IN ORDER OF CONFUSION"),
        ],
        "worlds": [
            "unlikely emergency contacts with specific practical advantages",
            "a social circle built around access to buildings and transport",
            "an improvised legal team selected by visual criteria",
            "people who can resolve one unexplained hotel incident",
            "advisors who do not know they hold the role",
            "spare-key holders with escalating conflicts of interest",
            "status measured by physical distance from a lift",
            "an alibi network around a marina event",
            "people trusted with a suitcase whose contents remain mundane",
            "a succession plan where each heir misunderstands the asset",
        ],
        "tensions": [
            "rank by a strange but consistent operational criterion",
            "make rank three the most intimate and therefore alarming",
            "include one explicit exclusion that reveals family history",
            "make the final contact whoever discovers the emergency",
            "start with a professional and end with building staff",
            "let every entry imply a different unspoken incident",
            "keep the parenthetical note only on the strongest joke",
            "make the ranking order itself part of the punchline",
            "use roles rather than random objects",
            "finish with a person who cannot know they are listed",
        ],
    },
    "timeline": {
        "layouts": ["timetable"],
        "titles": [
            ("THE PARKING TYCOON", "DAILY OPERATING SYSTEM"),
            ("THIS IS EXACTLY HOW", "A LOBBY KING OPERATES"),
            ("THE MUNICIPAL FALCONER", "MORNING ROUTINE"),
            ("A DAY IN THE LIFE", "OF A BACKUP MAYOR"),
            ("THE NIGHT PHARMACIST", "COMPLETE SCHEDULE"),
            ("HOW A TOLL BOOTH CEO", "SPENDS THE DAY"),
            ("THE REVOLVING DOOR", "MANAGEMENT ROUTINE"),
            ("MY PRODUCTIVE DAY", "INSIDE THE FOOD COURT"),
            ("THE AIRPORT PIANIST", "EXECUTIVE CALENDAR"),
            ("HOW TO OPERATE", "ONE VERY SMALL MARINA"),
        ],
        "worlds": [
            "a parking garage manager who believes he controls movement",
            "a hotel lobby regular who behaves like royalty",
            "a city falconer with excessive administrative duties",
            "a substitute politician whose office is never activated",
            "an overnight pharmacist managing unrelated neighborhood disputes",
            "a toll booth operator applying public-company rituals",
            "a building door treated as a managed business unit",
            "a food court customer running a parallel headquarters",
            "an airport musician who controls departures through tempo",
            "a tiny marina run like a global logistics company",
        ],
        "tensions": [
            "eight times, starting plausible and ending after midnight",
            "insert one two-minute interval that implies panic",
            "make lunch the most serious operational event",
            "include one action where the person briefly becomes an abstraction",
            "let the final bedtime action contradict the whole schedule",
            "use exact times to make each claim feel audited",
            "repeat no verb across the schedule",
            "include one ordinary task made sinister by context",
            "make the afternoon action change the meaning of the title",
            "end with the person sleeping inside the system they manage",
        ],
    },
    "checklist": {
        "layouts": ["giant_keyword"],
        "titles": [
            ("SIGNS YOU ARE", "FINANCIALLY VISIBLE"),
            ("SIGNS THE MEETING", "HAS BECOME A COUNTRY"),
            ("FIVE SIGNS YOUR HOTEL", "IS WATCHING YOU"),
            ("HOW TO KNOW", "THE MALL OWNS YOU"),
            ("SIGNS YOUR STARTUP", "IS ACTUALLY A FAMILY"),
            ("PROOF YOUR NEIGHBOR", "HAS GONE ENTERPRISE"),
            ("SIGNS THE AIRPORT", "REMEMBERS YOUR NAME"),
            ("HOW TO TELL", "THE LANDLORD HAS A BOARD"),
            ("SIGNS YOUR CALENDAR", "REPORTS TO SOMEONE ELSE"),
            ("SIGNS YOUR SUPERMARKET", "THINKS YOU WORK THERE"),
        ],
        "worlds": [
            "status judged through access to mundane conveniences",
            "a work meeting developing the institutions of a country",
            "a hotel displaying increasingly personal awareness",
            "a shopping mall controlling a person's routines",
            "a startup reproducing one family's unresolved dynamics",
            "a neighbor adding corporate process to domestic life",
            "an airport behaving like an old acquaintance",
            "a landlord forming executive governance",
            "a calendar acting like an employer",
            "a supermarket repeatedly assigning staff tasks to one ordinary shopper",
        ],
        "tensions": [
            "five symptoms with one concrete observation each",
            "start common and become institutionally impossible",
            "avoid explaining why any sign matters",
            "make the final sign a quiet personal betrayal",
            "one row should negate something strangely specific",
            "use no generic motivational language",
            "make ownership or reporting lines the final reveal",
            "keep every row visually short and syntactically different",
            "let the institution appear more alive with each row",
            "end with a physical object recognizing the narrator",
        ],
    },
    "daily_list": {
        "layouts": ["right_cutout"],
        "titles": [
            ("FIVE (CINCO) THINGS", "TO DO BEFORE NAP TIME"),
            ("HOW TO STAND OUT", "AT A FAMILY DINNER"),
            ("FIVE RULES FOR", "A SUCCESSFUL FIRE DRILL"),
            ("THINGS TO DO", "WHEN THE LIFT STOPS"),
            ("HOW TO COMMAND", "AN EMPTY HOTEL BAR"),
            ("FIVE WAYS TO WIN", "AT MUNICIPAL PARKING"),
            ("THINGS I PRACTICE", "BEFORE ENTERING A BANK"),
            ("HOW TO BECOME", "THE AIRPORT'S FAVORITE"),
            ("FIVE HABITS OF", "HIGHLY EFFECTIVE UNCLES"),
            ("WAYS TO IMPROVE", "A COMPLETELY NORMAL PICNIC"),
        ],
        "worlds": [
            "a pre-nap routine whose warped logistics all concern sleep, alarms, pillows, or going offline",
            "a family meal treated as a formal public performance",
            "a fire drill optimized for status rather than safety",
            "an elevator delay turned into a temporary government",
            "an empty hotel bar controlled through ceremony",
            "parking rules treated as a competitive sport",
            "pre-bank rituals based on looking operationally mysterious",
            "an airport traveler trying to gain institutional affection",
            "uncles framed as an elite professional category",
            "a picnic improved through needless administrative systems",
        ],
        "tensions": [
            "use a bilingual parenthetical after the count word, with total confidence and no explanation",
            "make item three change the setting's power structure",
            "include one instruction involving a piece of furniture",
            "end by leaving through an inappropriate exit",
            "make each verb distinct and immediately visual",
            "allow exactly one instruction where the narrator vanishes, evaporates, or otherwise exits reality",
            "turn politeness into an assertion of authority",
            "make the final step undo the first four",
            "keep the narrator completely sincere",
            "use one small transaction as the climax",
        ],
    },
    "agenda": {
        "layouts": ["protocol_card"],
        "titles": [
            ("THE PERFECT", "CASTLE ACQUISITION MEETING"),
            ("THE FAMILY GROUP CHAT", "AFTER GRANDMA BUYS A HOTEL"),
            ("EMERGENCY BOARD MEETING", "THE LIFT KNOWS TOO MUCH"),
            ("AGENDA FOR", "THE MOAT SUBSCRIPTION LAUNCH"),
            ("FAMILY COUNCIL", "THE AIRPORT PIANO INCIDENT"),
            ("THE QUARTERLY REVIEW", "OF ONE PUBLIC BENCH"),
            ("BOARD MINUTES", "FROM THE FOOD COURT"),
            ("THE PERFECT BRIEFING", "FOR A MISSING TOLL BOOTH"),
            ("EXECUTIVE SESSION", "THE WEATHER HAS COUNSEL"),
            ("CRISIS MEETING", "ROOM SIX HAS RESIGNED"),
        ],
        "worlds": [
            "a castle purchase managed with modern corporate language",
            "a family chat responding to an elder acquiring a hotel",
            "an executive team afraid of an elevator's knowledge",
            "a medieval moat turned into a recurring product",
            "a family investigating one event around an airport piano",
            "a board devoting full governance to one public bench",
            "corporate minutes recorded inside a food court",
            "a missing roadside structure treated as a national crisis",
            "weather represented by legal counsel in negotiations",
            "a hotel room behaving like a senior employee",
        ],
        "tensions": [
            "five agenda rows with named departments or people",
            "make finance take the strangest claim seriously",
            "use one absent participant as evidence",
            "end with a concrete action assigned to the wrong audience",
            "turn architecture into staff one row at a time",
            "include one budget or subscription decision",
            "let legal deny something visibly true",
            "make the family member with least authority sound most informed",
            "use a final row that closes the meeting but expands the crisis",
            "keep the copy dry enough to resemble real minutes",
        ],
    },
    "ledger": {
        "layouts": ["split_ledger"],
        "titles": [
            ("MY RETIREMENT", "PORTFOLIO"),
            ("WHAT I KEEP ON", "MY SECOND PHONE"),
            ("MY FIVE-YEAR", "HOTEL LOBBY PLAN"),
            ("HOW I ALLOCATE", "THE FAMILY EMERGENCY FUND"),
            ("WHAT MY SON GETS", "WHEN THE MALL CLOSES"),
            ("MY PERSONAL", "AIRPORT BALANCE SHEET"),
            ("THE COMPLETE", "LANDLORD SUCCESSION PLAN"),
            ("MY ALTERNATIVE", "PUBLIC INFRASTRUCTURE ASSETS"),
            ("WHAT I OWN", "WITHOUT LEGALLY OWNING"),
            ("THE FAMILY OFFICE", "ONE-PAGE STRATEGY"),
        ],
        "worlds": [
            "a retirement portfolio made of obscure physical rights",
            "a second phone containing one clue per row",
            "a long-term plan to control a hotel lobby",
            "family savings allocated to bizarre but related emergencies",
            "an inheritance tied to the closure of a shopping mall",
            "an airport interpreted as a personal balance sheet",
            "a landlord preparing successors for building-specific duties",
            "public infrastructure described as an alternative asset class",
            "practical control presented without legal ownership",
            "a family office strategy built around one local institution",
        ],
        "tensions": [
            "five allocations that sum to one complete worldview",
            "use percentages only when they add to exactly one hundred",
            "make every asset belong to the same physical system",
            "include one liability disguised as an investment",
            "let the final row reveal cash hidden somewhere mundane",
            "use labels that sound financially competent",
            "make control rights more valuable than objects",
            "keep every line independent but collectively narrative",
            "end with an asset that cannot be transferred",
            "avoid currencies unless the joke needs an exact amount",
        ],
    },
}


def title_count() -> int:
    return sum(len(family["titles"]) for family in FAMILIES.values())


def guided_capacity() -> int:
    return sum(
        len(family["titles"]) * len(family["tensions"]) * len(ANGLES)
        for family in FAMILIES.values()
    )


assert title_count() == 100
assert guided_capacity() == 10_000
