apiVersion: v1
kind: Secret
metadata:
    name: boarding-app-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Dn6uHEJWq92VG3kxG4fZl8TBeqiFOOfJ4EuDhR/iufjS8OfvkfpfxwFz4sWqCatqyMcltraWeZr8fIqexMAyTtYoyviV846W/IzyC7mbLw9R8aEImQ==,iv:8+1OnVUyhx2lTxsO7hJzi9nJLR5KrO4N5P6bsXM6x5I=,tag:GDqSIYqIeBTxYusgtb5Jqg==,type:str]
    APP_URL: ENC[AES256_GCM,data:x+QZILvzEl6EG0+zkLOalHIQRkFdanQfoM10/DNy,iv:Z+LLlJH1rGT3A85rSC9NV71mK1m8b+n6Iwt96Ix0ui0=,tag:ArdQGmNIg7jGOsggKLH/0Q==,type:str]
    MS_CLIENT_ID: ENC[AES256_GCM,data:m83mIT8NB79f+MhgrOzbQzOb3Yb+F6Km81nMRc7POqgDKE/m,iv:cwKh+GNQZ8gxEMfh/jaNIDoVYuNNWViTZ/w2Y/spvcM=,tag:Lf5Xr3eEMQeWO6cVMJPv1A==,type:str]
    MS_CLIENT_SECRET: ENC[AES256_GCM,data:D63QZoapzESwMZ2VDcpiyA7jF53NTvPU8dJUfh7hHHGGZ31OX1yk+g==,iv:fY905VAl8dmxHizThE+6JALnypNHOgDfxQHMEFk9Bq8=,tag:eqXPz6z9ZwHI+tgaeIX09A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:cONmVxUnLoTzCswi70knIgWEfkS3jhCSTkXGzNb04nJICi56KmRjGf7pdwGQgVUmn1N0TNTs60/jE+6A,iv:1EIBM+AV0V84N41bl2yI0errS1wIuC+MLmNoVX+T5fY=,tag:TOghT5JMIRiYvVrIMhJCyw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:wVWzq9LjnSLgflwSsH+svhr950fM0DdpuQcz/0ZfhjCMKfD36WCgMThpEZk=,iv:9GLnjO8NvwHjjAJag2XSeFXDxqREt84WtknOR9j+HjY=,tag:cZT3NEXqWNgcQJygTjV9HQ==,type:str]
    NEXT_PUBLIC_WS_URL: ENC[AES256_GCM,data:4P+8tqYbn85+EVW1MLZagB5QgZbZO+8WU+K/bN92,iv:Zr5rYe0KC64196ceegHZoOiU0M2dIYCSAwPM2qcV+SM=,tag:gyEQTfWXDrToUGlIOa9NXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1JIcWljSThtZ2JodFVJ
            aEpqZWdESDFURUdLckFWQ1IzUldyT0ZCd0JrCjh0MFRRQ1c5N3haRkZrQXYvU0VW
            TkpKQ04xTUVLN09ZUUx0T3pwVXp2U1kKLS0tIHl6RG5INEVpSzJvRnZUeldXd3R4
            Nk95dm5qdEY0d1lVc3dqRDJTNDlvQ1kKLixoeBTKgw8tdBEOgemi4P13l+WSaenK
            HX//jMdwuyBbOVgBvrQaN4u6NQjNANoG9WQC2pdJ5woT3aklNqaV2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-21T19:23:15Z"
    mac: ENC[AES256_GCM,data:5f4T/4PqmBn83gukS34Z2s3tU6HBer6LJ3MOIxrbNnx8r+XEHdUTIQGojV8Lzure7UU+Svkc30AoRGh1NrPuVs352iXxcHRxB4nmjskIBsXQfs0xK6O41WrgkvPccrTrWe3pmp3Wykr8nO/B3a+QlZNATgJW4eriwEeAwV5q+WU=,iv:8NghPRX81bHteNGnlLiENX7FojvoB8kbSmYC5pHv208=,tag:/LmqXTzJSW4iHjn2XtdXNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
