---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: telly
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      telly:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: tellytv/telly
              tag: dev-ffmpeg
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    service:
      app:
        controller: telly
        type: "LoadBalancer"
        annotations:
          io.cilium/lb-ipam-ips: 192.168.100.110
        ports:
          service:
            port: 6077
    persistence:
      config-file:
        type: configMap
        name: telly-configmap
        globalMounts:
          - path: /etc/telly/telly.config.toml
            subPath: telly.config.toml
            readOnly: true
