apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
type: Opaque
stringData:
  UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:CD36Cd5ck046r9U=,iv:GcdBsg0tz0MhaUcGTLhOnH9G3HnYDDienc73CySg80I=,tag:mailsilZ5sksZmY3GRCvzQ==,type:str]
  UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:Ni4BZh/JgsJSrr8Fzj3sd/sO1EHayy6G,iv:2L+O/womV7TTXigYZHkR0004z59IaJJSxWdzru+PhGQ=,tag:YdLL+GX7cdNHnwJbV2Ov0w==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaTBzNVZwQjRzRk01Rkcw
        dzdQUk84V2tSWWdOZmdnd3RsbSt0T2xxUWhFClNWd2Z1dGhkTWpNSVoyRXF4c1NN
        TXJXeExmR3dzSWt5Tk9jWFAzb05xNUEKLS0tIDBJRzFzOENpUVFOYXNhcUF3Ym0x
        MnhvZU9WQkd0NE5wVWl5bUNHOThHTUkKkhRpD+eHNYvlz4pADR5rtvM57VQrNeYc
        ArinQoqxbZU8YKBh/9VRU6YUYnnJ6sXqyF2sKgsEHgCHKdZ1LnMNeA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRkdwZ0JaUGlSMkZyY2k3
        ZHFxZkViNUdzT1pQOThzTlhSTzQ2MGp0TVg0CktKdFJkMmsyMWNyYlpGZ0c1N1FW
        VDFNcHB6RmlWanVjZDRyL3pRZzNRVmsKLS0tIE5pTTRCY2xRY2dLVnkrMFNmN1F0
        cm9HaUhBbldueUh3TGYrT3FseFh6UTgKb53gl1knlsGSNpdKf7nj+esT1tmLsqvv
        wJV69waK+WRmbmK24AR5f5DdadZGfbk7j3H/RLrNHnyJkI83n059ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-31T14:46:49Z"
  mac: ENC[AES256_GCM,data:cmyF/VKC6epYjHBRBCDVWJIJJr6BVEGx9zqygDs5PXMnVJvRlb29OpbSlsXuGudPndvE2Z+U2teglZhRrMuoAfxrInVijjxko9rxgCtwuHWmy8G5OZndnW1Q5NjaUkPvbsxQ5l4ZMF8Y3ktmCDTbTmwLLawWFJ0d2jQZNEykiug=,iv:dlxy790Ah/I2movveZ3N2aQbbNp5s69t7ZsgWDzqUWk=,tag:aNL1lDV076KH1z71TZ9OEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
