apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: Opaque
stringData:
    UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:HK+8xwUzu4D5ZqQ5ELMAithVDthmAd+UKYYTlLv2XjA=,iv:pKNxpgVBsEz9jd8Sl1/y0zqgM6xWNyjhRdAUkM1aNvw=,tag:4kI+P9ojcvfHZMUPMW4OmQ==,type:str]
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:lOAQjqcSuu1i73M=,iv:5IE5zjmIhoiMIpO1noGh0Ro/sMf+jecQJWOzpmjXD6I=,tag:uV0s33FA0kRvyCZVnBCkvQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:2MAQKc4dR3K5v9wUT6/ME+t6FVn5qYR4,iv:qEhfRaUPqMIeM0tcI9FEmjWY7ggJamfxMNIUVCDbxkU=,tag:+l1I3FABPG2BN9TVocDfeA==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T13:32:19Z"
    mac: ENC[AES256_GCM,data:bjAyh72uxrXzB3G86SCmVDFtuKjSdtIGUiMCPIQv14/dPQB5Zc9t6zcpxq2LgmgPCad/PI9fkthKmM/8tDS/hZu4/Cf2sfg9o4bsV8AnvtHk9VmxnRDHSLJgjqpePacnRcuZ2XISSBa9sYq8GW+XNQ8dTCzyb8qzX1lwJrOa6G0=,iv:XkzpZG/SOIww2omaiZbw2Oz0bmvzVqwf5l7UfHiWNdw=,tag:lW71k2VKI420MS+Tr0Av5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
