apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: Opaque
stringData:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:CD36Cd5ck046r9U=,iv:GcdBsg0tz0MhaUcGTLhOnH9G3HnYDDienc73CySg80I=,tag:mailsilZ5sksZmY3GRCvzQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:Ni4BZh/JgsJSrr8Fzj3sd/sO1EHayy6G,iv:2L+O/womV7TTXigYZHkR0004z59IaJJSxWdzru+PhGQ=,tag:YdLL+GX7cdNHnwJbV2Ov0w==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T14:46:49Z"
    mac: ENC[AES256_GCM,data:cmyF/VKC6epYjHBRBCDVWJIJJr6BVEGx9zqygDs5PXMnVJvRlb29OpbSlsXuGudPndvE2Z+U2teglZhRrMuoAfxrInVijjxko9rxgCtwuHWmy8G5OZndnW1Q5NjaUkPvbsxQ5l4ZMF8Y3ktmCDTbTmwLLawWFJ0d2jQZNEykiug=,iv:dlxy790Ah/I2movveZ3N2aQbbNp5s69t7ZsgWDzqUWk=,tag:aNL1lDV076KH1z71TZ9OEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
