apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:QAXPjljAgfZNo2SMbLIjAar7vMigvFaf12q+CHQXUGQh09h2jxIJ53P6rnbzceJ/MJFcogH8UdmO3Wo=,iv:ToTGoIyEnG1fjMW/An2qHALKQTh3n+6R+cVKJwQAZos=,tag:VzhkizWhOmEJ+zx3e44z4A==,type:comment]
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:lOAQjqcSuu1i73M=,iv:5IE5zjmIhoiMIpO1noGh0Ro/sMf+jecQJWOzpmjXD6I=,tag:uV0s33FA0kRvyCZVnBCkvQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:2MAQKc4dR3K5v9wUT6/ME+t6FVn5qYR4,iv:qEhfRaUPqMIeM0tcI9FEmjWY7ggJamfxMNIUVCDbxkU=,tag:+l1I3FABPG2BN9TVocDfeA==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T14:21:06Z"
    mac: ENC[AES256_GCM,data:9J4brSk3PX6rutDBPEu7XvsI3N6wHmCRyCqvKJyr2+NhqSmiapT0veNg+KX4/PQnzWfLMpXT+3Ayk59X2PK0KpfGftqmwbYrEnm2U6h9yGQmGxytP+6xzyv6UcvbmNVaL6Ik5sxn8fDN2nPR9eXrpGFWYaxJFJo0SI6q70EAfvE=,iv:9VGs3g6JjKZEx8m2Pi5hXvBn7EDXEf5vCIWldTb66X8=,tag:6SOYwrtjSPmWmsJ7tO2XBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
