apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: Opaque
stringData:
    UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:T8PwzFuRxqzJGuYfQCz5OcRlchFBVzr58CHIhNbEAF8=,iv:y+Fyrw0Pv/15L5O97Te2KbHfKb3UXeAQ7c1/XusVHFM=,tag:yDXF9SnUZL6OpFdLx0yPBA==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T14:27:49Z"
    mac: ENC[AES256_GCM,data:k9uSnQ3lnQIU4Y7exo3AQHkiYFzMsbxhlmI3Kxh3fV8/gJ/ZHQCA8LrUfkKq0OD7fJ1suhey3mWckFQCYXU8W+d+pOV2iAZ1RQ8N8RnNl9v9BK0pzp5tLxzgJQjd6bYPAKEgjuWe5IkOyfsVzIpd+H+Ue26NMXcw/lZ5FNOK5Tw=,iv:QO9eb5zw3yLa/UfTPFzt0yteDPlo2uQPSVRd6GGjPFc=,tag:7xUTFQeOSBYy4m/2ordqBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
