apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: Opaque
stringData:
    UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:HK+8xwUzu4D5ZqQ5ELMAithVDthmAd+UKYYTlLv2XjA=,iv:pKNxpgVBsEz9jd8Sl1/y0zqgM6xWNyjhRdAUkM1aNvw=,tag:4kI+P9ojcvfHZMUPMW4OmQ==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T12:32:11Z"
    mac: ENC[AES256_GCM,data:ASHLLxt1R6UeaSHzT3vsKlfiQzWPbgxVd9kwAglXme2YB8MeFKC/vnAzWgYRl0zANVcXD9jsDZHC4SFC79FjIy9cA0ISpvrJdIlbxCr+NPWuFgRI/RJwyybJfCbW2v/i1vrWUa0U/JcWIfwgBqaALqal5rzzTm5LcNrNJxvqfqc=,iv:ITL2le0ucemBU/EGhYpttoxIiTD5Ee7hv3qNhFOp7gE=,tag:NTVC6Y5iFsbro6BcjyZ5zA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
