apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
type: Opaque
stringData:
    UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:gZQnQYRq4rVHAOJ/ybxcZiZNSwCXPVnLC/sFnUPwwsU=,iv:2FWi+KLcQ9TpUuRdp0oYNoOzTLhqRb9fxOmHweqV/O8=,tag:AXQ4t6O4zNS6fye75PwqGQ==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T14:29:47Z"
    mac: ENC[AES256_GCM,data:9AKZpyqxNn1hcuUAk+lBDUrNeg0FQeL9uINa0PptcYoPQ5uQCfa8BKBmcEGWpzMP4OwTlj475xjkK9AjwTiMyEOma6qYy5Wuiuc4vrwEj05I3TJFaWGpvIwiND/K45NSCob0ukCCogmBPZG0VRGg/8KFR5bTf3Mu6iY6r07fkvM=,iv:JwRJbvIsBiavt526lSsm2tCTqhC3ugU7+8T/k4v3oAA=,tag:l+1zeNiSHLni908is43NWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
