apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worklog
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    imagePullSecrets:
      - name: docker-regcred
    image:
      repository: ghcr.io/davidilie/worklog # {"$imagepolicy": "flux-system:worklog:name"}
      tag: master-d59f555d-1706782400 # {"$imagepolicy": "flux-system:worklog:tag"}
    envFrom:
      - secretRef:
          name: worklog-secret
    service:
      main:
        ports:
          http:
            port: &port 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "worklog.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      secret.reloader.stakater.com/reload: worklog-secret
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        memory: 2Gi
