apiVersion: v1
kind: Secret
metadata:
    name: worklog-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:78W5QCqgD/4El61N69sU+b7bKbI9Ky3xZ+w1bk9CXKDhaLjq9ESRHK6nEsiMO+NYpfgO7ZCe1P51pRCCmLIrCkLJttMZJak5I2UMvz0Kd9nwL4Fi,iv:OLVHuW1le7Rzj7uQJTPp31Glvm7a6n6G7ecKjgCSCpg=,tag:9YBR5oOstL4X6livQKIGBw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:abwL1/NtTkigTJsswV5wlzrjLJOxC9jg6mbL79H5wnJP4hzb,iv:C01LQS3pcYNPneG/ic/ltOnqf5MRN31zdw8lcdXR9ic=,tag:qjr41vEk/LfRpCX6P4N8WA==,type:str]
    APP_URL: ENC[AES256_GCM,data:sn1gHR4ND/rwK/modEtDHyGucEjc3/3x03IcG00=,iv:VUpUTnXQzNfi13jlu8rVz0ZShsLLj2zZu4JjNdl6R1E=,tag:geMeJH3BqEsO0OSJb7jcSQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:xIwqM/k832/GThNqMGyzuzfVQc0ZwztHcwIya70IdOJJzbtJqzmQUD5JF/qT5z21vRwhpAbu1EqasdmK,iv:H7/UhvvGnL0+3ssIAo92+4BrJrTJ0kL4PYiL7ugWqbQ=,tag:1yeTiFi0fglHUcJzx0Q1ig==,type:str]
    SIGNUPS_DISABLED: ENC[AES256_GCM,data:D9XaGA==,iv:I55aVFtJrRPI5sAJw++qNQasGQP6RhCj+GoqxR1b7+4=,tag:hxmkBRfVAdYhKw+YOZcZcQ==,type:str]
    SENDGRID_API_KEY: ENC[AES256_GCM,data:jjdkuXXxdApKUXgd3+opsj/35m11Z9S09HK7wegHrVFh02FEMpJAuqor03a5WqFmbRwBmiQ+Y6sm6hGwp+IAc9gSqUCM,iv:P3slxBRCcXOlUPPfROboe7n9YWGRj/XYwFyFfL6NBEU=,tag:dDtyANf/JAZ9pdnq4BmMDw==,type:str]
    MS_CLIENT_ID: ENC[AES256_GCM,data:kkTAlTzZDL9cS+eWeeoZCvMqiscRqF0/hRJ3KAXefBabsuNR,iv:5/+zz1/Amr832bmCldGch0UfBRg7LuXkP4wy6461dBo=,tag:wioEvasdJm+sQzQG+fdzNg==,type:str]
    MS_CLIENT_SECRET: ENC[AES256_GCM,data:Pa060OKlTN2+cPh0vhhOqLIEjYA6HLFLgZgLMXViQNJqBoHKNzK3,iv:VnOiExeni905vVJQkUvpyUv0QoqpGT6PKxsOoiwjUjQ=,tag:mgHkmkWs04Zr9keOxhT6+w==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:JXH0sDFRsaulvAQUJBBMYUoEgaUEtN3LsPZ5Ni0DWLulgJ0SCN3iskBHganWQEjduXFe8brKzdn6XDUkaRnaV+nyY8eJdbo=,iv:4cozKRA+O9TzOk/eI7hM4RMwZWmFHWojrWLTXLSb+Z4=,tag:+l/AlVM6ZB0DJ/HcR5ln1A==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:XJpHf/wtCoMLES1D/G+EY2w6ybMjNmqoZrCnkymWPrW5j2U=,iv://7MmJ/ZNJVhXLiT32BVqbkY3wEW9I8sHQs9O5syIQA=,tag:iI0GPPQEn5MEANOCRrYV3w==,type:str]
    OPENAI_KEY: ENC[AES256_GCM,data:s7z95wKpw0SEKJqkE6Z73O7bogD5zSf/IDdWBU7PTkRxBfH99yCYtMAIsAXOD2q4SIiB,iv:iPqh/DOryIx3UoT8NhsTAEsvMi3+kmPjXSXHf/nkf9o=,tag:wwL96HdQIKhgzHTEiz/qAQ==,type:str]
    S3_KEY_ID: ENC[AES256_GCM,data:PthyEwo=,iv:oTVEZB4R/is1Ivvi7ujgUMq8z7xPCLP7qfhEaHO25ww=,tag:Nb6vv1wv/vDi6kuE8XUFMA==,type:str]
    S3_PASSWORD: ENC[AES256_GCM,data:0KVzHz3zVd0yK2qmrKw=,iv:53uvfVNsoFDXOHUryhGkJ0YY+4BHADc3vQrp8swhN34=,tag:n7Y2r5B44LlrTScqP/wZqA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:l+oIvxfWTQ==,iv:a6vtJ5s27QAgZhYoCLaBUheSv7ts5HXXkYOkXEy1Gg8=,tag:xvBR3Jq1sXiv7i0mWCGbJw==,type:str]
    S3_URL: ENC[AES256_GCM,data:KFDxLVVmoNwNky63p5yH7tI=,iv:/iLC7KLm4/ozke+jpSDfSFVxywR4HrrdEjbzEotmOYw=,tag:LcP03MvOqgK+vdLCB1KzKA==,type:str]
    S3_PORT: ENC[AES256_GCM,data:mOQf,iv:VBEjI6/+ooflWdo1G8r3uBu8FfrL8uqtmyapd1OmkTQ=,tag:Y2wVKzU4/7fFVBt2nVHgfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1JIcWljSThtZ2JodFVJ
            aEpqZWdESDFURUdLckFWQ1IzUldyT0ZCd0JrCjh0MFRRQ1c5N3haRkZrQXYvU0VW
            TkpKQ04xTUVLN09ZUUx0T3pwVXp2U1kKLS0tIHl6RG5INEVpSzJvRnZUeldXd3R4
            Nk95dm5qdEY0d1lVc3dqRDJTNDlvQ1kKLixoeBTKgw8tdBEOgemi4P13l+WSaenK
            HX//jMdwuyBbOVgBvrQaN4u6NQjNANoG9WQC2pdJ5woT3aklNqaV2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T15:40:14Z"
    mac: ENC[AES256_GCM,data:8qpnamzWZNlJ8IiHVlUBMZyvbgKsqJURqLBmVoh5llpE6nG2qm6Id66aqqrIkZtRiVNkMwE4Sf6ptaY7uBfXDr1rz1bN4Su72lTGIFiCDzepfBUuqcmOjJIVDn1wgZbe+3NiIWmcoqWNB69o24LdZDtoOldmnFJNNUVeo8qQ5JM=,iv:mabpVx5dTsRJ0BZ8QCWVBba6idVo2WMm86HZaNwh6ik=,tag:/rIxKck/mdtnVX8p3nAW0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
