apiVersion: v1
kind: ConfigMap
metadata:
    name: idrac-exporter-config
data:
    idrac.yml: ENC[AES256_GCM,data:KEULkADowf+sKI3NKlb9W1v6TXhN3ikPWSwdTKvGRPJgT+l4oTSuwsguqzsOQ9q3CQwGuNknp7psZu4m+qHfwL5Rc+XzgA6iMoMKWb2HhwG/rFWZVIzvfcQ8SIwEyOBCZXex1fsvXNVUWSXDyJchR2Z4W0CYUbpojQ==,iv:cBgzH0mzqYnqes2i9NTdByGLUoUKaST9XkAA8WrjTVI=,tag:Rdu8h70L1O4nPttT7P9qCg==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOWQ3QkhCbkhQZFhVTVJC
            SmpCeWdNZHV3YlpudnFWUlorY3pTcDlUVUNnCmE5eXJwV241dUlOb3FiVW9DelRL
            b2pwYlArNDI5ZjJGOXlKSjV5aFZ2YlEKLS0tIFFReGlqRHNpNmY4RWh5RjFOeVRh
            aXFwTnlGWE9scHZPQnB4MXZQZzRqeFUKyC+Zp9syH35RdlDgwHls+aeCXRwzkmfq
            LeSHJAYpkOMOc03jFIioP6hkEyMYkqow2g4ZI/1iLriQ/oUSQW/67A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T13:16:23Z"
    mac: ENC[AES256_GCM,data:MTKycnFZjpwlLfydppjzqO28Lm5KnOAC+C3/NVyn+t/0DpznHS72DX/qCUKqCqeBqw7jnR3HCFJUyBdFHi8AhHLqirxuRhKtQT+8oQBJ4eQiZUEQ5YwaCvxj8DSgwk3uEB22jBIXgYPWiXw5iS2rEIjcDKb8lUKOCt68q+v1I1M=,iv:z5z84D7b5YOG4CIDaw9XCYYSTqAOackzeI/D6rBR+/Y=,tag:c2ibAzvDGWeIUqeo5VmusQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
