apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idrac-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      idrac-exporter:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mrlhansen/idrac_exporter
              tag: 1.6.2@sha256:d9d62464d82fa1e73b9ef117fd636d7e10a28e9dc4109f0bde2999dd975a03d7
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 750Mi
    persistence:
      config:
        enabled: true
        type: configMap
        name: idrac-exporter-config
        globalMounts:
          - path: /etc/prometheus/idrac.yml
            subPath: idrac.yml
    service:
      app:
        annotations:
          coredns.io/hostname: idrac-exporter
        controller: idrac-exporter
        ports:
          http:
            port: 9348
            nodePort: 30173
        type: NodePort
