---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: idrac-exporter-config
    files:
      - idrac.yml=./resources/idrac.yml
generatorOptions:
  disableNameSuffixHash: true
