apiVersion: v1
kind: Secret
metadata:
    name: idrac-exporter-secret
type: Opaque
stringData:
    CONFIG_DEFAULT_PASSWORD: ENC[AES256_GCM,data:FIg3/1fxYUs=,iv:4SwIWZo6mckxiiWcfvMXZfiV/k5HuIyhfP7ad43nwwU=,tag:jfb9qZ5DV0t0Tqbd263m7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T16:51:01Z"
    mac: ENC[AES256_GCM,data:bJOt0GF7AxwBwl+l6KjnZ8gGanexQkmDrbYGwt2MGroiILIP64tUQN6Vuzwb7QcZMQ7MB4UBmGG6TfJ4nbGomW8lgj9MVzQza8Z17W4H7JU9lNJRpxL8BJ2MmatF8nGnKSvACufB0h+UksaObc4zLysD97Q/gzpyi/GeXDNF1Ws=,iv:9NW6EA9WKUTiMxtz1L1Hx4O+UDuydgXyQv5POy0+f7A=,tag:Cn4JiefqVtTc0xTfe54+Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
