apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:X9431fWizuJiZxPBHw==,iv:xRasc/U4rfB4JAJ42F6E5OwJF/spVdm248xOc2nYpdQ=,tag:mhXPx5DVB0h7thcRFPj2VA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:BCQ5ImVraWTs/69KMI1trlxT0Q==,iv:BQYOXOZxQV6AClWOCVG3D3QR9DmEZBI9Zlnge2c9jpY=,tag:xAQvQXrSEpgFh78bHTYf4w==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:lPgA7Q4YLmlfw4cBHqs=,iv:vWnBwE0l9R6wRQmq/Y+ByrxVBAhYdv1xV5Nw1JMVK7c=,tag:XyiDG6erbgHtNIWH+dUU8Q==,type:str]
    PTERODACTYL_MARIADB_PASSWORD: ENC[AES256_GCM,data:oVBd7I7PmbVa6DRq6ow=,iv:6NE4YhB9dat5FZX7YzTHitYn5TiYfmLXxeb52hhB5/U=,tag:eiXDXm8xx6cXtdj9eZpR3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN3dCZnBZYjl1QmczZzJr
            MVJSclhvRjJNVHZZTWhDeGw2enFBMU1nY3hvCmVNRXkyblJxeHgzUVhqeUNLZWoz
            MEwzekx6TmpkbnBsSDU2SEtNYlRQdzgKLS0tIFZqeVdSbUU5ZkhiUTkvZm1zNVFR
            NWM4K1YxcmdyYThWN3hWOURFWE8vaXMKBML7AP7wjj3U6JmFYR7nN8w+Iz+Pzb22
            zrIIAYzWuUgbs8sdprovO9TcMyMd/zbw8hdRjnfNj3nt+2XQxTYqKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T01:18:02Z"
    mac: ENC[AES256_GCM,data:sLbCcIIYvbLrkrJAqWxB2ZlCBkJzweLSWipa2PR0UJf46G1c92wktwiL/sMesjEjza02DuSMKN3HenNZWHhu7ZlsY1znclO4a1c6IcvqnZALjSDMR8fI9tZS12G0lPiNG26hNxmySmH3tvQ9yMtlQwTRGCYEf9S+mEMt1NsebCM=,iv:PrwEDyEnNZfqy61JIdp7Dtnjf4tGU2Wkks2Q8RbMk4I=,tag:fy11BudqjqftGu+CBDu6Yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
