apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N90/GpCEfkfe6Avy6w==,iv:VJ7EgP0pjwg5Y6I5wsSxmnK5h49fqwNEgE0Ufr8EPYA=,tag:CrGT++1NlizGs5iBugsYEQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:T06/XMGFPmNepQy9m21/JG8+xg==,iv:bZ87goYU96UMhU1TiEZdBFLBuOSsuOgMiTPU2XEYsZ0=,tag:8f3IOaleqqRrWY3BSWqOsg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TvtIdG3nr9XCsMndPxB0igUo8IzCK1fN/rinMDRD8DeSnanN,iv:2+bf9/WtY4j6BbQpZ4+BrYjE9bHou+pwCVXK1fV9tKM=,tag:/kOyFCb6JnM4VLQ6fJ5raQ==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:IQ65RbY81Fqeaz/UkgY=,iv:/5OJB2LhlhiGqziUQ39IsQvvpdABrKZZVcE1Xm+RYzg=,tag:13OtnGMaQdmA47TJKJdfIQ==,type:str]
    PTERODACTYL_MARIADB_PASSWORD: ENC[AES256_GCM,data:iP6iskgBnh0vNH2x/KA=,iv:BwZ0jHtVfhgLh2osWKtfniHiiJH3aedHIy1kIlPalR4=,tag:Vdnh19UhcHuwseycuOi+Sg==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:TIDffiIHrB0HoU7X2g8=,iv:Ntp1lpoBG1fsj+8zu5E+vel99obIZah7SgRTKSYi6N0=,tag:dDK96A9FwRPfZ5UYCDgnyw==,type:str]
    PROXMOX_IP: ENC[AES256_GCM,data:rLLevgBGWir6Ik+tUZQ=,iv:7yrGt6UAjb3PCSIEjoi7MsTcANW8QG3R0CPSBwfws7o=,tag:7cyxjFOyrsB++okjqJhCnA==,type:str]
    PTERODACTYL_DAEMON_IP: ENC[AES256_GCM,data:vV7hCBBTERR+gd+gUVw=,iv:F8D3EkyETBAgAM1WaPmYyXsLVSyoiLBs7dFXx9XXS+k=,tag:y+Vo4pT4ECUTcUEZc8korg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:nPhllJKHp/suhp81Cb0FUQ==,iv:i7gdtBOL+m+OjpGmU8jgymbESFqgK86zy1H4Fk4RBIo=,tag:28cD1+TK96oRceJlZBBhyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcW5meVVxZkhDZC9UVjlK
            cGpoYUVsV1lxV3I0ejUveUxRVzV6cUxVTVZVCmtnR0RUVjlSSkc5NE5xMTB6Zmtj
            VmlNTU5rVEZPUzRxdFFnWkdnR0hFWjQKLS0tIFZMK2g4c1E1SUNRdVNLcVZOZmxp
            aWtUUUpBWWlncGJXOHc1L21HWFlyTEkKxnNWVtSpdZcEXW/++VdCvAqj8HRaQeYM
            0H5HFEUtODnMvLSFkdqZROi0XOaJG3ngehPJjmKS144M7uyNFCtS8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T19:14:32Z"
    mac: ENC[AES256_GCM,data:knLnal/wO5w0F0TZ3BxjBvSP2CkqmgM5gYXKKtieyFl9my1dN7YcwZ8fgI2WxTFsPonni1xijo8qLSzvwmYc0adM9hZnxlBfEpOmMOaheXR1ypnBCVgkr7rOlxIy04MhtGtovKJKMOjGzm79iZShrih++P4cvYu6/X7w35uWkq0=,iv:1EJe+tRAEyXkI6+yxTek/SkxFafRVf8Ug6xk3lUmCA4=,tag:fz6Wchmhbtx+aiYDAzIMrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
