apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Qh6iqPcxjJPh3Hrv4XShG/zYNCnBpTO05n8lg2rVBeQnM5ddcazA4LXSq+dT7Lq66IXJCKbf1V/gR1gJZ/ZwnqctC5DTBtc9+ZB6xR6CtyeS673uBqK94UjH1jZUKg==,iv:g0BVYMpPvrdyvWJwAZp7FwNDF4PVjwv9/TKHwxdf/Qs=,tag:vyJ3a/H2v7dNJ5+mAh6wAQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:lk/vZa4gmftF9IHkRw==,iv:mkIYA0wvotcFHNlAj5vR+JzuEwK7x1B/uzHkkzwyHJA=,tag:SipcMxm2dKdzwlzsPcqtDw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1P2uDiREpg2YakSXZfuzqWxrqw==,iv:LDQZnHuggaZIQPa75iCFFKpA/dsG/TCMiO9ET1GRR98=,tag:T7Ig044jwKr4MDfixk+zqw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:qUAnYbzjm+tYcmttpdm47gJ1qhqYYIRZS9nO7sZnppEasx8I,iv:uWOhE3PcF6t8GuR5UldyJatZ3iyDfv5pESlgOLCDEp4=,tag:jxD+XEfsEgKegiBN4I7wDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWWlUQ3M1dC9HOTcxRXFy
            MEZkb3BLYkxoM0psY1d6Vm1VQnIzNEEwOEZrCjl3WWRqM0FaTVFpdXdya1RvRlg2
            WmlwdnF5MFN0T3A1TlJ1L3ZQL1lQN3MKLS0tIDR1VVg2TmJyWHI5dGlQM3hHdFpW
            NzJUMlpmT0wvdENFRkNLRHJaVFhOL3MKVAhSzHndkeh3akV8LAnEmFzx55OpIUoi
            4rxkLGrLu1ap8HnTmoVLutdh9YQ+khbnlY22NAhbejg0eDo/WXc4TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T22:05:27Z"
    mac: ENC[AES256_GCM,data:CDolUEGS1WNjny7q6LUiZECDGAX9oC+MNrZ7i97ZOpG1nTjZ6TLlHcZt5m1ySQHJmwJk/R7ILQ1HRHLCSkpB9prNtuVczT94DctN4a9guclxwruTll+Ip3/DfZnxsToaVyjys/l8/9Q94nuUvVd1V9d6Ac/Plpuituo0HG+RAfo=,iv:rkyOtAvsjMHuxOkEx7skd/ouHFCjFO0rkM1ryF2Upz0=,tag:6NvspaCdaPF58rWkqr03IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
