---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subgen-models
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
