---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nas-download
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bernd-schorgers
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      nginx:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: nginx
              tag: latest
            args:
              - nginx
              - -g
              - daemon off;
            volumeMounts:
              - name: data-volume
                mountPath: /data
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
        volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: nginx-data-pvc
        securityContext:
          privileged: true
          runAsUser: 0
    service:
      app:
        controller: nginx
        ports:
          http:
            port: 80
    ingress:
      public:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: dl.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - dl.${SECRET_DOMAIN}
    persistence:
      config:
        type: nfs
        server: 192.168.25.3
        path: /mnt/data/share/dl_facing
        globalMounts:
          - path: /data
    config:
      nginx.conf: |
        server {
            listen 80;
            server_name public-dl.${SECRET_DOMAIN};

            location / {
                root /data;
                autoindex on;
                autoindex_exact_size off;
                autoindex_localtime on;
            }
        }
