# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nas-download
spec:
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bernd-schorgers
  interval: 30m
  values:
    controllers:
      nginx:
        type: statefulset
        initContainers:
          setup-temp-dir:
            image:
              repository: busybox
              tag: latest
              pullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - |
                mkdir -p /tmp/nginx_temp/client_temp /tmp/nginx_temp/proxy_temp /tmp/nginx_temp/fastcgi_temp /tmp/nginx_temp/uwsgi_temp /tmp/nginx_temp/scgi_temp && chmod -R 777 /tmp/nginx_temp
        containers:
          app:
            image:
              repository: nginx
              tag: latest
              pullPolicy: IfNotPresent
            args:
              - nginx
              - -g
              - daemon off;
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
    persistence:
      data:
        enabled: true
        type: nfs
        server: 192.168.25.3
        path: /mnt/data/share/dl_facing
        globalMounts:
          - path: /data
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp/nginx_temp
    service:
      nginx:
        controller: nginx
        ports:
          http:
            port: 80
    ingress:
      public:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: dl.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: nginx
                  port: http
        tls:
          - hosts:
              - dl.${SECRET_DOMAIN}
    configMaps:
      nginx-config:
        enabled: true
        data:
          nginx.conf: |
            user root;  # Run NGINX as root user
            worker_processes auto;

            events {
                worker_connections 1024;
            }

            http {
                client_body_temp_path /tmp/nginx_temp/client_temp;
                proxy_temp_path /tmp/nginx_temp/proxy_temp;
                fastcgi_temp_path /tmp/nginx_temp/fastcgi_temp;
                uwsgi_temp_path /tmp/nginx_temp/uwsgi_temp;
                scgi_temp_path /tmp/nginx_temp/scgi_temp;

                include mime.types;
                default_type application/octet-stream;

                sendfile on;
                keepalive_timeout 65;

                server {
                    listen 80;
                    server_name dl.${SECRET_DOMAIN};

                    location / {
                        root /data;
                        autoindex on;
                        autoindex_exact_size off;
                        autoindex_localtime on;
                    }
                }
            }
