---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: nas-download-config
    files:
      - nginx.conf=./resources/nginx.conf
generatorOptions:
  disableNameSuffixHash: true
