---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: plex-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 20Gi
