apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
type: Opaque
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:mquW/QO2z+Ly/y6S11dkRQ4hkZRykBx26X8=,iv:FRCVoG88jq+CU61dCOe9P0QtE0xcV64gZdkNiqo15vI=,tag:dyaJqYTRI16M0rdekLeZeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T16:39:15Z"
    mac: ENC[AES256_GCM,data:ENF6e5LtgvLQI1BIL4Kl1U/MOURVObj1duZRBsOhmwOPVtj6tBbK2eGMOHzSQlZ0ASOAmg/IJnduLjeYR2p/5EPqj25H4gNpY00oYdaF8d2JPh+Utn2ORwle/ATHk8Q8kEjTGeEyVs3JqELo2gQSnd9aT1j3mbM5jIeADXIycxk=,iv:3gPogmg50JdKohP53q9CjRqahXy+CFACJk6UWubfgCk=,tag:Ss9WABdydT9ywzz/xu9rWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
