apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: default
type: Opaque
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:WAq2LxCWgeGgJKx0zfEh5g41pvojVgWBWck=,iv:7JqX5IiktYB5qM0gz4fSJbK2VAcqk0/SEC8MtD3wkZI=,tag:jvEhONYPEQcvV1PrdYt5ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-13T10:53:52Z"
    mac: ENC[AES256_GCM,data:stRl6SUEtmR1fiNwiI+xPjHiLtiOFgaJa3/9352gsHr5f9UaBDzhFhIlwD35W2/u9WdqyqpW+1PVoFEEulFvk8WTdjQwPAYwfe2JQ3GcWe//Rs9/HlIye0LixvxmMcq9VoaKRvnGrTOxUo2nqs/mcuXb94X3Yh01OnlumaEATVE=,iv:j0I5rYx/JuqOcEo2zcLh01dCKhq6WHBWe8V+Pzk2YtQ=,tag:VwqsYoZGwVnCH/7upOIS6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
