---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      scrypted:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostNetwork: true
          runtimeClassName: nvidia
        containers:
          app:
            image:
              repository: ghcr.io/koush/scrypted
              tag: v0.137.0-noble-nvidia@sha256:7e8a908720d34706d852ec71ee2aac698a3183d98bd5d3664d96de9d7fc8d1ea
            resources:
              requests:
                cpu: 136m
                memory: 1Gi
              limits:
                memory: 4Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        controller: scrypted
        ports:
          http:
            port: 10443
            primary: true
    ingress:
      app:
        className: "internal"
        hosts:
          - host: scrypted.davidhome.ro
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: config-scrypted
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
