---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: workroad-minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bernd-schorgers
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      minio:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-12-13T22-19-12Z@sha256:149fdd73108553247ceee85fc65466f51034bd6e145d6e0c0e415167f5f1274f
            args:
              - server
              - /data
              - --console-address
              - :9001
            env:
              TZ: Europe/Bucharest
              MINIO_UPDATE: "off"
              MINIO_BROWSER_REDIRECT: "false"
              MINIO_BROWSER_REDIRECT_URL: https://minio-workroad.davidpps.dev
              MINIO_SERVER_URL: https://cdn.workroad.app
              MINIO_API_CORS_ALLOW_ORIGIN: "*"
            envFrom:
              - secretRef:
                  name: minio-workroad-secret
            securityContext:
              privileged: true
              runAsUser: 0
    service:
      app:
        controller: minio
        ports:
          http:
            port: 9001
          s3:
            port: 9000
    ingress:
      s3:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &cdn "cdn.workroad.app"
            paths:
              - path: /
                service:
                  identifier: app
                  port: s3
      dashboard:
        className: internal
        hosts:
          - host: &minio "minio-workroad.davidapps.dev"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *cdn
              - *minio
    persistence:
      config:
        type: nfs
        server: 192.168.25.3
        path: /mnt/ssds/workroad-minio
        globalMounts:
          - path: /data
