apiVersion: v1
kind: Secret
metadata:
    name: minio-workroad-secret
    namespace: default
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:YcEA1Rp+h2U=,iv:77Qpwd1geKMQURdSXF5sNWI0O49LGQJLuqrRSoEuyWM=,tag:2gA0Cdx9OB3kMcLK5wsDUg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:zNJEkl3lmzvrrk7Rmv5WFy0oOxw=,iv:kzFWkBkYMSyuU0xdc8Jr1q3wBLvMBpdeKu8CKEzu5EQ=,tag:FizC5TEBPxpLumGZO4lRLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-04T22:20:11Z"
    mac: ENC[AES256_GCM,data:nSHsI3MiK0NuewTK3SE5hlrXU8mZ6Q6S6N3ZZ2/XyF8LQM3NIuJk689WncdrsrZIQ/nqG7jSJ8EpQqkLOwlWFbFLIr8nCHSKnVPI/70Ybq6LkFfj5Nqwh7xG54LD4h/cttOdgqGXxkiSQSZnYdsFuB3oHsQQxRvMKrz0lGzJocA=,iv:5oc1zfGRR10E2Xmp5KMzxqAwbwzoYh7kmMDlaLtNZCo=,tag:X0rgyotBZSQ1CriM6lXOmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
