apiVersion: v1
kind: Secret
metadata:
    name: sops-age
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:0r7bGHC5MOJGeoMarFeQQYJ6KaPdxbixo2c5gLpj71BSYfxddT2XZg1w+cfhZSeT5xIHiodlP8Iqrl55gWuWtPG7ybNXGumBZhEJGCDDKLI41NZOzSuDVGO+29Bx/svkGCmWQ30zzS9roRXCSB+vPelhk+ZDoTyNdFHuFQX90TXufI+yGIuVjzt30UF/rFqys0LSIhfxvs+xV8IGHMCg1FSaPZLeIaZvMT8xVg8ZxzV1hE4uzoGWCx6RAhBE,iv:vSE8gAIz1DrxybtAcqt6skVhZUtxxCr5nIWbRD2wdCI=,tag:/jguY3XF55EtDWgTslxkrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T23:59:45Z"
    mac: ENC[AES256_GCM,data:130FhVZArNM2SAJPSpjzZrj2Vnv3G7T1sys28Y+W5cdqkA2hmBmB5uxSYZ5ZEXEkfkr42TC9bZIEpRx+MhY2bQYN62kYnHeiRvaJ5+XH2JDxj0v/OxUJQjue+lPCKNQy8KgdxfAc7Z1R8W68PUDHaWPMO+lnO50Abs3eqIsBxTM=,iv:+HuFYe2eSFoO6MW5LDzv2KlwjMOyHTGAKPFxIBqDdFk=,tag:iqhioZiqvKLYBwr/tMuKvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
