apiVersion: v1
kind: Secret
metadata:
  name: sops-age
type: Opaque
stringData:
  age.agekey: ENC[AES256_GCM,data:y+8HbtiRVoXPHNWulLluj1fotzW9Wh1G3PWAqGFqpbtXUhmosTshmFdD+MqYczUEsiQdRwQSnFW9+m1o7ju6tPuFaNv3ld0tuw++5sigUgF9RxsT+XxlSPcXZfThAg1D5IuLarJSEimh9+51uTN/KxP+pKnGs+QzvHYYKZDcFJVyiGRF3PGvUmwoucWkqSh+yObl3/D6y5Ksi4Xy2PdiNxB8rHcXOBgu+YGWVWcaIhvt61mk/8OLTSnpp1HXakXXk/gdLncOExIKaZVn2+dDwdw+cgSyjKKiZoIAFZZCdmZCWR7oX2MfN/uhVqnkfiRAnVs0R0C1c6D09g65CJw6Haoz1yz7Lj2Mhzd9rjzkFAkrFz5aFIIsiSjuxsZWCvfnvv8KMp9oKgolxBCQwLgtRrpGcYMaWIS0Dm8/jX2Aul+OAc3YTofHBFB+MDbQMfR7GdJOhEO7bGIyiHIuQOCuXEy0NsX9Qfkg+tk7345wcRgzPJ1rftGruo1YXQ==,iv:57FMJKqHB6JIZAVovskDLuqrYJhv7QE2G/MEpkZ2+Cg=,tag:raYBADkT6ew0LEjOFT04ww==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSG9PZ1ppa21rSmNpQmtS
        RVhkOGZUTGpMbmprbHpCc3JIMXd3UlJLZXpzCkwxVXV5WVZMMkZKeW1UY2t6NjdF
        ZTUzQlZsZGFtd29kZmE1SkU3eHJheFkKLS0tIGNkcEhBbmZLdGMxVzNTdnhtT0Jq
        TURtY2VjK2FmWVBtZVZLdEhobm1iTFUKOwUuwfemDjGBPZ4yuysoAS0M5SWjIRWb
        lejKy2Fr5LYVGgiRYulBNXyWTZDVWrC0rBDjr9CWsHbdWbbPfe/4Ow==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWjJPVmVSOThUTmdiOW9w
        ZUpzaDdqZEhyMS9ydnZzQ29pa0lkOEhTZDJvCk1LVk5xY2FoYkQ1SlBhWEwxaXRl
        YW1BaEJ1MDU0V1BEMzlwUDQzZ2J5SHMKLS0tIFdoTFJ4SzdBbTZBMzZyQzh6Ykh1
        RXIzUUVENU0zYkhXSERDN0FibE9yamcKPs+Imq6q1cwuSVX8JiTOf9xTA5TmZeXo
        9KxKVYGlFArKoWbP4cgmRqF6L9MNBPY523/UHGSzcWHHMM4xmJpQTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T18:08:59Z"
  mac: ENC[AES256_GCM,data:fWNpM6cQjm85e6Om+TeS01n+Oxod8qNQYjSZSpqxtIBjMuquK/BWhf/qHdLDigR9ZUy9kHJiEVGKiwlzCCglJFqDGXQJou678rrrxWhU+HvZkOgw91QoQqv5w8WLqSlrt3g+5x5pgFDshSvwBf4erhrjpdiPfw1uVti5Vlcl2SE=,iv:Recji5YIYaf7zG5o2hWqLjMspfPMfv2sdRayUcuGRGM=,tag:8kyJb3/uRkrqi7kipc3Y+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
