apiVersion: v1
kind: Secret
metadata:
  name: sops-age
type: Opaque
stringData:
  age.agekey: ENC[AES256_GCM,data:v1lsCrGyGJ+XPgFcAcu09vBsriLi+mM/TB2Afh2pLuPcxrj4HcWrBQNQVi2om2db9DQmzfkyt9PMAAPW9xEltASKFsfIxHV8l+BToKzbEs6oh9ROFx3lYJi8+o5svWHN6dmC04cVTEHIujnP8k4WoDP7m9k7hK26ZI7rf6qB8TdbiKxs2MAn1Ks70Yxk0zXApYmTv4CW2uyvbZgbvRXjCr8G2JRG+fa8EgPWFd5KBmgeNrqY+mfIpdh/Lj1K,iv:pLFRn01LtbV9PdNbtAIY0TijvpXr+b6mhc2YJnXc7S0=,tag:OTIvf1NjE3rse7smBB5kWg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOHBwYzFpcFN1OGp1VWhq
        QlhUSGVYRWhSRE9USzNIRmg5UFQvNWtEZFhzCmhUYnhrK2NRMlJxRlZuQzZXWnM3
        OVZjOHI1YXZOV2Z4TWFlUmtyMnRtZ3cKLS0tIG1jRnFWSFhDNWZtSnhrNFRCTy9Q
        OEZ5Yk1RWjdFbnFEQjI2RmttLyszWWcKnzI8I4bBgIVQhn3SPJaPQudqI2qnUGnn
        Y21+JwCBuzn+2AoqzQW4MLhX8qKPioWfaZro3sSUoX1la0ZmapfKLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-10T18:14:15Z"
  mac: ENC[AES256_GCM,data:opZzJ3D5+j0dWaTr5wDt2g+fO3KCXy8yp0SucvAwrt8uG2I6ZjuPJHUpFHkZFCFst3MKBpv6vQfoE6KA3+SP09P2GFT7sDrY9IsCzigSk9sMx2sUnBFk6hpRZLayiM0q2afiI7yAusQHRQuOMkv92aW1f6jvi+Yrxmr3nuEtbXI=,iv:Q4864E6BoNpAmT8wdJWEr2auIgAxChdkdUs8G3klV2k=,tag:Icrfu3OcmRl74+gUVfZxjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
