apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-exporter
type: Opaque
stringData:
  CF_API_KEY: ENC[AES256_GCM,data:xsspon3AcbeFShFFDbbN+Y4TOqeS9KX0fKIkqAAWX3JGD2eZ7A==,iv:vVzrhRkL91BmsCc1JS6EkT4LZHqNT8NiLnmglYNa5DY=,tag:NFr6IFNrWa5ouf/VvLkcrA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDhyZWtKSEpuN3BrL2tp
        OWg5ek1kKzhmT1BNRXZEbldJbjhOeloxZldNCmRna01leStsT1cySVR6cTA1MHp2
        U29pL2RJb1NFSkg0UUw4VERwQ0dhM28KLS0tIE5mT0NHNlZRWjVuaHlLODhrbDg4
        djNhRlZiNGNIaGxNcFdTTVdRSEQ5a1UKNvhwEeDBVDmki+a8RWOB5eN9A8wRYFxv
        NWGXMmQ7UhnykL9KfV6kk9zNs7ovdjfrhImfdT7uyCNAJd5/YhXy5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T20:30:09Z"
  mac: ENC[AES256_GCM,data:ncRxNNNXsCOiRj1ikHvtVDC/wumonu5FDqO4CjrNPyt4P9P6mV7n9fR89AptX6LPl7boXiyrQgFHcN7znlNiPfOZ4viurtV3fp+HI1ATHBffyZYZCe+GeDsLN0LakKAwjFdtnPJrR6aWKjYKxRcu7GWTTEeOF5NEjFs2neVhAz0=,iv:w2ktO+nTuYyK9GxhQ6B8SudQ/NpAbdl5hz2Y7mZq77A=,tag:3xSoIz6k8E+OL+unIAcCLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
