apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-exporter
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:xsspon3AcbeFShFFDbbN+Y4TOqeS9KX0fKIkqAAWX3JGD2eZ7A==,iv:vVzrhRkL91BmsCc1JS6EkT4LZHqNT8NiLnmglYNa5DY=,tag:NFr6IFNrWa5ouf/VvLkcrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T20:30:09Z"
    mac: ENC[AES256_GCM,data:ncRxNNNXsCOiRj1ikHvtVDC/wumonu5FDqO4CjrNPyt4P9P6mV7n9fR89AptX6LPl7boXiyrQgFHcN7znlNiPfOZ4viurtV3fp+HI1ATHBffyZYZCe+GeDsLN0LakKAwjFdtnPJrR6aWKjYKxRcu7GWTTEeOF5NEjFs2neVhAz0=,iv:w2ktO+nTuYyK9GxhQ6B8SudQ/NpAbdl5hz2Y7mZq77A=,tag:3xSoIz6k8E+OL+unIAcCLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
