apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-exporter
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:cpoPTEU0dj6C21/2rWlHjS/h55bvsp0WGiTJZaSIZug1hkn8QQ==,iv:mncuoLVKxjj+oGHT22c9OGxYGzPYmIBrxU3jGPS685w=,tag:pxcu09COVaKkeMNGn2D4+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T20:15:29Z"
    mac: ENC[AES256_GCM,data:m39wQ8HQRW12yYFj4PYfGlaAfyb/sclOenfIgl9vQ5012+VMaXuAtPIAFDPSU00i/oAMlJlpYKVrGL4w3yZ0T7DiG8bwtas2Z/og2pcdeieiAqcnQxpOdh+TCUph7dPsmZeC0JC01fcglEgaT2v4R1A/T7e6/VgcOuXvWI+ksWE=,iv:VF41JH4HrTPqqwI/t+vJbRgpAZVYYzCi51lQPvVUp/Y=,tag:JdOcX60Q50muoXoHPI5vfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
