---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app internal-external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: internal-external-dns-secret
            key: pihole_password
    extraArgs:
      - --pihole-server=http://192.168.100.82
      - --pihole-tls-skip-verify
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=internal
    policy: sync
    sources: ["service", "ingress"]
    domainFilters: ["davidhome.ro"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-pihole-secret
