# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: internal-external-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:UP0BfueAHspH1ogyMEcQn3ZZJsWDrpIUL5yBvh1/KTY=,iv:8KXjJomTLVDOd+j6pm1T4n+x7qFpKTxz0LukF+QWHgI=,tag:73Bks4uj2GBFNb83c/oZqA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQVp5VDlpMGF4YkdWaGd6
        TEpEN25pdndFTWJiWEtha2g2dFhkRUNaNGdNCjdJTnlBUllmTmppZ3M2TXFncmRN
        V0pUYUdDd1RoOFNwY2VzODk3NU5qb2cKLS0tIDVZd0JWa1h2MjhyRlVGcWFFT3Jy
        WkdWbjVPUVBCNkZFY2lsYkhsRTcvdEUKbfYThbeyLIVjZFUxRiFXni+cOx5XkHAw
        OqObOdUbK75iGPtD190ckoIwfqwTRR3I0BeWvX6vw8U9/oPoHfcNLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-07T09:28:02Z"
  mac: ENC[AES256_GCM,data:IzkcN4YMlfUIq7bh6v4JDOo5chnTiozWNwbEYQiPDTCH7v3QByXx+T462CUJAohDwgdcVfCR80KDKQbmKnTEzdVa4V0ZW6IBAHZr/gGdW1zBtOm2hucrUEz8AeuxJn45zMspCFlhPdAyeKhoDdoSyQIdHGV74OE5EviL0pk9z+8=,iv:truuHMUd0SGb9Ez8AtBtA4hAJiC5o5enKrJMy/C1CRs=,tag:up+dt//MUDoY8zQf/0gP2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
