---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-analytics
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tempo-analytics
  local:
    path: /var/mnt/mdadm-analytics-storage/tempo/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-home
