apiVersion: v1
kind: Secret
metadata:
    name: workroad-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:mXZae7WOENVZ6jp96yBEyP1Fh9CSdO7PUe66BUt+hjLR0r49/bZf0+aMzpCjxVldqUPJPb1VoV/FtZkS3UAPZzY3iS15wjVKEF16v2NrnY6SqFpCX9aeID33yv8oNs+iN1g34eSWKicd,iv:W38rYAR/xJDdLJriMRJcpwP4iZihD/sRXSch2sMv1rY=,tag:ntDAF45rdxB3IXkZnIJSAQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:677CUkH069l8VFxzlg==,iv:5YgMimDF7ARQdDTQ1OjvbgFiUTb8f4u6JZFGn7uaciM=,tag:G0gTPniwFleLrddy0fBlDA==,type:str]
    APP_URL: ENC[AES256_GCM,data:jsV/MjicOCI7OHmxuZLds04GHJE=,iv:dD0qNZxb16KW6JaQi2oKWi7SBfcDyMh2j7Out7RO6eM=,tag:w2hq0rT77CFSgntALpBx7w==,type:str]
    STORE_URL: ENC[AES256_GCM,data:hdmR8cHUFOnrDf7GjayY8eaJJflygtmYzFs=,iv:fZ36+XABd3XPomLYivtIq96MNY3CNLUiqjYsh9cyCGk=,tag:S6rcdaa5vFavrydq9HOWLQ==,type:str]
    JWT_ACCESS_SECRET: ENC[AES256_GCM,data:UB1pObG33s+5yO2BYViIlkoSnRRI2Z/ZM/VvIVSckhw/Z4Nb84hY32R46QKSSeMaiVWp02nx5S25kpQvTVUpPA==,iv:Y6XOTDLunDElIP9uXZ2vSCcj/S0luuyKJePVEBYRCEU=,tag:OlAzlS9kjD+t2ryPKReeBQ==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:1hFjvFrK2Y4jeSbvUeVzl2ukZ2hsyxCgKHHaSXFixuiHfs06SpDFHjKYATmcIbOossQlVeGB3zIKG3JavrPdNQ==,iv:igCvd5ApT/txxBH0WT1G+1MBtPxHtzoIIVvRo7rGe5M=,tag:oaNduz+KvlDEG91k7XxGHA==,type:str]
    PLAUSIBLE_URL: ENC[AES256_GCM,data:c3By/ytiI2WYvntysVPG195qFvb0ByiJ,iv:GMmjSy5BtOEE6HNfkM9SMx7XlCJqGixNUYi6KTc4bbU=,tag:1FxeHAIysbrmO5HTvJCl7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb1JIcWljSThtZ2JodFVJ
            aEpqZWdESDFURUdLckFWQ1IzUldyT0ZCd0JrCjh0MFRRQ1c5N3haRkZrQXYvU0VW
            TkpKQ04xTUVLN09ZUUx0T3pwVXp2U1kKLS0tIHl6RG5INEVpSzJvRnZUeldXd3R4
            Nk95dm5qdEY0d1lVc3dqRDJTNDlvQ1kKLixoeBTKgw8tdBEOgemi4P13l+WSaenK
            HX//jMdwuyBbOVgBvrQaN4u6NQjNANoG9WQC2pdJ5woT3aklNqaV2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T01:19:40Z"
    mac: ENC[AES256_GCM,data:GRyWe2k6RAIIrOZfI5TDD3xcY3YcYIAqX4AEaNC0OeBFXCreqsHB5lrf7MrIuJkE2JjhCT9rBqRb1fKCl3K9lj1XgZG0wioMMxrnxLGyryYBXC+zYTLD9DPT8woR+qLZsE6YEhdPRIa8TyLKZYA5W+4s7XVm5SXqNqzeEJIbk84=,iv:lTs73/YyExda/C0Zk+oKmNb70UyYVQf7qZOuf59XCpw=,tag:Fw34rtXzb8hEhUDTOh2Azg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
