apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
type: Opaque
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:SAy6nbez6ZEBPsBaVHiC5aqscvut0UlHrmPSxbYNvEzGx/D1OFQC4Lsw0bQ=,iv:0OejfP3596y1HxbffKpFqHzjiof1ElqVQxq60VisPmw=,tag:lD+RgT8W7I5KT2DSDn9mJQ==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK1o4cCsyY0puMWtnMFRI
        OThQTFVuK1czVFdJVUVuNHltL210MXVHSDNnCitXWXoyL0ZXZUNkbmE5b3lpMXBM
        SXZ0UTRHa3BlMWFmM2VmbWxKblNwSmsKLS0tIFhUN2dJRmsyU1ZDQnhMUUxIU3NP
        clZ2SnlxMnJSYXlhcGtwN0t6MVhyYU0KquNW2ZcTB+b9SvHZTwI9xKDeuyW3arhn
        yZIZLAAvP5zj1Y2mowGB/cpXG44fYyZXjTpma7jf1cIfSUYQPClJwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T23:00:43Z"
  mac: ENC[AES256_GCM,data:9QBhUBojd2+v+x/F4K35nL9kjN9C13api2lsuZfpOAmW2Ysms38ir+yA/eU3iDwG4KilnseXoOwNC7m+iXnCdQVK9yVhgUtacfcnIifa0GeXPeyXVH0YvsFuKPLVuucPdASLFY50j2x2hbHg66zwLzbZ1iXayR76QmEF/RdhzwU=,iv:PzsBPmXMgMfWjjCAxZ+5/XQevshTGfidCC6/xr5ipZs=,tag:8l4nqOgs9aNAr/Y6j/nZWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
