apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
type: Opaque
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:SAy6nbez6ZEBPsBaVHiC5aqscvut0UlHrmPSxbYNvEzGx/D1OFQC4Lsw0bQ=,iv:0OejfP3596y1HxbffKpFqHzjiof1ElqVQxq60VisPmw=,tag:lD+RgT8W7I5KT2DSDn9mJQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SUE0K1NuaVN2VjEvL0Vm
        YjN0WnhHYTkrdk5aKy83cUVqTmtXQmtEWUZzCkJpNHQrRmVOME9Eenh6NEg3dGJx
        aURnUjhtTU9Vdzd1TVBFZnBxUGMzbW8KLS0tIGRZeDZtZ3AwcnFSRTZtZWlMNGZY
        dW51NGFEUjkzWjNJd1hWWC9lUW0zVnMKck12ItaARzv64JJk0cA1Hl840C6VpbtK
        celyXx9SeCs06uoDSk60dhjloj79GKPYmuzFwGHO2KZfOM2vGan2gw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRW1yZjRPQWViVlVlbk15
        eFhWRzZJK1dZVDJHWEcweEpLRVVYVktMcUg4CkxoLzVDL3c3Z1V4ZnFGeElDTmFH
        YWtjWWtxY29WQjRLazIyVmplSTl3eDQKLS0tIFFVN0VVTVBmTU1kYmhjOVJRK1Er
        ZnZaSGt4ckJuWXAwaVJudXROU0FOUVEKj/9YiUtZ/JYlNYjLyxtDBojMOE8RDJEa
        UkuAYyRWsYAGFji+cdN7Efhg4x0Jwn7kIeYdlGDDY6k2MAoyntWuAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T23:00:43Z"
  mac: ENC[AES256_GCM,data:9QBhUBojd2+v+x/F4K35nL9kjN9C13api2lsuZfpOAmW2Ysms38ir+yA/eU3iDwG4KilnseXoOwNC7m+iXnCdQVK9yVhgUtacfcnIifa0GeXPeyXVH0YvsFuKPLVuucPdASLFY50j2x2hbHg66zwLzbZ1iXayR76QmEF/RdhzwU=,iv:PzsBPmXMgMfWjjCAxZ+5/XQevshTGfidCC6/xr5ipZs=,tag:8l4nqOgs9aNAr/Y6j/nZWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
