---
apiVersion: v1
kind: ConfigMap
metadata:
  name: posthog-clickhouse-config
  namespace: observability
data:
  default.xml: |
    <?xml version="1.0"?>
    <clickhouse>
      <tcp_port>9000</tcp_port>
      <remote_servers replace="replace">
        <posthog>
          <shard>
            <replica>
              <host>posthog-clickhouse-0.posthog-clickhouse.observability.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog>
        <posthog_single_shard>
          <shard>
            <replica>
              <host>posthog-clickhouse-0.posthog-clickhouse.observability.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_single_shard>
        <posthog_migrations>
          <shard>
            <replica>
              <host>posthog-clickhouse-0.posthog-clickhouse.observability.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_migrations>
        <posthog_writable>
          <shard>
            <replica>
              <host>posthog-clickhouse-0.posthog-clickhouse.observability.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_writable>
        <posthog_primary_replica>
          <shard>
            <replica>
              <host>posthog-clickhouse-0.posthog-clickhouse.observability.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </posthog_primary_replica>
      </remote_servers>
      <named_collections>
        <msk_cluster>
          <kafka_broker_list from_env="KAFKA_HOSTS"/>
        </msk_cluster>
      </named_collections>
      <macros>
        <shard>01</shard>
        <replica>ch1</replica>
        <hostClusterType>online</hostClusterType>
        <hostClusterRole>data</hostClusterRole>
      </macros>
    </clickhouse>
  disable-logs.xml: |
    <?xml version="1.0"?>
    <clickhouse>
      <query_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>query_log</table>
      </query_log>
      <query_thread_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>query_thread_log</table>
      </query_thread_log>
      <query_views_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>query_views_log</table>
      </query_views_log>
      <query_metric_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>query_metric_log</table>
      </query_metric_log>
      <trace_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>trace_log</table>
      </trace_log>
      <text_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>text_log</table>
      </text_log>
      <metric_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>metric_log</table>
      </metric_log>
      <asynchronous_metric_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>asynchronous_metric_log</table>
      </asynchronous_metric_log>
      <part_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>part_log</table>
      </part_log>
      <processors_profile_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>processors_profile_log</table>
      </processors_profile_log>
      <error_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>error_log</table>
      </error_log>
      <session_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>session_log</table>
      </session_log>
      <opentelemetry_span_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>opentelemetry_span_log</table>
      </opentelemetry_span_log>
      <crash_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>crash_log</table>
      </crash_log>
      <backup_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>backup_log</table>
      </backup_log>
      <asynchronous_insert_log replace="replace">
        <engine>ENGINE = Null</engine>
        <database>system</database>
        <table>asynchronous_insert_log</table>
      </asynchronous_insert_log>
    </clickhouse>
  prometheus.xml: |
    <?xml version="1.0"?>
    <clickhouse>
      <prometheus>
        <endpoint>/metrics</endpoint>
        <port>9363</port>
        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
        <errors>true</errors>
      </prometheus>
    </clickhouse>
