apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    labels:
        cnpg.io/reload: ""
stringData:
    username: ENC[AES256_GCM,data:euZUJKj9/q4=,iv:+oYDyS/uctykRzTrPGupBmyeckleJnbupXhjyp4b9es=,tag:wXL/Lt0AXiUeCtAYRpUCtA==,type:str]
    password: ENC[AES256_GCM,data:vVCwkksj+GFgWncyXpY=,iv:S0r9sUgmkQVM9K2ArA9KyI3NrvAe14Ixhb2loIv5Dug=,tag:1ELXMA7cAeoD9uS+lcDArQ==,type:str]
    pgpass: ENC[AES256_GCM,data:ohK8BPnj3DfjaCRun74=,iv:B4gVCX5qdnGwGVfNmlaeS4QnsSSfgoXJf8Y8bsQ+DIU=,tag:PlZZynkw11sv6Txk6lsrPg==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdVRpWkZJYjNOUURLaVVx
            NTYyYVVKVkIxY0d4SW1pbzd5bTdlZTltZTBzCkpsZFo0Mk9xZi84RXBXaXEyTFVF
            cVhkdWY4Z0hCL1JGdVUxdUtyK3lZbnMKLS0tIGdjdXRoeWpkTVBNcnlnVkNXd1B4
            SmVkVTVpaDlaUGl5ajAxYzRYMEZsZ0EKPCRcs3/haVvdaWY4oaBPVUbgJ5Dt/zP4
            5/QAmQhWDh92Ulqu0VnybeNrcKVx6IhGoleASKaxMrxy3lQKbt1BpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T03:30:08Z"
    mac: ENC[AES256_GCM,data:2HXq2jYoHkfxKv9z+ZAytctzjQt6GAmhauRz+96xItenx2ej/WSQO99dtnMVfqi3M9yb7Q1fJhayV0v1EYZopV9RSSNH9IW0dZSXylB/S3Y3hktNxqpQKnVLBs+ljt2a6a8YwvOJeNAOFmJ2iOcefk8kW+eIWuxOc0Uht+AZGsk=,iv:lhcD4mlqooCmnXoHLzW+s0thnYsUi9KEnLKVQNTRiBk=,tag:GYInxU8sWQNhKAqsyLsAHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
