apiVersion: v1
kind: Secret
metadata:
    name: clouldnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: true
type: Opaque
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:S3vmgyw=,iv:G83S2O8JDcy6wwrTgI28ua8tmVUiv8nfcdxZ/HR+qe8=,tag:7XVNn1atFeT85BUJCtqHTw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:szTIcC/+6xvIb2GBA94=,iv:aFHPtod7d1UYnOZmCEAn3v/yWqyXdFNB2WndJrGGOfc=,tag:02Q+abTW6ufGxcL9jLgMFA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:mkt4UW8=,iv:U+hH/SB6FHvRrMWvhhbqJNT5Gi2g4cpCOnk9xFsgunM=,tag:j7CxYys7o/09eDvrVOwgrQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:JnoSwE1FyjPKBoMlTzk=,iv:VWviYZl8lkLUxQHxaOib41P0qXT1j/05+FM86+XecR0=,tag:bpjdSdTQf+naZJDSrJMyCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-06T09:51:51Z"
    mac: ENC[AES256_GCM,data:q5/Fto4rpgOqMhSWoC6YGXomZ+6iSFw/Ho5bzhryNWcMFfiMKtd5pmLlkMdrp5C/Gml5XH4c0GLrR+nsmZd3/ySkTzExhoMSN7fmNsizzhMZ68ATpCWogja0gHd8We+7FHQ0gQZZblaDI3u5UxFytbJZg0UKzg6mSLAtT2RfEdg=,iv:6Y9BgMHcI226rsStUSvWGIhSPNCkVX+NbzWV/UcOkfs=,tag:mNOTSlc8IqIaAX6zwvWv/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
