apiVersion: v1
kind: Secret
metadata:
  name: grafana-kidays-admin-secret
  namespace: observability
  annotations:
    davidapps.dev/credentials: provisioned
    davidapps.dev/application: application_c01d5a7c-bc89-4cad-8b19-2628b30cab9c
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:Tk2SGItTWp1ZZ9bCLMY=,iv:U/BDet02EKu2Y1JVhr+tJwkzjpk4hvPGXM+2e8Hlf9w=,tag:nIluJgKzZcm3p82n3pN5sA==,type:str]
  admin-password: ENC[AES256_GCM,data:t+wX6GFYMArUFtEDC5dUkf2YZy9h/HfPoyAXXnVJwPyCDk5eL3xeJxDK5w==,iv:CwXqPjGrVNV7prY6oUJgxPIcq9xPh3btgz9S0oNfSZI=,tag:iS48Z/DteHJId8k1po90eA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByKzZ1dUk0QmtXT1N6Q1Zu
        N3RIanZtRHBOSzFNc3hwaTRsMWFLSlZPUURNClZYOWRZYUtwMWFMOVJ5ZDFqZGRW
        L0c0c2ZMRE91RHJFeWVDais1cFdTd3MKLS0tIFUrZytwcU54blFpWEVPS05lTzZu
        VktuSW1kbklWRkwyNzg1MG9kOWNLb2sKzGX6Yba5/5El1VvfUFtUgf9QXS+980rR
        rq2X44Lc9vjFn6sgJ4EBfYmSq8GAxIWSGP4ij1wGnQs4gPd6+HnneQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-29T22:20:26Z"
  mac: ENC[AES256_GCM,data:T0q5XK1iIK/fP8fgSry8pH8HyRlvHmeKWE4nI2D+DmTqDBDwGzrG4X+pgPOKmCUkRYPzJfhTsHr+VzdVZPiao+Y9TwYtNoOV6sI3YgjRcdtbSG0xjon69TsBeJg/UHWE7wxPUdwtGSgLF+Wd97nmiO/wV10YhP/+yEyi7/CvYvM=,iv:BHQkM5z/lhVMMMzkMnAj0TlY95qJOstAVo4R6O8jErk=,tag:uJgUPzoLkEYie5NusLfSPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
