apiVersion: v1
kind: Secret
metadata:
  name: kidays-query-gateway-secret
  namespace: observability
  annotations:
    davidapps.dev/credentials: provisioned
    davidapps.dev/application: application_c01d5a7c-bc89-4cad-8b19-2628b30cab9c
type: Opaque
stringData:
  bearer.token: ENC[AES256_GCM,data:nhqSc5+k9rgm9aIcnmdF5sHWX2XnaRufG1rW59jV//HiAAEh9RIvkM2HqJoywjDonoULLWHn5MFsCs1tF/ARlQ==,iv:F6fljVhHKVlcf9OR0IT7yepZQHp6dE0Xc1tftmdOyDs=,tag:DT3W9vxMwU1TIQ3H8RR2Aw==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmw3VWJFL2dnbWpRT055
        Zncxc2pRd0pBNGZCaWZSN1lOQWNXVlhIRkhvClh5dmJwaVNGZHBtVTJxeUZCcjhD
        bmVRSFRpdVh5OGFUK0JkYlordFZhMW8KLS0tIElsY1JZWEl5d1Q0TS85Z1JBbVF5
        ejZuTWszWnROYUR4LzBCdXNNbWgyQzgKXg580IzoSAuAp85vQrv3YQaU8lG4heQw
        d+5uuZh2y66NVzc0RDuRUJb3IdhNBZEkHzc8//Z7/zYgdCHWZH+V7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-29T22:20:26Z"
  mac: ENC[AES256_GCM,data:fYBtiiNXS0VghsBTOvjhKl7+BILwHmS4aqsLgtXQGj1eZwAV3cFLiVEAPRw/uTPcxiZaTPBgOTz8oT184vY8FF6yVzm0F1ROFVJseRrVHvbDExBhli9NPtFDoEODYU2u3oGtJiBOV2zwuu2cJq0l70S3GsJr8t9GRgMilv1GFZM=,iv:yJgTJGkD2zw05EMJAQoK91gJe1qdmg7vDPOrjZbYlWY=,tag:GDdTXCLJlkOjx7rzsGXKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
