apiVersion: v1
kind: Secret
metadata:
  name: grafana-kidays-oidc-secret
  namespace: observability
  annotations:
    davidapps.dev/credentials: provisioned
    davidapps.dev/application: application_c01d5a7c-bc89-4cad-8b19-2628b30cab9c
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:DofuDE4MoMqWVzPmHK1ch/grxPgwRWxdixyualUR3s8=,iv:teFaqA56HP9s88eJK5FgWpkxboIA21872RDsf9atTFU=,tag:ULPrQaQXvNj64uw3JkVA8Q==,type:str]
  client-secret: ENC[AES256_GCM,data:9yf16PJkp/g/S2XRR7DXJLnbvTygAcb7zqdVu5cRlRAnEqvm0eaxLytDIA==,iv:rK8ijVLmdPkVDvDJ70rLAfGPZMk2ZzP/9fjkx066eUU=,tag:EmR7PQ4VeGsIEbXLXSYHZA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwK0EyaXZXM1FnaUZNLzZt
        cWx6N0k4YTh3eS84RjlDZ1NSK3VrdWd4cGlrCnR4TTg0TmZQMEdudk9IRCs0Tzg1
        bFRkYTcrWVNtNnRrc2dYdFRRSG9uUk0KLS0tIGtFQTVHNWkycFRFamlQN2JIN1ZW
        NEFxR05hSWJYZWJ5aVNPZVpySjE2cG8KQmPQ8dIv036CvydBCNhezn3gJ17lumMM
        upJRqrBYcLW09S8Fa1pykh2MmfzbakSjGNpARzrVF+ZHeZBMkNcB+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-29T22:20:26Z"
  mac: ENC[AES256_GCM,data:OP6dBfwTX5My9oLcgCwiwTrdhMCYSNSiV4r6dNyhSUkNbzVKznuCweHpoD4MssnyuQ7pwHdTmIMApprs3+23HoTFwLwQOHFNA035xAmd4JHg2pYFn4GyzKuOxz/tjZ8gr9HsWq3C2+ZaEZpj5OgXs01PtWi4ZrrlCokJ2obZTd8=,iv:Y1MM6sux3r+KKbquh5ot8qPfsGX12kafyUcGXwWrBRA=,tag:frdzpz2mVBk0xjyfaxuGIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
