apiVersion: v1
kind: Secret
metadata:
  name: paperless-oidc-secret
  annotations:
    davidapps.dev/credentials: provisioned
type: Opaque
stringData:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:2iILTr2MCnJcHPXy89HRvAGyyTWO9om0PZVTSfepwvc2SnFbkBSfeTaGTgfpg8+UI0/VtjRXyrXR4JJ3a00mkZcQwITG/YF0WnZPGYSKsAyLD54/KgsM9oQnEYNZc9YfRzIKMbsx7qMxGAqqaqU4tyuiJ5eNhIVAcs0t+5p/0H6/iynkOqrMQvY2yefIU2CnkWzUstXEr0OADioFUXewcNu3L6Py0f+vqRM0daoVCG056tcU5i+c+6CnP/vJypL4DG0FyfKMpqWmTcEzHeEMgEj2lz7lw7bYUcvwdoJGC0x/Lf86TlF4CGm5f3Zq2Pm6zGIY61HUcurGoP1YiHiHK94V5IdAoOU3wBhs1wbpTWNQaM3AEqJ6Ufs8L80kVRN/VIsrJzfbSeteGoNncVxSN9cAI44Pq27aqltHW3UnCRoSvA6q7/IilhRuPYzAcIy+dsJozPngyVsu05dwmGA+3v/GOcWzg6WwDJEtt8w44ELW4v1L1pbft8Me9y9e14QWHeXx3gAus6TeYMqjqKhsfSXVBKo5XF6gHw==,iv:fXK8/jYgEx2XFoKh2/H3vhRS6C3GToY0Ds5TAiR6Cag=,tag:W9ckFlReeyuqLQt+WZ41Jg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ylp4MW03MnJMM1k5YmFP
        OHAycGQ0ZU1EZkh1alBnNFN5bWhlK3ZFbXhJClBlM3l0c2tKUGcyT3lrU1hpYjJB
        NXVYZXo4a2dHclBMVVdWZlNjbXdNYzQKLS0tIGFjYlA3THZGbzd4U2dtajBmQVN0
        TTUzMFFManBKYW95QzZiMVp1N0p6Q0EK6zOdVyLy9iw/+EK5fByAsCVtD58F8r7X
        EORWlq8+9qdcoyDUmhOXp6jvUEkkXrZHINbQdns1dq/sPdmgJs4kyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:53:39Z"
  mac: ENC[AES256_GCM,data:JTJdBcbGO8oUoQqjutXP9kg9j8pqQkCbURMyB6y7QzPcWBAquGbiOMKKiiyShgofiSuAVNC6XfGcm/5yzoL9uWZ4cnbJB8QQosuxey4+BXs/uC4iWBDNfe17B0pnesQJQwrLxRnuU35W/+34AYkpCcTjG7LPcqCReobTqfEo5dg=,iv:Cuiec29Usp4fB8rzFSCdFqIhJU5wFfzUqt/hzQZ9KSk=,tag:abNkWqnVbaE7pRwjgC7log==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
