apiVersion: v1
kind: Secret
metadata:
  name: paperless-oidc-secret
  annotations:
    davidapps.dev/credentials: pending-provisioning
type: Opaque
stringData:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:7JPtoThIaPq2l7qRI/ia2Q3GxSkTAS9vijXVsAyFPtsrUUptOW6fuSq1FHcBxnmSk5XyUV2FnuovE6P8YBdmDtVx8YKz5ysAMPN1RrUCFgjm6YXVMRJh599++DwM9uC/lhmtaq9X9bxQ7P6Q4kGb5UrSPHLO3FqgFEZYBRJsNA7a1rmU7ftZNSpBGeSkpJvHA6QABc0Ukgrf5htYd52dBL8d/LWsIOzAaZsBuceAjLpWQ70lhERgi+Zik1jnTmB4ybOde8jaktkmZvG+8hAhc7bcIKTapsOov3pr3PDIjqlK1oSSjjIMChN/GYH1ZhuDURKYNe5ibPUr3pq6jMsqsCQEjdhp614WNVnaSegOzSzVT26y60wNEdF3ZBHR4Qt4Aic/HfRNWPIbKd6vG1qYuIYipL14YX3i164B2+m0xTChgc+6WYc+B7o1zixWSg0XJKcAFEfdhNbcvdmsJ/jqqKBkAp+VmsRHDQufzt6gHAeTJnEII2/bsLRCe6ebVM3D9D+KdZfSSe5HlkGeNRJoInnSxeHgAqy6nDHkPMJiml0zAH9k+A/L+4FiuqY=,iv:2UJRRNpYSh1wwyKDp8Rl1gw/lywUzJGWV62E6l6Pvls=,tag:GFTVYxssU6gcsVkBiuzjzA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcmtwSmExajhFd0tGa2Rl
        YmpEU1h2d08xUGRuTHFzN0pKazVNdEhDbkFvCkswS0hDZ3B1T3ljYTB4ZExaaWRl
        SStDOE1PSDZOYmx6TG1MUkJFMmdQMnMKLS0tIGtCeUtFMzNvUXoxdm4ydHdtQ2hZ
        di93OVY4MzUwR21wZjBMREpCKzNmeFEK8QqLkkKrJbFqqj9K4RqryV8Bq+tTVaVG
        cieKO6sy54xk3A7pQhWR7czxKgmZGHO+AMrrm0pxcn937PTJyUsDVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:34:42Z"
  mac: ENC[AES256_GCM,data:8/OzJBb5i1Jgp0MZZlA8FKBx8C1ZcP6aEUCSYkhHrCRkik6DRfTA9bYw0Y6b1bwBY54zC27vzShDXIwQFtEi8fteakH2gQW3Mtbc8SInUrf2L3ZBGUrUfqLr1EZ7AwMI71uxpUHOfmChjIuz+V3zcBxrYN8VEAVZaTywXeebTRg=,iv:nefW42rb2wHzemSgifCaoLYBJjjYIdiQu2MddePEz40=,tag:UZNUiBmGEEzLHZSzdSV4KA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
