---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./proxmox.yaml
  - ./homeassistant.yaml
  - ./truenas.yaml
  - ./gpu-docker.yaml
  - ./monitoring.yaml
