---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-services
resources:
  - ./docker-gpu.yaml
  - ./homeassistant.yaml
  - ./proxmox-nucleus.yaml
  - ./truenas.yaml
  - ./idrac.yaml
  - ./pifour.yaml
components:
  - ../../flux/components/namespace
