apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:3mKPMmgQEeMRQO+lVA==,iv:l7qXGTENccteR3Tg5gyNZWOTg9opJ1DXtuw4oETc9II=,tag:x+K1OQB21eLlO6DsA+dOWg==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQWtyZmJTdnJjU1IwM0lW
        bXFsY3ljaGJ6SjdiK2l6N0xSeXY4Ykw3VXo4CkpvNVJXRmFzSnVVWVRVTSsrVFIw
        WGRyYWY3cVNrNlZ6dVh5SGxSSUxzd0EKLS0tIFZFSFhSVkZLUkU5UWpRNVBEb2tI
        Vy9jSytBQmhvSll5UjVKVGlxcWhXVEEKUGzapvHmWejSvy2xu29fuApNLrxd3PhG
        eyNxnIw431v/UI0vXg8Fncuh/GLiN7GmjdyItDAEjkAVm97Cr7mQhw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb080WFpHMGR0dVVzNFNv
        MGFJckdjVXJjdjFpVDFYbzNUUENtMEQ2TGlzCm1kdzJaRGFpQU5adE5xZ0FDNm9q
        ckR2dXB5eVdySTYySnB2Ri84ak5FaWsKLS0tIEo2MDFBQzJYZlFneS81akFpb3pq
        d0ZaZ1RXM01qNisyYWF1T1VpZnFCTWcKuZHOasjQ1/fNBjT8y7+Wzn2mB6Vzc68E
        pWB8clY1kLCeFZlaV+dvkDu+UnxkHdhG17vuZLkYe8ANHJ81+q4R2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:54:01Z"
  mac: ENC[AES256_GCM,data:TTDkiRQInjThdKxi4wBT3nUBQdSmtckb5BLOru9gQVuBdtw+BDRHyYT9Vu5ALrqBCoFXZVKbBx5rVofu/x/55Hu/Cm1oWAQTv3lqrLN6Nad58KuH6ddSy6adnE87HOb+jF5T68LhImz/MV2Tctg8PJ3A7KKJwy3HVJeHV5qfeUQ=,iv:TIj9p2jMwM60xgzwk1C8AZ1OUpAGTU4SpRnwMvQcBSA=,tag:Dp0Ksen3w7CqDSgWD638yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
