apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:3mKPMmgQEeMRQO+lVA==,iv:l7qXGTENccteR3Tg5gyNZWOTg9opJ1DXtuw4oETc9II=,tag:x+K1OQB21eLlO6DsA+dOWg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb1Zxajl3UTV1MkZXVHhI
        K1NLbU1GYXNsUThGc29LSHF6UDFiK01KYjFFCkI1YitaalNyS0tqQ3lJNHczSWll
        bm5ONkdNcHFFSTBvNWhkTENLbTdTOWcKLS0tIFVaek9TeSs3ZFZUaEt4NHpVbTMw
        bFJXYSt2OFJvTUFFd1FJMDdkREc2M2sKBmTRV9a8TD+3+kBbr6l37HpCy+nZheKG
        8TkHaAEaDshK+sdDbNiW94ohJCGKcd0ihChe4Q5/Nt/bICGIo/gyYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:54:01Z"
  mac: ENC[AES256_GCM,data:TTDkiRQInjThdKxi4wBT3nUBQdSmtckb5BLOru9gQVuBdtw+BDRHyYT9Vu5ALrqBCoFXZVKbBx5rVofu/x/55Hu/Cm1oWAQTv3lqrLN6Nad58KuH6ddSy6adnE87HOb+jF5T68LhImz/MV2Tctg8PJ3A7KKJwy3HVJeHV5qfeUQ=,iv:TIj9p2jMwM60xgzwk1C8AZ1OUpAGTU4SpRnwMvQcBSA=,tag:Dp0Ksen3w7CqDSgWD638yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
