apiVersion: v1
kind: Secret
metadata:
  name: plausible-employee-hub-reader-secret
type: Opaque
stringData:
  PLAUSIBLE_READER_PASSWORD: ENC[AES256_GCM,data:TYsjfgZ+cYBY8bX1yn1WZA8jr/unIFxDaKMRV7LGQQOCF8P2coI8ptQwlQB5xmHPU1TZN/LPzCapr5RFfYQFrw==,iv:gnvLoE0PlyV5ATnLFk4jG9QPb+59lxkZ8mkkuv+tFhI=,tag:ZzPB72ppcONvTjiv17KvHA==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aVl0SnF4WUhKNXZJcGJ4
        azVoRytWbmMvNk11OC9pSEI2dzhWTnN2Y1RvCnMyT281RkN0c2ZGbitxdlpMZDI3
        UG9DekdtbTYwMlJOZHFrcDlKNXcrQ2sKLS0tIGdsZDZ2cXdvbjRYMnFKaUNkOWNE
        a01naHdxV2ZuK29jOEpYTFpqNjFJSW8K9MXrslQj+bRGdL//p3/FgfGc00OttiV4
        EV9FGDM0jSp8FME25mHZi0btUEWovfrfP2BIE1A9SqKQqPo7MmFXMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-25T15:54:17Z"
  mac: ENC[AES256_GCM,data:Qj/m0XgmSqAib2R/uo19U2qUYnS1BC6fTKZgxKN/GtzvyAxEQDIusLnJJbL8zNDwx3P8zJR9P+PbLSc+JdFUGt9oS58IuOZbPuTTcU3YU+Q4Qi1KVqoBvro0y2J7bA8Zk15oLy7xHew9pSmSmF7TMuEqyPDgYwS3Q2iWgtjpSF4=,iv:5+RVkcJnwa+G9QB7weMsJQe67IOOmJFslc9aCoLK6r4=,tag:OsqjYiD2zBtqDIqEFSF+0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
