apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Iytlroltwi3pZ0j71w6CWPaUDm9yY95c8/N+GEedv59er8Jt,iv:6YFkSyG+V1JrBZ5zEbxEyE4+y8/cALCY1R+L+VwvSk8=,tag:6ffAS0n5fcTlb9TtrsNWpQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:6OwgmZf7ipb46jaGnks6ohhMTG71gkTDcUplie5B+cH1ERBhFKrswhe5II8QgVK8yjo/CF0zfu4Wko3P5lupZmDIcNR61awvlHOtRm4VjyyrRVmb9tzCBTTcAd58IMYO8uDCmMeoB1XJbnPBaQJ2dYF9HXBOdOgfnOQGvf0tcYfQxsabu3mvO45Y8+bM5sbqtM8DptqZoziDs7aclRQu0eOeA8dXPKHpH9s9kf9NCg==,iv:xHqcVPk6QVUCc7hgcDzPeYhB0w3H+jhxTAPJUuPcDzU=,tag:Vg7W7kNuLpPE9N8GuKO0Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOXhpdDdtZHRFR3VhaVVS
            d041YWlOLytIdjJ5WkJJSVZpK0d1SlcyelJVClBpMmxUUzNFdEdKU1puM1ppTzY5
            eUJFMUhVZUhuWUNzeUorSytLclZaejQKLS0tIDRqMHg4MHZuMFdHRkhzNUZGMFg5
            eVc2cmFDMWxCZlNDVU5FS3pvalo4QXMKPMB2/e0MyZeRoMhaMtDUy2hQbuw3n7Ba
            NqhdFW9HSZBLHvcRBSrirBrJaLkgD0wIozBvf9jG1oRLUVQwzVqFlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T01:56:23Z"
    mac: ENC[AES256_GCM,data:V+F12omVmGdCUHGQAZTJNFmsp783x9pygz8r8keaYxuEZ8x2GTm4v79xLrXb/1QfO8yEwPeUK8Ha9ftJ3OivbsSh0IBl6tfYyCir4+TlnRzqfnexqCstfG0MBVECWTQfCoDq9KYOZh0KujxYVrNk4Et6Iv3yw7fUbXqTLrv6pOY=,iv:WPGZPjNYnnIvtM4PHPTxpTCbLZSeFttxawn10K4ayyk=,tag:h+PtH3cl0mDoe66IqmCx6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
