apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ErA2XOmxluUuwOF8BeL6iyO894eW72IAxMHcxVdJLc2ZB2a7,iv:fmOrYn+1G1oYdbqVBETSUlqg6Kx21q/XxZnh+HikHeY=,tag:rVVr3UMu4wNmJDCUx6KFrg==,type:str]
    credentials.json: ENC[AES256_GCM,data:0rIxkM5HBpFPTJfNrEVuxuMyvcejG0dSY+VwMeokg4Wj4UoujYmPlgPStROu/Rh0KlLNNOnsffXlbAcRTDus0POL0EKUuv02lUKzw9MquoGLVT/SxWo6jGUw4A+MlVpLKV97F4lhuhtSm2jByMcPpo1gQs6s4A7jDL1gvRlO1yZ8uAMMxWXnSGc/yVJ42fbmTc6kAAXC8NemsbQlhGy56DNpsTqzPHCj3mg/4as6,iv:7P7+SNE/bWHgdQZMTHh7gF1do+IrLqcZn1tcYy8ozHM=,tag:5bNjZwxSEXWvmLJgR/669Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMnl5dmczTStXRml0SzBJ
            a25MWkhXa0J0WWsrWUtVYktNZEZtNklJU0ZNCjdkMlU1LzFYcGg2TEFWQjNDL1Ex
            UXhrUzNKZ2FpZWhHNUwvN0lnOU5JamcKLS0tIFBrMFViN05DZmk4SzdsazJrWnl6
            bG9TVDJxRlZaMVJDOHdvTDdNVWdRelEK3pd2fxi5P7JL4cvXPYh4j0fDAshr6jIe
            jvPi6piGaIUlSu3bcnP/aVNqSJCFWIwrwxRjuy6ZK6ufZUdUeDRhkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T23:22:16Z"
    mac: ENC[AES256_GCM,data:3+K8xzAV7/n/2W7Pl/CI/NlfDbMFrU2QFTt3E6Fpwhs0v5GUPp9Q8xnH6dCbze/UuNunblEB8063G00ED3GYGlwWTBrr62Frb77rk2Xg1cQJhid2u/R7UBUyCnqd4zsHn+39AJPyEFcIi79snhrF3ma2qLwMPeptXDj9gxrF34w=,iv:2z//5vgApWOaECqi8k78DaRkcQ9ShKWtl0SX93DIhco=,tag:96MpQTQeHi0MYNPvDFGgqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
