apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:JGXoZT1QMSAjJAI+3fd3XF6jC1Pt9zxE4RraNK+fyrqrGRSQ,iv:0C7GGOdNd4PK1A4Jw6mK5HKyHNLh/m7OZRRs9ILM84o=,tag:518E56Cg7hViUZGLxgYhTw==,type:str]
    credentials.json: ENC[AES256_GCM,data:UZXgV363slSpIlTXO/gKDOYtqAU9nHSahRYaJqaD78yKqSGlW0BZi5pzQPbGW7/4PyYT37zlBZ83a8YSOuovUSpNo0FxytwIQwnD2UMQ8ilG9oFr2ptPIgXqUJF9lbQW3ZJXHRXDotX7mBDmgC+y9nDenuRhiJOg8DmXMHbrouk/uKaCHZPNeQ9c78qm7/9vQfhGCIA0mRluAyHAP4ZtECYv88r0Cu8KAwuxdHGe,iv:tUlSa0OYF2mooARsO2QwfHE/CyjvpwSkDWCw3cXzDR4=,tag:G8OP1Zx0d+i8j6o8LkDSGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYTlaTUtHeTl2TVhyMjZH
            ZVE5UXlrSVBMQ0VOVi9YS0pQVGU5a3lhN244CjdveUswc2srMDFtQ08zb2wyNzVx
            OUpPaHVjTjArQXJmMzhFZUZyQ2I1d3cKLS0tIGRlUEhuNW9mSEpPZURER014K2cy
            NEtpQWg0OEFtd2RnUUlxV1JKWFpRVVEK+gXRQgxWMIjkSFtWY8iX+6iYDbdx0kNb
            HBAAW++Z00dvznfrjVi4G1x6IPuryUNbo3ZZMVD5JXw3F432i3mAxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T19:14:32Z"
    mac: ENC[AES256_GCM,data:6DlTOhy/nGFgzybhtJbZ57jqa9z1xpONsuigbjL/OgxLH3JweQURwKjxGUNH3EMkJjEQIjzDanw+Fmup1M09cDI4JowjbX+4hfRnsJpncyNG2Wm3EUBmiZLWbo+SQJkhO3mcvF5lL0cihBH+HXh6iE+QWc23ya/xHjX26uNUOCQ=,iv:oCrjEXSEsa2igGcIdVmUyd/yzVIvdTC3yjLZLekhNog=,tag:u6kW7hF8CzYaIfNfRCOL8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
