---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "${BOOTSTRAP_CLOUDFLARE_DOMAIN}"
  SECRET_CLOUDFLARE_EMAIL: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  SECRET_CLOUDFLARE_TUNNEL_ID: "${BOOTSTRAP_CLOUDFLARE_TUNNEL_ID}"
  MARIADB_ROOT_PASSWORD: "${ROOT_PASSWORD}"
  PTERODACTYL_MARIADB_PASSWORD: "${ROOT_PASSWORD}"
  TRUENAS_IP: "${SERVICES_EXTERNAL_TRUENAS_IP}"
  PROXMOX_IP: "${SERVICES_EXTERNAL_PROXMOX_IP}"
  PTERODACTYL_DAEMON_IP: "${SERVICES_EXTERNAL_PDAEMON_IP}"
  ROUTER_IP: "${SERVICES_EXTERNAL_ROUTER_IP}"
  TIMEZONE: "${BOOTSTRAP_TIMEZONE}"
