apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:2THcV0SuLg6/e1qbXRirAnBC/Z9QnM3WKyYhbTmgmruTzv68TIG1aw==,iv:r74sDqwC5/dZGmNebXMN7QKvSFroV0ZufQsXjeh8sWM=,tag:Mn1mh7l9KuvZQJeqeuTMSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdVpMUHA2UlhpT3NLQ2Vv
            czVyNmwwd3BEYTR1ai9RZlNaRWk0bzFqVVgwCnFOMVZkSk5XdXluRE5VQkc2V3I4
            cDdSL09JemUxMjUySktHTUo1Q3hVR28KLS0tIGg5M3J2am1xbldwT1hLRi9qMXRx
            MUVJY21lUGVIR05Ga01GRjVDRDBkVXMKBaFWMvgXNkfUCCRPn0y6cro6IAf0SIex
            Y4VL5SuTq63AbiR3QEGU5iDfMcxX/vkrMhV94AOZ+Gph7GxyNebGxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T21:42:11Z"
    mac: ENC[AES256_GCM,data:OBbM3xSyfVurUgWrJmECBjRRHyRP6m3ncyvkFLmAHvgzDjJ9jb7DF5wze0njV6isH1ulKPtcP1u3u30sC6XKtyIx+VqkDN7tNDjrj3IVAUIa3G4SJ0H25j7pZV7ktsxb1ppxfQvES+fW0os8aNVYGyrW2TjZ0iHxDDQiB8mazbo=,iv:FXc6fqtU4fdTjmJtMydzNsEzAmsBV2U11nU6n/eUCoc=,tag:ywrSBqp5aOFp7IVUIBMljw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
