apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:rOTADtny7Nhiw1uQNyc6LoRJDTieJ06Wp4BDUfun+48EY7K7FsPQqg==,iv:sxnrwpoBPWbOxGwFNTbDRR+Wxfoiy/OBw5t2WZkSixs=,tag:xyLSa9e/Qzvjg/5M0bJo9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VmlnMDlSVzRjRTVsTjQ5
            WmlBV0psYTJqOXo1QkR4eTl0WXlyL2VlSjFjCjJQVUJjOHhPRmhaNGQ4eTFtRUdx
            T2tCM1NjdnUwZ1djZkExbVE1WS9aYmMKLS0tIERobC8xdEpiWnFEYmJKRmVYb3U0
            bkJwcVU0M2FoTmhyLzB3eDF0cWpNZlkKlk0yFKChLDXRnunTlYdksaUuOX2Gm5UG
            XZf9WxMcAAOOwjG2Z23AFlKNTXWGEfuMtMD8bytotSLsHXhCaezR1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T00:50:42Z"
    mac: ENC[AES256_GCM,data:X5a2f5zJdS+F3AOIgQdDZjOb39A0lcQjam50mKnUUa7DQQahjOeOgXSnvdmi3sXURh4LrgYGpvpBqS0PTRnAI/yP+jIt9SoDiboALQHiXLQhs08SJerIU81/9JEYMqc+EgZa7++f/WFv14CFWAk6KlVvNTirbGnpCXxF7IJiW68=,iv:R1agNowCb1cXe8aIMcK8sJn1n6HCtb+ttUF3N0qHHHA=,tag:xc1kLWx+KoXbvv/QEhw9JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
