apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:byiRCEuoayNmKuAPq/8saiyP6I1s+4WII/eFg7EIrO6u7aaP40UORg==,iv:FtPLCd/7Zj5Gt7sF/o47SVI5nmV8qqP5Qwx5xXHrtzo=,tag:eTBr6q+wJo1SwR9Uv95Ucg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZStzN1BOazVBSXNrUzA0
            Ry9iRTJmNTNGVlhsaXRjWmQ5cHg5VTMrUFdvCnZzcXBiaERzN3p0bVR2VVlCYVlH
            Tm4wM0ppR1UzSWpFSkJZZFl2TmNoVVUKLS0tIHdybTBVbWd4NEdTVlJaemNtd1RR
            MlFOUW81MkVUOUlpSWRnN0UzR3ZFek0K/NJvoBgqFfei2lHda/l8/rvlFS49bpk/
            xO6lrMGs7JBAbnb/6KiczTQl0eXQ8f7bTCu+Xz7NUF1zHne8WCi6tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T20:55:22Z"
    mac: ENC[AES256_GCM,data:xuSpWDsm+RVpG/12kMmvi17EkQ/Oq9EUWAkSKN6pb1ExbkLIYI41i9lM1PQ5n9MQRXqwxG1InGtrarKq6105PQRvXlYYsu0U0cFpHfzskttMpQEop2/7ZtHfPm+AL1F8g4qOFQhTiivx57p7Mg01qaZF7ugKxrWJHl6hk55Wdx0=,iv:MhtH3GfiHPU/L3RG/W1Ea5kXdzH8I5SLjOIwJAit3B8=,tag:vDa2DmXABSKyanf3eJunrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
