apiVersion: v1
kind: Secret
metadata:
    name: speedtest-secret
    namespace: default
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:ZuP/3C+J8vz123eUx/BIvkZg5h5w9UUfObLpgGnj/mc/nHVcLpy/,iv:B7YdnYXnrr5BvqLJLIDB58nIL9z54zgBFgyQh238yXE=,tag:dMRwS8tj3zzoHIJt0vxF9Q==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:tZdEs9cpQX5p,iv:Tv3YQow+YeqTpud1P7qJdyjJ36Y3ofW5S570PWw4J0Y=,tag:mz3tOs5V1Q2Xhf7krtfvtg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:FkuGN6xiDqgb,iv:ktULDyBb+BV1Q72Ab6gOAu8WmsZQjkX1553UjdGgH04=,tag:4DSxrOwUN2hLW+Klr/TeQQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:yChUAYtDZ8J0pN9cyyA=,iv:L/6tdaCFWB6OhURT4LSZGd4fPp46oJbOW+BHIHZ298U=,tag:plQB4oSjxmyEZBDbfqhEHA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:IU1k+10L+3yw,iv:MEHAZaRxyIFLXKEZdx9DwfFoPVmcxLgDAd3GMPq7QMY=,tag:4nhAYbtzCH8AxzrJC6kyNQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4/hDu/4Yo0VnYWixaq6SrZIBzdKXOpwGvveatvgrVTw5TezhPc/J,iv:8GxeK0iZ2cfHxQL3rYMPILShbPgMCDd6eqCSn3Oj4+E=,tag:qHtRGr/P9jYqOPY/yjP63g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Ou++1l2gm6/2,iv:hNrQdjaZl91S8xM936MixJOkWfa5/Q1mSeVBUpQekdc=,tag:OZ7UV1lZAIT7qRUw2cCCLw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Pc3WVDD2eq84QHRXO/k=,iv:/MlJdqAJtLPno+d5zqDIQZTl6bmy0yycpw6EycaJY+Q=,tag:wsQW16/Vi0EALIybRY7m0A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:izUD2d0p1ZnNwI5dAIs=,iv:hNsxQDvD1vcr+lHcFqNV6Se6Mcaz2rXdSzphjNbU0oc=,tag:j/mvQQNpqYDCealpbjbH2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQUVvUk5NL3pxVzFxZ3hX
            NG9Cb1FoN2thNVVscWRLVXc2T0c0dE9CbzNNCmxzVDBwZFNCSHlNdjAzN1Fwdk1p
            YzhlbWJmZFQzWlg1ditoTFFIVVlTM00KLS0tIHBLMjVicFVoNXZLcFhmMlZyVEYw
            QTNhVlFsODVZQUpQZFRMOFJIWDhrTW8Kj/zkIDJg37XoFu8SicQpRBqIetyF4gy9
            5mNrd9iul7stX/VFLQywzJY0REqLYRxFPgG7b5DqD6DOHWvjQKPp3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-19T22:22:04Z"
    mac: ENC[AES256_GCM,data:MvYVAdKh4kD4RU6n/elPEahTM0Wi6OgIrOywpx8r0DXrdtBKJwhFx5redb6WWZQX8sIft/eNk8ZujVggjl+t/4xar83hSYFL211cslG0n4eI5lBvDiIbYZfteLW+tVfCYUOeixxHM9E2yjevbLjmSkl+NX3GXxmghxh2maWfIJI=,iv:mmrHY/a45LCn1vEz90wq//VUQ6ZiMYoXj1kJeWQZbxg=,tag:HBGl+13RMcSGuJKPARlhEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
