apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: default
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:aoO+kaQDl34/BU/WY8A4y24=,iv:dx5aOmu3bL7GCeasLHFXyhgo3ctk6EpcIKb7C0PXMgc=,tag:+59I/WlfMwXBG8BqkLCbqg==,type:str]
    client_secret: ENC[AES256_GCM,data:mDO1EpTwDLKhzP49ftorUpGLpWbWfO/a8kGa68Iv8Qrpw3OsufIKY5EzK+uPECIektlwz2V8kqHON3Le+nWp8Q==,iv:eLdQgxUfAqD+3//NygOsHLOPgBldgbHBshMKyOvWQDM=,tag:u9QrYxqoOkcN/3Ysk9zdxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T17:29:35Z"
    mac: ENC[AES256_GCM,data:sn4GwGKmk9LakA/LYBfQJzJrzmLS4396RhoTWbdiR0kNgPiSRESCwk1EatT5OzQfhLFh3CT75Wbi0oMz+EeWaZJSpDhoL8k8+RqcdAVDB9aOf8F8YRBABd6rXsabLIrDAG02Krr1Ag0uAYvEqZJ1GhRANR9FtbgBBe/UAPqs5D4=,iv:uFAlecsjmQYSfJBdj2BClmLLNuC88MWDa5CKo1PLrmY=,tag:Al2lQM1Ot5MX+xsCxs/twA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
