apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secrets
    namespace: default
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:1kXqYWVAnzzVUMeipPfPtXjlTPo2zZOLbA1CCGWjL64rNkfZ4s5LofKUn6PlfFJcsCD74QYaqEJp2Q3GnLutXzietfXhSHYZNk3ukELfKLv8M7yy4fyJAbyN+h0+tgiiA4C9pBLiDGcUYzhJkyTvvmDfbqHoXg==,iv:DrQDx7UP+U1E8C/kkMiD6yrXptwA+mK9Txy21T4CODU=,tag:9jgPYD8KAFvQj5uU0tY5Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T17:25:15Z"
    mac: ENC[AES256_GCM,data:Rg8ODJTHaERMwJT2gsSUBjQwlvJ+VHLByTo7wmqPlAYeqVEyZo5ewbl5rk/U8tBuncMWOsqkgxI4MN5g2eQ/osBK5NN6oBma35XvjzqM2vc9r9lcCpDydUI33kmNqCdfsF3GJJCg+grAkH69EAe0boXg3CsZDl1Q/+5BTTAP1mA=,iv:rkWhh3au183HxEtz6RsIYPyrdWnD4IN7CgktHIl5aDk=,tag:MOej+FsEw0wvmhHqPkQDTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
