apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secrets
    namespace: default
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:rrSMQGkAExOjt8V3tcEdYGA=,iv:UnCgnIqZysnrAJrHSTll9Vr7i6Ezb1tPIlL7t6B7TO8=,tag:2masDNMycZVXvl/GX62GHQ==,type:str]
    client_secret: ENC[AES256_GCM,data:sZ8Hoy9d0ho2oU14iKHh6g7gaWHy0bH1IRuoLTkmPa5aKOn4I3v3oNjy7SkDvhpx9v9Rf2R7WsIiclbx9L0rLQ==,iv:XXfDlh2SlVpFXnh1C1Bvssc/eU7HI77OykGjQ0uN7rQ=,tag:AU5tUvprRksAi4ZUZFBKww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T17:23:26Z"
    mac: ENC[AES256_GCM,data:AmrLS1Mx4Xs0pJ88KD6VrE7XCh+QEUGP2pMIft84rZhmO0tc3W5w7iUxSCfo5GM/W6ZcceTGimAxqhlZ5QCuYGU1ILpL3hKePiRqKl9wP0C0UUd4qcuZKWhel+Vvvl8lHu/U2ZebiQbgye0cDMzoHia3Br+TOKP98ovOPdbXQzo=,iv:BAr2U0lnqqcVQ5lkNgBucKa82kMRE45EfC04+70yKzA=,tag:Qy9F8FcgIGYkDaV/BQZehg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
