apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-users
  namespace: databases
data:
  users.xml: ENC[AES256_GCM,data:TuB83Eb9RHEv+1C87/q1O9fYJzkjAa4wLXM9GuIsVUSPRqOvvZ/cdTsUj4hGwMlNsVKEgh7vlHbMaboWWRRGXy3DzrA4X5jcd8K6aK1ltM10KfHBt5c82YqGMUHnWZbVW7sRyY52EjKEASNXenEq+vchVNp7zhRN0fvvMrT42EF7eNfX87+VDGmQURQ1cpupsGmW2ukZNJD4sH1fnNAExBoawtyBFwFPeSuq6rXZbl7+4ZASSCrmUrKExfZqtPDzRwu/vMdIylTzmLO5fE/DrcYzItTe38qAXpIEaLI9BaKZN8Y0st2OvxB4Rlu7aHeF541pdQ8BSd9+4YSbHmlguAbPLZh9CPfbMkvC4AzChE4GB2E0KFXY/KhHGlysDlhoCtQdc80SwyBZK+fM0aqS+yuc058VIgJ3Ffj6vJz/G9Tq92/8cpzAWWA83qNEFrCfxlB9MDucFsGs/EyMt095PENaCHUFSG86siKYZ2Nu33PYWzBJj3TmsXTn+7OuYeEWONtWf5+61o3t50uO3OsOlcnceciY/vs=,iv:AyCpuhGzqh5jSgeG7S1YL8YFpt49nFhP2FTjoNHTn1A=,tag:xRMOXfIhP2zs2P2YiLrs1Q==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZXBkMGdPWTJFSXRIN3pG
        V3hLRjJnVjNITXVLbE1mcVlYSG5jNDBqakFjCmdjYXdUcUJxV1pXWkZEQ29QalM5
        bTV6ZitxaUtiWisrR0xwN0V3NUJzWEEKLS0tIEhWN3FTZ1I0OVhwWU9SbVRyZ0N4
        dnphYWhhZWg0R0E2S09JaTlJRVdaVnMKCXqKdR0r2KrE0wa1nVAiUhfXD6ph92Up
        oJKvvWWTxZUnTJRVXQhbUaO8h0+J0iZcHYGW6eYXNGfQOVinjDt1bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-09T14:55:45Z"
  mac: ENC[AES256_GCM,data:gLlzgKrisK7J5iEIX9lZJR5gC5buUKvPnpG54QVxlC4Q8hmq2wUT9Z2jwwFk+dj0G1HMblOlVnuH5o+1wgG9lPMuNbzlnhjJ+hyhBh55NVyKmTrn1JBq0RiTJoavghYrtv4uMatqo9KurmYJcDl4z7B8UEmokkzw+jHGcsslUyM=,iv:uHz99+epO3A4fyF1zprvpquuS+P2Frwr0+yEWP6adYk=,tag:ZO1O8yuGEg7ZAB8BJdPhug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.13.3
