---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: prometheus-davidapps-cluster-config
    files:
      - config.yml=./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true
