apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: default
type: Opaque
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:bvnsin9R,iv:swzfDfv9axr3cknKrU2qXNhVUeqqhBwWob2VVXs37Io=,tag:ssbUXdEGEa1XzbxjXodchQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:F2ERgRM7T11HKEMxAg3Zu3JyZyXKhmvLmgcMei4vKZ77yIJ84HHD,iv:0xiLM46EggsvJJX9Xvddo0+0wFeg6ZTgJC/j8n2YQRQ=,tag:19Kp3x+DuXnhg6I4i0STug==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:WVnGWv67coL+7+cJ2Bw=,iv:6dw/WLV4H+K19NOEzCn49u/LrZH7j3nz2W7COK4iB78=,tag:TTwBCOuC551+Ub9YzLt6Nw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:J4yLQhbX,iv:Pkbwzz+akgaOvmjVWHJ5J6QeG74xxgLP+CnJQ1QWteQ=,tag:RLjtJdUvi4J17sYkQ3QSdg==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:6H/4yF6otnhUv742TOjk4zPMv00MmMjtWULalBTag+TaCz+z1qXMYqmB34w=,iv:g51UJ9frlI08eevgRVfT6F3gDTO/YfDK81aXVZLiWYA=,tag:KnCZy+YEgIMn1ZlUIV+HVQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Sqb0OzkDWDJAl3c70HO7NikVvr9LMlDw3BFZ7O3pry4bZbCHzRWRyJcAr+E=,iv:uzAi1oD3otJJHPjUTkkz3iHfvCTyEHy5bsayk0hIK54=,tag:FnTUM6kgJ0fLXlkeMoZKRA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:utHmbuftpw/9FQ+W9qug7RYAil7FIuTmnLCZZ/aQ3Ig47nRgf1B/,iv:C+SuRrubztnWWa7SPyWbbdCi4W61Cnn4U+mIBWg4Mzk=,tag:gOh88Pc+8MvX5rwLvSUWeg==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:iRAp2Sc=,iv:G7NFtvCVN/Oxh64XG6I5VpKzal7zO1DA6e3oneDFowY=,tag:iZDLVrmmCa8uMfWv5sptTw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mamLvCJXO2NHPWjdzDo=,iv:iakBRW/DP4bDgnGjisO1QSZwewe2CRs5XX9PRqoWY9c=,tag:hWgIYyDNhZ50oO4jvNGLHQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:hXC+dfw8,iv:BnP654gbQHMgTSXpamLb3B2+PdbvD9iWMf1P1qYN0N4=,tag:83jkZX6NjPyDub0f0/YcUg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:JsS+VLIf3C97DMDHtBc=,iv:ZRWZB9SV002DICiRtXItcibFNL/g9zlxQAfFNT7opcs=,tag:OJYXjT7Hc8m6JDDsXzIjLQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2oScaqGn,iv:Z18Qz6tr+t0owSdSTGvL+mkc9Ya74JSNUgqs64n8/YU=,tag:k8Kaj7WRBOqoY0fZUaga4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R1hkVkppMHNrNHVGTTJz
            L0JLRk1aeFEzbGxYSkZYQmFqZXV2MUovc0NBCmxFU08ydlZmTWx4cCtrMVpQTkNT
            aVhTa3VpRVJrNVBFTnJsSS9FTDMxR1UKLS0tIHRFMTYvUUpkaUtkcHdBdDRXVTNO
            OGJrQkh6RzcySFpXV3dhSTZVRVU1RHcKnbzpR+L3ZfeLD55chcysfXUrmiigXwIQ
            aqxFVtTem0CibeKBrW37rjmKsY8drbuypyxCAGoVjVNOP0FQlg78PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-19T22:36:35Z"
    mac: ENC[AES256_GCM,data:hhTLH+gIBc1l6vCIBmC0Dlul/zYxBP7SgmotIu+fueNMDYbrt15fgrSlrGO9NgAFebjRsSNW+jhsOteNtM/2KGNOBe9yWU1BZazTQilkIaV7DtgtSKEWyuoWkW5V2+0wcoeGP8gE0UFWqxRuAe6wo4vgaUWfgz8cAQWByf5kg08=,iv:LwgcCBb2J5It7xUp2PoSUvBk4voi9XwO2GZpQJz6GZg=,tag:uJLczjOhffDGQVHOEuYdQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
