apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:7L6U0jQ=,iv:c1z1lNg+3X3gOBPzGitwv8Ms5e4c/8RCWCV4iTHzUA4=,tag:fCkBVMKaGHgO4NIcW9vYjQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:66RbNx37+0izy8x3mgo=,iv:Nuz0zS5oyYjQh73n1PTHH6YrZOKD8vaLsM2NdjJ2zks=,tag:eIATCWTftjmArznCAiarYg==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:Ut1rC+tncSWN,iv:9hw9E34r3ZbYjVRnC1BhfafjhGDoay7GoIWZ6dgbC0M=,tag:uBIw+QoGoj8OpuCuLCKV4w==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:VfXRnMrCKHPq,iv:mzAqZtWJCsHMlU6yqxiVTTRuRzeULguy7fJ5893Xp8E=,tag:hFy/IOUK2LTBjrzlJi5FcA==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:EHU=,iv:GDhEIpcNHdPp685w+tZkN/cqxb7NJVXqsNYeP0mtZgk=,tag:7Mv26p320bwXfNKFLWc9YQ==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:Yt8j1GpNMsaQ/X7Bl5yyESkQ2nCtjwXyibJcrCXw04K/TXJYHtT3VydVwzV1sRN+t/W4+cK5hGLUMPVWCWzLcBSxbtHV2rnOGtc4Q1pI,iv:BERv+dXK8W8I2AvdOMNRfSgjuFdfaN2sbSMDX4QSfw4=,tag:JQcBajZM5yhC8cwILO5VSw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/KtoOx9wNp3Nhzu0OVD6Fgchc1Ywx2hatDS/QEJYYDgmPHFFEZuk,iv:OOKWNccLM4aSmSJ9kqtClcC0Dg+rABOwV8VyHFCz2Yg=,tag:FBQixV1V68064vnikDrS7w==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:nFfCSWY=,iv:5U8F1Gyj2qV9aFlY1qMldx8avUQFq5O0kDyoSbCSo7Q=,tag:HumfAvc4WdbQ7PzbUVEtwg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:EO7nyzkhGtwWuGJngMg=,iv:mMBo1GpO9fYANTqzuhnyQmV9DZmIcitVO4fs4dvCVpQ=,tag:fIi0+AYkdaW2yaHrDL5JeA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:cQIcag==,iv:S7Z140YwMOQzXTry3P53KvxBxyU4Z+utCDVU5i+NmZ8=,tag:UlfFsh9LP8NENNGGv9qkjQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:uSO3amL7aoBvzPN6ZMQ=,iv:iyy69yTkfuVRBxblZNIjqzQIlvnejO0oEjXZpgdRdxE=,tag:T3r5loZ+tNW0/47uQ+naYw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:qv1O/Q==,iv:5qsyBc5myyVY2TRlhZdkieWgxSTGAkhrCuzbloDiAnM=,tag:AGpfjXmEbRce/8alJiosFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVDBKUDJVRVByaDBlcHdG
            OGgzSXNCNEdYbldFRHdybW44Z2JKdU1PMlZRClRDNi9lclZ0V0JPazNKMzR1Z09V
            bGFrSlBLaGVzRHRlUEx3WktYR2xuRWMKLS0tIDA0a1F3YlhkTkdJV2VGd0Mrd2VB
            QndWdjVmQ1BiSU5yajZ1R1l1MzBjVFkKV+7tIZ2TKVgG0ZBadiAeHsmIh8qd0FcF
            guylBVOXIEj7/LDeI+CS+ngIoPfNTmrUE9LjRofmZKFEPc8SvZP3rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T09:08:05Z"
    mac: ENC[AES256_GCM,data:W1GYzrAmF8AjSp7+soyhf7zgK/jIRYAva4wiC0H6IMdbhb+HFXZoFbM2LtVCmGzjzSshRim3xwFUiAakHaAbAUZCFlcqdhSWD6WIkiZacSW4Dvj88rmC9bl8VRE9eKvIsRv3fS9o3b5o6JTv0fWoorsIL+XiQsfStbwF6YROmaU=,iv:2Yosi+ANJX0+HZ2LvWOP++/IP2CG2XZB6WlkotY4pF0=,tag:1nBO0i5sHJC2hD7wzp0pvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
