apiVersion: v1
metadata:
    name: ghcr-io-creds
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ruHQ3NrFuNcOROEEUAXuY/FbmDIZpYg62jpesqcxZNuZWh26lrmxu/YvpNDtkMc/ig4lorKjrhSAESpO1e4qSPe3ZdNBShuOZRwHn53+9CnkzvbTyj5TYLHITWMzkTIaos5ShiXXbUe8mqeQI0YWA5jWUPh0/0HxjePrVGykO8h9ZQ7XqZf+og2dcdJYDuuMxp0tNhiq/Z2tCdgJmfa+WUcCMFXDVbyTQMJA0ppKM0fdVS/EG8DxSumVWdmTNkd4zIt7v/OHtIP+cOlJ6r7IqOFX3vJ8D5uKlEbCca4w08dgT8HLHqngDduI8Wej04PTjDou8/gddKsI0CKHrzfTm6JnmDdKKlwI8P1+VpSYST7MWJJay07CvQ==,iv:Ho4Ro4oYfc2Z4DJMmfqsE0lTYWtY9Gqa4U46tsWPgrs=,tag:u2t0jdG9+S2Hts+ND9C/zQ==,type:str]
kind: Secret
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2xIZ0tKTkFKa25YMG9I
            VTc0KzdLbU9KYkJoOHdiNGwwbFIzcmxHWVhrCldNRStvbUVqNmRZUmo1K1VsUjBZ
            dEVUQzYzVHNhajVkWXVLZ01EdXg3dTgKLS0tIDY2ZDcyYkF5dDJaQ29TdmRxQzRZ
            ZEUzclVETGpuMFN5Vm1LQXVRaHpHMUkKxRWMiUPu22AHkQa12VSXNc6qwIMyCVQu
            s4oXq966x35ZUEmP+9xQW9D3wc6GvUQpslZ7BConYQb/4FQGr/6XHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T21:16:48Z"
    mac: ENC[AES256_GCM,data:0BbS0ciEfc6ZMqVrir/gNe+sIix0aLpRdV/CMtbTyJLirEdB8+XhbenaopYUzDxJh1cT+QEY0FlQ9h4XJcMNo+GmUWzsuSy7RMG+m6Q51edNTDTxP1YLOlhCNKvEOTj9kwsB4OueBoFziqDRuZUU4ecZlIQp8Oy9IvVjCLK4hSw=,iv:LdnpQz0qjerPq6D0gknWWMV+O5HjzPyRSsa7Vtjkn4I=,tag:aYr4+fOGFkzrDksxwrVhKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
