apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
type: Opaque
stringData:
    LIDARR__POSTGRES_HOST: ENC[AES256_GCM,data:q0T/XCA3C2i56/r0tJ9xwaGq06ezzxBN2b5r3evRQMvNSHCkemdFrA==,iv:vbh3ipMdMrG9mNH2AA2afO5Xvkyo7Ozg8jOinx99uAs=,tag:mTNqhpqic9ogjz4C1CeRQg==,type:str]
    LIDARR__POSTGRES_PORT: ENC[AES256_GCM,data:qFn2Kw==,iv:3oSwWXmTgtohJPJ7hwNOeKatx5BVTjNu52OZHaihapY=,tag:hXR+kE1trRn/0HLcIUbVIw==,type:str]
    LIDARR__POSTGRES_USER: ENC[AES256_GCM,data:fPc5Z+Fq,iv:aA3+32yApl3KC2T2sy+YsELYZEqAaNn4wBwQHlVpv4c=,tag:QP2GJmTYTLZ329kVkQz46Q==,type:str]
    LIDARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:lJBX4wmQcgw=,iv:xsvHWLv9l+b6dOJX6PdEuBhVFfoxNuMNlpFEYlxZusM=,tag:Xp5glwuuBAulp5+TbY/8Tg==,type:str]
    LIDARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:HOiDU46VXJiJn8I=,iv:xt6Vy6ywFqbi8XUoLiF6mCXf3zVyvss7B2Olw5SN9ig=,tag:pB+FlPtcFHauDc9YSlp7OA==,type:str]
    LIDARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:A3Ud0Vzi4z97DA==,iv:7VKzW5lrTMFMG2G94oRA6VX6SpOwrIYmxRgx6VueCeg=,tag:XcJVrfslbcJaA+2ZInK+Vw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LEXrSY0/6Ui7uRnalGieI7BpUDrmWA==,iv:epla5C3la4LqN90zh1c+cSiHuMw/RErWcXl8JnXjgNU=,tag:iGWi8ZNxa+mQMqeeckFFag==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AgHkeJMUhDEjwNBbbG+LuDBcIeJlULM1bXilh9SKOphqpF+nmHSePQ==,iv:di+rLzaQJ4wzC+m84o9H9dJO043Izv69DpVNSrg3DXQ=,tag:OzPtURI0FA8lu8YMfyCBJA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:miDOLJv0,iv:vIcRtNP0hvPiBmagJY4DaMQ2WPz0fwADUKO4Zxl9awo=,tag:WcbIFl+yfquW5tI+/DShBw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T11:30:05Z"
    mac: ENC[AES256_GCM,data:itA92juFG32z3JVrSadoeMX+rgtgctF+TB8QBkvcg8q+fqvYSkU/grQZsWktuR4h1jozrAR5BdlVhw14QJSucOyFtCwRL9E4lfIIGkAGMUW3R06u3ouCK5Vd98yQXjqaW7g4DFmmnyubxWAFKS81uPrAwTuGbUol590Yj6FCC+w=,iv:6f4hYtut4/L+t16raOeMNw/6935dsPLvOSvFFeue6Kc=,tag:Z8KJ+Jq+ey20M650Up3jzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
