apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
    namespace: rook-ceph
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:EJSfh6O0V7lgoMrKuAE=,iv:bc8Em9or0Q1F6br7edYU2JEpJNVaPGxC4C0WDwndHDU=,tag:MuO9RH00RoL14N9s7bgJzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T03:45:55Z"
    mac: ENC[AES256_GCM,data:kw4iZkUBIzCkCkY2eR8tzGU7Tp0EnfxhKgvNdq0aQSMftWhMbLYRGoY7qwsv3rVXwoD2NiJvEYD0pVFNchPpPNbR/k1pO+v1GYwHK+MEjYt82dyBpj1IbFAEcpQUqx241CUsFuuNpVvvU5FE9owgMH++TSXh458LUpABUKz6gVI=,iv:td87xDT4GG2D1BArG932xuh2FkIdGl+uKfk5H5DcFk4=,tag:YNj4mOcqrm5/XiZgRxGzKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
