---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-v15
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: local-path
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
