apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:ldnN8fM=,iv:YCCrQwkUF+TnSg0e+qzTh72FS77B7byWJabgaPDkiyE=,tag:MMs8GF/Tf5gD6md9rAmQvQ==,type:str]
    password: ENC[AES256_GCM,data:ZHee13J+peRAdpOoBxo=,iv:zCaMvNn3D2Kg4XAphrS+AF9ACH4BEtLlt02hNLXsoJE=,tag:KtVGPfK4N7mDBa2R1StRlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK2NnblJwTS81SkJjOFRR
            eGp5QjZHd3Zha3QzU3pwRGdQZ01WbFlLVGw4Cm1tUmJEOTdENlFSdEFzSzJkaHRE
            cEdNZlpsTklDMmJBT1J2Ui8yK20vOUEKLS0tIG83ZmM5RStjZ2ZPVU9TRmxhOHBx
            QmtibVUvUDJsVm0vRlhpNTU4ZjhadWMKS/Ye1y6jT3SYYk7elz572+1EfOwN4Rr0
            E9PhNG/tKZNRUGHEOeKV+5xOPXYUjJFpbEyFJaq4z0q9VpBGwuZXZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T20:24:13Z"
    mac: ENC[AES256_GCM,data:JhtAdOe+k/EKrrSGAWUigJ9KO3i3n9V6iAkcM8eFjANWg2pza+JeY/8dKz88k/zDZT4ORuWcvSACRKtmlqpzxgiPquIP0X53Txq8pJdBZ82fbm9gP2SVLaUPRs1NaAw3+zKZfQbKox0qHNBi6Sr/r2hiDuytadmn8VZFVKRKBrQ=,iv:+MCN2nDqMCF1k9le0GX21slXafJPzmyx2cLULhi3l2g=,tag:E9baAHBA/F+I3LnzvM6Hyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
