apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-minio
    namespace: databases
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:4AHR3qg=,iv:WpcDEpRogEifC2HAYdI7LU5haL/QqTiqc7bV+BFlSJE=,tag:AV+0a3zDIVO0ZO3VoTrhuA==,type:str]
    aws-access-acces-key: ENC[AES256_GCM,data:Phq23PgtBpvMyjPEd8o=,iv:kfkv9VliHfT4Msoo+N1pq5RvZnXBGfYkV/JjS225LNY=,tag:UzDh+3urrudmoZi5+MUmhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydis5Z3huZk5GdHBPUmRS
            ZFhOWXpNOFpEa1JsM3lxS2xXd3krR3ppYWs0CkxNS1U2U3czTDIxV3dSN0hDcGFG
            VUpxb1R3V01CZDBPOXFjYUNpdzQ2b2sKLS0tIFIvWnlyeHBGOFBXY1BSc0gya3Rn
            d3lvcm1WTW5NVS9VU3lnMEtJc1RuMWMKVN7PrurjgftNigFzpgREk5OuLcJdvf/C
            5nbp42QyAb1X7RiYNgPWZL9aq2m6AsceBqGoSwzW5RL3+HzgVnpzRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T14:33:02Z"
    mac: ENC[AES256_GCM,data:nf7wbvjMmYkdjnokMr0i5p1FIKUZq/LEXjEhe0ONNMcMpPU27vkFhX6iBrvZrS2TqcIPNRdF9GnO+aktzkfpFw7jygolqOwVY/hc/7Tyw0Kv7fDCo58IXMUw7w9mXEU7+yQK5ZP7agmIeLle/n8VShYyGb2wOAFedlV+4nVKZZ0=,iv:bpKCcnIo9Nn+8gmczoOVlnbKXLGApUbnMbgRqQJ+Hdg=,tag:D36lC5a1Jubb72b+ydto3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
