---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres-lb
  namespace: databases
  annotations:
    coredns.io/hostname: postgres.davidapps.dev
    metallb.universe.tf/loadBalancerIPs: 192.168.100.102
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres
    role: primary
