apiVersion: v1
kind: Secret
metadata:
  name: seedyn-secret
  namespace: default
type: Opaque
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:wXvteQzkaDqrIGk5Lm0Cv2l0icx+iKYENOS2n00sRY9kJg1TDUi8SyIzqTA1H4aEtEZQSTsobZKlkQ8qirnxXg==,iv:0qY57xdk2gQ/7l1bWCSl16Yv1cd4LrcuaFMi8xtatkk=,tag:RePGdM04TJE2QJTgcw9Bhg==,type:str]
  AUTH_DAVIDAPPS_SECRET: ENC[AES256_GCM,data:kYywbYk+vyF/slA/SZsXgsWPLMeNwiJpQIG8ywrjaaJhp6Y8mzkn3QuVhA==,iv:N7wWjnFilg9V7MBLEGyxHYJJPa27ES/r0xPW5eU91Fg=,tag:QhwRgy5RXEp+6S7XZsIwuA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:hJ7WAzG3tE6K3t3W55SUphIQqM2YXzBuBzRdSwR08bOsD6Dv5QbE5/ODC3wcyI31FdoPuydpjUtbCRIEGXR4QXANETwx49P6ewJVKppypff1mrXYcwo1inMDURIdWDUNEA9hjCYUo/oEuQ8e4+2BeEqLGnhBrtM0lo4Im/psLMoknVY=,iv:8VD3XiPZohGoFJ45VQ68Oo/8jBoiI0Egb6EEYjy4SNo=,tag:pGRq7WvwUNSUmjMyqOIVfg==,type:str]
  MINIO_KEY_ID: ENC[AES256_GCM,data:yYnITbHgRjLlZNbW5HCDRu6Xaw==,iv:rpGOon794RrEFhmSUsgMiQWhwK10KTdj3IMA2U6tBFM=,tag:dwAR+pC1PGNS8WUg3FBUMQ==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:q85g2cd17z/46xqBtX/9ekBwGnQLmlUGtED/fYUGFAaHC2+NFc54laz1wA==,iv:5gYKxd6UEdxcWf45TdXR84nVCYQJiCjwl/B2FfR1UYs=,tag:W4UeaMAkaoTXHj8A2KcTvA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YBC1Gaau,iv:YNIIP4m0OiT9JW2zuUUq9eOA+H8pVW6J/6bJ+MTNd6M=,tag:IbpAlckoGI7pfbyBtUpFCg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+jWAbYaMLn7NUiLqIF8DFEdmP0L1//jSoGDzoSB75GB3i8pSucYXYVs=,iv:/U+UR4L8pOVZmgZnyz+uRAh/GeUSwTyCe6guFy0LuwM=,tag:iugXMXLTs9UFn6lvohGaIQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:gDo8Ghi6,iv:tX7l1igFZ0DxZPkkbW2Xw4dgik8SUcC+lGfDlE+z0wE=,tag:U935ufPW6DOsiaHZLZc9yA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:a6NxTw1NxjlvLXubywaUPYS08ir9xSS/v1zGPR/UG6jAadOctlUg2ppYdw==,iv:iVS4OwqbjB5jsHvKAcPFURY1wVhpGcFqw6vMcLzwibw=,tag:V6MAAo0dhv04WZXedAVMqw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2DbryAV9wxbP01z+daA=,iv:6dRp7IOAabV7QhiCb8WgDvwBQhAV2OXlzxrpO6x3H+0=,tag:wc+M+Q6uspnTffHZOotLlA==,type:str]
  AUTH_DAVIDAPPS_ID: ENC[AES256_GCM,data:DIVCUuM7XfDADCSyZDMj85gZ3WhhU4D4kkuPBFnY2Kw=,iv:SLyZ7FDTlullUzf8p/fzE2kflsluBfuTcSWPqdlU7uA=,tag:HXhd+QRl3Qq1hEw3Zr9gmw==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdnZmYUdyZHl0cHlkWnQ2
        UEtSNGMvSk0ySzhld1A2b3ZIeDZaeVg1c1E0CkNFM3dVQitVLzBwbTFZN3lzYkpp
        bGw5bElxNU8yZVNrMXRhM0FmREhsN1kKLS0tIFovRnArYnJDc3c2RWRyTmNYMWtv
        UUpRTXpSSnVpcGVBUFozajEzN1JpMWMKpviwQ2suoL4diAwl9gC/bOs54oRDzP0Q
        hfL7sa0OgsgfGifJr7ndGqdomXGShR0w+Y1jhTahgiyuWazqqAS+TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-19T10:53:36Z"
  mac: ENC[AES256_GCM,data:qg6lFNuI7DXMTWP5QcCsyyxO7MghWXcdtvTcUNn6VPxUFOaA/4Wt5zKRMwhZxYKdunfP4QgRaToEn968e+yemhTzmatcXUqKSWZvNKEwxr6HoGLR+OJsBIErlvVciu50o0S82zRSClxPA7RlojEJzSLIsBAOJEEMOcWjDq/b8wA=,iv:oKQcjTedhif3XUtjgyWwUGn5FdJSF5HuRqsoXYz3GN0=,tag:R3eg7Ho6lLSfxiIJv1axbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
