apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:SafxUQiwlap+g2JwSEheII5rb9KB7n/fq9TN9a/3uGBobg7mwWv7cA==,iv:sHZlSf67FZK/1HAeF7nKieuTHsQM3PhZt6qyNSGw8pg=,tag:YyVxzUthMxMuUK7OsrSfrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WHBxZm1pUDd4RXdhT1Vm
            Z01NTTBsdGhEV0FUQXpMWWRvNUx2blgzVngwCi9kRjdYdURyTk12Yi83eGI2VXlO
            d3NwL0QwVTZ2Z2lKbE5sVW1ZdEtteFEKLS0tIFZ2OG9MMk1jc0NEN0dTcFFIYnRl
            Mjgzd2lKTFVNTWpVOVRiem43T2pCT2sK4tytuh2fcIc6nAPmnSH7k08KdIUDnAvu
            2+jharjGk9rcaGzxK73T9gQkP0NpdBBmZjIOg0Z7U83DP5MPCFCgjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-11T20:12:55Z"
    mac: ENC[AES256_GCM,data:SMn2Q6WXY2OweCnTjqguVLg3zAJTHAA1La9dRZ7VMh2kZAxCG6xFTFq5H+0cFtVAwoCZrzDSJ8rJaFVBq017ePBmKcLKkBU2FDcC3vq8kNAz+KxYsliEnujQP7DuwegEhlTnCkc4pk4HeJ0+aum6iQdwtk6U9A/znn42SJHFRBM=,iv:MyNY73A5AafDsrAReI+OYQM6DrmlOpqmKwFLcgeZTHA=,tag:25PaZ5S3I7dJfJ7IIrdaeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
