apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:7qVQdDI/rL/3QFiahq7nO3vPPiJ/FWwWNlumGXVb4HGI5lSK0w==,iv:pk2hrqdCKb/4IqpT/U4UOdUdx9chmsiAHusWDig0HwE=,tag:ARkY+W957NPzHz5kLV+kPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRDBvT0Z0R1BTVUltd2tK
            MGd1UWhBR0JtV2JtUG93OHV6SGh1K3F3UkQwCng3aVpuWHltQzlmVjBWZlpGM1dK
            dGJqMjM1bzZQeUZHeHNLR2NBVE1MTDAKLS0tIHBSc1p3ZFlXV2loWXF6c2xUQ3dz
            bGw0aHVTS1lLVjFnek51Y1JZVUtxTnMK0Dnro+ikqil2SW5CBvxvAQSpm6qFC76E
            qsEnRjkk9HKNhGhRRUplvXBKdrsOL6UDEh4T81VA0sob592sMT71tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T21:42:11Z"
    mac: ENC[AES256_GCM,data:R7akzSB0geE5P0l/k+c4e6SC4YrvKrTAvbbA/753EWJg70fsrIrze6x8jAB5wIlSb1nZqFBGkc14tXJ2vuk6fVMHzeSu+N1bU2UUNIrzSRmE439fIVV4+BubuF4DFA0yqPmoVfK6INZZ+DbaGzA6IWVbcmmLfuKdjyX5frLtHzU=,iv:uPC9/sra88anJJlJfVITcrmJjjHCAf4xAgMcuaFZLeM=,tag:BE8N61Sz2jo1fdFu+3n23w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
