apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:SFMxJzdP7BGXrVd52G9kK80BN777QfO8bVSQnx/NzMye/1jJGg==,iv:6XQtM5SxcEj0cdti09i8zMRLDX9CI0c6lAOPMlyBBqU=,tag:rAtG3Stu4r4ogpqyHv7GDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ2RiN3RRMzhndW55Q0lE
            RnNNcVVLeEh0UE1XMlIrKzArbG5uZk1mTjE4CkViZXlMUFZja29GWTFFcHJqMGhz
            WThja2RNVkZRenIrTHIxalliNTlqbncKLS0tIENSRVk1WUlULzE2YU5tdkxnWVV6
            bks4aGN3WkNQSDArbWlRREtub2ZHOGMKiVAPzgKMGl0fd89Gzbjp7PbTU5/xhSeb
            r8ygwKt+VazRrhIBvrcCMVgU1Nc4uTw58DiWEEIImZ36PD1f3WmHTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T21:32:53Z"
    mac: ENC[AES256_GCM,data:ZoJCARkBmRMYzn9F91b+YEV1Zz48dnEbz0xSg4NxcjW4Qrodu17wVxj8eA8wGLg81vjbA6Sa8ek3+Vc0D8EWlzu+gfLdonai1+fy2rUaax4bswbPKWb5T6ouhnhc4GW8/TRpsFAxHIKsbMPO88NZyKQiHpzJUQtrSS3vGFMcmoI=,iv:UXAnEeKa++5TEkFKPgpxfDLi2NZQKzihOYoOvpLpGj0=,tag:uMpO3zhYMGjJNxbZIp4ydQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
