apiVersion: v1
kind: Secret
metadata:
  name: volsync-secret
type: Opaque
stringData:
  VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:wuNTSnDEhgDJHLlPii0T,iv:R14fABmY5u+ZxoXdf+8B9MMDIMEYjZigz9WKUQeo/TE=,tag:sFEe6cOz/YIbN6zoBUUGrw==,type:str]
  VOLSYNC_S3_ACCESS_KEY: ENC[AES256_GCM,data:tZbQq7I=,iv:lXUJeeAG5FqgGgzGFDHtGfKqw00iFZQ1fhsYrawVcfU=,tag:8e1VK0I84gbT/mvqsGEjiw==,type:str]
  VOLSYNC_S3_SECRET_KEY: ENC[AES256_GCM,data:rFtGXHrpYJr1YXte98U=,iv:grpWUFc5nkB6l563aFzmZ+9rh01dlk63/+iQreqkSUY=,tag:Xw+4iuEhuxpTQ/IymjjIng==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodHFTNnFGK1JQQVVWUWkx
        aGRZRDJBc3VsWXVNZEtBOG92bTlpSStvQTNzClkxVUNuWjFGMVBkSFpLYjkxT2Nz
        bWYrTHVSZzVsVittZnBmY1NvRTl3SWMKLS0tIDd2eVdIL29sYjZmYUMxSUc1aWpO
        RjM5b1UxVCs1OUE4dnpGUVk3eTY4NjAKvgpJFid+z5p0e0UpKdyVoRqS4ja7pd2M
        IJ5CYYglMBbp72ETtnRJYNBd8TXyAmu/DLmvXnCPLjbkybSt+LgkGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T17:09:46Z"
  mac: ENC[AES256_GCM,data:eBhO3bu2LfK3GQP0CM1xy/7IUGVEtSBmhu1H7Cco+c1jmAcq87TDu1K/N7c0LWimdlngcsEhatRdhx+ArGdAif7aQs2IN9S47fVApie3z9llqVNbu2tDJwrDxHNB7AO+Uxfo4+mVcVKRo4SYsDmCsFA35Ro1m2dMsfLUEeccghM=,iv:oL3E9PsE0+6qEJ2xe93vBQdoEFjophdU+RDRvKvrpR4=,tag:vckx8ZUaLojGhcUHyzK3Og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
