apiVersion: v1
kind: Secret
metadata:
    name: minio-dl-secret
    namespace: default
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:p7JSia8=,iv:WCbsQzwJHtGkUF4NvUU5cDOgQXSj36+hi6yy8PDn47g=,tag:hSMonvFGwIgXMkLyd6m00A==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:IxlYfiKPw5fAAvCfX3o=,iv:ySKmnEYF17h/TAGQ/ckiZLcU51OATDEJPZ6DhxAufIQ=,tag:XIyaNUS8HmPc/CzEjsSlyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T11:48:02Z"
    mac: ENC[AES256_GCM,data:4RvmD8CtGWyZ5LZrDViSNZPyjA3x4Trru4yZ9PQL+hKtln7sWuE7n0BlmUsFDSPVjvrL2skA16jWxiCi9MTzAs9hUY4JREI3jdKA+9MV1DTtsti6MVBfcZ8VwQUEIgn8pKN5p3B9VIoRQfy6WG6Sf/xz3WK6Hq9jDJ6DTXDkhO0=,iv:xol7x3cs7TUCc1T1YprqhfavePdaJ+OoCY2oDoknxmY=,tag:uuJ7dLkaNBBM0kaQgtsKBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
