apiVersion: v1
kind: Secret
metadata:
  name: open-webui-oidc-secret
  annotations:
    davidapps.dev/credentials: pending-provisioning
type: Opaque
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:1tdWCGGmGPZHhreYjewdd1vQcT89m+vEB9cdn4gdXgFvqBJ5TDKt800gchOu,iv:OzlINgQZs2zpqrsp6t6qMGOjDv3njCLwol2L4DrPqjY=,tag:L9aBlGDUTRMZR8RozK60TQ==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:5euh5tJ9d0MWCxnIF9xgs19ATBgq+ZartPYTNbYc8prVXch77XPSF2cLP3/TRA0YEg==,iv:gWh/XZr5Zwyksd34WP2vWRFaK+Bh4vV8K30OqTNGB7s=,tag:mHfl4RwC05q2GHAku5Tu2Q==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SnVrOUcvVUJzV0tYKy8z
        akVHTFdxUVN5Q1psRTdIai9weEtVTDB3d0ZJCnZ0S2xTTGhtM0duOGdPQWZLdU5h
        NE1JU245cE41R3NhMEk1U0dsclVRU2sKLS0tIFVRT1g2aFlrYmZsclRDMno3UHl1
        U3BqSkpCNldJWXVSZVV4dG03aWd1bzgKAJQLpkPP18dYeC8a4/EMu/w3AJJ3W5pw
        8LUsKN8eO5CjWOTNLxtuT0DPWe06cOzGXKTlIJ0tk5CMAAAAGpzUVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:34:42Z"
  mac: ENC[AES256_GCM,data:9Mz6Ci1/N8ODEJgPfgXGp3CRHBCqXxKqjbsHJzlR7N+sapV0MwlJbAvVARQBN47t/IaLflv9/Dz0iLzptYD29/ksATR593lLZwBUaYvKh3tXvL+uV9QW6tEbI7HXVjbM1UP9BLyyUTY+HahKLx3UT82xBVDG+nZ6E0jBaAEckDw=,iv:qKsaUlFfmHEIJu4M5rwHEVVlwMSGjQVRd2/fv+64k6s=,tag:+TabZggCGYhz0/Ufy+sv0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
