apiVersion: v1
kind: Secret
metadata:
  name: open-webui-oidc-secret
  annotations:
    davidapps.dev/credentials: provisioned
type: Opaque
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:wS5mM9eqXxMRRb2Xffnt9eVg/qjqnXGNv1W8IcSiNws=,iv:kqGExz5/3LOoJggpYxhjQT8pIJ2wwD8V26Q3xcsGQ0Q=,tag:2uP2EbHELl0Kj/i0UZA4hA==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:PC7f+Gr73gEPHifuRwNiZLH9G/3LCi8MFpb/hwKv+nc7S0+Tkn1ZOrCGJg==,iv:UW7p2m1LBP0SR4wOPtNlehJN69+LvtHVVmuEScRk5bQ=,tag:6loE/oQWe3eMBMaZpQwKPg==,type:str]
sops:
  age:
    - recipient: age1a62pe7lp5xdm2f5v8lhcdsvglht6hr7qvduc6ap2w79r8rqn09tq0fgjcn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWjAyV1NMRG1RZDZYaGZu
        QjZwOTQvRXFWcnlEendpNElzNkhxbXNIcFJZCnNHQlozMjIwbVVJSEx2RDVHUnB1
        UFN3TUdnRndVVEN0LzNTL0lkUWd2VkEKLS0tIHNkQTZjYlJpQVFmTUNEeVp5YTM3
        elFTUFdhMWxoZkRrZFNPemxkRFBWRVUK1cELnWTwuSWjTVETDiNjUD8gyY4zRRTH
        mNvXQuYISTTm8nJ0ovXq7X0mw+8iFHCHFoR1AeweqHAzyRl+CaA5xQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T14:53:42Z"
  mac: ENC[AES256_GCM,data:B6u/eNN39iTwBe3+jrjZO2vpAr3QiUO1LhUuJr5KqlE9hrq9SuIPsjYtfJBj3uTq+412CnEvssuednpNoMar9S5dIm0rH/k9hjSxKTjgKt4Z03/2/2YM2YcCn9qCXsKh2pfD5zbaE+ryHBFpm35F3gpMWt7+40sKR6dUsURjeIg=,iv:73NTgD3jACq0v1ml2soPqzUDo5GZw+X9gANBM9RtuRA=,tag:e3xQVJkvNQeS9lEI2IltOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
