apiVersion: v1
kind: Secret
metadata:
    name: laundrey-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:a6GE5RaBpUlSQPGk+hpIcrqXEE9m/WA3ZaZS0oIu7B8pAaapeOWZiGaCHHSK9JiYpaVq4DICoZGzpkXtbTe5k0SYv/mzw+MDpveJvNJ8EgPXy2xl8Q==,iv:p4qzfVt1Br0NmyLMzLlBbO6WA4xs8AozaVRO6/qhsUc=,tag:sQk+4Ta/8N//EnEQHLJ1kw==,type:str]
    APP_URL: ENC[AES256_GCM,data:rsYLbXvMSmLuKzB/VRuCwtZ7A+L2qd3/iukhZCrT,iv:z8HzK9UXeq79Glzp/RDT5kZqfjLxBJVi+kSNZ+4+FrY=,tag:JMbfpzyGY7zd8WmaFMsxKQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+B+PKSWbzd6zvv678QBsaclAnfXu/c/LJAxgNf49vxtxl1pknoOBUoa1BGndyFT50AUmhUtr766U28crL+Ff0Q==,iv:SBRyxblw9hnHE870s8nEMUQrEapR3KIDUSEkAXZyEss=,tag:dqH7IpEwxNfyzIPcNIS2ng==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:fKosxFw=,iv:y0jk6uvbPUhAk5yd3zMFufsx4CaZSz7LD9pNG5Pn/PA=,tag:fbveX/H78Pe1ej99GFxXUQ==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Njc1Y94/TtnrIFwEmKU=,iv:Tqt7chCIP/sseV6L5LAYjQey3Ifc3lzHB9sx0fpQSIo=,tag:KpmnvzEymidspQhJLJXYdA==,type:str]
    MINIO_BUCKET: ENC[AES256_GCM,data:s24jpCmO6sw=,iv:gbwrYD4KJwjn6gajSi8S4GzMIzq1WoZirdU26eVTNWc=,tag:DIGgHwpjyo4fJSXkJKqwAA==,type:str]
    MINIO_URL: ENC[AES256_GCM,data:Q+XnJcrmY8I+PP8t+Ztfd5Y=,iv:6tb3yKgxKzXSmUfwczziVeshTUJYCFBLGOhLpu1+p4Q=,tag:ntZwNaXpGCUsYf2P7geSzA==,type:str]
    MINIO_PROTOCOL: ENC[AES256_GCM,data:lpin0MQ=,iv:QG1YmjAe+L9j2il4iirOeNHIMXm52eQgOYN/+YvGKpQ=,tag:RWyNLUvcbYoGi6tJXi9Q7A==,type:str]
    MINIO_PORT: ENC[AES256_GCM,data:SRHS,iv:PaiwniCFR/3OKxOMbyyzfRSchTEyT/uVyYN/D7Lfiqk=,tag:UIJ25uzUilH9i3cTSaEqew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ3dhZlhtTlVtNTUxY3RE
            VlNiVWt6MDlGUlpUYmcyK3ZlRS9udGNDVVNrClV5RU1yQTZnak81cGZPTE52elVW
            ZEVCWnNQK0cvbmJSVS8wK0hOQVpld1kKLS0tIEFVdmc5c1JvcEVJeFBEeVpQcDg0
            eUJaN2ltSFI0S1l3RHVGeXRhQkRrRVEKBrvHgG2fAmuu/0TRvmIGNMIcEcA6BDeN
            ldlk0Hv6QrbqdDH8Hs4jPMhR907gE+XsG+IiIHX7QS9umsxnHravSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-29T09:24:52Z"
    mac: ENC[AES256_GCM,data:rv2jZh5VnRYaf8Rk0E1oQaex6qCrQE/Zf0rIyFXtRz9Pn5rzj0Kj44JEnpv8QzniyMJzlUhWlWU8807tfZe/KQhrmWNNGW+YsetrpIZtrArCWI0Dx80fyDn12hUAyvST4VfjRQO2pxT3Bsn7XQb8N29VgBodulNvGIAXw8cjCM0=,iv:1+5WJDZSpTGbbolb2ThhxTDS/0DvIzc2sj+hiN2K9/E=,tag:3ZwPMUWXaF0yvbrHe7HLPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
