apiVersion: v1
kind: Secret
metadata:
    name: workroad-pg-secret
    labels:
        cnpg.io/reload: ""
stringData:
    username: ENC[AES256_GCM,data:6cer0V+wuzo=,iv:3ANJ2ZPlbI52nptJfHM0d0Aq1vs/8R5+iEL2QQZPiJ4=,tag:AIjLiL/XBLIo/W5atDILvw==,type:str]
    password: ENC[AES256_GCM,data:u01Mlb9qI8RQ2pEvvoK8aAuXEWg=,iv:rC1+/UQNGdQ8nwsSAmcQGb6qqXEAIbM+yGF/O2ppZEA=,tag:CSqkPsQC+VJD6BLHvKVeZg==,type:str]
    pgpass: ENC[AES256_GCM,data:DA8Ru1HdydFBUR+I38mq2gqVeZA=,iv:dSW6I2QtTbPnllpzSM/GeIO2q+c3Y2JfGUf/hEJ2IDU=,tag:wWPcJNE5STABxJA51TFfDA==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:BvDlcdo=,iv:0wgijcUfs7MkSiYwxHEjN9TnJh27TglvR+mc17WAdao=,tag:EkgaBCkqmcDWdr9Nm33r1g==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:cpevDs/Ss33n+vbVmQpFt6ieSRZHlBPJfmKRw+HCu/KTsEHx5w+91qH59CI58SN6d4Kx34yQS2wAf/8UOpCHvw==,iv:EhrLPQy/Th4kDdOzSPB8VFb9jovCzekXcg4tSOcF+T4=,tag:zPh1eLT+iThNsYjhzT3NDw==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdVRpWkZJYjNOUURLaVVx
            NTYyYVVKVkIxY0d4SW1pbzd5bTdlZTltZTBzCkpsZFo0Mk9xZi84RXBXaXEyTFVF
            cVhkdWY4Z0hCL1JGdVUxdUtyK3lZbnMKLS0tIGdjdXRoeWpkTVBNcnlnVkNXd1B4
            SmVkVTVpaDlaUGl5ajAxYzRYMEZsZ0EKPCRcs3/haVvdaWY4oaBPVUbgJ5Dt/zP4
            5/QAmQhWDh92Ulqu0VnybeNrcKVx6IhGoleASKaxMrxy3lQKbt1BpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-04T22:10:44Z"
    mac: ENC[AES256_GCM,data:kz5cIGimd81jBzrxnl9VpQ6VQWPZEZRaGWbYZG+jsvNoZ73MQwh8Xw8Jmge4YDwX4Dk144QM99lpfbkxL0E2yCAXWp1krPzYXKIBwUWtyAuuG60QRH69B5mm52wV/RuG+bQ3YKI/wFww8ywNUli8SR154NyGjZpoCyLhZPQtAL4=,iv:EUzgoYWrD0bQHD+wBOQfTmD6/J7hNmeobzN+vozhN0E=,tag:C5d+xVSuPqrdrTJkiY6pRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
